### ISSUE TITLE
NXT simulation interrupt does not stop the robot

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1011]
Create a simple program:
![image](https://user-images.githubusercontent.com/1613069/116248212-f5140000-a76b-11eb-9ac9-be3f690853d2.png)
Open the simulation view and start the program. Now, before the program has finished, click on the stop button to stop the program execution: The robot moves indefinitely forward, but the robot should stop moving. The program itself does stop.

from a user

**Comment by rbudde** [comment]
changed robot.nxt.js
