### ISSUE TITLE
Integrate nano33ble

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1023]
the Nano 33 BLE should be supported by the lab. As it is a bit different from other arduinos with builtin sensors, it should NOT be in the arduino group (all group members should share the blocks. To do:
- [x] icon for robot selection menu needed
- [x] image for configuration needed
- [ ] all sensors/actors, that are supported for other arduinos, should work (to check this, reactivate the IT sensors*.xml actor.xml and drive.ino
- [x] check, that the chain arduino_resources -> ora_cc_rsc -> openroberta_lab is working
- [x] use the new validation and collector
- [ ] make the AIfES library part of the plugin
- [ ] write a prototypical C++ program using the current AIfES API
- [ ] finish code generation for the current AIfES API

**Comment by bjost2s** [comment]
empty checker need revision

**Comment by bjost2s** [comment]
won't fix, aifes library discontinued
