### ISSUE TITLE
add a REST method to do xml transformation from old to actual xml format

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1026]
**Context**:
- either in the data base or exported there may be outdated xml programs
- if this is detected, a transformer is called to update the xml to the current version 3.1
- currently this is done inline in rest methods that are responsible for loading/importing program

**Goal**:
- create a new rest method, that gets old xml and returns new xml
- add the uri of this rest method to the openroberta.properties
- the  rest methods, which detect the need of tranformation, should call the new rest method

**Reason**:
- the old method is not flexible, because the transformer makes it hard to update our AST classes

**Steps**:

- [ ] copy lab-git-repo to create a server for only transforming old to new blockly-xml
- [ ] create a new REST endpoint for transformation
- [ ] test it
- [ ] remove all other stuff
- [ ] concentrate all source to one project (???)
- [ ] add script to docker to generate an image from the project
- [ ] add deployment functionality
- [ ] make sure, that a missing transformer container is not harmful
- [ ] MUCH LATER: use that server later to transform all old calliope/microbit programs to new ones

**Comment by afif1400** [comment]
Can I work on this

**Comment by rbudde** [comment]
@afif1400 yes, of course, you are very welcome. I hope, the work is not too hard, but probably the setup of the workspace, etc. may be time-consuming. Some remarks:

- you should follow our README to setup the workspace. You must NOT install cross compilers (c++, ...), as you must not compile generated programs for a robot.
- the preferred way for questions is to use gitter: https://gitter.im/openroberta-lab/community, but mail is fine, too.
- I prefer to discuss a short sketch about proposed changes before implementation to avoid oversights, misundertanding, etc. But this varies depending on experience.
- your work should be submitted as pull request against develop.

Enjoy :-)

**Comment by bjost2s** [comment]
no time to work on
