### ISSUE TITLE
Simulation accuracy depends on speed of movements

### ISSUE THREAD

**Issue by aykborstelmann** [OpenRoberta/openroberta-lab#1033]
As you can see while the simulation is correct when using the speed `2` the simulation is in correct (rotates to 180°) with speed `90` it rotates to 186°. The accuracy is antiproportional to the speed of the movements.

Our simulation should be correct independent of the speed. 

**Low speed**
![image](https://user-images.githubusercontent.com/31162687/120199604-b5857b80-c223-11eb-8da4-1cb53ea243d2.png)
![image](https://user-images.githubusercontent.com/31162687/120199619-bb7b5c80-c223-11eb-8b6e-bc0c8e9767af.png)

**High speed**
![image](https://user-images.githubusercontent.com/31162687/120199731-d9e15800-c223-11eb-85d0-20618f36b784.png)
![image](https://user-images.githubusercontent.com/31162687/120199758-e1a0fc80-c223-11eb-9743-fa6851544ac5.png)

**Comment by rbudde** [comment]
Have a look at our FAQ and open the first entry of the page: https://jira.iais.fraunhofer.de/wiki/display/ORInfo/Robotersysteme

**Comment by aykborstelmann** [comment]
Okay, I didnt know that
