### ISSUE TITLE
Import Export Function

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#104]
**Is your feature request related to a problem? Please describe.**
 - A clear and concise description of what the problem is. Ex. I'm always frustrated when i want to import parts of a specific program into a other program.

**Describe the solution you'd like**
 - It would be nice to import functions (prog parts) of other programs.

**Describe alternatives you've considered**
 - A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
 - Add any other context or screenshots or a mockup about the feature request here.

**Comment by VinArt** [comment]
#137 - related/duplicated
