### ISSUE TITLE
play tone for edison generates invalid code, if the frequency is no number constant

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1044]
write a program playing a tone.

- if the frequency is a constant (e.g. 2000), the code generated contains an expression 8000000/2000, which is evaluated by the compiler. The result fits into a number.
- if the frequency is a variable (e.g. x), the code generated contains an expression 8000000/x, which fails, because 8000 doesn't fit into a number.

**Comment by RaghuvirShirodkar** [comment]
Duplicate of #540

**Comment by rbudde** [comment]
is already solved
