### ISSUE TITLE
You cant Expand/Collapse only the Start block

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1054]
**Describe the bug**
 - when having a Program the only way to collapse the start block is by collapsing the whole program some goes the other way around, when having a collapsed program you cant expand only the Start block but have to expand the whole program.
 This is especially impactful when having an Arduino program since the whole program is inside a block that's treated similar to the start block
**To Reproduce**
1. Have a Program of any size preferably with some variables
2. try to collapse only the start block
3. only help appears no collapsing option
4. then right click an empty space
5. click Collapse blocks
6. try to open only the start block
7. only help appears

**Expected behavior**
 - the start block should have a collapse/expand button

**Screenshots**
![Screenshot from 2021-07-01 14-52-04](https://user-images.githubusercontent.com/57675018/124127408-f7e8e500-da7b-11eb-8f49-9cdd7d2d7b5f.png)
![Screenshot from 2021-07-01 14-52-45](https://user-images.githubusercontent.com/57675018/124127449-033c1080-da7c-11eb-8d4b-e9eafae56a94.png)

**Device information**
 - Type Desktop
 - OS: Linux Ubuntu 18.04
 - Browser Chrome/Firefox was tested

**Comment by bjost2s** [comment]
depends on old blockly, no time to work on

**Comment by PamoCurtis** [comment]
Can i close my PR nr.69 in the blockly repo?
