### ISSUE TITLE
Variables can be used out-of-scope without triggering an error when generating the code

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1060]
### Problem
- Initializing/declaring variables through **for**-, **foreach**- and **function**-blocks and using the "**set 'variable' to**"-block out of scope, does not trigger an error when opening the codeview/simulation/sourceCodeEditor (**pic 1&2**).
- Initializing/declaring variables like above but then deleting the block lets you use the variables even though they are never initialized/declared (**pic 3**)
- It is also possible to use the **variable**-block after the initialization or in another function. In both cases the variables are out of scope (**pic 4**)
- It is even possible to run the code and debug it (**pic 2**). 
- The code that is generated is faulty 

### Expected behavior
 - Triggering anything that generates the code, the codeview/simulation/sourceCodeEditor should not be opened and an error message should appear like in **picture 5** (picture is from the [open-roberta lab](https://lab.open-roberta.org))

### Screenshots
**PIC 1**
![Bildschirmfoto von 2021-07-08 15-34-04](https://user-images.githubusercontent.com/59732238/124931165-3c3b2e80-e002-11eb-9306-95008fd0c028.png)

**PIC 2**
![Bildschirmfoto von 2021-07-08 15-35-09](https://user-images.githubusercontent.com/59732238/124931260-5248ef00-e002-11eb-9846-c8a7fe8ff40c.png)

**PIC 3**
![Bildschirmfoto von 2021-07-08 16-27-08](https://user-images.githubusercontent.com/59732238/124940657-75779c80-e00a-11eb-8503-d767252c9c3a.png)

**PIC 4**
![Bildschirmfoto von 2021-07-08 16-37-02](https://user-images.githubusercontent.com/59732238/124941037-c5eefa00-e00a-11eb-9e0f-5cfdf83999b9.png)

**PIC 5**
![Bildschirmfoto von 2021-07-08 15-43-22](https://user-images.githubusercontent.com/59732238/124933471-35adb680-e004-11eb-9fbd-d57c93f5bae7.png)

**Comment by PamoCurtis** [comment]
Bug is still present in the lab and test/dev

**Comment by RaghuvirShirodkar** [comment]
Almost all issues* listed in the description seem to be resolved after testing on test server.

*For issue listed in pic 3 above, the set var block still remains in the program after removing the corresponding block that initialises the var. This issue is tracked in #1233.

**Comment by bjost2s** [comment]
#1233 is solved, too
