### ISSUE TITLE
inconsistent size of block help window

### ISSUE THREAD

**Issue by Ch40sl0rd** [OpenRoberta/openroberta-lab#1068]
the size of the block help is inconsistent between different robot systems. E.g. for EV3 the help has an appropriate size like seen in this picture
![test_cutoff_ev3_normal](https://user-images.githubusercontent.com/52046628/126602150-aae0b011-9803-4c3d-886f-00a65f1df9fa.PNG)

But for calliope mini the size of the window is too small so the last line gets cut off like this
![test_cutoff_en](https://user-images.githubusercontent.com/52046628/126602208-3612d1c5-d8f1-4e3e-bba3-f4ee2426a99b.PNG)

**Comment by bjost2s** [comment]
The problem seems to be an issue of the generated html, which is exported from the wiki. Likely the wiki text has errors.
