### ISSUE TITLE
language: changing the language does not update the already set blocks in robot-configuration view 

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1069]
When changing the language while not in the robot-configuration view and then switching to it, the blocks that are already set are displayed in the wrong language.

**PIC 1**: switched from English to German
![Bildschirmfoto von 2021-07-22 09-14-20](https://user-images.githubusercontent.com/59732238/126602529-f3eb3640-ab40-4da9-8429-3f4f197fa6e0.png)

**Comment by bjost2s** [comment]
testd
