### ISSUE TITLE
mBot: faulty config leads to server-error

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1071]
### Problem
modifying the motors in the mBot config like e.g in **PIC 1** and using any of the drive or motor blocks, unless the "stop motor port mX" block, results in a server-error when opening the code-view (**PIC 2**)

### Expected
Error message saying "There are errors in your program or configuration. Please check the messages." with a valid error message on the block itself.

**PIC 1**
![Bildschirmfoto von 2021-07-22 11-26-10](https://user-images.githubusercontent.com/59732238/126618043-d8a5403d-33f5-4f8f-98b0-3e1be360ebaf.png)

**PIC 2**
![Bildschirmfoto von 2021-07-22 11-54-06](https://user-images.githubusercontent.com/59732238/126621374-b44e5f95-bece-45ce-8013-750e1edc7f76.png)

**Comment by rishabhdeepsingh** [comment]
Can we close this one now? @aykborstelmann @rbudde

**Comment by aykborstelmann** [comment]
We usually wait until the changes are released until we close the issues. For now we just add the label resolved and move it to done in our project

**Comment by rishabhdeepsingh** [comment]
Cool, Thanks for the info.

**Comment by bjost2s** [comment]
The solution is not sufficient:
![image](https://user-images.githubusercontent.com/1613069/148073514-fa05754c-3429-4218-9531-e99cbd7672f0.png)
There is still a server error:
![image](https://user-images.githubusercontent.com/1613069/148073459-35667492-1438-4b64-bfad-df77295bc7a1.png)

and the drive blocks are not checked at all, see:
![image](https://user-images.githubusercontent.com/1613069/148073753-0645bff5-23e5-40d8-b4b9-9ddaa1dd66c1.png)
with no motor in the configuration

**Comment by rishabhdeepsingh** [comment]
This solves this error.
