### ISSUE TITLE
unable to  open Roberta lab in local host

### ISSUE THREAD

**Issue by Nithyasri2926** [OpenRoberta/openroberta-lab#1088]
I have started the open roberta installation server on windows 10 machine, It starts successfully after doing steps 1 and 2. Please find the screen shot below
![Screenshot (26)](https://user-images.githubusercontent.com/88312058/130417444-bd806448-0e4a-49f7-ac05-210f3f33caf1.png)
When I try to open  in the browser for url ,https://localhost:1999,I get the following error
![Screenshot (27)](https://user-images.githubusercontent.com/88312058/130417478-66498019-125c-46ce-8f3f-759cf1f268de.png)
Please let me know any worker on this issue

**Comment by rbudde** [comment]
Your are using tomcat for your webapp. We are using an jetty embedded in our application. There is no need to put our application into a webapp directory. Our scripts are bash scripts (we are using linux boxes). But with your git installation on win10 you get a fine bash, too. You can use this bash for the following:
- If you have checked out a valid branch (master e.g.),
- have run `mvn clean install` and
- have created an empty database with `./admin.sh -git-mode create-empty-db`, then
- running `./ora.sh start-from-git`

starts the server (the last line of a successful start shows how many programs are in the data base) and you can access it on `localhost:1999`
