### ISSUE TITLE
Configuration for all robots - visible or hidden

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#109]
Currently we have robots with the old configuration and some robots without a configuration (maybe internally on server side they already have a fixed configuration). 
We should add to all systems the "new" configuration, so that we can create a common way on server side to handle this configurations. Further we have than the possibility to assign multiple  "standard"  configuration to e.g. calliope to distinguish between different calliope like systems. A good example is here Calli:Bot:
- standard configuration for calliope itself
- Calli:Bot configuration to configure the maqueen board, the underlying board of the Calli:Bot
- another callibot configuration for the next calliope robot (there are several out there, mainly with an external motor driver board)
- ...   

The user can then choose in the beginning the "configuration" while he is choosing e.g. Calli:Bot as a system - or - if we do not want to offer to much systems the user has to make this choice in the configuration itself (might be difficult to show this opportunity to the user)

**Comment by boonto** [comment]
We also discussed an additional point: The current images describing all sensors/actors/ports on the robot should be accessible through an additional tab, e.g. "robot description". This would also require generating new images

Additional tasks:
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by boonto** [comment]
Calliope and Microbit were handled in #747.
Remaining robots with visible configuration:
- [ ] EV3
- [ ] NXT
- [ ] mBot
- [ ] Botnroll
- [ ] Vorwerk
Remaining robots with invisible configuration:
- [ ] BOB3
- [ ] Edison
- [ ] NAO

**Comment by rbudde** [comment]
will be solved with new issues, if really needed
