### ISSUE TITLE
multiple light sensors can't turn on their lights on NXT

### ISSUE THREAD

**Issue by Ch40sl0rd** [OpenRoberta/openroberta-lab#1090]
when using more then one light sensor with the NXT robot system, only the first used sensor turns on its build-in LED. Normally you would expect every sensor, when using the normal 'light'- and not 'ambient light'-mode, to turn on their LED.

Furthermore when using multiple light sensors with the official Lego Mindstorms Education NXT Programming Software, all of them turn on their respective LED when in use.

I guess

 the error lies in the implementation of the readLightSensor-function in NepoDefs.h.
![LightSensorTest](https://user-images.githubusercontent.com/52046628/130931951-cb43e209-30e4-4245-913c-5ada6dab3c35.PNG)

**Comment by bjost2s** [comment]
From the docu http://bricxcc.sourceforge.net/nbc/nxcdoc/nxcapi/group___input_module_functions.html 
if we exange 
`void SetSensor (const byte &port, const unsigned int config)`
with 
`void  SetSensorLight (const byte &port, bool bActive=true)`
in the code generation it should work
