### ISSUE TITLE
Checkbox in the simulation for line painting

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1092]
Currently we have backgrounds, in which the path of the moving robot is painted. This can be improved by adding a checkbox to enable the painting for every background. This is nice for programs in which a background should be explored (escaping from a maze e.g.) and helps programming and debugging.

**Comment by bjost2s** [comment]
implemented with the "new" simulation
![image](https://user-images.githubusercontent.com/1613069/234541854-25a20d07-ebcf-429d-8fa9-1aab6da8d111.png)
