### ISSUE TITLE
file path for nxt cross compiler resources does not work + cross compilation errors on windows

### ISSUE THREAD

**Issue by Ch40sl0rd** [OpenRoberta/openroberta-lab#1099]
When using the Open Roberta Lab on a Windows machine, the path for the nxt cross compilers is given es e.g.:
"C:\Users\Lars\Documents\ORB_dev\crosscompiler/RobotNXT//windows/nbc.exe"
which mixes forward and backward slashes and thus is not a valid path on a Windows machine.

Because of this the cross compiler resources for NXT can't be found on a Windows machine.

In addition to the above, there are cross compilation errors encountered on Windows machines for multiple robots:
* Robots under `RobotArdu` project:
  ```shell
  2022-05-11 11:36:23,527 [qtp366004251-37] session-id=[2] user-id=[-1] robot-name=[uno] ERROR de.fhg.iais.roberta.util.Util - crosscompilation of NEPO generated program failed. Messages are logged to logger 'crosscompiler_error'
  2022-05-11 11:36:23,527 [qtp366004251-37] session-id=[2] user-id=[-1] robot-name=[uno] INFO crosscompiler_error -
  ***** cross compilation failed with response:
  Der Befehl ".." ist entweder falsch geschrieben oder
  konnte nicht gefunden werden.
  ```
Add more installation steps for relevant robots in the README file.

**Comment by RaghuvirShirodkar** [comment]
I wasn't able to reproduce the error for NXT, but found errors for other robots instead!
@Ch40sl0rd, could you please confirm if you still get any errors for NXT?

**Comment by rbudde** [comment]
solved
