### ISSUE TITLE
Write and archive log messages in separate files 

### ISSUE THREAD

**Issue by vlebedynska** [OpenRoberta/openroberta-lab#11]
**Feature request:**
Currently all log messages are stored in one file. To evaluate the statistics, we need to retrieve the statistical information from the main log file as needed. 

To facilitate this process and for evaluation purposes in the future, statistics logs should be stored in a separate file. Info logs should also be written to a separate file.

For easy maintenance, log files should be archived automatically at the end of the month and automatically supplemented with continuous logs when the server is restarted.

**Solution:**
1. Separate statistical log messages from other log messages.
2. Save logs in separate files (e.g. using `RollingFileAppender`)
3. Roll log files based on date/time.
4. Daily rollover (at midnight) for testing purposes.

**Comment by rbudde** [comment]
I added two properties to the server properties, that allow to inject at runtime the log level and the logback configuration file (have a look at the comments in openroberta.properties)

**Comment by rbudde** [comment]
tested by inspecting the log directory, if logback-prod.xml is used for logging
