### ISSUE TITLE
Add Kotlin support?

### ISSUE THREAD

**Issue by rishabhdeepsingh** [OpenRoberta/openroberta-lab#1101]
**Is your feature request related to a problem? Please describe.**
 - While creating data classes in Java it's really hard and easy to mess things up while setting up the getters and setters.
- NPE and nullability check everywhere.

**Describe the solution you'd like**
 - A solution would be to add Kotlin support for our project so that its really easy to work on also with the latest APIs provided by Kotlin we can actually reduce the total lines of code.
 - Kotlin has an inbuilt nullability check as well 😃 which means even less NPE

**Comment by bjost2s** [comment]
This is an interresting idea, but unfortunately we do not have time for this
