### ISSUE TITLE
leJOS 0.9.1 - Subtracting a random positive number in a set command can result in no change, or addition to the original number

### ISSUE THREAD

**Issue by YogoGit** [OpenRoberta/openroberta-lab#1104]
**Describe the bug**
When subracting a random positve number from a variable containing a larger positive number on the physical robot, using LeJOS 0.9.1 on the EV3 brick, the resulting variable will sometimes be the same as the original number, or even larger, insteading of subtracting the value correctly.

ie;
  origin = 10
  num = orig - Random(1, 5) 
  if (num >= orig)
     ERROR("num should never ben larger than the original number")

  
**To Reproduce**
Import the attached project, which shows a working example (setting the result of the random value to a variable), and the failing example (doing the subtraction inline).
1. Import NEOProg.xml
2. Choose EV3 -> leJOS 0.9.1
3. Connect to the robot with OpenRobertaConnector, and download/run the program.
The program will display the count of valid operations for the first (correct) setup, and will quit running when any button is pressed, and then start the second (invalid) routine, which shows as many failed attempts as successful subtraction attempts.  Press any button to exit the invalid routine, and exit the program.

Note, both subroutines work correctly using the Simulator, and also work correctly using the experimental EV3c4dev configuration.

**Device information**
 - Type Mac Air (fails on Windows as well)
 - OS: MacOS (fails on Windows 11 as well)
 - Browser Chrome 93.0 (latest version as of 2021-09-09)

**Additional context**
- The uploaded XML file will need to be renamed, as Github doesn't allow for uploading XML files, so I renamed the extension to .xml.txt
[NEPOprog.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/7139658/NEPOprog.xml.txt)

**Comment by rbudde** [comment]
missing parentheses in the code generator. Applies only to Java code generation. C4ev3, C++ (Calliope, Arduinos, ...), Python are not affected.
