### ISSUE TITLE
Issue occured while Installation on ubuntu(MobaXterm)

### ISSUE THREAD

**Issue by KondraDivya** [OpenRoberta/openroberta-lab#1108]
I installed everything successfully about robots on ubuntu and step 1 is successfully done while coming to step 2 that is the creation of database there it is coming an issue

![Screenshot (358)](https://user-images.githubusercontent.com/88012589/133185796-fc4f2408-3386-48af-8bbc-f3e2824d64a2.png)

I

**Comment by aykborstelmann** [comment]
Did you try `./admin.sh git-mode create-empty-db` (git-mode without starting with a hyphen) ?

**Comment by KondraDivya** [comment]
Yes I tried it by removing hyphen still getting an issue as follows:
![Screenshot (361)](https://user-images.githubusercontent.com/88012589/133739980-9977f206-7158-43c7-8302-289a347bdc08.png)

**Comment by rbudde** [comment]
sorry for answering late. I'm the author of these scripts. `-git-mode` is correct, it's a convenience parameter.

The most likely reason is, that you didn't run `mvn clean install` (or `mvn clean install -DskipTests` to save some time) before. The mvn call installs -among many other things- the database jar needed for the operation. Can you check this?

**Comment by bjost2s** [comment]
please reopen if the problem still exists
