### ISSUE TITLE
Open Roberta Lab: No audio output directly possible from within Calliope mini app

### ISSUE THREAD

**Issue by joernalraun** [OpenRoberta/openroberta-lab#1119]
When using the Calliope mini app (iOS) there is no way to directly hear audio blocks through the simulator.

The only way to activate it (though this seems not to work throughout all devices/iOS versions) is to close the app, start the Lab in the browser, allow microphone access and open the app again.
This is a long way to get the sound activated.

**Comment by bjost2s** [comment]
Probably an issue of the app itself? [Here](https://stackoverflow.com/questions/33496883/html5-audio-not-playing-on-uiwebview-ios) is a similar problem description.

**Comment by joernalraun** [comment]
Good point, I'll check if this could be a solution.
I think this can be closed for now!
