### ISSUE TITLE
Blockly name connection not working properly when typing invalid names.

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1128]
**Describe the bug**
 -  When entering an invalid name into the textbox of a sensor or actor that is connected to a action block in the program workspace the last viable text gets added to the list of sensors/actors you can choose in the action blocks drop-down menu.
 - this causes more sensors to choose from then there are actually in the configuration
**To Reproduce**
1. Go to Program of a robot using the new config
2. pull out an action block that has a variable port field which is connected to the configuration
3. pull out the corresponding block in the configuration
4. change the name to something invalid and press enter
5. switch back to program
6. click drop-down of the added block
7. see issue

**Expected behavior**
 - when changing T to test....(invalid) test should not be added to the list of available blocks to choose in the program, instead only T should remain in the drop-down menu

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57675018/137301584-d89ace49-0e5c-40aa-93f4-fbd4b3fad4dc.png)

**Additional context**
 - I have partially fixed this issue in this(WIP) PR by changing [this](https://github.com/OpenRoberta/blockly/blob/master/core/rob_configuration.js#L83) to:
   if (dropDown[d].menuGenerator_[i][1] === **oldName** || subComponentNames.has(dropDown[d].menuGenerator_[i][1])) {
- however this only fixes the issue for every time the name is changed to something invalid except from the original name, which is arguably the most important time.
- this issue seems to be caused by [this](https://github.com/OpenRoberta/blockly/blob/d98347cf61ea40052d68e0f9e05f92ffb3f0e2ba/blocks/robConfig.js#L43-L50) from the validator of the configuration blocks, removing it resolves the issue completely but i have not looked further into why that causes the issue and why it is needed here.
- Special attention should be payed to the calli:bot which seems to have the most issues regarding this bug

**Comment by bjost2s** [comment]
seems to be solved
