### ISSUE TITLE
Trying to clone the system name and implement same system with different name.

### ISSUE THREAD

**Issue by Yashulekkala** [OpenRoberta/openroberta-lab#1136]
I am actually trying to built own system based on mBot. Like I was trying to built mvBot that has the same properties as mBot but not sure where to start and what part of the code has to be changed.

![task2@open](https://user-images.githubusercontent.com/93042947/138583176-75762502-ac35-422b-82f1-54a4d668c85a.jpeg)

**Comment by bjost2s** [comment]
please reopen if the question still exists
