### ISSUE TITLE
Lab crashes when having two blocks on the same spot and then opening variables

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1140]
**Describe the bug**
When you have two blocks on the exact same spot in your workspace and then try to open the variables toolbox the lab crashes.

**To Reproduce**
1. open toolbox
2. only click on the topmost block in that toolbox do not move your mouse while doing so
3. repeat 1. and 2.
4. click "Variables"
5. see Error

**Expected behavior**
 - Variables should open like usual.

**Additional context**
 - moving them wont cause this issue so it seems to have to do with the way they are pulled out of the toolbox by just clicking
 - in mbot it takes 3 blocks on top of each other to reproduce this bug

**Comment by PamoCurtis** [comment]
more details:
- **the blocks need to be above the 'start'-block** <- this is important
- if **'start'-block** has **no** other block attached, the lab will crash when there are **>2** blocks nearly anywhere above the 'start'-block (atleast one needs to be unused)
- if **'start'-block** has **one** block attached, there need to be **>3** blocks above it or **>=2** blocks on top of each other just like @heini208 explained
- if **'start'-block** has more than one block attached to it, there need to be **>=2** blocks on top of each other
