### ISSUE TITLE
Info regarding steps to add new robo to robertalab?

### ISSUE THREAD

**Issue by muruga86** [OpenRoberta/openroberta-lab#1142]
Need information regarding steps to add new robot to robertalab package.
During initial step planning to clone already existing robot implementations like mBot in homepage select system scroll box. 
Could any one share link or document regarding the code changes need to be done?

**Comment by bjost2s** [comment]
We have a lot of instructions in this wiki, if you have a concrete question it would be best to use our gitter channel.

**Comment by bjost2s** [comment]
Please reopen in case there are new questions
