### ISSUE TITLE
Wrong Link - EV3 Pop-up menue 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1144]
**Describe the bug**
 - The information links in the EV3 lejos Menue are wrong. 

**To Reproduce**
1. Go to 'Open Roberta Lab'
2. Click on 'EV 3'
3. Choose EV3 leJOS 0.9.1.and leJOS 0.9.0
4. See wrong website

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/19221359/142209290-8e6bf28f-744e-4b6e-85f9-a09837ec2826.png)

**Device information**
Link should be wrong with every device and browser type

**Additional context**
 - Add any other context about the problem here.

**Comment by rbudde** [comment]
I ckecked all other links. All are fine, except those for arduinos: three link to the funduino page, one links to the arduino.cc page. I propose to link all of them to the arduino.cc page and deploy this change with all the other changes of the next release.
