### ISSUE TITLE
Incorrect step numbers (Schrittnummer) in NAO simulation tutorial

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1146]
**Describe the bug**
In tutorial _Einführung in die NAO Simulation_ (available in Tutorials after switching lab language to `Deutsch`), the steps mentioned (schrittnummer) are incorrect.

**To Reproduce**
1. Go to `https://lab.open-roberta.org`
2. Click on language option, switch to `Deutsch` (in case default is some other language).
3. Click on `Tutorials` option, select tutorial _Einführung in die NAO Simulation_.
4. After _Schritt 1_, the next page is _Shritt 3_.

**Expected behavior**
Steps should be in correct order (_Schritt 1 => Schritt 2 => ..._).

**Screenshots**
![image](https://user-images.githubusercontent.com/43172112/142418461-7f737a60-d3a0-462e-a4be-e28e48b73622.png)

![image](https://user-images.githubusercontent.com/43172112/142418523-95300e81-383f-463b-bdd6-31624995c52b.png)

**Device information**
 - Type: Laptop
 - OS: Ubuntu 18.04 LTS
 - Browser: Firefox v94.0, Chrome v94.0.4606.81

**Additional context**
None

**Comment by aarindey** [comment]
<h3 class="quiz header">Schritt 2: Auf der Stelle drehen</h3>
