### ISSUE TITLE
Nepo4Arduino: Startup popup don't work if only one arduino plugin is active

### ISSUE THREAD

**Issue by pablopoo** [OpenRoberta/openroberta-lab#115]
**Describe the bug**
If only one arduino plugin is active (-d robot.whitelist=sim,uno -d robot.default=uno), the the startup plugin show the message "Robot not found" under the nepo4arduino icon.

**To Reproduce**
1.-Start the server with sim and uno plugin only: -d robot.whitelist=sim,uno -d robot.default=uno
2.-go to the startup popup

**Expected behavior**
 The popup screen must show the active arduino plugin. It works right now with the 3 plugins active (uno, nano, mega) or any combination of 2, but not if only one is active.

**Screenshots**

-1 active -d robot.whitelist=sim,uno -d robot.default=uno:

![imagen](https://user-images.githubusercontent.com/13492043/49966467-c086ad00-fefe-11e8-9dd1-90b1edfed0ec.png)

![imagen](https://user-images.githubusercontent.com/13492043/49966478-cc726f00-fefe-11e8-8c71-62e7c95ce415.png)

-2 active -d robot.whitelist=sim,uno,mega -d robot.default=uno:

![imagen](https://user-images.githubusercontent.com/13492043/49966389-9a610d00-fefe-11e8-9a88-a46321dd3111.png)

![imagen](https://user-images.githubusercontent.com/13492043/49966362-903f0e80-fefe-11e8-88c5-a75be23e2166.png)

**Comment by bjost2s** [comment]
won't fix
