### ISSUE TITLE
Debugging completely broken

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1155]
working on prod fine, but in actual develop:

- stepping doesn't work
- setting a breakpoint is possible, but ignored during execution
- if a breakpoint is set, you have to click elsewhere in the window, before you can unset the breakpoint

**Comment by PamoCurtis** [comment]
the problem is still present for the mBot

**Comment by rbudde** [comment]
2 imports in `robot.mbot.js` changed.
