### ISSUE TITLE
Calliope: local variables rename themself

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/openroberta-lab#116]
**Describe the bug**
 - Functions with local variable change the displayed local variable in use when your definition is placed under another function with local variable. This applies to functions with and without return value in any combination.

**To Reproduce**
1. Go to 'Calliope
2. Build the following Programms
3. Compile to Calliope or show code 
4. See the local variable change itself

**Expected behavior**
 - variables should keep their names

**Screenshots**
 - Generating this is fine:
![grafik](https://user-images.githubusercontent.com/25958792/49647787-f241d480-fa23-11e8-985b-079da03b15a5.png)
Generating this will produce the bug:
![grafik](https://user-images.githubusercontent.com/25958792/49647839-18677480-fa24-11e8-9758-30e04d2a64c3.png)

**Device information**
    Type: Laptop
    OS: Windows 7 Enterprise
    Browser: Firefox 63.0.3 (64-Bit)

**Additional context**
 - Code seems fine and programs work as expected on real calliope
- This was tested on the Testserver https://test.open-roberta.org//#

**Comment by bjost2s** [comment]
won't fix
