### ISSUE TITLE
Touch Sensor return value 1 and 0

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1162]
**Is your feature request related to a problem? Please describe.**
 - I need a integer return value of the touch sensor

**Describe the solution you'd like**
 - Integrate a drop down menue (like the light sensor) within the touch sensor - to select between - logic (true/false) and integer (1/0) 

**Describe alternatives you've considered**
 - A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
 - Add any other context or screenshots or a mockup about the feature request here.

**Comment by rbudde** [comment]
the ternary if solves the problem:
![2021-12-07 16_38_58-Open Roberta Lab](https://user-images.githubusercontent.com/15834363/145059755-883e6b33-0732-4d9a-9bcb-e3b00dda4814.jpg)

Nevertheless we'll discuss this request and decide about rejection or not:

- it must be done consistently for all sensors and
- is time-consuming to do
