### ISSUE TITLE
Arduino configuration allows selecting wrong pins for components

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#117]
**Describe the bug**
When configuring a component for arduino it is possible to:
- select the same pin number for different outputs (or inputs) of the component like this:
![image](https://user-images.githubusercontent.com/3738015/49522028-fac0d080-f8a6-11e8-94a3-96cf0433bd4b.png)
- select the same pin number for different components like this:
![image](https://user-images.githubusercontent.com/3738015/49522133-3b204e80-f8a7-11e8-8225-032035788f0f.png)
- select unsuitable pins (for example for analog output it is possible to select pins that do not support PWM) see image above. 

**To Reproduce**
1. Go to configuration tab of an arduino robot
2. Select unsuitable pins

**Expected behavior**
 - Either a message should be shown that the pin is in use, or available pin set should be reduced
 - Unusable pins should not appear in the list at all

**Additional context**

#756 is related

**Comment by bjost2s** [comment]
see #114
