### ISSUE TITLE
Mbot: inconsistent press button in simulation

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1180]
1. use the following program:
![2022-01-05 13_46_56-Window](https://user-images.githubusercontent.com/15834363/148220014-187d7648-d577-4d80-ac42-e0104cb972c9.jpg)
2. open the simlation tab
3. open the mbot robot window
4. run the simulation
5. the hello text appears

![2022-01-05 13_52_48-Window](https://user-images.githubusercontent.com/15834363/148220703-8e28bfbf-262d-43cb-a351-2f2295e01bcf.jpg)

On the upper left side there is a button to be clicked to repeat the output. This works fine, but a click on any point on the mbot robot window triggers the click, too. This behavior is unexpected.

**Comment by bjost2s** [comment]
fixed with the "new" simulation
