### ISSUE TITLE
Buttons disappear in other sim after opening Nao sim

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1186]
# **The Bug and how to Reproduce**
Just like the title says, system-view and sensor-view buttons disappear in other (debug) simulations after opening the NAO simulation 
- Select Nao robot
- Open simulation
- Close simulation
- Switch to any other robot that has a simulation (EV3, NXT, Microbit, Calliope, Mbot)
- Open (debug) simulation
- Buttons like sensor-view, system-view are not present

**Usual EV3 buttons in the simulation**
![Bildschirmfoto von 2022-01-06 14-35-00](https://user-images.githubusercontent.com/59732238/148391235-fb9ad2f3-d9b5-4d4d-8cc2-89114b415a66.png)
**and debug simulation**
![Bildschirmfoto von 2022-01-06 14-41-41](https://user-images.githubusercontent.com/59732238/148391874-8595157b-a970-4aa3-8a1c-e1503df6b0da.png)

**EV3 buttons after opening the Nao simulation and switching to the EV3 simulation**
![Bildschirmfoto von 2022-01-06 14-35-27](https://user-images.githubusercontent.com/59732238/148391343-ea4da1d3-6c4a-4dcd-8ecc-52855debdaf8.png)
**and debug simulation**
![Bildschirmfoto von 2022-01-06 14-42-14](https://user-images.githubusercontent.com/59732238/148391902-10858833-e370-4045-bffd-8e3561d01eaa.png)

**Comment by PamoCurtis** [comment]
There was one more problem: when having the microbit/calliope simulation started and switching to the Nao-simulation, the resetPose-button was missing, this is also fixed fixed with my PR.

**Comment by rbudde** [comment]
works as expected
