### ISSUE TITLE
Simulation disappears when sensor-view is outside the screen

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1188]
# **The bug**
This bug happens on every robot that has a simulation, sensor-view and robot-view.
The simulation turns white, when the sensor-view is below the bottom of the screen and you try opening the robot-view.
The sensor-view can be too long or just be dragged below the bottom of the screen.
**See screenshots**

## **To Reproduce**
1. open the simulation
2. open the sensor-view and drag it below the bottom of the screen
4. try opening the robot-view

## **Screenshots**
**The program (can be empty too)**
![Bildschirmfoto von 2022-01-06 16-23-53](https://user-images.githubusercontent.com/59732238/148409790-eb04cdf9-c5df-4746-879f-d106f8d8477a.png)

**Sensor-view goes below the bottom of the screen**
![Bildschirmfoto von 2022-01-06 16-24-16](https://user-images.githubusercontent.com/59732238/148409929-b210b0a9-be3e-48bd-bec4-db6743f414c1.png)

**after trying to open the robot-view**
![Bildschirmfoto von 2022-01-06 16-24-31](https://user-images.githubusercontent.com/59732238/148409984-1d5f20ac-a417-4a15-a605-2bce6975fa05.png)

## **Additional context**
This happens pretty quickly when adding too many variables or just two or more image variables, because every pixel value is displayed in the sensor-view when executing the code. 
So it would be good thinking about an alternative way of displaying the variables or at least the image variables because they need a lot of space in the sensor-view

**Comment by bjost2s** [comment]
works
