### ISSUE TITLE
Certain function names can lead to NAO sim errors

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1190]
**Describe the bug**
 - When using the NAO simulation the simulation throws an exception and is not fully exectued if the program contains a certain combination of blocks and function names.
 - e.g. when using the walk block and having a function named walk at the same time the function cant be executed because its overwriten by the internal function used in the simulation code generation,  [walk(a,b)](https://github.com/OpenRoberta/openroberta-lab/blob/6039bd8651145ee9dd92170c346d1691af8489d9/RobotNAO/src/main/java/de/fhg/iais/roberta/visitor/codegen/NaoPythonSimVisitor.java#L292) which expects parameters.
- walk is not the only function causing this for example the name turn and using a turn block results in the same error
- this is exclusive to the simulation since the code generation uses h.walk which cant be the name of an user created function

**To Reproduce**
1. Copy the program below or use this [link](<https://lab.open-roberta.org/#loadProgram&&nao&&NEPOprog&&%3Cexport%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%3E%3Cprogram%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22nao%22%20xmlversion=%223.1%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%22198%22%20y=%2299%22%3E%3Cblock%20type=%22robControls_start%22%20id=%22(93%5Ed/o8zA~GVcY%25;p);%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cmutation%20declare=%22false%22%3E%3C/mutation%3E%3Cfield%20name=%22DEBUG%22%3EFALSE%3C/field%3E%3C/block%3E%3Cblock%20type=%22robProcedures_callnoreturn%22%20id=%22uL*PzW~hxKRX~*AI)Z*m%22%20intask=%22true%22%3E%3Cmutation%20name=%22walk%22%3E%3C/mutation%3E%3C/block%3E%3Cblock%20type=%22naoActions_walk%22%20id=%22dCW6T(D_vTY!%7Dd*~aVU%25%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3EFOREWARD%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22d/*h7xsf%25S4fJDvQ8x6X%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E50%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%22200%22%20y=%22215%22%3E%3Cblock%20type=%22robProcedures_defnoreturn%22%20id=%22xdiJ@dS%5BGE=Lk)+Q+09%5B%22%20intask=%22true%22%3E%3Cmutation%20declare=%22false%22%3E%3C/mutation%3E%3Cfield%20name=%22NAME%22%3Ewalk%3C/field%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/program%3E%3Cconfig%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22nao%22%20xmlversion=%223.1%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%22138%22%20y=%2288%22%3E%3Cblock%20type=%22naoBrick_NAO-Brick%22%20id=%221%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cfield%20name=%22IP_ADDRESS%22%3E0%3C/field%3E%3Cfield%20name=%22PORT%22%3E22%3C/field%3E%3Cfield%20name=%22USERNAME%22%3Enao%3C/field%3E%3Cfield%20name=%22PASSWORD%22%3Enao%3C/field%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/config%3E%3C/export%3E>) 
2. Open your browsers console
3. Start the simulation

**Expected behavior**
 - Function names which are not visible to the user should not be able to be user created function names.
 - This can be achieved by adding a special character like `_` in front of the internal functions used for the simulation.

**Screenshots**
The program:
![image](https://user-images.githubusercontent.com/57675018/148550034-56c8b248-5d76-4345-ba1e-cc37cdb9fdb8.png)

The error:
![image](https://user-images.githubusercontent.com/57675018/148549993-3d4328ee-f205-4c22-96b4-bc6b0bb10e77.png)

**Additional context**
 - The cause of this issue is very similar to the one in issue #1191 but is affected by the NaoPythonVisitor
 - function names not created by the user should never be a possible function name for custom functions

**Comment by rbudde** [comment]
solved
