### ISSUE TITLE
a really simple integration test

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#120]
Often we have problems with a broken build of our front-end. This includes especially the build chain of blockly. As a consequence the front-end fails to start. We check this manually (very often).

It would be great to have a simple ("integration") test, that guarantess, that in almost all cases the front-end is ok. There are different possibilites:
- linting the Javascript source to detect (incomplete, wrong, ...) parts
- using a (simple!) selenium test to check that the front-end starts: clicking the intro and 2 or 3 menu entries would probably be enough for this problem.
- more ideas?

If somebody is interested in this, please write a comment with ideas, how to tackle this problem.

**Comment by bjost2s** [comment]
Too much work for us
