### ISSUE TITLE
Better Overview about Data in Sensor View during Simulation/Debugging

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1200]
The sensor view should show its data in a more structured way. Each group of data should be collapsable ("-") and expandable ("+").

Proposal:

1. group: simulator data. The first 5 entries. Initially collapsed
2. group: sensor data. Everything else but variables. Initially expanded
3. group: variables. Initially expanded.

**Comment by Shubham-Patel07** [comment]
I'm interested to work on this issue. please Can you guide me so that I can make my first contribution to an open-source project?

**Comment by bjost2s** [comment]
fixed with "new" simulation
