### ISSUE TITLE
Blocks are not immediately disabled after pasting them

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1204]
**Describe the bug**
 - When Copying an active block and pasting it the pasted block is enabled until touched even though he is not part of the program 
 - This can cause compiler errors due to the code generation being in unusual positions

**To Reproduce**
1. go to any robot 
2. take any block and attach it to the program
3. CTRL-C 
4. CTRL-V any number of times
5. generate code
6. see Error

**Expected behavior**
 - For everything but functions the pasted block should be disabled by default

**Screenshots**
 - Code is outside the main loop which should be impossible
![image](https://user-images.githubusercontent.com/57675018/150540121-24d39cbc-aaef-432a-8f44-6a24196c54cb.png)

**Comment by RaghuvirShirodkar** [comment]
Tested successful on `dev.open-roberta.org`.
