### ISSUE TITLE
For loop variables can be used outside of its scope

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1205]
**Describe the bug**
 - When using a for loop the counter variable wont stop you from generating and compiling code even if it's used outside of the loop it was created in
 - This causes compiler errors

**To Reproduce**
1. create a for loop
2. use the variable of that loop outside of it
3. see Warning
4. generate code or compile
5. see error

**Expected behavior**
 - There is a warning that you are using the variable wrong but the warning should a blocking error that stops you from generating wrong code

**Screenshots**
![image](https://user-images.githubusercontent.com/57675018/150541327-56497dcf-90d8-446d-9bb7-eea9de1c4c46.png)

**Comment by infernus01** [comment]
@heini208, I'd like to request you to assign this issue to me.

**Comment by infernus01** [comment]
Hi @heini208, please guide me on to how to recreate this issue and what packages/folders should I refer to?

**Comment by heini208** [comment]
@infernus01 sure let me first explain the issue again.
The Problem ist not in the code-generation this works as expected however the program shown in the picture should not be able to be generated. If you visit the Open-Roberta-Lab and build the program obove on any robot system you can see that you get a warning once you put the variables block "set i to x" outside of the for loop.

The problem is warnings dont stop the code generation on the right to be openable, but in this case it totally should.
So to put it short a warning is displayed where actually an Error should be displayed similar to this:
![image](https://user-images.githubusercontent.com/57675018/153596566-36083a7c-c4e7-4dca-9113-d58101ee36bb.png)

This is usually handled by a Visitor class in this case it should be the [CommonNepoValidatorAndCollectorVisitor.java
](https://github.com/OpenRoberta/openroberta-lab/blob/a5278052e5e83d4a23f3d969b4a86f8146485c2e/OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/validate/CommonNepoValidatorAndCollectorVisitor.java#L454) We have a method called addErrorToPhrase(Phrase, "ERROR_MSG"); which does exactly what we want.

This method should be called in visitVarDecleration() if the variable is a loop variable which is not inside its own loop.

PS: After looking into the issue a bit the warning comes from Blockly which is a library we use for all our Program blocks. You could first check if its possible to know wether or not the variable is outside of it's own loop, if that's the case we could remove the blockly warning afterwards.

**Comment by bjost2s** [comment]
related to #935

**Comment by RaghuvirShirodkar** [comment]
Tested successfully on test server with the following program:
[EV3LoopVarsOutside.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/10879271/EV3LoopVarsOutside.xml.txt)
