### ISSUE TITLE
Blocks related to deleted variables can be used by copy pasting

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1206]
**Describe the bug**
 - If you copy a program block of a variable and then remove that variable you can still paste the copied block causing invalid code

**To Reproduce**
1. go to any robot
2. create a variable
3. take a variable block like set variable x to 
4. copy that block with CTRL-C
5. remove the variable by clicking the minus
6. press CTRL-V 
7. See error

**Expected behavior**
 - the variable block should either not be pasteable or should show an error that stop code generation when used without the actual variable existing

**Screenshots**
 
![image](https://user-images.githubusercontent.com/57675018/150542377-f0952b89-c6b0-425a-9b5c-5125f9b164b2.png)

**Comment by rbudde** [comment]
works as expected
