### ISSUE TITLE
Occurrence of item block can cause runtime error in python

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1207]
**Describe the bug**
 - When using the Occurrence of item block in python and the item is not in the given list a runtime error will occur
 - The method list.index() used does not return -1 if the item is not included but instead throws an exception unlike java
 - as far as i know there is no alternative method which does not throw this exception
 
**To Reproduce**
1. Go to a robot that uses python like ev3 or mbot2 
2. Use the occurrence of item block and search for an item which is not in the list you gave it / or use this program [link](<https://lab.open-roberta.org/#loadProgram&&ev3dev&&NEPOprog&&%3Cexport%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%3E%3Cprogram%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22ev3%22%20xmlversion=%223.1%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%22602%22%20y=%22389%22%3E%3Cblock%20type=%22robControls_start%22%20id=%22@/2x6%5BbB%5BM8@vp1bK-V%5E%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cmutation%20declare=%22true%22%3E%3C/mutation%3E%3Cfield%20name=%22DEBUG%22%3EFALSE%3C/field%3E%3Cstatement%20name=%22ST%22%3E%3Cblock%20type=%22robGlobalVariables_declare%22%20id=%22)6:(%25W1,Z2D%7B)%7C%7B%7B6+li%22%20intask=%22true%22%20deletable=%22false%22%20movable=%22false%22%3E%3Cmutation%20next=%22false%22%20declaration_type=%22Array_Number%22%3E%3C/mutation%3E%3Cfield%20name=%22VAR%22%3Eitem%3C/field%3E%3Cfield%20name=%22TYPE%22%3EArray_Number%3C/field%3E%3Cvalue%20name=%22VALUE%22%3E%3Cblock%20type=%22robLists_create_with%22%20id=%22WppO6SX,%7CcgW,f%5BypNzx%22%20intask=%22true%22%3E%3Cmutation%20items=%223%22%20list_type=%22Number%22%3E%3C/mutation%3E%3Cfield%20name=%22LIST_TYPE%22%3ENumber%3C/field%3E%3Cvalue%20name=%22ADD0%22%3E%3Cblock%20type=%22math_number%22%20id=%22t/%5DUkR%7Dzr%25=Ha)cnoKC%7C%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E0%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD1%22%3E%3Cblock%20type=%22math_number%22%20id=%22Kg%7C@cMZ+Tjd97NCnIp2%5E%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E0%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD2%22%3E%3Cblock%20type=%22math_number%22%20id=%22ai4qCIqvO%60UW6FI@p%5BO1%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E0%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3Cblock%20type=%22robActions_display_text%22%20id=%22/o%7Cpz:v,5DEP2ekCx%25co%22%20intask=%22true%22%3E%3Cvalue%20name=%22OUT%22%3E%3Cblock%20type=%22robLists_indexOf%22%20id=%22x%5Ep)fxVra9%7C4%5Erv%7Dd_ZD%22%20intask=%22true%22%3E%3Cfield%20name=%22END%22%3EFIRST%3C/field%3E%3Cvalue%20name=%22VALUE%22%3E%3Cblock%20type=%22variables_get%22%20id=%22/3PD#%5E%7B=yP4+Y%5D%5DQSFVY%22%20intask=%22true%22%3E%3Cmutation%20datatype=%22Array_Number%22%3E%3C/mutation%3E%3Cfield%20name=%22VAR%22%3Eitem%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22FIND%22%3E%3Cblock%20type=%22math_number%22%20id=%22W!mW7!ylL%5E%5E/+q!/Fb~%5B%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E2%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22COL%22%3E%3Cblock%20type=%22math_number%22%20id=%22.kq%7CB:~e8,%5BkY-%5B%7Bj3L_%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E0%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ROW%22%3E%3Cblock%20type=%22math_number%22%20id=%22Ph5#6N@fdSR*PNOF:A%25t%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E0%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/program%3E%3Cconfig%3E%3Cblock_set%20robottype=%22ev3%22%20xmlversion=%223.1%22%20description=%22%22%20tags=%22%22%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%3E%3Cinstance%20x=%22213%22%20y=%22213%22%3E%3Cblock%20type=%22robBrick_EV3-Brick%22%20id=%221%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cfield%20name=%22WHEEL_DIAMETER%22%3E5.6%3C/field%3E%3Cfield%20name=%22TRACK_WIDTH%22%3E18%3C/field%3E%3Cvalue%20name=%22S1%22%3E%3Cblock%20type=%22robBrick_touch%22%20id=%222%22%20intask=%22true%22/%3E%3C/value%3E%3Cvalue%20name=%22S2%22%3E%3Cblock%20type=%22robBrick_gyro%22%20id=%223%22%20intask=%22true%22/%3E%3C/value%3E%3Cvalue%20name=%22S3%22%3E%3Cblock%20type=%22robBrick_colour%22%20id=%224%22%20intask=%22true%22/%3E%3C/value%3E%3Cvalue%20name=%22S4%22%3E%3Cblock%20type=%22robBrick_ultrasonic%22%20id=%225%22%20intask=%22true%22/%3E%3C/value%3E%3Cvalue%20name=%22MB%22%3E%3Cblock%20type=%22robBrick_motor_big%22%20id=%226%22%20intask=%22true%22%3E%3Cfield%20name=%22MOTOR_REGULATION%22%3ETRUE%3C/field%3E%3Cfield%20name=%22MOTOR_REVERSE%22%3EOFF%3C/field%3E%3Cfield%20name=%22MOTOR_DRIVE%22%3ERIGHT%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22MC%22%3E%3Cblock%20type=%22robBrick_motor_big%22%20id=%227%22%20intask=%22true%22%3E%3Cfield%20name=%22MOTOR_REGULATION%22%3ETRUE%3C/field%3E%3Cfield%20name=%22MOTOR_REVERSE%22%3EOFF%3C/field%3E%3Cfield%20name=%22MOTOR_DRIVE%22%3ELEFT%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/config%3E%3C/export%3E>)
3. upload that program to your robot system 
4. see error

**Expected behavior**
 - I think Javas behavior should be imitated by making a separate method which catches the exception and returns -1 if the item is missing in the list
 - Alternatively the block should mention the possible exception in the help view which is also currently missing for this block 

**Screenshots**
![image](https://user-images.githubusercontent.com/57675018/150553376-5ec3b7f9-c730-4692-b776-9224348765c1.png)
![image](https://user-images.githubusercontent.com/57675018/150553791-94b86c2b-db23-4b5d-a438-b5475be28320.png)

**Comment by bjost2s** [comment]
can only be solved in a sensible manner if we introduce exeption handlers in NEPO. This is different from the solution than proposed here and the effort is hight
