### ISSUE TITLE
Calliope color sensor TCS3472 is not usable

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1212]
The following programm is not compilable anymore:
![image](https://user-images.githubusercontent.com/1613069/151112133-23ed09bd-c11d-44ea-9d9a-d9d36904c5b3.png)
![image](https://user-images.githubusercontent.com/1613069/151112188-d86ae9e3-1a58-4651-b305-8588583240b3.png)

seems to be related to #1045, because before it was working
please also extend the tests for the colour sensor

**Comment by rbudde** [comment]
1. wrong pin declared for the color sensor (doesn't exist)
2. the checker doesn't distinguisl between "pin already used" and "pin doesn't exist". Thus, the error message is misleading
3. the checker doesn't detect overlapping on A1. The following program passes the checker, but should be rejected:
![2022-01-31 10_50_25-Window](https://user-images.githubusercontent.com/15834363/151772766-09ce254e-e907-46fe-a2de-fe592f5e8ff6.jpg)

![2022-01-31 10_50_00-Window](https://user-images.githubusercontent.com/15834363/151772797-7687144b-d9f2-4883-885f-55486f6dffd4.jpg)
