### ISSUE TITLE
Test/run source-code within OR Simulation

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1215]
**Is your feature request related to a problem? Please describe.**
 - for the ev3 (and other systems), it would be nice to have the ability to run modify the source code (c, python, java...) within the simulator

**Describe the solution you'd like**
 - Include a additonal button "Sim" which open the OR Simulation

**Comment by bjost2s** [comment]
Unfortunately this is impossible

**Comment by Thorlogy** [comment]
why?

**Comment by rbudde** [comment]
the generator of code for the simulation takes the blockly XML and translates it to some byte code, that is executed by the byte code interpreter of the simulation. Our simulation has no knowledge about the target language of the *real* robot (Python + Java for ev3, C++ for Calliope). If we get Python code edited by the user, for instance, what should we do? Program a full Python interpreter? Get Python running in the Javascript engine of a browser? the same for Java and C++? This is impossible for the team.
