### ISSUE TITLE
Motor A not responding to small values (20%)

### ISSUE THREAD

**Issue by doppelhammer** [OpenRoberta/openroberta-lab#1218]
**Describe the bug**
When connecting a mini DC-Motor to "Motor A" and sending 20% to Motor A, it reacts with full power and does not react to different values.
The same setup and a similar program work well with makecode.calliope.cc!!

**To Reproduce**
1. Connect a small DC-Motor to GND an "A*"
2. Program "Motor A with 20%"
3. Download to Calliope Mini
4. Motor goes with full power

**Expected behavior**
 Motor reacts to different values between 0 (off) and 100 (full power). Motor goes smaller and faster...

**Screenshots**
In makecode it works (motor goes on with a slow rotation rate)
![makecode](https://user-images.githubusercontent.com/64408442/153006629-6606d63f-5879-43d4-ac3e-1725532c1a3d.PNG)

In OpenRoberta it doesn't (motor goes on with full power)
![openroberta](https://user-images.githubusercontent.com/64408442/153006809-359742b6-68d8-4b2a-b70b-b5b46a8542b9.PNG)

**Comment by bjost2s** [comment]
@doppelhammer , we have fixed this issue and the fix is available on our test server, https://test.open-roberta.org. Could you please test it and report the result here? Thank you very much!
