### ISSUE TITLE
Misleading error message for not supported calliope communication blocks

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1225]
Attention, this bug is only for "calliope mini blue", so to reproduce please choose first "calliope mini blue"!

The following message appears when using at least one of the communication blocks
![image](https://user-images.githubusercontent.com/1613069/156165877-fcd121e5-0192-49c1-8f81-ae3bc1c8e020.png)

This message is misleading, because the program itself or the configuration are not affected here.
A better message should be attached to the communication blocks, similar like for the simulation (with a correct message text of course) like:
![image](https://user-images.githubusercontent.com/1613069/156166610-d36e36a2-b39f-4af7-ba42-56c0bae88a28.png)

**Comment by RaghuvirShirodkar** [comment]
It seems this issue was fixed, but never closed.

There are error messages annotated to the blocks not supported:
![image](https://user-images.githubusercontent.com/43172112/192974547-e47ad4b5-06c2-4758-85b0-da13d3fd545b.png)
