### ISSUE TITLE
Analyze the error logs

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1227]
the two error logs <month>.log and cc_errors.log contain too much errors. These errors are
- either to remove (or need at least an issue on github)
- or, if they are false alarms, to be removed (deleted or using a lower severity as ERROR (e.g. INFO))
Currently the <month>.log is flooded with calliope error, that appear, when the source code editor is used with invalid user-written c++ programs. This can be ignored, because this false alarm is already remedied in the develop branch.
Please contact @heini208, because he did an analysis in the past.

**Comment by bjost2s** [comment]
no time to work on it
