### ISSUE TITLE
improve message when a program is deleted and is shared

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/openroberta-lab#124]
If you try to delete or share one of your saved Programms, the corresponding window pops up for a very short amount of time and then disappears because the programm is loaded in the workspace.

![grafik](https://user-images.githubusercontent.com/25958792/43395942-33636e0e-9400-11e8-8288-c349a6438a11.png)

**Comment by boonto** [comment]
My first thought was to split it into two messages, one for your own programs. And one for programs shared with you.
However, as you can select multiple programs at once, including programs that are shared with others or shared with you, that would not make any sense.
I see three possible solutions:
1. One catch all message with all the info
2. 3 (your program, shared with you, multiple) messages with different info
3. Building up a fitting message depending on the selected programs

**Comment by boonto** [comment]
I went with option 1.

**Comment by bjost2s** [comment]
With this fix "POPUP_DISPLAY_HEADER" is declared a second time in blockly/robMsg/robMessages.js which leads to an error in the generated en.json. Please fix this.

**Comment by boonto** [comment]
The duplicate message seems to have been introduced a year ago and adding the semicolon revealed it. I'll remove the duplication.
