### ISSUE TITLE
Nao: Simulation problems 

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1247]
### Describe the bug
There are two problems:
1. When switching with an open simulation to the Nao-robot, the simulation won't close and an error is logged to the console. This won't happen if the Nao-simulation was already started once. *(See **Pic** for the error)*
2. When having the Nao-simulation running and switching with the open simulation to another robot, the simulation doesn't disconnect. That might not lead to any errors, but it's a waste of resources when the Nao-simulation is still running without being used. *(See **Gif** for the problem)*

### To Reproduce
Steps to reproduce problem No.**1**:
1. Go to the openroberta-lab website or refresh the page
3. Select a robot of your choice that has a simulation but not the Nao
4. Open the simulation
5. Now switch with the simulation still open to the Nao-robot
6. The simulation will still be open with the simulation running from the robot before
    - Go to the logging and see the error
    - The simulation won't close when clicking on the sim-button

Steps to reproduce problem No.**2**:
1. Go to the openroberta-lab website or refresh the page
2. Select the Nao-robot and open the simulation
3. Write a small program for the robot so it's clearer to see that the simulation is still running in the background
    - [NaoSimExample.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/8355481/NaoSimExample.xml.txt)
4. Start the program
5. Switch with the simulation still open and the program running to another robot
6. Switch back to the Nao-robot and open the simulation
    - The simulation is still running
    - The robot is still executing the program

### Expected behavior
 The simulations should close/disconnect automatically before switching the robots

### Screenshots/Gifs
**Pic**
![Bildschirmfoto von 2022-03-26 13-14-42](https://user-images.githubusercontent.com/59732238/160239017-755c4adb-9444-40e5-805c-80477eaf2f77.png)

**Gif**
![NaoSimIssue2](https://media.giphy.com/media/Csar4eG7VH3AqnIeaa/giphy.gif)

**Comment by rbudde** [comment]
works as expected
