### ISSUE TITLE
Openroberta-connector program travis CI doesn't work anymore

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1249]
Releases created by travis CI do not work anymore. Probable cause [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#what-will-happen-to-my-travis-ciorg-repository).

We propose using GitHub Actions for release purposes instead.

## TODO
- Create a new GitHub Action workflow.

## TESTS
- Released installers have to be tested against the different OS.

**Comment by RaghuvirShirodkar** [comment]
Added GitHub workflow instead of travisCI.

**Comment by rbudde** [comment]
- github action created
- release created for linux, win, mac
- release for win installed and tested. Works as expected.
