### ISSUE TITLE
[NXT] "sync" flag in NXC call leads to wrong movement

### ISSUE THREAD

**Issue by Stex** [OpenRoberta/openroberta-lab#126]
Possibly a continuation of #209

---

**Describe the bug**

When moving only one motor and trying to go forward afterwards, the motor with the smaller degree count is trying to sync up with the other one resulting in a fast curve motion.

**To Reproduce**
1. Write a program like the following:
   <img width="293" alt="image" src="https://user-images.githubusercontent.com/27221/48186256-c1448600-e337-11e8-8dd3-eab170ba01c2.png">
2. Send it to the NXT
3. The NXT will drive forward, turn left and then turn right quickly.

Video: https://drive.google.com/file/d/1Zk5IJ0oU0fkrdMjGfX8OZlFMQtPKq9eN/view?usp=download

Generated NXC code:

```c
#define WHEELDIAMETER 5.6
#define TRACKWIDTH 12.0
#define MAXLINES 8
#include "NEPODefs.h" // contains NEPO declarations for the NXC NXT API resources

task main() {
    SetSensor(S1, SENSOR_TOUCH);
    SetSensor(S2, SENSOR_SOUND);
    SetSensor(S3, SENSOR_LIGHT);
    SetSensor(S4, SENSOR_TOUCH);
    RotateMotorEx(OUT_BC, SpeedTest(40), (20 * 360 / (PI * WHEELDIAMETER)), 0, true, true);
    Wait(1);
    RotateMotor(OUT_B, SpeedTest(30), 360 * 1);
    RotateMotorEx(OUT_BC, SpeedTest(40), (20 * 360 / (PI * WHEELDIAMETER)), 0, true, true);
    Wait(1);
}
```

The problem here is the `sync` flag in `RotateMotorEx`: It leads to the motor which wasn't used in `RotateMotor` trying to catch up to the other one, leading to a very fast movement and therefore a curve.

Setting the `sync` flag to `false` in the second `RotateMotorEx` call solves the problem, but - of course - might lead to other problems again.

**Expected behavior**

1. The NXT drives forward
2. The NXT turns left
3. The NXT drives forward

**Comment by bjost2s** [comment]
Seems to be not solvable because regulated and unregulated functions influence each other when executed in the same program.
