### ISSUE TITLE
Small Changes to NN plugin

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1266]
Change requests:
- [x] weights and bias are shown in floating point mode. Show fix number of digits
- [x] thickness of arcs should be configurable between 5 and 10. Or set to 6, e.g.
- [x] remove the error message: key : value = TAB_NN : undefined and put all other texts in the msg files
- [x] the NNstep block should be usable more than once, the names of input and output neurons must match
- [x] for decimal numbers, allow both ',' and '.'
- [x] if a neuron is clicked, show the math for this neuron unconditionally
- [x] check, that neuron names in "get neuron value" exist. All names must be different.
- [x] code generator for pure nets in Java
- [x] It would be nice if the edge weights could also be entered as fractions (1/2 1/3...).

This ticket can be open for some time and should assemble small requests (~1h time for implementation).
From time to time it can be closed and reopened with an empty feature list.

**For new requests add comments. I (rbudde) will scan these comments and put them into the list**

List of change request, that will not be done (this may be discussed, of course!)
- representation of the NN as a matrix. REASON: many matrices are needed. Restriction to a single neuron is more user-friendly
- see the NN during run (automated training ...) so you could see the changes to the weights/biases. REASON: almost impossible due to timing problems

**Comment by Thorlogy** [comment]
It would be awesome if you could see the mesh during automated training so you could see the changes to the weights (similar to Tensorflow)....

**Comment by Thorlogy** [comment]
It would be nice to have a additional block: "get weight from ... to ..."

**Comment by Thorlogy** [comment]
With a view to a follow-up project, we should consider how smartphones can also be used for our KNN integration. For pupil could that gain a lot of fun.

**Comment by Thorlogy** [comment]
It should be possible to create at least 8 neuron within hidden layer

**Comment by Thorlogy** [comment]
Representation of the ANN as a matrix

**Comment by rbudde** [comment]
all comments so far moved to the item list

**Comment by Thorlogy** [comment]
Numbers with comma - instead of point - are "made" / convert to 0

**Comment by Thorlogy** [comment]
It would be nice if the edge weights could also be entered as fractions (1/2 1/3...).

**Comment by rbudde** [comment]
all comments so far moved to the item list.

This issue will be closed end of May

**Comment by Thorlogy** [comment]
the nn input and output Blocks should be pre-named (like variables) and functions

**Comment by Thorlogy** [comment]
Note in the tab -Neuronal Networks- : "In order to be able to program neurons here, you have to drag at least one input and one output neuron in the tab -Program NEPO- in the category >Neuronal Network< into the bracket >make a NN step<. 

--> A picture or gif, would be perfect

**Comment by Thorlogy** [comment]
for future updates: For the use in school classes it could be important to enable a possibility (interface) to upload files (CSV e.g. *Iris train  or some data set from SenseBox). In addition, it should be possible to display the sensor data display instead of a robot display.  

*https://gist.github.com/netj/8836201
https://github.com/ramp-kits/iris/blob/master/data/train.csv

**Comment by Thorlogy** [comment]
Integration of a Boolean activation function

**Comment by Thorlogy** [comment]
After clicking on a neuron (status = yellow), you cannot return it to its original status by clicking on it again. You have to click on another neuron or click on the drop-down "show values".

![image](https://user-images.githubusercontent.com/19221359/174791161-9ae545f7-b06a-46a7-b4ac-22115f873f20.png)
