### ISSUE TITLE
Colors of boxes in project library

### ISSUE THREAD

**Issue by joernalraun** [OpenRoberta/openroberta-lab#1269]
The different background colors of the boxes of the project library are quite nice, however on the darker ones the type is very hard to read. It would be good if there are only bright colors available as the type is always black and it would be great if color combinations are checked for different  accessibilities.

**Comment by joernalraun** [comment]
A possibility to change the color would also be great, so we could have certain project categories in one color etc.

**Comment by bjost2s** [comment]
"A possibility to change the color would also be great, so we could have certain project categories in one color etc." you might want to use tags for this, which is already available.
Only hight contrast colors should be supported in agreement with our designers

**Comment by rakshitgondwal** [comment]
Hey! Is this issue still open?

**Comment by sachinnandan** [comment]
I would like to fix this... Can i get this @joernalraun

**Comment by joernalraun** [comment]
From my point of view, of course! :) A color-picker (with pre selected colors that match the colors from the designer) might be the best way.

**Comment by bjost2s** [comment]
@sachinnandan , thank you, I will assign you. A good solution would be to change the color from #333333 to #ffffff

**Comment by RaghuvirShirodkar** [comment]
This is what the current implementation on `develop` looks like:
![image](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/5ccac53e-e93c-49fd-aa39-83c0e4da6b55)

Changing the text colour to `#FFF` from `#333` looks like this:
![image](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/c5239e12-091c-4991-92e3-b4c44377aa1c)

The relevant changes have been pushed to branch [fix/gallery-text-white](../tree/fix/gallery-text-white).

**Comment by bjost2s** [comment]
tested
