### ISSUE TITLE
Wrong spelling of BOB3 programming block "gib reflektiertes Licht Infrarotsensor" 

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1273]
see:
![image](https://user-images.githubusercontent.com/1613069/163205715-1763314d-e0aa-49e0-902f-e52b171e027a.png)

**Comment by RaghuvirShirodkar** [comment]
Tested successful on `dev.open-roberta.org`:
![image](https://user-images.githubusercontent.com/43172112/165938152-a055dbf4-6dd8-49a7-81ff-2c8d087cb73e.png)
