### ISSUE TITLE
Names of projects in gallery appear twice (parts of at least)

### ISSUE THREAD

**Issue by joernalraun** [OpenRoberta/openroberta-lab#1277]
It seems that for some reasons projects are displayed with a part of the original name.
All files should be saved the same, though some are displayed different. This might be a feature, but there is no obvious reason why they are shown and if they get the "second name" the original should be hidden.
 
<img width="417" alt="Gallery" src="https://user-images.githubusercontent.com/14014852/163384195-e5a39137-5765-47b0-b4e6-a738e3c62f88.png">

**Comment by bjost2s** [comment]
This is an undocumented feature of the gallery:
The first line of the program's documentation will always be displayed below the name of the program, like in your example.
We should explain this feature in the preview of the gallery tile.

**Comment by bjost2s** [comment]
@RaghuvirShirodkar , please create a new issue for the typo, because there is no time to fix it now
