### ISSUE TITLE
NXT reset encoder block shows more options than available

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1281]
**Describe the bug**
For NXT robot, the block `reset encoder ...` shows more options (4) than motor ports (3). See screenshot below.

**To Reproduce**
1. Go to `lab.open-roberta.org`.
2. Select `NXT`.
3. Click on toolbox `Sensors` -> `reset encoder ...` block.
4. See _erroneous_ options in the dropdown.

**Expected behavior**
`reset encoder ...` block should be represented with the correct number of options.

**Screenshots**
Incorrect number of options for `reset encoder ...` block:
![Reset Encoder Block](https://user-images.githubusercontent.com/43172112/164415550-582486d0-8c3e-4e06-8509-ab5bc0a3c017.png)

Number of motor ports in the configuration:
![image](https://user-images.githubusercontent.com/43172112/164415986-213548b2-dc29-448e-8c67-90d312d7e917.png)

**Comment by PamoCurtis** [comment]
Tested successful on `test.open-roberta.org`
