### ISSUE TITLE
Calliope mini robot: Button A and B as an selectable option 

### ISSUE THREAD

**Issue by joernalraun** [OpenRoberta/openroberta-lab#1285]
When working with buttons it would be more intuitive if the dropdown for button A and B would also have the option A and B integrated.

**Comment by bjost2s** [comment]
We think that users should use the logical AND to program this behaviour. This might also be a good learning effect.

**Comment by joernalraun** [comment]
I understand and the approach is close to the way you would code when typing, but when using A, B and A+B with this workaround it is not as easy to use in an application (have a look at "Tasten" from Calliope Code in the gallery on a device), as the execution is not as reliable as you would expect.
Therefore I have seen ways where people build rather complex functions only to make that that button press work as intended.
