### ISSUE TITLE
Ternary If - Empty Checker Missing

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1286]
the image shows an invalid program and the generated code. Expected: error message because blocks are missing
![2022-04-27 14_27_41-Open Roberta Lab](https://user-images.githubusercontent.com/15834363/165517949-cbc6610b-e60c-4cad-959a-eb527eef23c0.jpg)

**Comment by rbudde** [comment]
The problem is, that the ternary if is checked together with the regular if. The regular if gets a list of phrases in the then- and else-part, which may be empty. But this is illegal in ternary if.

One of many solutions: two methods in the visitors, one for standard, one for ternary.
Second solution: conditional processing depending on blockly type (less elegant)

**Comment by PamoCurtis** [comment]
Tested successful on `test.open-roberta.org`
