### ISSUE TITLE
Robot mBot2

### ISSUE THREAD

**Issue by gandalf222** [OpenRoberta/openroberta-lab#1289]
Can the Open Roberta Lab team add the mBot2 robot to the software?

Thanks...

**Comment by bjost2s** [comment]
This is already in work, will be pubished asap if we have solved the problem of uploading programs to the robot.

**Comment by gandalf222** [comment]
when is it operational?  this spring?

A segunda, 2/05/2022, 11:18, Beate Jost ***@***.***> escreveu:

**Comment by Carrascal1** [comment]
Dava muito jeito.
