### ISSUE TITLE
MBot2 - Integration 

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1292]
mBot2 also sometimes called mBotNEO is the successor to the original mBot unlike its predecessor it is using the  ESP32 based [CyberPi](https://education.makeblock.com/help/cyberpi-series-cyberpi/) as its control board. It can be found under a new subgroup for CyberPi based robots called CyberPi.

More Information about the mBot2 can be found [here](https://education.makeblock.com/mbot2/#:~:text=mBot2%20is%20a%20next%2Dgeneration,to%20upper%20secondary%20and%20beyond.). Additional information about the micropython API can be found [here](https://www.yuque.com/makeblock-help-center-en/mcode/cyberpi-api-shields#9eo89).

- [x] Check capabilities
- [x] Adapt compiler workers
- [x] Add crosscompiler resources: not needed!
- [x] Add code generation
- [x] Add reset worker
- [x] Revise empty checker for "steer direction" and "show serial monitor"
- [x] Add tests
- [x] Add background image
- [x] Add icon
- [x] Add wiki entries/help files
- [x] Check and support transfer/detection capabilities
- [x] Add transfer/detection capabilities https://github.com/OpenRoberta/openroberta-connector/issues/37

**Comment by heini208** [comment]
a reset worker is not needed because the mbot2 has multiple program slots and the ones used by the lab are not shared with preinstalled programs.

**Comment by pjfagulha** [comment]
When is the "simulation visualization" tool in the mBot 2 robot implemented?
When will the beta phase of the mBot2 robot end?
Thank you.

**Comment by bjost2s** [comment]
@pjfagulha, thank you very much for your interest,
"When is the "simulation view" tool in the mBot 2 robot implemented?"
Unfortunately, there are no plans yet to support the simulation for mBot2.
"When will the beta phase of the mBot2 robot end?"
As soon as we receive more positive feedback, especially for the newly supported communication blocks.
"When will I be able to transfer the generated code to the robot, without transmission errors?"
Please checkout the latest version from the connector program and report issues here. Our last tests ran without error.
