### ISSUE TITLE
Erroneous server error reported for cpp robots when creating lists + refactor function definitions for list-blocks

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1296]
A couple of issues related to lists are being reported in this issue:

* For NXT, when creating a list in the variable, the empty checker reports an error (expected) without the corresponding annotation to the blockly block (error):
  ![image](https://user-images.githubusercontent.com/43172112/167171319-73fac1ca-8a47-4930-9984-4ef1d75c75be.png)

* There is a weird error that is encountered when using lists. For cpp robots (Arduinos, Calliope, Mbot, etc), there is an error when a list is added as a variable. The empty checker works, but re-adding the missing value shows a server error nonetheless:
  ![image](https://user-images.githubusercontent.com/43172112/167110787-25ad7a90-cc50-4da3-ba38-2cedf27bdd8c.png)

* There is also scope to refactor some function definitions pertaining to list-blocks, since there is a fair amount of code duplication present. Common definitions should be moved to the parent class.

**Comment by rbudde** [comment]
it's great that the code duplicated are removed from the subclasses. Why are the 4 line checks added as copies many times in CommonNepoValidatorAndCollectorVisitor.java and not put into a private method?
From the ticket it is not really clear what has to be tested for the refactorings.

Nevertheless, I believe, that it works as expected. Tested with many variations of list creations for arduinos, nxt and calliope
