### ISSUE TITLE
Collection of (very) small changes

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1307]
Change requests:
- [x] distribute the nn blocks to the toolboxes. In the beginner toolbox: nn step, input and simple output neuron
- [x] select a final name for the new nn plugin: xNN
- [x] select a colour for the NN blocks
- [x] Name of the blocks, upper/lower case should be revised
- [x] the nn input and output blocks should be default names (like variables) and functions
- [x] Integration of a Boolean activation function 
- [x] After clicking on a neuron (status = yellow), you cannot return it to its original status by clicking on it again.
- [x] add get weight and get bias
- [x] xNN image for menu drop down
- [x] xNN image for start page
- [x] xNN image for configuration background (will be the ev3 image)
- [x] xNN image for the robot view in the simulation (will be the ev3 image)
- [x] add + and - button to edit card

This ticket can be open for some time and should assemble small requests (~4h time for implementation).
**For new requests add comments. I (rbudde) will scan these comments and put them into the list**

**Comment by Thorlogy** [comment]
After clicking on a neuron (status = yellow), you cannot return it to its original status by clicking on it again. You have to click on another neuron or click on the drop-down "show values". 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/19221359/174791010-91c352df-0a7c-4ae8-b132-95881912a6fd.png">

**Comment by Thorlogy** [comment]
Bug?

<img width="599" alt="image" src="https://user-images.githubusercontent.com/19221359/177157980-3d7b192a-5e56-40a1-8ba9-57d0083a0009.png">

wird ein NN Block deaktiviert, funktioniert das Program nicht

**Comment by Thorlogy** [comment]
@rbudde 
my a video explains more than i can with words..

https://user-images.githubusercontent.com/19221359/177318859-8d63518f-4a2b-41c7-b6b7-b88a1acd55d2.mov

**Comment by rbudde** [comment]
@Thorlogy  I cannot reproduce this. On dev4 the robot works independant of activation/deactivation of the block

**Comment by Thorlogy** [comment]
Categorie "Neuronal Network" has no german translation:

<img width="204" alt="image" src="https://user-images.githubusercontent.com/19221359/177333693-c88f6d68-31de-44af-89e4-31c52c0b74fb.png">

**Comment by rbudde** [comment]
**_--------- add NO new change requests here -----------_**
