### ISSUE TITLE
Improvements for lists

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1326]
The list create block could be annotated with the list index number, see screenshot
![image](https://user-images.githubusercontent.com/1613069/175257656-2425d525-8c5a-4178-8d3d-96e80f2d25b4.png)

This improves readability for long list

**Comment by rbudde** [comment]
don't forget another (really great) improvement for list create: #1298. Could be done together. Seems to be a good first issue?
