### ISSUE TITLE
Scrolling toolbox not possible

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#133]
With my asmartphone i can not scoll the toolbox.

![image](https://user-images.githubusercontent.com/19221359/38349925-811e699e-38a9-11e8-845d-ade4c1c47a48.png)

Browser: Chrome and Firefox
OS: Android 8
Display: 6 Zoll (15,24 cm)
Resolution: 2160 x 1080 Pixel

**Comment by philippmaurer** [comment]
I reproduced this bug in the iOS 10.3.3 Safari Browser and in the Roberta Mobile App on iOS and android.

**Comment by bjost2s** [comment]
There is a fox available here https://github.com/google/blockly/issues/1174
Unfortunately this fix is based on a version of blockly, that we do not support, so applying it is impossible. 
Once we fully sync with latest blockly this problem will be solved automatically.
