### ISSUE TITLE
buggy execution of nested if/else/if

### ISSUE THREAD

**Issue by jotwewe** [OpenRoberta/openroberta-lab#1340]
**Describe the bug**
The program as shown below (robot type mBot) makes the simulated bot rotate. The debugger shows that "if do" is correctly executed but execution continues with "turn right" before repeating the loop.
It does not matter whether the inner "if" evaluates to true or false.
Everything is fine once the inner "if" is removed.

**To Reproduce**
See screenshot below.

**Expected behavior**
 The bot should drive forward without rotating.

**Screenshots**
![Screenshot 2022-07-29 at 20-18-29 Open Roberta Lab](https://user-images.githubusercontent.com/4405433/181820733-27bfd77d-ec50-43c7-84b9-62be48c86ec4.png)

**Device information**
 - Laptop x86
 - OS: debian linux 11.4
 - Firefox 91.11.0esr and Chromium Version 103.0.5060.134 (Official Build) built on Debian 11.4, running on Debian 11.4 (64-bit)

**Comment by rbudde** [comment]
seems to be close related to #1291
