### ISSUE TITLE
Mbed-Plugin Validators refactor and issues

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1342]
**Describe the bug**
There are a few issues with the ValidatorAndCollector Workers and Visitors for robots in the RobotMbed Plugin.

- [x] the simulation validatorWorker does not check the configuration
- [x] the simulation validatorVisitor only shows warnings when using unsupported blocks, but should throw errors
- [x] Calliope has different workers for the same visitors, this is unnecessary since the same worker can be used in multiple property files
- [x] Similar issues should get tested for other robot plugins.

**Screenshots**
![image](https://user-images.githubusercontent.com/57675018/182832045-1368420f-b47b-432c-91ad-7d7197358942.png)
Sim can still be opened.

![image](https://user-images.githubusercontent.com/57675018/182832220-7a7ecc14-0507-482b-b249-dab333a1271e.png)
Sim can be opened even though there is an issue in the configuration

**Comment by bjost2s** [comment]
fixed with 924b48ed4f3d4487f90a3582c9dc8010fd578f5b
