### ISSUE TITLE
Display the system in use

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1358]
**Is your feature request related to a problem? Please describe.**
 - For users it would be helpful if they could see / read on which system their program will run. 
 - So far the message is: "Dein Programm xxx startet gleich auf dem Roboter." even if no robot is used. The english message is better "Your program »NEPOprog« will run in a moment!" 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/19221359/187180054-c44ac7fe-c7b5-40fb-920a-44ff67d5c069.png">

**Describe the solution you'd like**
 - Display the name of the system which is used. 

**Describe alternatives you've considered**
 - Use the english version.

**Comment by rbudde** [comment]
It is sufficient to remove the german words " auf dem Roboter" from the message. This is sensible for both real robots and simulation.

**Comment by rbudde** [comment]
solved
