### ISSUE TITLE
Calliope Mini: Can't using servo block and play sound block together inside a loop

### ISSUE THREAD

**Issue by MarkusBordihn** [OpenRoberta/openroberta-lab#1360]
**Describe the bug**
I try to play a sound and moving a servo in the case the A or B button is pressed.
This works fine separate, but it's not working if I want to play a sound and moving a servo at the same time.

**To Reproduce**

1. Connect a servo to the Calliope Mini (with extra/separated power)
2. Create a simple program which includes a play sound and servo command inside a loop
3. Run the program

The calliope is not playing the sound and/or moving the servo at the same time.
Most of the time there is no sound and the servo is also not moving correctly.

**Expected behavior**
I wound expect that the play sound and servo block are independently from each other inside a loop.

**Screenshots**
![image](https://user-images.githubusercontent.com/12183293/187937157-48b27ec5-c992-42fc-9385-7aa075a09e86.png)

![image](https://user-images.githubusercontent.com/12183293/187938934-d0c9c8ca-884d-4904-96e4-3063b9f1653a.png)

**Additional context**

- The first play sound and servo move block outside the loop seems to working fine.
- In the case I only playing the sound OR moving the servo this works fine as well.
- I tried different PINs (like P1, P2, C04, ...) for the servo, but without any difference.
- Adding a additional delay between both commands seems to have no affect as well.

**Comment by bjost2s** [comment]
This is a hardware problem of calliope that we cannot fix, because there is only one driver for motors **and** sound. They cannot be used together. For further information please contact calliope.
