### ISSUE TITLE
Calliope Mini: No separated blocks for analog and digital pin operations

### ISSUE THREAD

**Issue by MarkusBordihn** [OpenRoberta/openroberta-lab#1363]
**Describe the bug**
Inside the robot configuration the digital and analog sensors and actors are separated, which makes sense because not all ports/pins supports analog or digital signals.

![image](https://user-images.githubusercontent.com/12183293/188984678-5875d0f7-5142-46c4-955a-fb1f0d6683d2.png)

But the corresponding building blocks like **write digital** and **write analog** are not separated.
This creates confusions and makes it hard to document the single steps.

![image](https://user-images.githubusercontent.com/12183293/188984558-570303e7-b847-4b52-bb8b-a29b62a8466f.png)

**To Reproduce**
Simple example for adding a digital read block you have to perform the following steps:
- Move the **get analog value** block to your program
- Click on the select box and change **analog value** to **digital value**
- Adjust the port to the corresponding pin

The similar steps are needed for **pulse time HIGH** or **pulse time LOW** which are normally only available for digital pins.

**Expected behavior**
I would expect that analog and digital blocks are separated the same way like for the robot configuration to avoid any confusions for the user and to make it easier for the user to find the correct block for their use-case.

It's hard to explain why a kid needs first to move a **analog** block to their program and change it to **digital** later or the other way around.

For this reason my request is to create separate blocks for **analog** and **digital** actors and sensors.

**Comment by rbudde** [comment]
the same argument applies for micro:bit and arduinos, nano33ble and sensebox

**Comment by rbudde** [comment]
done for the robots/embedded systems ardu, nano33bl3, sensebox, calliope, microbit. Will be deployed end of this week.
