### ISSUE TITLE
copy and past of blocks BETWEEN different programs

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#137]
I use a function to explain what I want. I have written a function and want to use it in another program.
Many solutions are possible, but at least one should be available:
- copy in one program, open another program, paste and get the function.
- save the function in the lab using name "myFunction" and have a new menu entry "import fragment"
- drag and drop between different browser instances.
I prefer the first solution.

**Comment by bjost2s** [comment]
seems to be only related to #104

**Comment by bjost2s** [comment]
item 1 (copy in one program, open another program, paste and get the function) is already available!
+1 for item 2 as an addition

**Comment by corvus-albus** [comment]
Sorry for asking, but is it possible that item 1 is no longer possible? I knew that I once tried it successfully but either I do not remember how or it does not work any longer.
If it still works, it would be nice to hav some instructions in openrobertalab.
Cheers corvus-albus
