### ISSUE TITLE
Festobionic Flower: User defined functions not being generated!

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1370]
**Describe the bug**
User defined functions are not being generated for Festobionic Flower. The function signature is generated, however, the actual function body is missing.

**To Reproduce**
1. Go to `lab.open-roberta.org`
2. Click on `Festobionic Flower`
3. In `Expert` -> `Functions` toolbox, select any block to define a function.
4. Click on `Open/close source code view`
5. See (or don't!) missing function body.

**Expected behavior**
User defined functions (both signature and body) should be properly generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/43172112/191996314-3a0ff181-862d-48fc-99e5-ce9fd7d2be5d.png)

**Device information**
 - Type: Desktop
 - OS: Ubuntu 20.04
 - Browser Firefox 104.0

**Comment by bjost2s** [comment]
additionally tests for the Flower plugin are added!
