### ISSUE TITLE
[Continuation] Refactor AST classes to use annotations

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1371]
**This issue is a continuation of the [hackathon held previously](https://github.com/OpenRoberta/openroberta-lab/issues/1319).**
The Idea is to refactor all AST classes to use NepoAnnotations, as well as structure the code in a uniform manner, as far as possible. 
The current status of the AST classes is stored in a separate excel doc in Teams. This work is done by the core developer.

**Comment by bjost2s** [comment]
won't fix
