### ISSUE TITLE
Distribute XML/AST/validator/code generator tests to the robot plugin

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1382]
Currently the project `OpenRobertaServer` contains the very important tests `ReuseIntegrationAsUnitTest` and `TestToolboxBlocksAreUsedInTestFiles`. These tests are repsonsible for checking
- XML -> AST works
- XML -> AST -> XML works
- XML -> Java/C++/Python works
- that all blocks from the toolboxes are used in the tests.

These tests come in 2 flavors:
- common tests, that are used for al robots (testing if, while, ...)
- robot specific tests, that are used to test robot specific adaptions, but especially robot specific sensors and actors.

Goal:
- move the common test to `OpenRobertaRobot` (where it belongs to)
- move the robot specific tests to each robot plugin

Afterwards the project `OpenRobertaServer` should be free of this kind of tests. Writing plugins becomes easier (we want to avoid, that a new plugin **must** change the projects `OpenRobertaRobot` and `OpenRobertaServer`

**Comment by bjost2s** [comment]
not time to work on this
