### ISSUE TITLE
small enhancements for C (and Python) code generator

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#139]
- [x] 1. #define a constant for the sleep-time (wait blocks, ...).
- [x] 2. #define a constant for 255.0/9.0, which is used at many places for calculating the brightness
- [ ] 3. replace the pattern if (... == true) by if(...) and if(... == false) by if(! ...). Actually the patterns are mixed (I see both (... == true) and (...)
- [x] 4. replace while(true) by while(1) or vice versa. Actually we have a mix.
- [ ] 5. the layout of a label used in a generated goto (from a "break out from loop") is broken
- [ ] 6. we generate dead code after a generated goto (from a "break out from loop")
- [ ] 7. if a programmer chooses as function name a name used by the mbit runtime, e.g. "release_fiber", the compiler bails out. We should decide whether we ignore that or have a server side checker detecting this (will be a lot of names) or use prefixing to decrease probability of clashes or ...

These are small enhancement. May be done if there is time :-)

**Comment by bjost2s** [comment]
unclear status
