### ISSUE TITLE
Multiple robot simulation with xNN

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1394]
**Is your feature request related to a problem? Please describe.**
 - it would be nice if several robots could be simulated in the "xNN Plugin"

**Describe the solution you'd like**
 - The solution should be like e.g. in the "lejos plugin"

**Comment by rbudde** [comment]
currently impossible. Needs a substantial rewrite of the xNN evaluation.

**Comment by rbudde** [comment]
seems to be already solved :-)
