### ISSUE TITLE
Integration tests - file comparison with newline character

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1398]
Most of our generated programming languages like C, C++, Java have a statement seperator-terminator (often`;`), but some like Python and Aseba are terminated by a newline separator. Currently we do not check for these newline characters in our integration tests which makes them not really realiable. 
We should test for newline characters when comparing generated and expected source code for Python and Aseba.

**Comment by rbudde** [comment]
to be deployed 2022-10-29 04:00:00
