### ISSUE TITLE
Lower case names in robot configuration break program

### ISSUE THREAD

**Issue by lochotzke** [OpenRoberta/openroberta-lab#14]
**Describe the bug**
Using Nepo4Arduino you cannot use lower-case names in the robot configuration without breaking the program. Upper case names work. This seems to be similar to #2.

**To Reproduce**
1. Start a new program with Nepo4Arduino.
2. Change the LED name from L to foo in the robot configuration.
3. Add the "LED foo on" block into the program.
4. Open the source code view.
5. "In der Roboterkonfiguration ist dieser Aktuator nicht mit einem Actorport verbunden!" is displayed.

**Expected behavior**
Changing the name as described here: [instructions](https://jira.iais.fraunhofer.de/wiki/display/ORInfo/Programmieren+Arduino#ProgrammierenArduino-Roboterkonfiguration) should be possible.

**Screenshots**
<img width="927" alt="Screenshot 2019-04-28 at 20 29 07" src="https://user-images.githubusercontent.com/496177/56868570-5295da80-69f4-11e9-980f-25e79398375b.png">

**Device information**
 - Type [Desktop/tablet/smartphone]
 - OS: macOS 10.14.4
 - Browser Safari 12.1 and newest Google Chrome

**Comment by VinArt** [comment]
solved in #2, it seems
