### ISSUE TITLE
Bionic Flower öffnet/schließt nicht

### ISSUE THREAD

**Issue by ckaschny** [OpenRoberta/openroberta-lab#1407]
**Describe the bug**
 - Flower kann sich weder öffnen noch schließen (so wie im NEPO-Code programmiert). "zurück auf Werkzustand" half nicht das Problem zu beheben.
  
**To Reproduce**
1. Flower mit Open Roberta Lab verbinden
2. "zurück auf Werkzustand"
3. NEPO-Programm auf Flower übertragen (Screenshot unten)
4. Blume bewegt sich nicht (kein öffnen/schließen), aber der Motor ist hörbar aktiv. Das Wechseln der LED-Farben funktioniert. 

**Expected behavior**
 - Die Blume sollte sich bei Berührung schließen und nach einer Pause wieder öffnen.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/21109380/202440838-c8d4e0a2-cd05-44c2-8e64-e15ab5ebe6bd.png)

**Device information**
 - Windows 10
 -Open Roberta Lab , Open Roberta Connector 1.5.0
 - Chromium Browser

**Comment by bjost2s** [comment]
not reproducable
