### ISSUE TITLE
Change Robotino serial write block

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1413]
**Is your feature request related to a problem? Please describe.**
 - Currently the output of the serial write block for the Robotino is not really usable as it requires deep understanding about how the implementation functions and even then it's very cumbersome to access. 
 
**Describe the solution you'd like**
- A potential alternative could be to save the printed text into a variable which can then be watched inside the Robotino Web-interface.
- Depending on how the Web-interface displays variables, the implementation could either just show the last print or show every print thus far.
- Since even that is not very intuitive to use but very useful for implementation and debugging of features, the serial write block could be removed from the expert toolbox and the Debug block (CNTRL-2) could be used instead.
- In any case the SerialWriteBlock should be removed and a renamed block should be added to avoid confusion

**Describe alternatives you've considered**
 - If the above idea does not work, the block should still be removed as it's basically unusable

**Comment by heini208** [comment]
To make a program available to the web-interface, all you have to do is put it into the directory /home/robotino/programs. This can either be done via ssh or the rest API with a POST to /data/uploadProgram.

Starting and stopping a program is done by using this function in the web-interface program.html with a PUT request:
with data being an object that resembles the program to be started/stopped:


`function actionCellClick(e, cell)
{
  var row = cell.getRow();
  var data = row.getData();
  
  console.log(data);
  
  //gtable.clearData();
  //otable.clearData();
  
  $.ajax({
		url: "data/startStopProgram?sid=" + RobotinoRESTsession,
		type: 'PUT',
		data: JSON.stringify(data),
		contentType: 'application/json'
	});
}`

![image](https://user-images.githubusercontent.com/57675018/209333440-0e723385-d71a-4949-97d4-e100603003a7.png)
Data for the view-program "Circle-Kreis" which is the first program in the list (id=1)

**Comment by bjost2s** [comment]
no time to work on it
