### ISSUE TITLE
Open Roberta App - Simulation not working

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1416]
**Describe the bug**
 - The app on android but when I enter on the simulation, the logo of open roberta appears instead of the map and the robot.

**To Reproduce**
1. Go to 'Play Store and download the Open Roberta App'
2. Start the app and choos another robot e.g. Open Roberta Sim 
3. Click on  'SIM'

**Expected behavior**
 - The Simulation starts

**Device information**
- Type android smartphone e.G Pixel 6, 
- Android version: 12Open Roberta app version: 1.0.1
- Motorola X4: Android version: 9 Open Roberta app version: 1.0.1

**Comment by bjost2s** [comment]
the android app is not supported anymore
