### ISSUE TITLE
Robotino Simulation: endless loop when using "drive ... distance cm"-block

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1428]
**Describe the bug**
The robot does not stop driving when setting the distance value of the **'drive x speed %, y speed %, distance cm'**-block **(robActions_motorOmni_curve_for)** to zero. No other blocks will be executed after this.

**To Reproduce**
1. Go to dev.open-roberta.org and select Robotino
2. Import [robotinoDriveDistanceBug.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/10219517/robotinoDriveDistanceBug.xml.txt) **(you need to remove the '.txt' first)**
3. Open and start the simulation

**Expected behavior**
Since the distance is set to zero, the robot shouldn't move and it might be good if a warning is displayed that the distance should not be zero

**Comment by RaghuvirShirodkar** [comment]
The issue seems to be partly fixed, as the robot does seem to move a little bit even when distance = 0:
 
![Test](https://user-images.githubusercontent.com/43172112/223398555-8388a512-7d8c-4cc2-a8ea-c09271eed64f.gif)

In the `System Values` on the right, one can see the `Robot X` values changing.

**Comment by rbudde** [comment]
works as expected
