### ISSUE TITLE
Spike Prime / Robot Inventor Integration

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1435]
Integrate robot [Spike Prime / Robot Inventor](https://education.lego.com/en-gb/products/lego-education-spike-prime-set/45678#spike%E2%84%A2-prime) in the OpenRoberta Lab.

- [x] Check robot capabilities
- [x] Add code generation (Micro Python)
- [x] Add configuration (differential drive)
- [x] Add tests
- [x] Add background image
- [x] Add configuration image
- [x] Add icon
- [x] Add wiki entries/help files
- [x] Add program transfer possibilities in the [Connector Program](https://github.com/OpenRoberta/openroberta-connector)

**Comment by bjost2s** [comment]
forgotten issue linking 14c90adbb60498f270b1e3b0e6f060a723b629a4

**Comment by rbudde** [comment]
link to LEGO couls not be supplied due to legal reasons. Works as expected.
