### ISSUE TITLE
Mbot2: Open Roberta Connector program serial monitor does not display output

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1436]
The mbot2 robot has the functionality to write data to the serial port, but the ORC serial monitor does not display this data. This should be fixed

**Comment by RaghuvirShirodkar** [comment]
Tested source code on `openroberta-connector`. Supported robots (defined in `robots.properties` in the below commit) can now use the serial monitor in Open Roberta Connector program.
Related commit [here](https://github.com/OpenRoberta/openroberta-connector/commit/f44716d6b3073fc73cff4e4808f03f99f0677b53).

**Comment by RaghuvirShirodkar** [comment]
Tested on mBot2 with latest Open Roberta Connector app (v1.6.3). Serial monitor works as expected.
