### ISSUE TITLE
Edison: try / catch not supported

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1439]
The following program [EdisonExceptionTest.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/10354031/EdisonExceptionTest.xml.txt) cannot be tranferred to edison, the reason is the not supported try / catch statement:
![image](https://user-images.githubusercontent.com/1613069/210835457-1953568b-4773-41fb-ac90-c3584550ebcd.png)

Maybe there is an option to work with newer/better firmware, this should be checked before trying to solve this bug. The solution might not be easy to implement.
I checked one of our edison yesterday, there is no update for the firmware available (@bjost2s ), so:
A quick workaround would be to simply remove "break" and "continue" from the toolboxes.

**Comment by bjost2s** [comment]
fixed in 081d23be14c9fdee9947640c4626de0b657b132a, together with #1446

**Comment by RaghuvirShirodkar** [comment]
Tested successfully on test server. Toolbox does not contain `break out`/`continue with next iteration` block for Edison.
