### ISSUE TITLE
Return compiler output as feedback to users

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#144]
For many robots the program is compiled serverside and we get errors/warnings from the compiler.
We should add functionality to display the compiler output to the user.
The different errors/warnings should be mapped to user friendly messages or may displayed raw by choice.

This would also remove the need of restricting user defined variable/function names in some cases (see 7 of #766): the user is notified of overwriting existing functions/variables/keywords.

**Comment by rbudde** [comment]
beautification of the error message is needed, scrollbar or compiler specific cleanup. The latter must be an issue of its own for the next release.

Except that, resolved.

**Comment by boonto** [comment]
Shows nice message that gives more information than previously: ![image](https://user-images.githubusercontent.com/7438960/61795717-58992d00-ae24-11e9-8a61-a6c2de418b5b.png)

**Comment by ensonic** [comment]
Nice, but a few comments:
* can we make the dialog wider?
* can we replace the path of the tmpdir? Just having `/NEPOProg/... would be enough.

I also wonder that some people might be confused by the `[1/3]` output and expect 2 more messages.

**Comment by bjost2s** [comment]
For one of the next releases we will consider a more readable output of the error messages. Because of many different compilers (and output of compilers) that we use, evaluating all compiler outputs in general is a big task, we need more time.
