### ISSUE TITLE
Mbot2 Broadcasting feature (Communication between mBot2s) 

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1441]
**Is your feature request related to a problem? Please describe.**
 - CyberPi supports multiple types of broadcasts. With these broadcasts, CyberPi can implement communication between threads and devices on LAN's and the Internet
 - Documentation can be found [here](https://www.yuque.com/makeblock-help-center-en/mcode/cyberpi-api#Lh6Hs:~:text=to%20be%20translated-,Broadcast,-CyberPi%20supports%20multiple) 

**Describe the solution you'd like**
 - This still needs to be discussed in more detail
 - new blocks should be added so that a user can upload programs onto different mBot2s which are able to communicate with each other
 -  works without connecting to Wi-Fi
 - A mBot2 can send a message and value and another mBot2 can get the value of that message 
 
**Additional things to look out for**
- There seems to be no buffer, which means that if a blocking action is used while receiving a message the message will be lost 
![image](https://user-images.githubusercontent.com/57675018/211833093-6efd0eec-a32d-45e4-9ddb-d9173942b48b.png)

**Comment by RaghuvirShirodkar** [comment]
Tested source code on test server. Block category `Messages` is now available with `send message` and `receive message` blocks, with method calls to `cyberpi.wifi_broadcast.set()` and `cyberpi.wifi_broadcast.get()` respectively.
