### ISSUE TITLE
Mbot2 getLine Block is confusing and hard to use

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1442]
**Is your feature request related to a problem? Please describe.**
 - The getLine Block is not very intuitive, you will need a table open to and a bunch of if clauses to make actual use of this function
 - Instead, the RGB values of the quadRGB sensor should be used as a light sensor similar to other robot systems.
 
---
 - Also, the getLine block could be replaced by the [get_offset_track](https://education.makeblock.com/help/mblock-python-editor-apis-for-mbuild-modules#:~:text=quad_rgb_sensor.get_offset_track(index%20%3D%201)) [is_line](https://education.makeblock.com/help/mblock-python-editor-apis-for-mbuild-modules#:~:text=quad_rgb_sensor.-,is_line,-(ch%2C%20index%20%3D%201)) block
 - The getOffset track is not very detailed about the information off that line it seems like it is only checking if the line can be seen in one of the four color sensors and then gets an arbitrary value related to that
 

**Describe the solution you'd like**
 - A new block should be added: "get Light quad RGB-Sensor X ..." 
 - This block should use the RGB info of one or more RGB sensors in the quadRGBSensor
 - A standard formula for this calculation appears to be: ((0.2126*R + 0.7152*G + 0.0722*B ) / 255 ) * 100

**Describe alternatives you've considered**
 - This block could also be added to the drop-down of each sensor of the quadRGBsensor
![image](https://user-images.githubusercontent.com/57675018/211843188-1e547bce-d425-4799-b215-2ea9199a7a18.png)

**Comment by RaghuvirShirodkar** [comment]
Tested source code on test server. Block `get ... quad rgb sensor` now has a `light` mode, with generated method call `mbuild.quad_rgb_sensor.get_gray()`.
