### ISSUE TITLE
Indicate where blocks modify the input (e.g. clip max speed)

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/openroberta-lab#145]
Assume a block like:
```
[ Drive forward speed % ] [ 5000 ]
```

Since the speed value is to be given in percent, we will limit the input to a value from 0...100. It would be nice to indicate the to the user. We could do this with a checker. Ideally we put the warning sign into the number box though.

**Comment by rbudde** [comment]
this is a runtime clipping of values. We can add text in the help like "the value will be clipped to 0...100. But in _general_, we can't do that with a checker: there may be used an arbitrary expression
