### ISSUE TITLE
GyroReset, TimerReset and EncoderReset AST classes are erroneous

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1452]
**Describe the bug**
Some *Reset AST classes (GyroReset, TimerReset, EncoderReset) are setup incorrectly, wherein an additional `field` SLOT is being added to the XML. As a result, the robot specific XML programs had to be manually updated to be run successfully, which should **never** be the case.

These classes and the relevant tests need to be corrected to reflect correct usage of the AST classes.

**To Reproduce**
1. Go to `lab.open-roberta.org`
2. Click on any EV3 robot.
3. Create a test program with the erroneous *Reset AST classes.
4. Open console and see warning, signifying erroneous SLOT in the XML.

**Expected behavior**
There should be no error/warning reported in the console.

**Device information**
 - Type: Desktop
 - OS: Ubuntu 20.04
 - Browser: Firefox 109.0.1

**Additional context**
All test programs should be created/imported in/to the lab and then exported to have the correct, lab supported version of the XML program.

**Comment by PamoCurtis** [comment]
Tested successfully on dev Server, no warnings where logged in the console
Program: [Ev3Issue1452.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/10934133/Ev3Issue1452.xml.txt)
