### ISSUE TITLE
Introduce "deprecated" property for plugins / systems

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1455]
Over the years we have integrated a couple of systems and some of them are / become outdated now and we would like to remove them from our platform (and repo)

To inform the users we should introduce a new property "deprecated" connected with the following actions:

- label the deprecated system with a stamp in the start popup, similar to "beta"
e.g.
![image](https://user-images.githubusercontent.com/1613069/218969852-af3f8054-783f-4b54-af3a-acffdaa9a6c3.png)

- react to the user choise for a deprecated system with a warning popup, explaining what happens and providing information for workarounds (alternative systems, how to update, etc). This warning should appear each time the deprecated system is chosen.
- explaining reasons and workarounds in our [wiki](https://wiki.open-roberta.org)

**Comment by RaghuvirShirodkar** [comment]
Tested the following points on [test server](https://test.open-roberta.org/):

- [X] label the deprecated system with a stamp in the start popup, similar to "beta".
- [X] react to the user choise for a deprecated system with a warning popup, explaining what happens and providing information for workarounds (alternative systems, how to update, etc). This warning should appear each time the deprecated system is chosen.
- [ ] explaining reasons and workarounds in our [wiki](https://wiki.open-roberta.org/).

There seems to be a new "bug" now. The icons for the robots in the start carousel are shifted to the right/not centered:
![image](https://user-images.githubusercontent.com/43172112/222656174-8d8c98fb-1efe-4d24-a64c-ad177c876c83.png)

Maybe related to this issue?

**Comment by rbudde** [comment]
works as expected
