### ISSUE TITLE
Help users to understand large numbers (e.g. beep for 7000000000 ms)

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/openroberta-lab#146]
I notices that some kids like to use large numbers. A common case where this can be problematic is the duration on the beep block. I even heard the justification "it is just milliseconds". It would be nice to show the kids how much the value is actually in years, month, days, hours, ...

This could be done:
* as a comment in the generated code
* as a dynamic comment on the block itself (needs to be refreshed when the input changes)

The checker is probably not the right place, since we don't want to add a hard limit.

**Comment by bjost2s** [comment]
see #114
