### ISSUE TITLE
Sprachen-Mix

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1465]
**Describe the bug**
 -In der Ansicht "Sensordaten" gibt es einen Mix aus Deutsch und Englisch" 

**To Reproduce**
1. Go to 'OR Lab'
2. Click on 'SIM' and Click on "Öffene die Ansicht der Sensordaten"
3. See error

**Expected behavior**
 - Wenn die Sprache Deutsch ausgewählt ist sollte alles auf Deutsch angezeigt werden

**Screenshots**
<img width="315" alt="image" src="https://user-images.githubusercontent.com/19221359/223956257-1feafdd8-c15f-4a96-af15-d1fa06ef5912.png">

**Device information**
 - Browser: Chrome. Version 110.0.5481.177

**Comment by bkochsickm** [comment]
Getestet
