### ISSUE TITLE
Only Englisch "Move-over" text/hint

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1468]
**Describe the bug**
 - A clear and concise description of what the bug is.

**To Reproduce**
1. Go to 'Open Roberta Lab'
2. Login 
3. Click on "Bearbeiten" and on "meine Programme..."
4. Move mouse over the first green square button in the right corner 
5. See "error"

**Expected behavior**
 - Germen text

**Screenshots**
<img width="572" alt="image" src="https://user-images.githubusercontent.com/19221359/224932365-33013ab7-30f3-420a-ad1e-aea35668f384.png">

**Device information**
 - Browser: Chrome (latest version)

**Comment by bjost2s** [comment]
fixed with #1568
