### ISSUE TITLE
Renaming programmes

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1469]
**Is your feature request related to a problem? Please describe.**
- If i want to rename a existing program i have to load the program and to save it with a different name. This is a bit inconvenient, especially as the old programme is still in the overview with the old name.  
- 
**Describe the solution you'd like**
 -  In the overview of saved programes, another button would be helpful with which programme names can be changed (renamed).

**Comment by bjost2s** [comment]
no time to solve
