### ISSUE TITLE
Dragging simulation window/right slider does not track mouse release action

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1475]
**Describe the bug**
 - When you try to drag the right window/slider in which the simulator is located, unpredictable behaviour occurs. The window does move. But even if you no longer want to move it, it still follows the movement of the mouse (to the left or right). Thus the window enlarges or shrinks unintentionally. 

**To Reproduce**
1. Go to 'OR Sim'
2. Click on 'SIM'
3. Drag simulation window/right slider and quickly move the mouse over the simulation background
4. Release mouse button while the mouse resides over the simulation background
5. Move the mouse over the lab interface without touching any mouse buttons and see error

**Expected behavior**
 - Enlarge or reduce the window as long as the mouse is pressed. Releasing the "mouse" ends the re-size. 

**Device information**
 - Type: MacBook Pro
 - OS: Mac Ventura 13.2.1
 - Browser: Chrome Version 111.0.5563.64 

https://github.com/OpenRoberta/openroberta-lab/assets/124324517/275e5525-6902-400e-885e-b28e88ca6e97

**Comment by rbudde** [comment]
Not reproducable on windows system. MAC-related problem?

The problem, that the windows follows the mouse movement (independant from zooming), is well-known, but seldom and hard to reproduce.

**Comment by PascalOchel** [comment]
Could not reproduce on MacBook Pro macOS 13.3.1 (a) with latest Chrome, Firefox, Safari browsers.

**Comment by Thorlogy** [comment]
Did you use the touchpad?

**Comment by bjost2s** [comment]
seems to be fixed. @Thorlogy and @rbudde , please reopen if the problem still exists. Make sure you have deleted the cache with the new version.
