### ISSUE TITLE
calliope SIM - gear wheels missing

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1478]
**Describe the bug**
 -The simulated gears are missing in the Calliope mini simulation. These were originally present and simulated the motor and move blocks. 

**To Reproduce**
1. Go to 'OR Lab'
2. Click on 'Calliope mini'
3. Click on SIM

**Expected behavior**
 - Gears are simulated again

**Screenshots**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/19221359/227153589-767494fb-5257-4b6d-a2eb-7a393b769187.png">

**Device information**
 - Browser Chrome on Mac

**Comment by bjost2s** [comment]
@Thorlogy , please add at least one calliope motor in the configuration tab. Returning to the simulation view you will see the motors
