### ISSUE TITLE
The raspberry pi server images should configure "lab.open-roberta.org" in /etc/hosts

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/openroberta-lab#148]
This would allow people to just use the raspberry pi as a drop-in replacement without having to change the server-address on the computers or the EV3 robots.
This is okay since the raspberry pi would not provide any connectivity to the real internet.

**Comment by bjost2s** [comment]
The latest image is available here: https://www.roberta-home.de/lab/lokale-installation/
The host name is orlab. 
I will update https://www.roberta-home.de/lab/lokale-installation/ Tipps und Tricks with a hint how to change the name

**Comment by bjost2s** [comment]
still waiting for fix on our homepage
https://jira.iais.fraunhofer.de/jira/browse/ROBPM-830
