### ISSUE TITLE
block "random integer" cause program abort

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1481]
**Describe the bug**
 - When using random values via block "random integer from ... to ..." the hub aborts the running program with the RGB LED flashing red or bad smiley!

**To Reproduce**
1. Use block  'random integer from ... to ...' to show on LED matrix
2. Download programm
3. See error
4. Optional: Start programm - if you want to see the error once again

**Screenshots**
- Screenshot_show-text
![Screenshot_show-text](https://user-images.githubusercontent.com/19265064/227724724-50dba456-4e91-40bf-a0f3-2fe30d596ca6.png)

- Screenshot_steer-random
![Screenshot_steer-random](https://user-images.githubusercontent.com/19265064/227724748-b578f7b2-e741-4e86-ba91-31895306471d.png)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser Brave [Version 1.49.128 Chromium: 111.0.5563.110 (Offizieller Build) (64-Bit)]

**Comment by sachinnandan** [comment]
I want to Solve this issue... Can I get this ?? @AHberta

**Comment by bjost2s** [comment]
@sachinnandan , it seems that this is an error for our spike plugin, feel free to check the code generation! It will be hard to test without a Spike Prime / Robot Inventor set
