### ISSUE TITLE
Sim crashes on program with picture

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1487]
**Describe the bug**
 - Assigning the values for the variable "hase" in the loop for further processing works only once. 
 - 
**To Reproduce**
1. Go to https://lab.open-roberta.org --> Calliope mini
2. Code the example program
3. Start the progam and process it more then two times

**Expected behavior**
 - Assigning the variable "hase" should work all the time. No matter how many times the loop is run..

**Screenshots**
<img width="592" alt="image" src="https://user-images.githubusercontent.com/19221359/232025133-87afef0f-9f4c-4e0b-89ec-4283aa74e5ca.png">

**Device information**
 - Type Laptop
 - OS macbook
 - Browser Chorme

**Comment by Thorlogy** [comment]
Indeed its SIM-related! 

Program as .txt file ;-) 
[Debug_Hase_Prog.txt](https://github.com/OpenRoberta/openroberta-lab/files/11233661/Debug_Hase_Prog.txt)

**Comment by bjost2s** [comment]
looks like with the third iteration an variable "k0" is added, which has no value, so the error occurs ...

**Comment by bjost2s** [comment]
While working on this problem, it turned out that we have a similar problem with the mbot image simulation. But here the hardware behaves like the simulation so the question is whether we should change both (hardware and simulation for mbot) to make it similar to Calliope?
