### ISSUE TITLE
Robot mBot2

### ISSUE THREAD

**Issue by pjfagulha** [OpenRoberta/openroberta-lab#1488]
When is the "simulation view" tool in the mBot 2 robot implemented?
When will the beta phase of the mBot2 robot end?
When will I be able to transfer the generated code to the robot, without transmission errors?

Thank you.

**Comment by bjost2s** [comment]
@pjfagulha, thank you very much for your interest,
"When is the "simulation view" tool in the mBot 2 robot implemented?"
Unfortunately, there are no plans yet to support the simulation for mBot2.
"When will the beta phase of the mBot2 robot end?"
As soon as we receive more positive feedback, especially for the newly supported communication blocks.
"When will I be able to transfer the generated code to the robot, without transmission errors?"
Please checkout the latest version from the connector program (and mBot2 firmware) and report issues here. Our last tests ran without error.
