### ISSUE TITLE
Calliope mini Sim vs. real hardware

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1492]
**Describe the bug**
 - Its seems there is a different behavior between real Calliope mini and SIM. In the simulator, a single instruction is sufficient for moving: 
 
![image](https://user-images.githubusercontent.com/19221359/232505091-e6cde669-b565-40c4-b3cd-eb5d517bfb56.png)

Apparently the action "move" is not only executed on the matrix, but also stored in the image variable.
On the Calliope I need two for this:
![image](https://user-images.githubusercontent.com/19221359/232505249-a5581773-b785-4356-b800-b8cd3c0731b7.png)

**Expected behavior**
 - Same behavior on real Calliope mini and SIM

[verschiebeBild.txt](https://github.com/OpenRoberta/openroberta-lab/files/11250925/verschiebeBild.txt)

**Device information**
 - OS: max
 - Browser chrome

**Comment by bjost2s** [comment]
This bug is related to #1487.
