### ISSUE TITLE
Hidden "ruler" in the SIM

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1493]
**Describe the bug**
 - In the Open Roberta Sim there is a ruler that is not displayed.  
**To Reproduce**
1. Go to 'Open Roberta Lab'
2. Click on 'OR SIM'
3. Click on 'SIM'
4. Click Click near the blue object 
5. See the ruler appears

**Expected behavior**
 - The ruler should always be displayed

**Screenshots**
<img width="494" alt="image" src="https://user-images.githubusercontent.com/19221359/232986313-dd278c4e-1c4e-4ddc-8044-5e3c0149f6d0.png">

<img width="622" alt="image" src="https://user-images.githubusercontent.com/19221359/232986391-f0b9ef10-9858-4193-bbf1-1fb8b4a50464.png">

**Device information**
 - Type Laptop
 - OS: Ventura 13
 - Browser chrome (latest version)

**Comment by bjost2s** [comment]
see #1474
