### ISSUE TITLE
Configuration for RFID sensor (Arduino) is not evaluated correctly

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#15]
Seems that  "RST" and "SDA" are swapped in the code generation. 

**To Reproduce**
1. Choose any Arduino
2. Go to the configuration tab and select an RFID ... Reader block: Standard Pin RST=9, SDA=10
3. Go back to the program tab and open the source code view
4. See 
`#define SS_PIN_R 9`   
`#define RST_PIN_R 10`   
`MFRC522 _mfrc522_R(SS_PIN_R, RST_PIN_R);`   

**Expected behavior**
`#define SS_PIN_R 10`   
`#define RST_PIN_R 9`   
`MFRC522 _mfrc522_R(SS_PIN_R, RST_PIN_R);`   

**Device information**
 - any

**Additional context**
 - Currently we do not care about different standard ports for mega, what about nano?

**Comment by simonedegiacomi** [comment]
Hi, is anyone already working on this issue?

> **Additional context**
> 
>     * Currently we do not care about different standard ports for mega, what about nano?
The standard ports are the predefined port numbers that appears in the robot configuration page?
