### ISSUE TITLE
MicrobitV2 get LED brightness returns wrong values

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1504]
**Describe the bug**
 - The get LED brightness block does not return values ranging from 0-9.
 - Instead it returns doubling values till 256 (0,1,2,4,8,16,32,64,128,256)
 - This bug is not reproducible in the python editor by [microbit](https://python.microbit.org/v/3). This most likely means that this issue would get resolved by updating the firmware hex used to generate the hex file in the lab.

**To Reproduce**
1. Go to microbit v2
2. Go to the expert toolbox
3. Set the LED brightness to a value greater than 2
4. Read the LED brightness via the display or serial 
5. See Error

**Expected behavior**
 - The get LED brightness block should return values from 0-9 that match the value set in the set LED brightness block.

**Screenshots**
Example program showing the blocks affected:
![image](https://github.com/OpenRoberta/openroberta-lab/assets/57675018/fc446c73-6f56-440c-95ac-0fdfc2f6967d)

**Additional context**
 - This should also be tested on the original microbit.

**Comment by bjost2s** [comment]
Solved with latest release.
