### ISSUE TITLE
Simulated EV3 display does not work 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1506]
**Describe the bug**
Since the latest release, no texts / characters etc. are shown in the display of the simulated EV3.

**To Reproduce**
1. Go to 'OR Lab'
2. Click on 'Open Roberta SIM or Open Roberta xNN or EV3 lejos or ev3dev, c4ev3'
3. Create a programme that displays any text in EV3.

**Expected behavior**
 - Text / characters... will be displayed.

**Device information**
 - Type laptop
 - OS:mac
 - Browser chrome

**Comment by rbudde** [comment]
deployed as hotfix 14.5.2023. Becomes active 15.5.2023 3:00 am

**Comment by YogoGit** [comment]
As of 8/24/2023, this no longer works.

![image](https://github.com/OpenRoberta/openroberta-lab/assets/12058007/302b12fd-6518-4f14-886c-680a01dba9a9)
