### ISSUE TITLE
OpenRoberta-Connector: removing robots.properties file and adding its content to OpenRobertaConnector.properties file

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1508]
Currently in the [ORC](https://github.com/OpenRoberta/openroberta-connector) repository, through the last release there was a new property file (robots.properties) added which contains data about which robots support the serial monitor and its baud-rate.
This should be refactored by removing the file and adding its content to the already existing OpenRobertaConnector.properties file so that there is only one central property file containing all the necessary data.

**Comment by bjost2s** [comment]
released
