### ISSUE TITLE
Error in Notification  Controller

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1513]
Probably when the structure of the notification data delivered from the backend to the frontend was changed (but maybe an older error), the following function (copied from the Chrome debugger) became corrupt:
```
    function loadAndInitNotifications() {
        notificationModel.getNotifications(function (result) {
            activeNotifications = initNotifications(result.notifications.notifications);
            activeDeprecated = result.notifications.deprecated;
        });
    }
```
the notification propery may be {}, thus accessing the property notification crashes.

**Comment by prajwalbandak** [comment]
Hi, I understand the issue. If the value of **result.notifications.notifications** is empty or null, it is throwing an error. To handle this, we can use a try-catch method or  or if **result.notifications.notifications** is null or empty return an empty object.
Could you please check if this is the issue? Please correct me if I'm wrong.
Can you please assign this task to me?
Thank you.
