### ISSUE TITLE
Add NN support for all robots

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1516]
**Is your feature request related to a problem? Please describe.**
Neural network is already implemented for xNN plugin in the lab. Next step would be to introduce NN support for other robots as well.

In essence, the following needs to be carried out: 
- [x] Add NN support as a first step (NN tab, code generation for real robots)
- [x] Add multi simulation support for NN
- [x] Add activation function implementation (in code generated for real robots)

### List of robot plugins that need to be updated:
- [x] WeDo
- [x] EV3 leJOS 0.9.1
- [x] EV3dev
- [x] EV3 c4ev3
- [x] NXT
- [x] micro:bit
- [x] micro:bit V2
- [x] senseBox
- [x] mBot
- [x] mBot2
- [x] Nepo4Arduino Uno
- [x] Nepo4Arduino Nano
- [x] Nepo4Arduino Mega
- [x] Nepo4Nano33BLE (on `develop`)
- [x] Robotino
- [x] Thymio
- [x] Calliope mini
- [x] Calliope mini blue
- [x] Calliope mini 2016
- [x] Spike Prime / Robot Inventor 
- [x] JoyCar  

### List of robot plugins that are excluded for variuos reasons: 
- ROB3RTA
- Bot'n Roll
- BOB3
- Bionics Kit
- Bionic Flower
- Edison

### NAO

... is a special case, because of its non-standard simulation. This problem will be discussed/solved in another ticket

**Comment by bjost2s** [comment]
@RaghuvirShirodkar, @rbudde please check the boxes before we close this ticket

**Comment by rbudde** [comment]
solved
