### ISSUE TITLE
MBot Simulation error (in console) "motor on speed | time"

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1517]
create this little program:
![image](https://github.com/OpenRoberta/openroberta-lab/assets/1613069/bba255eb-3ffd-4ff2-b19f-a70b9bbaf332)
start it in the simulation and open the browsers debugger:
interpreter.util.js:14 Uncaught pop failed with empty stack

The execution seems to be fine, but the error message must not appear!

Tested in Chrome and Firefox, both the same.

**Comment by AyaMoussa** [comment]
solved on branch [feature/Issue1517](https://github.com/OpenRoberta/openroberta-lab/tree/feature/Issue1517)

**Comment by rbudde** [comment]
sorry for the mistake. Your commit DID SOLVE the problem. Now merged to develop.
