### ISSUE TITLE
Python code generator: unnecessary semicolons generated for Spike and Microbit/MicrobitV2

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1522]
**Describe the bug**
The python code generator for Spike, Microbit and MicrobitV2 generates semicolons at the end of some functions. This for sure does not lead to any error but is a style issue.
The only functions that seem to be effected by this are:
Spike:
 - visitPlayNoteAction
 - visitPlayToneAction
 - visitLedOnAction

Microbit/MicrobitV2:
 - visitMbedPinWriteValueAction

**Comment by rbudde** [comment]
works as expected.Merged to develop.
