### ISSUE TITLE
Refactor AST class `LightAction` 

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1523]
The AST class `LightAction` is currently responsible for the following blockly blocks:
- robActions_led_on
- robActions_brickLight_on
- robActions_sensorLight_on

These blocks themselves are defined on the basis of their characteristics, for instance, not all blocks have field SWITCH_COLOR. This has led to conditional statements in the AST class itself, something that we would like to avoid.

The idea is to:
- separate the blocks based on their functionality and characteristics:
  - if needed, create new blockly blocks.
  - if needed, update relevant configuration of the block.
- create nepo annotated AST classes for the newly created blocks:
  - where possible, use same class for blocks with similar functionality.
- maintain backward compatibility:
  - map the old blocks (contained in old user-saved programs, for instance) to the relevant newly created blocks.
  - if needed, update how the block should be defined in the XML (is the field called MODE or SWITCH_BLINK?).

An extension of this idea would be to update blockly block `robActions_led_off`, so that in essence, all LED blocks are neatly refactored.

The goal is therefore to use these new blocks moving forward, while still allowing old programs to be run in the latest version of the lab.

**Comment by bjost2s** [comment]
fixed with:
0382e9615add65c6c1a392a6c6adbbcf95f23759
09c2c71689e791735dceb430f9302b321054304f
7216de988d6db3e6f2ea8aaa4cb42144758eba31
935c02610e01baff401a9b289cb841a144107627
8feb56d0966aa33f949bd50f2e069642baa1880b
538824d5df5ca73e3c6717e28bad3111f3ff4656
