### ISSUE TITLE
Position of Robot within Simulation

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1524]
**Describe the bug**
- Push the robot to a position in the simulation and close and open the simulation afterwards. The position of the robot has changed. 

**To Reproduce**

**Expected behavior**
- When you have moved the robot itself to a starting position. This should be maintained even after closing and reopening the simulation.

**Device information**
 - Type laptop
 - OS: mac
 - Browser chrome

**Comment by bjost2s** [comment]
This is a feature, please use the "reset position" button
