### ISSUE TITLE
Moving the position of variables

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1525]
**Is your feature request related to a problem? Please describe.**
-Currently, the position of an initialised variable is fixed. It would be nice to be able to change the position of variables within the start block. This would bring more clarity. 

**Describe the solution you'd like**
- Moving the variables could be done with a position number or by drag and drop.

**Comment by AyaMoussa** [comment]
Solved in blockly. Pull request can be found in [Pull reauests](https://github.com/OpenRoberta/blockly/pull/87)

**Comment by bjost2s** [comment]
Please test this fix in detail, there are a lot of changes that could (hopefully not) break the xml

**Comment by rbudde** [comment]
I tested a lot. Everything looks fine except the following error:
- create a function with param p1 and p2
- use this in some function calls
- the generated target code is fine (first image)
- move p2 to the first position
- regenerate the target code (this includes a server round-trip)
- the sequence of parameters in blockly is updated correctly
- in the code generated the sequence is wrong (second image).
I attach two images
![Image](https://github.com/user-attachments/assets/51f34233-66dc-4b78-8678-cd19b3628a5e)
![Image](https://github.com/user-attachments/assets/a90ef3b0-0268-4e13-8cb1-486da7007eaf)

**Comment by rbudde** [comment]
works as expected
