### ISSUE TITLE
Spike Prime / Robot Inventor: undefined variable 'hub', import is missing

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1531]
**Describe the bug**
 - The default code of the spike robot in the lab calls **hub.light_matrix.show_image('SAD')**, but hub is not defined in the code. Its missing the **hub = spike.PrimeHub()**

**To Reproduce**
1. Go to lab, test or dev.open-roberta.org and select the **Spike Prime / Robot Inventor**
2. Open the code view and see the issue

**Comment by bjost2s** [comment]
fixed
