### ISSUE TITLE
Spike Prime: Bugs in program and configuration blocks

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1535]
**Describe the bug**
The Spike Prime plugin on `lab.open-roberta.org` has a couple of bugs:
1. In the `Configuration` tab, the block `gyroscope` can be deleted, which should **not be** allowed, since it is an inbuilt sensor.
2. In the `Program` tab, using the block `show animation LED matrix` leads to a UI error, since the program simply vanishes!

**To Reproduce**
1. Go to `lab.open-roberta.org`.
2. Select robot `Spike Prime / Robot Inventor`.
  - For bug 1 listed above:
    1. Go to the `Configuration` tab.
    2. Click on block `gyroscope`, then delete key, **OR** right click on block `gyroscope`, then `Delete Block`.
    3. The block is deleted.
  - For bug 2 listed above:
    1. Go to the `Program` tab.
    2. Click on category `Action`, then select block `show image LED matrix` and connect it to the `start` block. 
    3. Click on the dropdown in the block and select `animation`.
    4. Add a variable of type `List Image` with name `item`.
    5. Click on category `Variables`, then select block `item` and connect it to the `show animation LED matrix` block.
    6. Click on `Open/close the source code view.`.
    7. See the error.
    
**Expected behavior**
 - For bug 1 listed above:
   The block `gyroscope` should not be deleted, rather the option to delete it should be disabled, as is the case with other inbuilt components.
 - For bug 2 listed above:
   The usage of `show animation LED matrix` block should not lead to UI errors.

**Screenshots**
 - For bug 1 listed above:
   1. Option to delete gyroscope block
       ![Option to delete gyroscope block](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/c74b9ab8-48d2-4c00-9170-7444ba7079a3)
   2. Deleted gyroscope block:
       ![Deleted gyroscope block](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/48cde12c-b922-4146-85c1-3850214cd72c)

  - For bug 2 listed above:
    1. Program before showing source code:
        ![Program before showing source code](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/3262299a-87af-455a-a092-3c7ad596ba88)
    2. Program after showing source code:
        ![Program after showing source code](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/7b0b6200-82d6-4918-a7f3-d1e06edc03d4)

**Device information**
 - Type: Desktop
 - OS: Ubuntu 20.04
 - Browser: Firefox v115.0

**Additional context**
Error log retrieved from logging (for bug 2 listed above):
```
[[ERR ]] 26 msec: show source code of program 'NEPOprog', then in function successFnWrapper EXCEPTION: Connection checks failed. in function successFnWrapper with stacktrace: wrap@https://lab.open-roberta.org/js/helper/wrap.js:47:27 rest@https://lab.open-roberta.org/js/helper/wrap.js:122:20 u@https://lab.open-roberta.org/js/libs/jquery/jquery-3.3.1.min.js:2:27457 fireWith@https://lab.open-roberta.org/js/libs/jquery/jquery-3.3.1.min.js:2:28202 k@https://lab.open-roberta.org/js/libs/jquery/jquery-3.3.1.min.js:2:77651 send/n/<@https://lab.open-roberta.org/js/libs/jquery/jquery-3.3.1.min.js:2:79907 
```

**Comment by bjost2s** [comment]
tested
