### ISSUE TITLE
Selected robot plugin is not always grayed out in `robots` menu

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1536]
**Describe the bug**
When using the lab, one selects a robot plugin from the start carousel. The corresponding entry in the `robots` menu (2nd from top left) should be grayed out, so as to notify the user which robot is currently being used (there are quite a lot of robot plugins now! :smiley: ). 

This is not **always** the case. On first selecting the robot from the start carousel, the entry in the `robots` menu is grayed out as expected. However, upon switching over to the `Configuration` tab and checking the `robots` menu again, one sees that the entry for the selected robot plugin is not grayed out anymore. Switching over to the `Program` tab again has the same effect, the selected robot plugin is not grayed out.

**To Reproduce**
1. Go to `lab.open-roberta.org`.
2. Select any robot plugin, for instance, `Open Roberta xNN`.
3. Click on `robots` menu, 2nd from top left.
4. See the grayed out text of your selected robot plugin, this is the expected behaviour.
5. Click on `Configuration` tab, then click on `robots` menu, 2nd from top left.
6. See the lack of grayed out text in the list. 
7. Click on `Program` tab, then click on `robots` menu, 2nd from top left.
8. See the lack of grayed out text in the list. 

**Expected behavior**
The selected robot plugin should be grayed out in the `robots` menu, irrespective of the tab being used.

**Screenshots**
The selected robot plugin in this example is `Open Roberta xNN`.
- Upon selecting the robot from the start carousel:  
  ![image](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/747008e3-ad2d-418f-851b-cb43723b0ae6)
- Upon switching over to the `Configuration` tab:
  ![image](https://github.com/OpenRoberta/openroberta-lab/assets/43172112/3081bd2e-3567-4b9b-8d2c-04fb2bc08c4f)

**Device information**
 - Type: Desktop
 - OS: Ubuntu 20.04
 - Browser: Firefox v115.0

**Comment by bjost2s** [comment]
Solved by the new start page
