### ISSUE TITLE
Add group level server properties for plugins belonging to a robot group

### ISSUE THREAD

**Issue by RaghuvirShirodkar** [OpenRoberta/openroberta-lab#1538]
**Is your feature request related to a problem? Please describe.**
Currently, all robot plugins have a dedicated property file, for instance, `ev3lejosv1.properties`. There are robot plugins that belong to a robot group, for instance, `ev3`. These individual robot plugins also contain common properties that are applicable for that robot group. This could be refactored in a way that all common properties pertaining to the robot group are extracted to the robot group's property file, for instance, `ev3-group.properties`.

**Describe the solution you'd like**
The common robot properties could be extracted to a group level robot property file. More specifically, this issue deals with:
- identifying robot plugins that belong to a group:
  - Arduino
  - Calliope
  - Ev3
  - ...
- identifying common properties that could be extracted for the robot group:
  - robot.sim
  - robot.multisim
  - robot.nn
  - ...
- updating server side code to accommodate these changes.

**Describe alternatives you've considered**
The branch `feature/nn-for-all` explicitly defines properties `robot.nn` and `robot.nn.activations` for each robot plugin in a robot group. This issue is an improvement on that idea, in that robot group level properties are being proposed, instead of robot plugin level properties.

**Comment by bjost2s** [comment]
fixed
