### ISSUE TITLE
Feature request: add local variables

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/openroberta-lab#154]
Hello!

It would be very useful to have "hidden" variables in functions. If you like to add for example a loop variable in a function there will be a useless input position at the function-block. In effect I see no possibility to create a non-input local variable in a function. 

I think it would be very useful to have those hidden local variables in functions.

Keep up the good work.
corvus-albus

**Comment by bjost2s** [comment]
implemented in the feature branch nepo (new blockly)

**Comment by bjost2s** [comment]
no time to solve (Blockly update needed)
