### ISSUE TITLE
Migrate Spike Prime Robot to Pybricks Firmware

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1542]
Currently, the Lab uses outdated firmware for the spike prime plugin. Due to difficult communication with Lego, the open-source firmware [pybricks](https://pybricks.com/) could be used as the firmware from now on.
 
This includes:
     - code generation for the new API
     - new connection method, pybricks currently only supports Bluetooth, but USB is possible in cooperation with the developers.   

- [ ] Code generation new API
- [ ] Bluetooth Connection
- [ ] USB Connection
- [ ] Integration Tests
- [ ] Adjust documentation for firmware

**Comment by DrTom** [comment]
Can someone give any indication if this will be implemented?

**Comment by bjost2s** [comment]
it is very likely that it will be implemented, soon
