### ISSUE TITLE
Spike driving blocks cause exception when using float type values

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1544]
**Describe the bug**
- Spike driving blocks do not support floats.
- This means that it is currently not possible to use division on a number you plan to input into any driving block

**To Reproduce**
- go to spike prime
- take any driving block
- either ad a float value or a division
- upload to the robot
- see error

**Expected behavior**
 - floats should be cast to int when necessary 

**Aditional Context**
![image](https://github.com/OpenRoberta/openroberta-lab/assets/57675018/3b4209e0-d5f7-449d-aa2e-0eda2d4b8122)
 Blocks that have at least one not working value. If the field is empty that means float caused an exception.

**Comment by bjost2s** [comment]
fixed
