### ISSUE TITLE
Simulation breaks after a period of time

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1552]
**Describe the bug**
- When the simulation is open for an extended period of time, at some point it goes blank, only showing the robot.
- This has only been confirmed to happen for the **Robotino** plugin, but it might be an issue on other systems too.
- The simulation works again after closing and reopening it.

**To Reproduce**
1. Go to robotino
2. Open simulation
3. Wait until you see an error

**Expected behavior**
 - The simulation should never disappear.

**Screenshots**
 - Added later when reproduced

**Device information**
 - OS: Linux 20.04
 - Chrome
 - Touchscreen monitor was attached

**Additional context**
 - This needs testing for other systems 
 - There might be a difference in how frequently it happens when the simulation is idle or running.

**Comment by rbudde** [comment]
I switched all energy savings options on my win10 laptop off and run simulations of robotino and ev3 programs for more than 1 hour. Everything was fine.

**Comment by bjost2s** [comment]
not reproducable
