### ISSUE TITLE
Migration from Bootstrap 3 to 5

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1568]
The migration from Bootstrap 3 to Bootstrap 5 is a huge change, since Bootstrap 3 has been around since 2013. There might be no easy way to convert Bootstrap 3 to Bootstrap 5, due to many major changes and additions.

**Comment by Lexorius** [comment]
Hi, 
the following security vulnerabilities 
https://security.snyk.io/package/npm/bootstrap/3.3.1
was found on the Release 5.2.9 (Docker)
greetings 
Thomas

**Comment by bjost2s** [comment]
We tested this implementation for more then 2 month now (in the whole Roberta team). Please write new issues if you still find issues.

**Comment by rbudde** [comment]
@Lexorius thank you for your comment. We have almost finished the transition to version 5.
