### ISSUE TITLE
CORS error when trying to upload a program using BobDude

### ISSUE THREAD

**Issue by heini208** [OpenRoberta/openroberta-lab#1572]
**Describe the bug**
 - i can't upload a program to either Rob3rta or Bob3 using BobDude
 - While Rob3rta or Bob3 are open, I get the following CORS error
 
```
Access to XMLHttpRequest at 'http://127.0.0.1:8991/listrobots' from origin 'https://lab.open-roberta.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
jquery-3.3.1.min.js:2 
               
GET http://127.0.0.1:8991/listrobots net::ERR_FAILED
```

Additional remarks:
- This error appears only when trying to use chrome on my current machine
- I can't reproduce this using Firefox or chrome on windows and other Linux machines
- This error appears only when using https://lab.open-roberta.org/ or https://test.open-roberta.org/

**To Reproduce**
1. Install BobDude
2. switch robot to Rob3rta or Bob3
3. open console

**Expected behavior**
 - The behavior should be consistent for all browsers and operating systems
 

**Screenshots**
 - ![image](https://github.com/OpenRoberta/openroberta-lab/assets/57675018/4d9bb043-40bf-4059-8592-e26f74ea6205)
 - How it should look like (except for the URL):
  
![image](https://github.com/OpenRoberta/openroberta-lab/assets/57675018/97f23544-3c01-4a5b-a052-6a8b53dc42b8)

**Device information**
 - OS: Linux 20.04
 - Browser Chrome: Version 118.0.5993.88 (Official Build) (64-bit)

**Comment by bjost2s** [comment]
This isssue can not be solved, because the CORS policy doesn't allow to access non secure connections from secure pages anymore.
A good workaround is using the connector program.
