### ISSUE TITLE
wrong color in statuslight-color-picker for cyan

### ISSUE THREAD

**Issue by NiHoffmann** [OpenRoberta/openroberta-lab#1575]
Valid statuslight-colors for used Version of Spike Prime are:
'azure', 'black', 'blue', 'cyan', 'green', 'orange', 'pink', 'red', 'violet', 'yellow', 'white'
The Code Generation works fine, but cyan is displayed as a light green in the OpenrobertaLab.
The Color Cyan gets in the Color-Picker should be changed. All other Colors are displayed correctly.

**Comment by bjost2s** [comment]
The color is not wrong, it is derived from the LEGO Education App:
![image](https://github.com/OpenRoberta/openroberta-lab/assets/1613069/1c447249-3ea5-4689-997e-1caf1c182b63)

A change in the colors in blockly will break backward compatibility, which is not  allowed.
