### ISSUE TITLE
Simulation lacks precision when sensor values are read from the environment

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1580]
See the attached pictures of a background and a program

![2023-11-16 11_55_48-Open Roberta Lab](https://github.com/OpenRoberta/openroberta-lab/assets/15834363/e9dcb012-9cc9-4de7-afb7-a66bd08ede8e)

Optionally open the sensor view. Move the robot around with the mouse.
The background colour seen by the sensor is displayed in the small robot. The update of the view is not done, when the sensor (which is attached at the FRONT of the robot) is above the colour, but much later (as if the the sensor is attached close to the end of the robot). A program gets the color info in the same way delayed.

![2023-11-16 12_12_51-Open Roberta Lab](https://github.com/OpenRoberta/openroberta-lab/assets/15834363/c899310a-039b-4d9c-aebb-6b40efcabef4)

Remedy: if the front of the robot hits a colour, it should be used by the simulation immediately.

**Comment by Thorlogy** [comment]
Reproduction of the error: 

1. Open Roberta SIM,
2. Click on SIM
3. Change the scene (its not a must)
4. Click on "Add a color area"
5. Draw the color area
6. Close the SIM
7. Open  the SIM 
8. See the error

**Comment by rbudde** [comment]
yes, the **close and open** of the sim trigger the error.

It seems to me, that the color area is painted at wrong coordinates (?)

**Comment by PamoCurtis** [comment]
solved
