### ISSUE TITLE
Spike: pink color-block double available

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1587]
**Describe the bug**
 - Pink color block is duplicated in the Colors category

**To Reproduce**
1. Click on 'Colours'
2. See the color of the 2nd and 5th color block are identical

**Screenshots**
![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/290ef28c-f174-4208-8955-a141b5f7fca2)

**Device information**
 - Laptop/Desktop/etc.
 - Windows/etc.
 - Chrome/etc.

**Comment by NiHoffmann** [comment]
pybricks has an additional color distinction please also add the color brown to blockly for color sensor and picker

**Comment by bjost2s** [comment]
@NiHoffmann , this issue is only for the toolbox in this repo. So for adding a new color, please add a new issue.

**Comment by rbudde** [comment]
tested.
