### ISSUE TITLE
RPI: compilation on latest raspbian image (debian stretch based) stops with an error

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/openroberta-lab#159]
Hello,

compiling the latest snapshot 2.3.1 on a raspbian pi 3 with the latest raspbian image (based on debian stretch) ends with an error. With the last jessie-image from july 17 everything works fine. 
Mavens output is attached: [RobotArdu_failure_stretch.txt](https://github.com/OpenRoberta/robertalab/files/1371383/RobotArdu_failure_stretch.txt)

Cheers corvus-albus

Infos about my enviroment:

$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

--> you get the same error with 'openjdk version "1.8.0_141"'.

$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /opt/apache-maven-3.5.0
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.9.35-v7+", arch: "arm", family: "unix"

$ uname -a
Linux ORServer-Corvi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

$ cat /proc/device-tree/model
Raspberry Pi 3 Model B Rev 1.2

$ cat /etc/apt/sources.list.d/raspi.list
deb http://archive.raspberrypi.org/debian/ stretch main ui

**Comment by boonto** [comment]
Compilation for all robots (except C4EV3) works on stretch and buster.
