### ISSUE TITLE
xNN - Input Trainings data on Ipad

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1590]
**Describe the bug**
The pop-up window for entering training data does not appear on iPads. 

**To Reproduce**
1. Use a ipad
2. Click on 'Open Roberta xNN'
3. Click on "Neuronal Network learn"
4. Click on "Open a pop up window - input/output test/training data"
5. See error

**Expected behavior**
Pop up window appears. 

**Screenshots**
 - If applicable, add screenshots to help explain your problem.

**Device information**
 - Type iPad
 - OS: 
 - Browser: Safari, Chrome?

**Comment by bjost2s** [comment]
@Thorlogy , please add more information for Ipad version and browser version. We could not reproduce the error

**Comment by rbudde** [comment]
@Thorlogy please try it again. We could not reproduce the error.
