### ISSUE TITLE
xNN - activation functions

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1591]
**Describe the bug**
It see

**To Reproduce**
1. Go to 'Open Roberta xNN'
2. Click on 'Neuronal Network Define'
3. Click on activation
4. Click on ReLU, Tanh, Sigmoid
5. Input trainings data 
6. Run forward propagation layer by layer
7. See error

**Expected behavior**
![activation](https://github.com/OpenRoberta/openroberta-lab/assets/19221359/1953872d-89c2-4b0c-863e-30d9bc50b958)

**Screenshots**
<img width="960" alt="xNN_activiation" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/20c56b9e-4895-4384-903d-6de137b7049a">

**Device information**
 - Type Laptop
 - OS: Max OS
 - Browser chrome

**Comment by heini208** [comment]
Output is now always updated. However if you switch activation while switching layers the input disappears.
