### ISSUE TITLE
xNN - scale browser window

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1592]
**Describe the bug**
The "training loss" display window should not change when the browser window is minimised from bottom to top. 

**To Reproduce**
1. Go to "Open Roberta xNN'
2. scale browser window (horizontal)
3. See error

**Expected behavior**
training loss display should be the same

**Screenshots**
<img width="1789" alt="xNN_window" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/40854027-cd7a-43e1-ba8b-5d5a5a4d1836">

**Device information**
 - Type Laptop
 - OS: mac
 - Browser chrome

**Comment by TomGruene** [comment]
not solved

**Comment by bjost2s** [comment]
should be fixed with together with c4136b6
