### ISSUE TITLE
xNN - display with many neurons 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1595]
**Describe the bug**
if many input neurons are present, the input number is truncated

**To Reproduce**
1. Go to 'xNN'
2. Click on '.Neurnonal Network Learn'
3. Add as much as Input neuron as possible
4. Add trainings data
5. run training
6. see error 

**Expected behavior**
The number will be shown correctly

**Screenshots**
<img width="613" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/d2458866-8968-4cd4-b5ea-9a7fedc2ee0b">

**Device information**
 - Type Laptop
 - OS: mac
 - Browser chrome

**Comment by bjost2s** [comment]
solved
