### ISSUE TITLE
Python Mbed: New line character in comment generates faulty code

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1598]
**Describe the bug**
 - When using the "comment"-block, it is possible to generate faulty code by adding a new line "\n" character, because the input is not sanitized properly

**To Reproduce**
Import following program and open the code generation (remove the ".txt" before importing it)
 - micro:bit v2: [errorMicrobitV2CommentBLock.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/13745237/errorMicrobitV2CommentBLock.xml.txt)

**Additional context**
- Following line is the issue
https://github.com/OpenRoberta/openroberta-lab/blob/6c8aabdd53817014f7f4e92c51b78fb00caaa0f1/RobotMbed/src/main/java/de/fhg/iais/roberta/visitor/codegen/MicrobitPythonVisitor.java#L448

**Screenshots**
![Screenshot from 2023-12-21 19-45-05](https://github.com/OpenRoberta/openroberta-lab/assets/59732238/ec5e77b5-380f-4076-8c3d-15784a9cdcc3)

**Comment by bjost2s** [comment]
solved
