### ISSUE TITLE
VendorId problems with WebUSB when using Microbit devices

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1601]
when connecting a Microbit device to the lab the vendorId is used to filter devices. Currently one vendorId is defined in the plugin property files. But there are more than one. Currently an exhaustive list is unknown to me. 

in the Microbit v1 plugin: robot.vendor = 0x1366
v2:  robot.vendor = 0xd28

but my v1 has the same  vendorId robot.vendor = 0xd28 as the v2. Consequently the device is not recognized.

1. use a better name as robot.vendor, e.g. robot.vendorid.webusb
2. allow a list of ids
3. try to assemble as much ids as possible. Inform the community to deliver their ids, if connection problems occur.

**Comment by bjost2s** [comment]
Cannot be reproduced by me: Windows 10, Chrome

@ćommunity: please test this, if you have a micro:bit or micro:bit v2 by hand and report results here

**Comment by rbudde** [comment]
solved with commit 57fa4f18a51aed8a1b2960f086612a41f8b1b113
pr closed
