### ISSUE TITLE
Show Time Value OR SIM

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1604]
**Describe the bug**
- No Time Value will be displayed
- 
**To Reproduce**
1. Go to 'OR Lab'
2. Click on '.any Hardware System e.g. OR Sim'
3. Choose / code a program
4. Click on Sim
5. Click on Open Sensors data view
6. Click on Time Value
7. See error

**Expected behavior**
Time Value will be displayed

**Screenshots**
<img width="321" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/4e7ee1f6-2897-4f51-ae3a-97f3885fbb05">

**Device information**
 - Type Laptop
 - OS: MacOS
 - Browser: Chrome

**Comment by rbudde** [comment]
I tested with a program, which contains a timer (reset and read). The value is not shown on the sensor data view

**Comment by bjost2s** [comment]
tested
