### ISSUE TITLE
[Calliope mini][micro:bit] Messages->Set channel to bug in some languages

### ISSUE THREAD

**Issue by fabianhugo** [OpenRoberta/openroberta-lab#1608]
**Describe the bug**
The block "Set channel to ..." is not usable in some languages, since it does not leave space to set a variable number and shows _1%_.
![grafik](https://github.com/OpenRoberta/openroberta-lab/assets/32654742/8acd3112-5ca2-434f-b68c-375ac05050a1)
Correctly it would look like this: 
![grafik](https://github.com/OpenRoberta/openroberta-lab/assets/32654742/4a64d3bf-41d7-412c-89ae-da56dcf91bb5)
Checking briefly I found the following languages affected: 
- Svenska
- Italiano
- the language two below Catalá
- Polski

The "set channel to ..." block is particularly important when working with a bigger group of children.  

**To Reproduce**
1. Go to Open Roberta Lab 
2. Use Calliope mini or micro:bit
3. Go to Extended Blocks (Click on the number 2)
4. Go to messages, use "set channel to" block
5. Change language to one of the above e.g. Italiano

**Expected behavior**
 - The block should leave space for a parameter.

**Comment by bjost2s** [comment]
Thank you for this bug report!

**Comment by AyaMoussa** [comment]
Solved
