### ISSUE TITLE
Calliope mini - get LED brightness x y reversed within SIM

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1609]
**Describe the bug**
 - The x and y axes were swapped in the simulation display.

**To Reproduce**
1. Go to 'Calliope mini plugin
2. Code a program using the "get LED brightness x y" Block
3. Click on SIM and run program

**Expected behavior**
 - The x and y axes should be displayed correctly

**Screenshots**
<img width="353" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/864d41ea-26f2-4c4e-9301-c258f1270313">

**Device information**
 - Type Laptop
 - OS: max
 - Browser chrome

**Comment by thoschi** [comment]
Dupiclate of #1585 (but good to know I am not the only one)

**Comment by AyaMoussa** [comment]
Solved.
