### ISSUE TITLE
Running Thymio from CodeEditor does not work

### ISSUE THREAD

**Issue by NiHoffmann** [OpenRoberta/openroberta-lab#1610]
Running Thymio from CodeEditor does not work,
throws following exception in console:
![errorthymio](https://github.com/OpenRoberta/openroberta-lab/assets/82971538/49daf7fd-e064-41bd-ac65-0c600cd3742d)

**To Reproduce**
1. Connect Thymio
2. Switch to SourceCodeEditor
3. Press Run

This error happens with and without empty program.
Running the program from NEPOeditor works.

Additional Information:
in ProgRun controller there is a if statement for thymio: 
PROGRAM.showSourceProgram is called for runOnBrick
but not for runNative.

**Comment by bjost2s** [comment]
works as expected!
