### ISSUE TITLE
Pulling the right sidebar

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1618]
**Describe the bug**
 - After selecting a system via the start page, it is possible to activate the dragging of the right-hand sidebars on the left-hand side of the block categories (approx. 5 mm from the edge of the browser). However, it is not possible to move the sidebar completely to the right. To end this state, a view such as the source code must be opened and closed.

**To Reproduce**
1. Select Calliope mini as system via start screen
2. Go to the left side until mouse cursor changes |-|
3. Click and hold left mouse key, and drag right side bar
...

**Screencast**

https://github.com/OpenRoberta/openroberta-lab/assets/19265064/22ff284c-545c-4085-847c-0d6b7948c115

**Device information**
 - Type Laptop, iPad
 - OS: Windows, iOS
 - Browser Chrome, Firefox, Edge, Brave, Safari

**Comment by bjost2s** [comment]
solved
