### ISSUE TITLE
Initial position not equal to starting position

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1619]
**Describe the bug**
If the button for resetting to the initial position is pressed directly after opening the simulation environment, the 2D Edison model jumps to the starting position. This does not correspond to the initial position directly after opening the sim.

**To Reproduce**
1. Click on 'SIM'
2. Click on "reset position" in the simulation environment
3. See new starting position

**Screencast**

https://github.com/OpenRoberta/openroberta-lab/assets/19265064/d70ec19b-4832-40eb-ba12-ea3813d7c7f5

**Device information**
 - Type Laptop, iPad
 - OS: Windows, iOS
 - Browser Chrome, Edge, Firefox, Safari

**Additional context**
 - Add any other context about the problem here.

**Comment by bjost2s** [comment]
tested
