### ISSUE TITLE
Combination switching left and right LED 

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1620]
**Describe the bug**
When switching the right LED of the Edison on and off in combination with switching the left LED on and off, different behavior occurs in the simulation. However, the program works as expected on the Edison itself.

**To Reproduce**
![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/b1c24bd0-b4f7-4ce0-9a5b-66e09933ebb8)
-> right LED is off

![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/8d496118-57bf-49ff-8f7b-dbf53fdc1a04)
-> same behavior

![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/0df06c60-14b3-44a3-9c48-d806acc02f8c)
-> right LED is always on

![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/1b860040-ea82-47a7-a7c5-687995c6ef87)
-> same behavior

![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/6db6a98a-679f-45fa-8909-9021b7b82982)
-> everything fine!

Is there any tip?

**Screenshots**
 - see above

**Device information**
 - Type laptop, iPad
 - OS: Windows, iOS
 - Browser Chrome, firefox, edge, safari (current versions)

**Comment by bjost2s** [comment]
tested
