### ISSUE TITLE
Simluation - colour field

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1623]
**Describe the bug**
In the simulation, the colour field for changing the colour of a selected coloured area or obstacle is only partially visible in the browser window.

**To Reproduce**
1. Go into Sim
2. Add colour area
4. Click on 'Change colour"
5. See the colour field only partially - 'Change colour' near the browser window edge

**Screenshots**
![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/40ca9db2-a1d4-4a1f-9195-36c9c602ac9c)

**Device information**
 - OR: test.open-roberta.org
 - Type Laptop, iPad
 - OS: Windows, iOS
 - Browser Chrome, Edge, Safari

**Comment by AyaMoussa** [comment]
Solved on branch [feature/Issue1623](https://github.com/OpenRoberta/openroberta-lab/tree/feature/Issue1623)

**Comment by AyaMoussa** [comment]
Tested. Issue solved.
