### ISSUE TITLE
Translation of 'set channel to' block to Polski 

### ISSUE THREAD

**Issue by AyaMoussa** [OpenRoberta/openroberta-lab#1625]
**Describe the bug**
Translation of 'set channel to' block to Polski doesn't display an input space instead it shows %! 

**To Reproduce**

1. Go to Open Roberta Lab
2. Use Calliope mini or micro:bit
3. Go to Extended Blocks (Click on the number 2)
4. Go to messages, use "set channel to" block
5. Change language to Polski

**Expected behavior**
 - The "set channel to" block should display a space for an input parameter like with the English language

**Screenshots**
 - Issue in Polski: 
![Screenshot from 2024-02-13 14-35-21](https://github.com/OpenRoberta/openroberta-lab/assets/113432454/aa32f9e2-c10d-4a01-a9fe-74827b6034ee)

- Expected reference in English: 
![Screenshot from 2024-02-13 14-35-11](https://github.com/OpenRoberta/openroberta-lab/assets/113432454/1cd2498d-2007-4989-b155-39695b6eea86)

**Device information**
 - Type Desktop
 - OS: Ubuntu 22.04.3 LTS
 - Browser: Chrome Version 120.0.6099.224 (Official Build) (64-bit)

**Comment by bjost2s** [comment]
resolved
