### ISSUE TITLE
Tabs for beginner and expert mode inactive

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1626]
**Describe the bug**
The tabs that are normally used to switch to beginner and expert mode are inactive when using the iPad.
The following workaround can be used: edit > NEPO-Blocks expert
or, if in expert mode, switch to beginner mode: edit > NEPO-Blocks beginner
In addition, the beginner mode tab is always displayed as the active tab, even though expert mode is selected and the categories are displayed.

**To Reproduce**
1. Move the mouse pointer to tabs 1 (beginner) or 2 (expert)
2. Click on the tab 

**Screenshots**
![MicrosoftTeams-image (13)](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/89533b99-b1be-4357-8d0b-c9758c544a09)

**Device information**
 - Type Tablet iPad
 - OS: iOS
 - Browser Safari, Chrome

**Comment by bjost2s** [comment]
tested: 
macOS 14.3.1
- [x] Safari 17.3.1 
- [x] Chrome 121.0.6167.184 
- [x] Firefox 122.0.1 

Windows 10 Windows 10 Enterprise Version 22H2
- [x] Edge Version 121.0.2277.128 (Offizielles Build) (64-Bit) 
- [x] Firefox Version 115.7.0esr (64-Bit) 
 
Windows 10 Windows 10 Enterprise Version 22H2
- [x] Edge Version 121.0.2277.128 (Official build) (64-bit) 
- [x] Firefox Version 115.7.0esr (64-Bit) 
- [x] Chrome Version 121.0.6167.185 (Offizieller Build) (64-Bit) 
- [x] Chrome Version 122.0.6261.58
