### ISSUE TITLE
Edison - using repeat x times loop

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1632]
**Describe the bug**
 - A clear and concise description of what the bug is.

**To Reproduce**
1. Go to 'Open Roberta Lab'
2. Click on 'Edison'
3. Code the "repeat x times loop" 
4. Download to Edison
5. See error

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**
<img width="299" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/460116db-4d77-4ecb-bdb3-8c2b6909f9b2">

<img width="259" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/40f34ab0-d832-4313-ad90-ca16a6f8b2c4">

**Device information**
 - Type laptop
 - OS: Mac
 - Browser chrome

**Comment by bjost2s** [comment]
Please be more precise and send a screenshot of the generated source code (Source Code View) of line 12

**Comment by Thorlogy** [comment]
<img width="785" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/174df61b-5a29-45c5-8a7d-f5268c32db7b">

here you go.

**Comment by rbudde** [comment]
I tried the following code in the EdPy-IDE and it works:
```
import Ed

Ed.EdisonVersion = Ed.V1

Ed.DistanceUnits = Ed.TIME
Ed.Tempo = Ed.TEMPO_MEDIUM

#--------Your code below-----------

for x in range(10):
    Ed.RightLed(Ed.ON)
```
Using this code in our source code editor, generates an error of the Edison compiler we are using:
```
Achtung

Das Programm kann nicht auf dem Roboter oder in der Simulation ausgeführt werden. Das Program kann nicht übersetzt werden. Die Fehlermeldung ist:
{"error": true, "messages": ["ERR: file:10:0: Syntax Error, FOR code too complex for Ed.Py"], "wavFilename": null}
```

A possible reason: our Edison compiler is outdated.
BTW: the program can be executed in the simulation. We should change the error message.

**Comment by bjost2s** [comment]
The "old" (and origin) Edison Python compiler works, but unfortunately only with Python 2. That's why we changed it [here](https://github.com/OpenRoberta/ora-cc-rsc/commit/80b990d111a9bd2954b056b06f3c7c02ee0b14d0) to a python 3 compatible version. Seem like the issue with "too complex" comes from this compiler: https://github.com/thonny/thonny-edison
One workaround would be, to switch back to the Python 2 version or trying to fix the thonny solution. Last year the information from Edison was, that they are not working on a Python 3 compatible compiler for Python.

**Comment by bjost2s** [comment]
The implemented solution is to use edison's compiler directly. In conversation with the people at edison, it turned out that we are allowed to use their API for this purpose.

**Comment by AHberta** [comment]
"Run on Edison" returns compiler error: Permission denied

**Device infos**
- Type: Desktop
- OS: Windows 10
- Browser: Chrome, Brave, Edge



![Image](https://github.com/user-attachments/assets/170db90b-d814-4360-b3b0-9e41aa30a5be)

**Comment by AHberta** [comment]
Tested and works fine on Windows also! Thanx ;)
