### ISSUE TITLE
xNN - output column in tab "Neural Network Define" tab 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1634]
**Is your feature request related to a problem? Please describe.**
-The output column in the Neural Network Define tab is not required. 

**Describe the solution you'd like**
 - The second column can be deleted. 

<img width="285" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/82c5a57d-a900-4a63-8d7f-04b10faf8aa3">

**Comment by bjost2s** [comment]
already fixed
