### ISSUE TITLE
Calliope: old programs cannot be imported anymore

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1635]
When importing specific programs into the Calliope mini plugin, the system reacts with _„Fußgaengerampel.xml“ ist kein gültiges NEPO Programm und kann nicht hochgeladen werden._

The program will not be imported and the user cannot work with this program anymore. Some time ago it was possible to import the programs (atached) and work with them.

[Fußgaengerampel.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/14409692/Fussgaengerampel.xml.txt)
[Suessigkeitmaoam.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/14409693/Suessigkeitmaoam.xml.txt)

**Comment by rbudde** [comment]
the error occurs in the TransformerVisitors for mbed and is not related to the RGBLED changes. It will hit all old programs that write to a digital or analog pin.

**Comment by bjost2s** [comment]
tested
