### ISSUE TITLE
xNN - Adding another neuron and the effect on the training data 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1637]
**Describe the bug**
if a new column is added to the training data, the assignment of the data no longer matches the columns

**To Reproduce**
1. Go to 'OR LAB'
2. Click on '.xNN learn
3. Add trainnigs data
4. Click on xNN Define
5. Add neuron
6. Click on xNN learn
7. See error

**Expected behavior**
The data entered should be linked to the columns (neurons).

**Screenshots**
<img width="237" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/83dd4e8d-8203-4b3b-8147-5a6706f49d80">

<img width="553" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/dd986c02-7445-4a0f-93de-f3c7eee914cf">

**Device information**
 - Type laptop
 - OS: MacOS
 - Browser chrome

**Comment by rbudde** [comment]
needs a new strcture of the data table internally and externlly for both learn and define and both upload and typing. Could be a small student project. I tag it as visible on the right side.

**Comment by rbudde** [comment]
It's not a big problem for users, as the standard workflow is to define the net structure (depending on sensors, actuators) and then training data. If the data is reused, the data will be put into a csv file. After changing the net structure it is easy to edit the csv file. In almost all cases (beside pure demonstations as we do sometimes), you have to think about the data and change the values anyhow.

**Comment by rbudde** [comment]
no time to work on
