### ISSUE TITLE
Startpage: Login out breaks the lab

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1648]
**Describe the bug**
Switching form the *startpage* to the *Manage user groups ...* and THEN logging out will break the lab by switching to a robot but the *Program* and *Configuration* tabs are missing and the *robot*, *gallery* and *tutorial* tab is not usable

**To Reproduce**
1. Got to the startpage
2. Log into your account
3. In the 'login' tab click on *Manage user groups ...*
4. Now log out and see the error

**Expected behavior**
 - The view should switch back to the startpage instead of the robot view

**Screenshots**
- After logging out. See the missing *Program* and *Configuration* tabs and the greyed out *robot*, *gallery* and *tutorial* tab
![Screenshot from 2024-03-14 13-11-12](https://github.com/OpenRoberta/openroberta-lab/assets/59732238/5d2f0b9c-7d28-4a45-ae8f-bbe7a9298905)

**Comment by AHberta** [comment]
Tested and works perfectly! Thanx ;)
