### ISSUE TITLE
update robot protocol

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/openroberta-lab#165]
The improvements need a clear concept before starting implementing.

The push protocol is necessary to handle restricted network setups. It comes with limitations (bandwidth and latency) and overhead though. A websocket won't have these limitations, but might not work in all cases.
- [ ] prefer websocket with push protocol fallback
- [ ] send connected peripherals with each push (or heartbeat in the case of websockets), sensors or encoder will contain their mode and value as well
- [ ] publish new endpoint under versioned urls. this allows us to keep older version alive for some time

**Comment by rbudde** [comment]
for the txt4 controller plugin we revised the protocol and documented it in the Github wiki. It supports everything we currently require. We close the ticket, even if a complete redesign of the whole robot-server communication makes sense, but we don't have the time to work on that.
