### ISSUE TITLE
Server Error after starting the simulation with an old xNN program

### ISSUE THREAD

**Issue by bkochsickm** [OpenRoberta/openroberta-lab#1655]
**bug on the prod system**
Starting the simulation with an older xNN program (from my programs, 19.09.2023) generates a `Server Error`

First click on NEURAL NETWORK define, then start the simulation, it will work.

**Comment by rbudde** [comment]
program to reproduce the error
[abstandZurueckSchnell.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/15009095/abstandZurueckSchnell.xml.txt)
