### ISSUE TITLE
RGB LED does not show red color, when color is set by a variable

### ISSUE THREAD

**Issue by el-voss** [OpenRoberta/openroberta-lab#1664]
**Describe the bug**
I have a RGB-LED wired to a Arduino Uno with the standard configuration of the ORL (red: pin 5, green: pin 6, blue: pin 3). When I set the RGB LED to shine red and I put the colorblock directly into the command, the RGB LED will shine red. But if I use a variable instead, the RGB LED will do nothing at all. The screenshots below suggest, that there is a problem with the RCHANNEL-command, which is used to get the red part of a RGB()-instance.

![grafik](https://github.com/OpenRoberta/openroberta-lab/assets/32771752/719c79f1-3f10-491d-9272-f0ebcc7bfae7)
Figure 1: Codeblocks, that work 

```

#include <Arduino.h>

#include <NEPODefs.h>


int _led_red_R = 5;
int _led_green_R = 6;
int _led_blue_R = 3;
int _v_colour_temp;
void setup()
{
    pinMode(_led_red_R, OUTPUT);
    pinMode(_led_green_R, OUTPUT);
    pinMode(_led_blue_R, OUTPUT);
}

void loop()
{
    analogWrite(_led_red_R, 204);
    analogWrite(_led_green_R, 0);
    analogWrite(_led_blue_R, 0);

}
```
Figure 2: The corresponding code of Figure 1 shows that the analogWrite-commands get numbers

![grafik](https://github.com/OpenRoberta/openroberta-lab/assets/32771752/ed6ceeeb-ddf2-4457-add6-f8015589bc64)
Figure 3: Codeblocks, that do not work

```
#include <Arduino.h>

#include <NEPODefs.h>


unsigned int ___f;
int _led_red_R = 5;
int _led_green_R = 6;
int _led_blue_R = 3;
int _v_colour_temp;
void setup()
{
    pinMode(_led_red_R, OUTPUT);
    pinMode(_led_green_R, OUTPUT);
    pinMode(_led_blue_R, OUTPUT);
    ___f = RGB(0xff, 0x00, 0x00);
}

void loop()
{
    analogWrite(_led_red_R, RCHANNEL(___f));
    analogWrite(_led_green_R, GCHANNEL(___f));
    analogWrite(_led_blue_R, BCHANNEL(___f));

}
```
Figure 4: The corresponding code of Figure 3 shows that the analogWrite-commands get CHANNEL-commands

**To Reproduce**
1. Produce the programs above and load them on an Arduino Uno, which is wired to a RGB-LED.

**Expected behavior**
 - The RGB-LED should shine red.

**Device information**
Tried with Firefox on Windows 10 and Firefox on Tuxedo OS (derivative of Ubuntu).

**Comment by bjost2s** [comment]
tested, well done!
