### ISSUE TITLE
New Library for Sourcecode-Editor and Code-View

### ISSUE THREAD

**Issue by NiHoffmann** [OpenRoberta/openroberta-lab#1665]
The current Library (Code-Flask) is very basic and doesn't add a lot of features. All it offers is a very basic syntax highlighting.

It would be nice to replace Code-Flask with a library that additional offers at least:
1. Code-Completion (for basic language features and a robot specific API)
2. Language-Specific-Highlighting
3. Easy extendability and customizability

**Comment by bjost2s** [comment]
solved
