### ISSUE TITLE
Server-Error - Calliope mini v3

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1668]
**Describe the bug**
 - The generation of the source code of a NEPO program (even if it only includes the start block) causes a server error. The error is visible when attempting to view the source code, run a simulation, or upload the program to the Calliope mini v3.
 - With the import of the SOS.xml file, everything works perfectly.

**To Reproduce**
1. Go to 'Calliope mini v3'
2. Click on 'Sim', 'source code view' or 'run program on system'
3. See error

**Expected behavior**
 - Code generation, download/run program on Calliope mini v3, etc.

**Screenshots**
<img width="217" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19265064/3b600a23-3846-4694-a478-ea331db36984">

**Device information**
 - Type: laptop
 - OS: Windwos 11
 - Browser: Chrome

**Comment by bjost2s** [comment]
this issue was already fixed and released with 36d05c53547bdb50970f41a8234896ccd95c5411
