### ISSUE TITLE
Add Gyroscope rotation measurement to CalliopeV3

### ISSUE THREAD

**Issue by AyaMoussa** [OpenRoberta/openroberta-lab#1671]
New CalliopeV3 doesn't provide a direct measurement of roll and pitch like older versions. However, I intend on using x, y, z acceleration to calculate roll and pitch based on the program used for Calliope on Makecode editor [accelerometer.ts](https://github.com/microsoft/pxt-calliope/blob/29ddc0edc12e6b972ca5a64beb3fbd21d7ad9667/sim/state/accelerometer.ts#L324).

**Comment by AHberta** [comment]
Tested and works fine! Thank you!
