### ISSUE TITLE
Start screen - Release version incorrect

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1672]
**Describe the bug**
 - The release version specified under Release  is incorrect.
 
![image](https://github.com/OpenRoberta/openroberta-lab/assets/19265064/5549a0c2-77ed-47dd-bcac-37f85d549cbf)

**To Reproduce**
1. Go to start screen
2. Scroll down to 'footer'
4. See 'release 2.0.0'

**Expected behavior**
 - release 5.2.17 -  The latest release (see github)

**Screenshots**
 - https://github.com/OpenRoberta/openroberta-lab/releases

**Device information**
 - Type: Desktop/Tablet/Smartphone
 - OS: all
 - Browser: all

**Comment by rbudde** [comment]
reviewed
