### ISSUE TITLE
Calliope mini V3 - Neopixel RGB colour codes generate error message

### ISSUE THREAD

**Issue by PetraSohnius** [OpenRoberta/openroberta-lab#1678]
Describe the bug

- Input values for RGB LEDs of Calliope mini V3 generate folowing error message on the board: 
" :( Line 19 typeError function takes 2 positional arguments but 5 were given"

**To Reproduce**
1. insert "turn RGB LED on - all - colour"
2. connect with "colour with - red - green - blue - white"
3. type any value from 0 to 255 for the four colour options
4. send code to board
5. see error message

**Expected behavior**
 - Colour of RGB LEDs should be determined by numbers inserted. Simulation shows working LEDs.

**Device information**
- Type: Desktop
- OS: Windows 10
- Browser: Edge

![bug_colorV3_sim](https://github.com/user-attachments/assets/60514f6e-09c2-4a49-93cb-b9f1cb485f05)
![bug_colorV3](https://github.com/user-attachments/assets/5329766b-ba09-4e0c-a995-2438ea874057)

**Comment by AyaMoussa** [comment]
fixed on branch [Issue1678](https://github.com/OpenRoberta/openroberta-lab/tree/feature/Issue1678)

**Comment by AHberta** [comment]
Tested and works perfectly! Thanx ;)
