### ISSUE TITLE
Open Roberta Lab Tour: Server error starting the interactive tour 

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1680]
**Describe the bug**
 - When attempting to start the interactive tour in Open Roberta Lab using the "Take an interactive Tour" button, a server error occurs. This error prevents the tour from loading and starting. 

**To Reproduce**
1. Go to the start screen of Open Roberta Labs
2. Click on "Take an interactive tour" to start the tour
3. A popup with a server error is displayed

**Expected behavior**
 - It is expected that the start screen will be exited, switched to the Open Roberta Lab, and the tour will interactively explain the principles of program creation and testing in the simulation.

**Screenshots**
![image](https://github.com/user-attachments/assets/bb88df23-b7ce-48fe-b382-c0e8fbd73691)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome, Edge

**Comment by AHberta** [comment]
Tested and works perfectly! Thanx ;)

**Comment by bjost2s** [comment]
There is a very similar issue for working with old links to a program.

**Comment by rbudde** [comment]
reviewed
