### ISSUE TITLE
Calliope mini v3: »receive message number« return value "NONE" no message is received

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1683]
**Describe the bug**
 - Calliope mini v3: If no message is received, »receive message number« block returns the value »None«. This doesn't  correspond to the previous »receive« values -> therefore old calliope programs can't be used. Note: return 0 if no message (number) is received.

**To Reproduce**
1. Insert »receive message number« 
2. connect with »show text« 
3. send code to board
4. see return value

**Expected behavior**
 - It is expected the return value "0" as discribed in the wiki, if no message is received as discribed in the wiki.

**Screenshots**
 - If applicable, add screenshots to help explain your problem.

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome, Edge

**Comment by AyaMoussa** [comment]
Fixed on branch [feature/Issue1683](https://github.com/OpenRoberta/openroberta-lab/tree/feature/Issue1683)
