### ISSUE TITLE
EV3 leJOS 0.9.1.: Block »conncet to robot name« is not displayed als disabled block

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1695]
**Describe the bug**
 - In Open Roberta Lab or NEPO, the block »conncet to robot name«  is not displayed as a disabled block if it is not part of the current program.

**To Reproduce**
1. Select the EV3 leJOS 0.9.1 system 
2. Switch to expert mode by clicking on ![image](https://github.com/user-attachments/assets/815dac18-772f-4a08-bdc3-693c9a4e870c)'
3. Open the categorie »Messages«
4. Using drag-and-drop, take the out so that it is not part of the program.
5. See the block is not displayes as a disabled block

**Expected behavior**
 - »conncet to robot name« block is displayed as disabled block

**Screenshots**
 - If applicable, add screenshots to help explain your problem.
![image](https://github.com/user-attachments/assets/63f88a6e-20ed-4f4a-8e0c-5745ed7ec22f)

**Device information**
 - Type: Desktop
 - OS: Windows 10/11
 - Browser: Chrome, Edge

**Comment by AyaMoussa** [comment]
Tested. Issue solved.
