### ISSUE TITLE
Color of disabled and/or not in task blocks is sometimes missing

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1698]
When working with disabled blocks, e.g. copying or simply any server interaction, the color of the block disappears. Further the handling during and after using the simulation or debug simulation leads to wrong opacity and/or color. Some examples:
 block disabled, initial ok
![image](https://github.com/user-attachments/assets/3996723d-158c-4a2a-b699-ca8dbb398316)
 after opening code view, not ok
![image](https://github.com/user-attachments/assets/6a9039e1-5865-4af4-9da4-2b1df08b4d14)
after leaving focus, not ok
![image](https://github.com/user-attachments/assets/547493dc-63be-4743-bac9-b16c18ec1ce8) 

 block not in task, initial ok
![image](https://github.com/user-attachments/assets/825ace04-caef-47ff-a5a9-935b79b3ae57)
after opening and closing debug mode, not ok
![image](https://github.com/user-attachments/assets/8e4c70c6-c504-47f4-a146-899629d73780)

**Comment by AyaMoussa** [comment]
Tested. Issue solved.
