### ISSUE TITLE
BOB3 compilation without arduino-builder

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#170]
#34 - related

Currently bob3 uses arduino-builder to build and compile programs, though it is not necessary, since bob3 does not need a bootloader or other parts of Arduino framework. It works bare-metal.

Excluding Arduino framework will also make it easy to use the precompiled bob3 library, reducing the overall compilation to two compiler calls.

This can be achieved as follows:

1. Once:

```
avr-gcc -D_BOB3_ -std=c99 -g -Os -fno-exceptions -ffunction-sections -fdata-sections -DAVR -Wall -I.. -mmcu=atmega88 -DF_CPU=8000000 -c analog.c -o analog.o
avr-gcc -D_BOB3_ -g -Os -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -DAVR -Wall -I.. -mmcu=atmega88 -DF_CPU=8000000 -c bob3.cpp -o bob3.o
avr-gcc -D_BOB3_ -std=c99 -g -Os -fno-exceptions -ffunction-sections -fdata-sections -DAVR -Wall -I.. -mmcu=atmega88 -DF_CPU=8000000 -c ircom.c -o ircom.o
avr-gcc -D_BOB3_ -std=c99 -g -Os -fno-exceptions -ffunction-sections -fdata-sections -DAVR -Wall -I.. -mmcu=atmega88 -DF_CPU=8000000 -c leds.c -o leds.o
avr-gcc -D_BOB3_ -g -Os -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -DAVR -Wall -I.. -mmcu=atmega88 -DF_CPU=8000000 -c main.cpp -o main.o
avr-gcc -D_BOB3_ -g -Os -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -DAVR -Wall -I.. -mmcu=atmega88 -DF_CPU=8000000 -c bob3tht.cpp -o bob3tht.o
avr-gcc -D_BOB3_ -g -Os -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -DAVR -Wall -I.. -mmcu=atmega88 -DF_CPU=8000000 -c bob3smd.cpp -o bob3smd.o
avr-ar -q libbob3-smd.a analog.o bob3.o ircom.o leds.o main.o bob3smd.o
```

2. For each compilation:

```
avr-gcc -I../../../build/lib -D_BOB3_ -g -Os -fno-exceptions -fdata-sections -fno-threadsafe-statics -MMD -ffunction-sections -DAVR -Wall -Wextra -Wpointer-arith -Wcast-qual -Wmissing-include-dirs -Wno-unused-parameter -Wuninitialized -mmcu=atmega88 -DF_CPU=8000000 -finput-charset=UTF-8 -c teil3.cpp -o teil3.o
avr-gcc -L../../../build/lib/bob3 -mmcu=atmega88 -Os -Wl,--gc-sections -o teil3.elf teil3.o  -lbob3-smd
avr-objcopy -j .text -j .data -O ihex teil3.elf teil3.hex
```

courtesy of @springob

This, however may cause changes in code generation.

**Comment by bjost2s** [comment]
where is the commit?
is it now released? We haven't tested it!

**Comment by VinArt** [comment]
It is not resolved.

**Comment by VinArt** [comment]
mixed up the projects, sorry

**Comment by VinArt** [comment]
ArduinoSTL would not be compatible

**Comment by VinArt** [comment]
So this is actually possible and compilation is instant. Lists cause the problem of applying this method.

**Comment by VinArt** [comment]
- A small implementation of lists will be provided to substitute std::list
- Arduino builder will not be used

**Comment by VinArt** [comment]
- there will be no lists for now

**Comment by bjost2s** [comment]
works like a charm!

**Comment by bjost2s** [comment]
Unfortunately math constants or more is not defined any more!
![image](https://user-images.githubusercontent.com/1613069/71737147-2e2bb100-2e53-11ea-8cf8-90b1e3428215.png)

**Comment by bjost2s** [comment]
In 1425720a9312df32aa90be2de912644fbcc6851d NEPODefs.h has been removed from code generation, this causes the above-mentioned error
