### ISSUE TITLE
RCJ RescueOnlineSim

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1700]
Integrate robot [RCJ RescueOnlineSim](https://robocupjunior.at/simulation/) in the OpenRoberta Lab.

RCJ RescueOnlineSim is only a simulated robot, there is no hardware available.
- [x] Create a simulated robot with sensors and actuators related to the [RoboCup Junior Rescue Online Rules](https://junior.robocup.de/wp-content/uploads/2024/03/LineEntryRules2024.pdf)
- [x] Allow importing a simulation environment created with the [RobCup Junior Map Editor](https://cms.rcj.mytech.zone/service/editor/line/2023)
- [x] Add a scoring tool, 
- [x] Activate NN, all activation functions

**Comment by rbudde** [comment]
has been tested with some typical programs and works.
