### ISSUE TITLE
RGB Sensor Value Not Updating Continuously When Used with xNN 'schreibe Wert Eingabe-Neuron'

### ISSUE THREAD

**Issue by ckaschny** [OpenRoberta/openroberta-lab#1702]
**Describe the bug:** When using the "gib RGB Farbsensor" sensor in combination with xNN's "schreibe Wert Eingabe-Neuron" command, the RGB value is only read once at the beginning, even when inside a loop. This does not occur when reading the RGB value without using xNN. This issue can be observed in the variable values shown in the simulation: for example, the red value should display 255 but instead shows the initial value of 0 when the robot begins moving on blue. The sigmoid function was used as the activation function. Screenshots are provided below to illustrate what works and what doesn't.

**Steps to reproduce the behavior:**

    Replicate the NEPO code shown in the screenshot.
    Train the neural network using the data provided in the table below.
    Start the robot on a blue surface.
    Observe the variable values in the simulation: the red value remains at zero, even when the robot moves from blue to other colors.
![bug_orl_xnn_rgb](https://github.com/user-attachments/assets/49746c92-c0ec-4cc2-9c3a-329bd8e4b4d4)
![rgb_werte](https://github.com/user-attachments/assets/9eabb64f-4def-4d78-aa21-82ed2c811004)
![xNN-rot](https://github.com/user-attachments/assets/0ca7fd56-85c1-4a94-9726-ac4bdfe8ddf5)

Values for xNN training: 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kaschchr/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kaschchr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

205 | 92 | 92 | 1
-- | -- | -- | --
240 | 128 | 128 | 1
250 | 128 | 114 | 1
233 | 150 | 122 | 1
220 | 20 | 60 | 1
178 | 34 | 34 | 1
139 | 0 | 0 | 1
255 | 0 | 0 | 1
255 | 99 | 71 | 1
255 | 127 | 80 | 1
0 | 100 | 0 | 0
0 | 128 | 0 | 0
34 | 139 | 34 | 0
50 | 205 | 50 | 0
0 | 255 | 0 | 0
60 | 179 | 113 | 0
0 | 255 | 127 | 0
32 | 178 | 170 | 0
72 | 209 | 204 | 0
0 | 128 | 128 | 0
0 | 255 | 255 | 0
135 | 206 | 250 | 0
0 | 191 | 255 | 0
30 | 144 | 255 | 0
65 | 105 | 225 | 0
0 | 0 | 205 | 0
0 | 0 | 139 | 0
0 | 0 | 128 | 0
255 | 255 | 255 | 0
0 | 0 | 0 | 0
255 | 255 | 0 | 0

</body>

</html>

**Comment by rbudde** [comment]
this issue is not in a good shape.
- please attach the program
- the training state and the state submitting values to a NN are unrelated. It is unclear to me why you supply trainingsdata. The trained net should be sufficient for your demonstration
- the example should be minimal, i.e. contain only the stuff to reproduce the error
- I don't understand your program. Your wait block will never terminate, your loop will run only once and then be blocked. Why are you using sigmoid?

**Comment by ckaschny** [comment]
The apparent issue was resolved by implementing the correct code. It turns out there was no bug in Open Roberta; instead, the behavior stemmed from an error in my initial implementation. I apologize for the premature issue report and appreciate the quick and insightful response. In the future, I’ll make sure to review my code thoroughly and take a moment before posting an issue.

The working NEPO-code is attached as zip-file:[rgb_rot_klassifizieren.zip](https://github.com/user-attachments/files/17639547/rgb_rot_klassifizieren.zip)
The weights used are given by:
gewissheit_rot = sigmoid( 0.7461046233479266 + 0.02326065161333958*rot - 0.017875524474638117*gruen - 0.015853326731916997*blau )
The sigmoid function was used instead of linear mapping to constrain the output values between 0 and 1, making it suitable for binary classification in identifying red.

**Comment by ckaschny** [comment]
The reworked code for quick reference: 
![grafik](https://github.com/user-attachments/assets/e43e79a5-a89a-4feb-84d3-56f0d11dc447)
