### ISSUE TITLE
German blocks in 'Robot Configuration' for SenseBox needed

### ISSUE THREAD

**Issue by vlebedynska** [OpenRoberta/openroberta-lab#177]
Some actions blocks in 'Robot Configuration' for the SenseBox are only available in English. They should also be available in German.

**Comment by bjost2s** [comment]
Where is the commit to blockly and what changes have been made in blockly_compressed.js?

**Comment by vlebedynska** [comment]
> 
> 
> Where is the commit to blockly and what changes have been made in blockly_compressed.js?

Here is the commit link: https://github.com/OpenRoberta/blockly/commit/0051d1e36bad268e90c737156abb876799becbc8 and the pull request link: OpenRoberta/blockly#31.

@VinArt re-generated `blockly_compressed.js` because of changes made in the `de.json` file. No manual changes were made in `blockly_compressed.js`.
