### ISSUE TITLE
Calli:Bot does not move backward when moved forward before

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#179]
**Describe the bug**
 Calli:Bot does not move backward when moved forward before. See also screenshot. Calli:Bot doesn't move after the first forward movement
**To Reproduce**
execute the program on a Calli:Bot and observe the behaviour

**Expected behavior**
 -Calli:Bot moves first forward and then backward
**Screenshots**
 - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1613069/60702900-7f88d100-9f00-11e9-95ae-7580bc1847c5.png)

**Additional context**
I would like to do some more test concerning different movement sequences

**Comment by bjost2s** [comment]
Seems to be a problem of the Calli:Bot design. 
Comment from the manufacturer: Please use accumulators instead of batteries, this will fix this problems.

**Comment by rbudde** [comment]
Note: if the motors are stopped and then a short wait is executed, the program works for me.

It is questionable for me, whether we should support robots with such a weak design. Programming and debugging must be a nightmare for the user. Or?

**Comment by bjost2s** [comment]
Following the the instructions from the manufacturer, Calli:Bot is working correct when using rechargeable battery instead of a normal battery.
