### ISSUE TITLE
Revise and improve program checkers for all system

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#180]
A common solution for all systems is needed, which makes sure that checkers for all blocks with  parameters are available. This excludes special checkers for the program configuration relation which is handled in #114

We should start with EV3 to derive from this example the needed steps for all other systems.

**Comment by boonto** [comment]
This issue changed in the process of the refactoring to lay the groundwork for revised and improved checkers. Now, additional checkers can be easily implemented as workers into existing workflows.

**Comment by bjost2s** [comment]
Then this  issue is not resolved?

**Comment by rbudde** [comment]
This issue is NOT resolved, but should probably be divided into some more concrete ones. It is too large and too unspecific.

**Comment by rbudde** [comment]
overlap with #114

**Comment by rbudde** [comment]
was tested. Remaining work put into new issue #306
