### ISSUE TITLE
Refactor ConfigurationComponent to contain blockly information

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#182]
Currently robot configuration is handled in a different way to the program, it is not being transformed to an AST and back, so it is impossible to annotate the blocks, for example.

Information is only pulled from the XML and not written back.

In order for us to be able to annotate configuration blockly blocks, ConfigurationComponent needs to contain all the needed information to rebuild the blockly block.

**Comment by VinArt** [comment]
see #114

**Comment by VinArt** [comment]
ConfigurationComponent extends Phrase on feature/workflows

**Comment by bjost2s** [comment]
There is a fix for this issue in the development branch, @VinArt please do not remove it from the project

**Comment by bjost2s** [comment]
@VinArt , please provide some information how to test the solution

**Comment by VinArt** [comment]
I added a unit test to check this.
