### ISSUE TITLE
Calliope set motor A+B generates unexpected code

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#184]
**Describe the bug**
![rand-ab](https://user-images.githubusercontent.com/15834363/61054863-a0fe2700-a3f0-11e9-81ee-0768cf2ec51d.png)

generates the following code:

![rand-ab-code](https://user-images.githubusercontent.com/15834363/61054902-ae1b1600-a3f0-11e9-9c28-1f8bf478b36a.png)

If I use this block, I expect, that random is called only once and that both motors get the same speed.

**Expected behavior**
 
call rand only once

**Comment by boonto** [comment]
This is also the case for "Calli:bot both".

**Comment by boonto** [comment]
Now, when using either of these modes on the "motor on" block a global store variable is generated and used.
