### ISSUE TITLE
Can not transmit a program with "say" block to EV3 leJOS 0.9.0

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#189]
**Describe the bug**
If the "say" block is used in a program and you try to transmit that program to an EV3 leJOS 0.9.0, an error message is shown and the program will not be transmitted.

**To Reproduce**
1. Go to the ORLab
2. Select EV3 leJOS 0.9.0 as robot type
3. Connect an EV3 leJOS 0.9.0 robot to the lab
4. Put the "say" block into the program
5. Press the "Play" btton to transmit the program to the EV3
6. See error

**Expected behavior**
 - The program should be transmitted to the robot and the EV3 should say whatever is specified.

**Screenshots**
![Screenshot-2019-7-15 Open Roberta Lab](https://user-images.githubusercontent.com/10925094/61202613-47477680-a6e8-11e9-855c-4d245c77f5a8.png)

**Device information**
 - EV3 leJOS 0.9.0, connected over WiFi/WLAN

**Additional context**
 - A program with the "say" block does work in the simulation, but the "say" has no effect, as if it was skipped. THis is the same for EV3 0.9.1

**Comment by bjost2s** [comment]
The say block is only implemented for EV3 0.9.1 and EV3Dev and it definitely cannot be implemented in EV3 0.9.0, so we should improve the error message for this case!
The simulation supports all blocks from EV3 0.9.0 with the standard configuration, so far
and also I think there was an issue with text to speach in the browsers, we will check it again.

**Comment by bjost2s** [comment]
unfortunately this block has no help :(, I think that will be also a good place to explain the situation to the user

**Comment by boonto** [comment]
Usually there should be a warning annotation for EV3LejosV0, which notifies the user but allows compilation and running the program. But that is missing.

The missing simulation speech is handled in #204

**Comment by boonto** [comment]
After fixing the old approach the message says `The exection of this block will have no effect!`, but `Überprüfe die Einstellungen bei diesem Block. Er wird so nichts ausführen können.` in german. The english message sounds fine, however the german one does not. @bjost2s should we introduce a new message `This robot variant does not support this block. It wont be executed.`?
