### ISSUE TITLE
When using the "play frequency Hz" block on WeDo, the program will not be executed

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#191]
**Describe the bug**
If a program contains the "play frequency Hz" block on WeDo, the whole program does not run on the WeDo and it is no longer possible to start another program on it. The robot needs to be reconnected.

**To Reproduce**
1. Start the Open Roberta Mobile App
2.  Connect a WeDo to the App
3. Create a valid program and add the "play frequency Hz" with a valid input to the program
4. Press the play button to run the program on the WeDo
5. The WeDo will do nothing.
6. The Play button will be grayed out.
7. To run programs on the WeDo again you need to reconnect it.

**Expected behavior**
 - The program should be executed, including the "play frequency Hz" Block.
 - It should be possible to start other programs on the WeDo after the program ended.

**Screenshots**
![Screenshot-2019-7-16 Open Roberta Lab](https://user-images.githubusercontent.com/10925094/61295370-32e2a700-a7d8-11e9-91b9-9438ee54f503.png)

**Device information**
 - WeDo 2.0
 - Open Roberta Mobile App
 - iOS & Android

**Comment by bjost2s** [comment]
see #74

**Comment by rbudde** [comment]
See #215
