### ISSUE TITLE
Open the correct keyboard view for numeric inputs on iOS

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#194]
**Is your feature request related to a problem? Please describe.**
 -If you set a number in the number block (![Screenshot-2019-7-16 Open Roberta Lab(3)](https://user-images.githubusercontent.com/10925094/61298973-85739180-a7df-11e9-9d30-1bbf3f67f862.png)), the normal keyboard opens on mobile Safari.

**Describe the solution you'd like**
 - Open the numeric keyboard.

**Describe alternatives you've considered**
 - Switching from the normal keyboard to the numeric view each time.

**Additional context**
 - Reproduced in the Safari browser and in the Roberta Mobile App on iOS on an iPad 4th. Gen. with iOS 10.3.3 and on an iPhone X with iOS 12.3.1

**Comment by bjost2s** [comment]
unfortunately the IOS systems doesn't offer a "-" in their numeric keyboard, so no way to put in negative numbers. To reduce IOS mobiles that they cannot access negative numbers will restrict them in a way that it makes no sense to work with the Open Roberta Lab
