### ISSUE TITLE
Create list with item (int or string) repeated N times doesn't compile on Arduino

### ISSUE THREAD

**Issue by simonedegiacomi** [OpenRoberta/openroberta-lab#197]
**Describe the bug**
The block to create a list with an item repeated N times doesn't compile on Arduino if the item is an int.
This is because the utility function `_createListRepeat` get expanded to return a `std::list<int>`, which cannot be casted to `std::list<double>`.

**To Reproduce**
1. Create a new program and select one of the Arduino targets
2. Connect an Arduino
3. Create the following program
![image](https://user-images.githubusercontent.com/15476739/61380101-0ea2cb00-a8a9-11e9-9d3a-a1fbe0f6e55f.png)
4. Press Run and see the compilation error

Notice that the following program compiles:
![image](https://user-images.githubusercontent.com/15476739/61380162-2c703000-a8a9-11e9-937d-c6402e2a00a5.png)

**Expected behavior**
The program should compile.

**Screenshots**

![image](https://user-images.githubusercontent.com/15476739/61380304-680afa00-a8a9-11e9-9cf2-061f0e82140b.png)

**Device information**
 - Type: Desktop
 - OS: Ubuntu
 - Browser: Firefox

**Additional context**
Bug discovered while working on #29

**Comment by simonedegiacomi** [comment]
I resolved the same problem in c4ev3 with this commit https://github.com/OpenRoberta/openroberta-lab/commit/b56181d76bb4bc4fb28f9cbbc1b30e44063db032. If it is okay I can move this code into AbstractCppVisitor to fix the block also for Arduino

**Comment by bjost2s** [comment]
Sounds good. Please check if (float) would be ok, too. I think we use float in general on the robots unless it is defined differently. Please also check the IT tests, they should have covered this.

**Comment by rbudde** [comment]
Nope. Actually nosystematic test coverage for lists. A student ist working exactly on this topic, if the other tests he is working on are complete (hopefully in the near future)

**Comment by simonedegiacomi** [comment]
I updated the title, since the program doesn't compile also with string. A cast is necessary, otherwise the following error appears:
```
error: conversion from ‘list<const char*,allocator<const char*>>’ to non-scalar type ‘list<std::__cxx11::basic_string<char>,allocator<std::__cxx11::basic_string<char>>>’ requested
```

**Comment by simonedegiacomi** [comment]
@bjost2s I checked about double or float and it appear that in Arduino double it's used for numbers and list of numbers

**Comment by VinArt** [comment]
This is compiling (at least) now and is already in develop
