### ISSUE TITLE
Functions with deactivated blocks may not be executed correctly in the simulation

### ISSUE THREAD

**Issue by munka21** [OpenRoberta/openroberta-lab#198]
### Describe the bug
Functions with deactivated blocks will not fully be executed or get skipped in the simulation. 
The only exception is, if the deactivated block is at the end of the function. In that case the function will be executed as expected. (Without the last deactivated block) If you deactivate multiple blocks at the end the bug will yet occur.
Most of the time when the bug occurs, the function will be skipped and the rest of the program will be executed normally. Sometimes though, the blocks before the deactivated block will be executed normally, but all blocks after the deactivated one will be skipped.

### To Reproduce
1. Select any robot with a simulation
2. Create a new program with a function, that has at least 2 blocks in it.
2. Deactivate a block in function that is not the last block of the function.
3. Run the program in the simulation.
4. The function will be skipped.

### Expected behavior
The function will fully executed and only the deactivated blocks will be skipped.

### Screenshots
![Program](https://user-images.githubusercontent.com/48803535/61441638-54fa3780-a946-11e9-8e5b-8aa72247ed58.png)

**Comment by rbudde** [comment]
See #215
