### ISSUE TITLE
Access to all pins on the micro:bit board

### ISSUE THREAD

**Issue by munka21** [OpenRoberta/openroberta-lab#199]
**Is your feature request related to a problem? Please describe.**

When you connect a micro:bit to an IO F5 board, you need to have a access to all of the pins, which are available on the micro:bit. This is necessary if you want to program a fischertechik model for example. With NEPO, you only have access to 3 of the 16 available pins. 

**Describe the solution you'd like**
 I would like to have a access to all of pins on the micro:bit board

![Foto microbit Board (1)](https://user-images.githubusercontent.com/48803535/61463896-9eae4680-a975-11e9-95fe-da12dfafa181.jpg)

![microbit (1)](https://user-images.githubusercontent.com/48803535/61463862-8fc79400-a975-11e9-9e6e-c1e337f0bd5c.png)

**Comment by bjost2s** [comment]
Interesting, so far we do not have an appropriate board to test this, so the implementation will be hard. Once we can get the hardware we will come back to you request

**Comment by boonto** [comment]
I followed [these](https://microbit.org/guide/hardware/pins/).

**Comment by VinArt** [comment]
I think, before resolving this, we should test how it works. I am not quite sure, whether it is possible, for example to use pins 19 and 20 for GPIO, since they are connected to I2C.
