### ISSUE TITLE
Improve statistics logging

### ISSUE THREAD

**Issue by MatthiasSchmickler** [OpenRoberta/openroberta-lab#200]
Improve statistics logging by adding several logs and arguments to specific kind of logs for generating new information of the given data. The analysis will be more precise (ServerRestart) and extensive. Therefore issues and errors shall be recognized faster and the analysis gives more information about the usage of OpenRobertaLab. 
- [x] add UserCreate log
- [x] add UserDelete log
- [x] add ChangeRobot log
- [x] add ChangeLanguage log
- [x] add ProgramNew log
- [x] add args to every log, whether it was successful or not
- [x] add ConnectRobot log
- [x] add ViewHelp log
- [x] add ProgramExport log
- [x] add program length as args to ProgramRun
- [x] add "create Link to share" to ProgramShare log
- [x] add ServerRestart log
- [ ] summing up ProgramRun, ProgramRunBack ... to ProgramRun with additional transfer arguments

**Comment by boonto** [comment]
Merged.
