### ISSUE TITLE
Reduce unnecessarily high logging level

### ISSUE THREAD

**Issue by MatthiasSchmickler** [OpenRoberta/openroberta-lab#201]
Several logs have the logging levels ERROR/WARN but do not contain error or warning information.
For those the log level has to be changed for keeping a clean log file. 
Only errors shall be marked as errors.

For example: Error. The error key is: USER_ERROR_EMAIL_USED
- [x] filter error and warn loggings and change loglevel where necessary

**Comment by boonto** [comment]
Merged.
