### ISSUE TITLE
view of ev3 block in simulation not working, change background not working

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#202]
- write an ev3 program
- open sim
- click "EV3" button
- screen is white (press ctrl&- to see that the brick is outside of the screen (?)

- changing background in sim and pressing "ev3" button generates many different errors (I expect for the same reason as above). Sometimes many ev3 bricks appears an the screen.

the same behavior on both chrome and firefox

**Comment by bjost2s** [comment]
already fixed in #61
