### ISSUE TITLE
Simulation does not open if ternary block, with empty branch, is in task

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#203]
**Describe the bug**
 - If a ternary block, with a branch block missing, is in task the simulation does not open.

**To Reproduce**
1. Add a empty ternary block to any block in the program
2. Try to open the simulation

**Expected behavior**
 - The simulation opens.

**Comment by bjost2s** [comment]
here are two programs where the problem does not show up:
EV3
![image](https://user-images.githubusercontent.com/1613069/62444314-75efc480-b75d-11e9-83c7-6bb53182fc37.png)
Calliope
![image](https://user-images.githubusercontent.com/1613069/62444337-86a03a80-b75d-11e9-9c7a-a31bd20a5c1d.png)

Please provide an example

**Comment by boonto** [comment]
I just checked, one of the branches has to be empty.
Works:
![image](https://user-images.githubusercontent.com/7438960/62448807-e8b26d00-b768-11e9-87af-471e84aff684.png)
Does not work:
![image](https://user-images.githubusercontent.com/7438960/62448835-0089f100-b769-11e9-8c51-0220c1555acc.png)

**Comment by rbudde** [comment]
See #215

**Comment by VinArt** [comment]
Simulation does not open, ternary block has wrong colour of output.

**Comment by bjost2s** [comment]
Will be solved with EmptyBlockVisitor
