### ISSUE TITLE
Open Roberta Lab does not "load" in Internet Explorer

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#211]
**Describe the bug**
When opening the Open Roberta Lab on the Internet Explorer (testet IE Version 11), the loading indicator at the beginning never stops turning.

**To Reproduce**
1. Open the Internet Explorer
2. Go to the Open Roberta Lab
3. See error

**Expected behavior**
 - The Lab should load and be usable.

**Device information**
 - Internet Explorer 11 
 - Windows 10

**Comment by bjost2s** [comment]
This is a problem of not supported ECMAScript 6 in IE and IOS Webviews. Will be fixed asap

**Comment by rbudde** [comment]
startWith is not available in IE<12; wrong behavior in some IOS webview impl.
Replaced by indexOf

Added to 3.5.1 for a later review
