### ISSUE TITLE
Faulty backtransformation of "in list x remove" block

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#217]
**Describe the bug**
 - The "in list x remove" will become connectable when it is returned to the frontend. The backtransformation seems to be missing the mutation.
 - The issue may be related to #216.

**To Reproduce**
1. Add "in list x get" block to workspace, it acts as a connectable block
2. Change block to remove, it changes to an action block
3. Open the code view
4. Observe the block is still an action, but is now connectable as well
5. If connected to the start block it behaves weird and cannot be removed again

**Expected behavior**
 - The block stays the same and behaviour does not change.

**Screenshots**
![image](https://user-images.githubusercontent.com/7438960/62708889-92595e80-b9f4-11e9-9c34-6d4c5a1b97c7.png)

**Comment by bjost2s** [comment]
fixed with https://github.com/OpenRoberta/blockly/commit/54a5bc542adea80f8d008434eceb47ffd2bf4d12#diff-573941d1cf414bd2137f8eddb3d14574
