### ISSUE TITLE
EV3: regression in python codegen for MotorEncoder and Gyro Sensor

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/openroberta-lab#219]
**Describe the bug**
This change
https://github.com/OpenRoberta/openroberta-lab/commit/dc121fc956062d8c1478ed796b20f87ba5678cf1#diff-a1a68ba2a40bafdf896b0e4f68ffbea5L512
and
https://github.com/OpenRoberta/openroberta-lab/commit/dc121fc956062d8c1478ed796b20f87ba5678cf1#diff-a1a68ba2a40bafdf896b0e4f68ffbea5L535

dropped the 'getEnumCode()' function. This causes the python code to ne generated as:
```
hal.getMotorTachoValue('B', DISTANCE)
```
instead of
```
hal.getMotorTachoValue('B', 'distance')
```
The HAL code (https://github.com/OpenRoberta/robertalab-ev3dev/blob/develop/roberta/ev3.py#L680) expects strings. The hal does not define constants for those (at least not for ev3dev).

**To Reproduce**
![image](https://user-images.githubusercontent.com/1279486/62835100-bfa44780-bc54-11e9-9537-a95ccf8494fb.png)

This is a regression and luckily very easy to fix.  From a quick look this applies to:
```
visitEncoderSensor()
visitCompassSensor()
```
If we can apply a hot fix for the server, that'd be great.

**Comment by boonto** [comment]
Already merged in 3.5.2.
