### ISSUE TITLE
Blocks which are not supported in simulation should get marked

### ISSUE THREAD

**Issue by rhasel4s** [OpenRoberta/openroberta-lab#224]
**Describe the bug**
 Blocks that cannot be used in the simulation or have no function should be marked, for example:

- Serial Write (micro:bit)
- get presence (EV3)

**To Reproduce**
Steps to reproduce the behavior for micro:bit
1. Select micro:bit as robot
2. Open the advanced mode action display menu
3. Select the block
4. Add it to the program
5. Open and start the simulation

**Expected behavior**
 - The user should be informed, that those blocks are not supported in simulation

**Screenshots**
 micro:bit:
![serial_write](https://user-images.githubusercontent.com/15631864/63154729-8d5a6780-c011-11e9-8da4-1aec9b391d77.png)

**Comment by ensonic** [comment]
I think we could support serial write. We could have a text view in the simulation that shows the text output from serial write.

**Comment by bjost2s** [comment]
This feature is already implemented, see developer console:
![image](https://github.com/user-attachments/assets/649ded73-4a71-4dff-b975-7ec0e99ccb53)
