### ISSUE TITLE
micro:bit create list shows wrong type 

### ISSUE THREAD

**Issue by rhasel4s** [OpenRoberta/openroberta-lab#225]
**Describe the bug**
 - when creating a list via the advanced block menu the drop-down shows the option colour, which is not supported by micro:bit.

**To Reproduce**
1. Go to micro:bit
2. open the advanced menu
3. drag on of the two or both create list blocks to the workspace
4. click on the drop-down menu

**Expected behavior**
 - The drop-down menu should show the same options like when creating the list via the variables option (see first screen)
**Screenshots**
 
![micro_bit_color1](https://user-images.githubusercontent.com/15631864/63156717-96e5ce80-c015-11e9-9b36-4104183c2641.png)
![microbit_color2](https://user-images.githubusercontent.com/15631864/63156718-977e6500-c015-11e9-9f0a-f1a9db4316bd.png)
![microbit_color3](https://user-images.githubusercontent.com/15631864/63156719-977e6500-c015-11e9-8b32-02b6af0c9b1f.png)

**Comment by practiceiqx** [comment]
？？？

**Comment by boonto** [comment]
Types are now consistent.
