### ISSUE TITLE
EV3: Compiler error when deleting a used function

### ISSUE THREAD

**Issue by rhasel4s** [OpenRoberta/openroberta-lab#228]
**Describe the bug**
 - When a function used in a programm is deleted the block of the deleted function remains in the program.

**To Reproduce**

1. Create a function
2. Add the function to the program
3. Delete the function
4. Run the program

**Expected behavior**
 - The block should be removed from the program

**Screenshots**
Complete Program
![deleteFunction1](https://user-images.githubusercontent.com/15631864/63172148-513cfc00-c03d-11e9-94c8-88005206c483.png)
Function deleted
![deleteFunction2](https://user-images.githubusercontent.com/15631864/63172150-513cfc00-c03d-11e9-9536-f30f5a2e5e99.png)
Try to run the program
![deleteFunction3](https://user-images.githubusercontent.com/15631864/63172152-51d59280-c03d-11e9-84b0-7d834e8d3e70.png)

**Comment by bjost2s** [comment]
see #69
