### ISSUE TITLE
Reduce ping request whenever it is not needed

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#229]
The ping request is only needed when the client would like to get information about the state of the robot. Depending on the way the programs are transferred to the system, the ping might not send back any information. The robot.connection property can have the following values: arduinoAgentOrToken, token, autoConnection, webview and local. AutoConnection, webview and local are applied to systems where the state of the robot is always unknown (for the server) so no ping is needed.
@VinArt, you have introduced "arduinoAgent" as an additional property on the client site, but there is currently no plugin using it, so it will be removed with this commit.

**Comment by bjost2s** [comment]
Due to the reduced httpsession timeout (60) we have to keep the ping. But systems which do not need it should ping less often.

**Comment by bjost2s** [comment]
When switching the robot system, sometimes the new ping time takes too much time, blocked by the current timeout.

**Comment by boonto** [comment]
After running programs on Dev/Lejos the run button does not reactivate.

**Comment by boonto** [comment]
Run button works for EV3 again.
Run button is not reactivated randomly during compilation process, of e.g. Arduino, anymore.
