### ISSUE TITLE
Calliope Programm with receive boolean not executable Error

### ISSUE THREAD

**Issue by kwollw** [OpenRoberta/openroberta-lab#23]
Given a minimal example to show the bug:
![Bildschirmfoto zu 2019-05-16_08-54-49](https://user-images.githubusercontent.com/6341023/57832796-c8ea5900-77b8-11e9-9155-8080e0469fdf.png)

**Comment by VinArt** [comment]
Tested by sending (an receiving) altering true/false booleans.
