### ISSUE TITLE
Replace usages of BlocklyMethods for Java robots

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#230]
Continuation issue to partially solved issue #95:
`BlocklyMethods` and `NEPODefs` still have to be removed from C based robots.

- [x] Find all "BlocklyMethods.py" / "NEPOdefs.h" etc.
- [x] Find common Java methods
- [x] Extract Java one liners (constants?) directly into code generation
- [x] Combine Java multi liners into common helper methods
- [x] Implement class in all Java robots
- [x] Default implementations for Java
- [x] Special implementations for Java robots that don't support default
- [x] Unit tests
- [x] Test each method on Java robots

**Comment by boonto** [comment]
Will be continued in #278.

**Comment by bjost2s** [comment]
couldn't find any string "BlocklyMethods" in the java code generation files.
