### ISSUE TITLE
c4ev3 compilation on raspberry pi

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#231]
Previously c4ev3 could not be compiled on a Raspberry Pi.
Commit daaaa0cfb49ec6586d2a42ee062a6e45533d4cf6 should have fixed it.

Additional information of @simonedegiacomi:
This is the compiler for raspberry: https://drive.google.com/file/d/1qz6nKB1nZ5dW4DXi2opePIvNRVZaHR96/view?usp=sharing
It is not the version that c4ev3 will provide, since they haven't finalized the config files yet, but the changes shouldn't affect us (anyway we can update to the final version easily).
To use it just extract it and link the g++ binary. Something like this should work:
```
tar -xzvf C4EV3.Toolchain-2019.08.0-rpi.tar.gz
sudo mv C4EV3.Toolchain-2019.08.0 /opt/C4EV3.Toolchain-2019.08.0
sudo ln -s /opt/C4EV3.Toolchain-2019.08.0/arm-c4ev3-linux-uclibceabi/gcc-8.2.1-uclibc-ng-1.0.31-binutils-2.31.1-kernel-2.6.33-rc4-sanitized/bin/arm-c4ev3-linux-uclibceabi-g++ /usr/bin/arm-c4ev3-linux-uclibceabi-g++
```
This shouldn't break other robots compilers, since all the files are in the toolchain folder.

**Comment by bjost2s** [comment]
tested and published here https://www.roberta-home.de/lab/lokale-installation/
