### ISSUE TITLE
Support for Calli:bot

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#24]
Calli:bot is a Calliope compatible robotic platform, look [here](https://shop.knotech.de/schule/calliope/calli-bot/videos-und-programme/239/calli-bot)  for a detailed description or [here](https://www.dfrobot.com/product-1783.html) for the original platform.
Support is needed for accessing
- differential drive
- ultrasonic sensor
- line infrared sensors
- 2 front leds
- 4 rgb leds

Support for the maqueen platform for micro:bit would also be very nice (probably in a second issue)

**Comment by VinArt** [comment]
Unit tests are still needed.
