### ISSUE TITLE
Forwards/backwards option in steer block in ev3dev has no effect

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#241]
Steer blocks in ev3dev have options for directions that do nothing and only possibility to change direction is to supply negative/positive values for left/right motor speed.

![image](https://user-images.githubusercontent.com/3738015/64119275-bc0a6900-cd99-11e9-8336-435ae0bea137.png)

After a quick look into the hal I could not determine the cause of such behaviour, so this needs further investigation.

**Comment by ensonic** [comment]
It works for me. Could you retry?

**Comment by boonto** [comment]
It only happened on one of our images, I updated it and everything works.
