### ISSUE TITLE
Get degree from encoder produces KeyError if no motor was used before on ev3dev

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#243]
If one creates a program that simply reads out the encoder value and shows it, then this program will crash because an actor is not added in the configuration of ev3dev, since a motor actor was not used in the program.

![image](https://user-images.githubusercontent.com/3738015/64119817-fcb6b200-cd9a-11e9-8372-08486edaa049.png)

So an actor should be added even if no actor is used for this particular case.

**Comment by ensonic** [comment]
Shouldn't the UsedHardware visitor check this?

**Comment by VinArt** [comment]
Looks like a job for it. I am working on a similar topic, so I will come across this at some point, I think.
