### ISSUE TITLE
Calliope new dal available

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#247]
here https://github.com/calliope-mini/microbit-dal/releases/tag/v2.2
we should rebase on this

**Comment by bjost2s** [comment]
Reviewed by the calliope team

**Comment by bjost2s** [comment]
The attached program is one from the gallery (a little game). It is not compilable on the testserver anymore, `region RAM overflowed with stack collect`

[Diamantenjagd.zip](https://github.com/OpenRoberta/openroberta-lab/files/4023682/Diamantenjagd.zip)

**Comment by rbudde** [comment]
this is a general problem of the code geenrator. Compiling a program with 9 variables for example, without any other behavior, crashes the linker.

Changed the code generator to fix this.

**Comment by bjost2s** [comment]
Seems that the bluetooth stack uses too much memory. So one solution is to offer the calliope plugin with the bluetooth stack and without (with the radio stack) to make bigger programs compilable.

**Comment by rbudde** [comment]
by adding a new noblu calliope plugin, the problem vanishes. It is likely, that it will re-appear, if either new dal version arrive or user write large programs.

See for a discussion related to microbit/gcc/newlib&locales the following resources:

`https://github.com/bbcmicrobit/micropython/issues/363` and the issue referred there: `https://bugs.launchpad.net/gcc-arm-embedded/+bug/1686067`
