### ISSUE TITLE
compilation error on buster on a raspberry pi 3

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/openroberta-lab#249]
I try to build a openroberta-server on a raspberry pi 3. I downloaded the latest raspbian image, whitch comes with debian buster.
I installed the the "default-jdk"- and the maven package. They show:

$ javac -version
javac 11.0.3

$ maven:  mvn -v
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.3, vendor: Raspbian, runtime: /usr/lib/jvm/java-11-openjdk-armhf
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.19.66-v7+", arch: "arm", family: "unix"

I cloned openroberta-lab as suggested.

Compilation (mvn -e clean install) ends with an error message. You can find the error log attached.
Should I go back to debian stretch or is there another solution?

Thanks in advance for any hint.

Cheers corvus-albus

[error_log_20190905.txt](https://github.com/OpenRoberta/openroberta-lab/files/3580404/error_log_20190905.txt)

**Comment by VinArt** [comment]
You can also try java 8 if that is available for your distribution.

**Comment by corvus-albus** [comment]
Thank you for your hint. I finally managed to install oracle java 8 manually and it compiled without errors.
