### ISSUE TITLE
Sensebox does not get flashed with generated binary data

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#252]
**Describe the bug**
 - The program that is delivered to the frontend is wrongly read-out and later encoded, so the resulting file is unsuitable to be flashed onto the sensebox. Sensebox consumes the file, but stays in the programming mode.

The generated binary should be read out as a byetarray and not as a string with encoding.

**Comment by bjost2s** [comment]
@VinArt, there are changes also for other robots than sensebox, please expand the issue so that we do not forget to test everything!

**Comment by VinArt** [comment]
test that eclipse's refactor->rename worked for following robots:
- [ ] mbot
- [ ] botnroll
- [ ] arduino

**Comment by bjost2s** [comment]
+1 for a hotfix, non working plugins are the main reason for no users :-(

**Comment by rbudde** [comment]
Upload to Sensework working.
