### ISSUE TITLE
Bug: lightsensor in NXT-simulation

### ISSUE THREAD

**Issue by munka21** [OpenRoberta/openroberta-lab#258]
**Describe the bug**
I programmed a line follower with NXT in Openroberta-Lab.  Unfortunately, when I run the simulation, the robot rotates  only in a circle.

**To Reproduce**
I have programmed a simple line follower (screenshot below)

**Screenshots**
![Screenshots](https://user-images.githubusercontent.com/48803535/65762360-23110880-e121-11e9-9874-bedfe1ba4ee2.png)

**Expected behavior**
I want that the NXT to follow the line.

**Device information**
 I use Windows computers and Firefox

**Comment by boonto** [comment]
The line following program works now.
