### ISSUE TITLE
Simulation window gets all white if you click "EV3 - open the robots view" or "open the sensors' data view"

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/openroberta-lab#260]
Choose ev3dev (or NXT/Calliope/...) and open the simulation window. Then click on "open the robots view" or "open the sensors' data view". The simulation window gets white you can't see any simulation.  

It was still working in ORS 3.5.2. I see the same behaviour on my self hosted ORServer. If I switch back to 3.5.2 anything works fine.
Cheers 
corvus-albus

**Comment by corvus-albus** [comment]
I tried it again at Saturday evening (22:30) and it's working properly now.

**Comment by bjost2s** [comment]
Maybe a problem of cached data? Please close, if it is not reproducable, thank you.

**Comment by corvus-albus** [comment]
The popup was build outside the canvas. You could change zoom of the browser window  (Ctrl- -) and the popup appeared.
It is solved for me now.
Cheers corvus-albus
