### ISSUE TITLE
Arduino: error in refreshing the names of new sensors or other devices

### ISSUE THREAD

**Issue by mary-ho** [OpenRoberta/openroberta-lab#261]
**Describe the bug**
 - For example, if you have written a program for an LED and then insert a new LED in the robot configuration, all the names in the program are changed incorrectly.

**To Reproduce**
1. Go to ‚program‘
2. Click on 'Turn LED on ‚L‘'
3. Go to ,robot configuration’ and insert an second LED.
4. Go to ,program‘ and the name of the LED switch to the new LED, e.g. ‚L2‘.

**Expected behavior**
 - The names shouldn‘t change to the new device.

**Additional context**
 - The behavior is to be observed also with other sensors, button and so on.

**Comment by boonto** [comment]
Does not happen anymore.
