### ISSUE TITLE
The program could not be generated. Pin 43 is incorrect in block LCD

### ISSUE THREAD

**Issue by sebastiankmilo** [OpenRoberta/openroberta-lab#262]
**Describe the bug**
I can not upload my program to Arduino mega, it said that The program could not be generated. Pin 50 is incorrect in block LED, but the Arduino mega has pin 50
**To Reproduce**
1. Go to galery
2. find efi
3. click on efi
4. connect arduino mega
5. upload de program

**Expected behavior**
 - upload de program 

**Device information**
 - Type [Desktop]
 - OS: [windows 10
 - Browser chrome and Firefox

**Additional context**
 - a 2 month ago, i can upload de same program

**Comment by bjost2s** [comment]
@VinArt , could you please check if the (new) checker for the pins is working correct? The program and configuration seems to be valid!

**Comment by bjost2s** [comment]
@VinArt, there is already a hotfix branch for issue #258, please commit on this, if there is a solution.

**Comment by boonto** [comment]
I can take a look and maybe fix it.

**Comment by bjost2s** [comment]
works now
