### ISSUE TITLE
Only include used hardware in EV3 Lejos generated code

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#264]
Our EV3 Java code generator currently produces code for the configuration strictly based on the configuration. However, we can only use the actually used configuration components to save on generated code and maybe startup time.

- [x] Add checks whether component is used
- [x] Fix (a lot of) tests

**Comment by boonto** [comment]
No startup time will be saved. The used sensors are passed to the Hal, which passes them to the DeviceHandler. Here only the used sensors are initialized.

**Comment by VinArt** [comment]
sensors and actors are appended to configuration only when used now
