### ISSUE TITLE
Background upload doesn't work with Chrome, but with Firefox

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#273]
**Describe the bug**
Press the upload background image button in the simulation. The image is visible in Firefox, but not in Chrome

**Expected behavior**
 should work with ALL browsers

**Device information**
 Windows 8, Chrome Version 77.0.3865.120 (Offizieller Build) (64-Bit)

**Comment by boonto** [comment]
After uploading in Firefox the simulation is fully zoomed in and if I zoom out I get the Error `NS_ERROR_FAILURE` in the drawBackground method in scene.js line 76.

**Comment by boonto** [comment]
In Chromium on Linux the Image is uploaded, but not autoselected. I have to cycle through the images to get to the new one.

**Comment by boonto** [comment]
But only sometimes... similar in Chrome, here the image is not uploaded most of the time.
For some reason the change event is (sometimes) not triggered.

A working solution is to use a static input element in the index.html instead of dynamically creating one every time.

**Comment by VinArt** [comment]
Can upload now, although any file type.
