### ISSUE TITLE
Status text is no longer visible after a server restart

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#277]
**Describe the bug**
If you set a status text that all users can see in the startup message, it will disappear as soon as the server is restartet.

**To Reproduce**
1. Add a status text to the Open Roberta Lab and set the expiration date to some day in the distant future
2. Restart the server
4. See, that status message is not shown when you open the ORLab

**Expected behavior**
 - The status text should be shown for as long as it was defined in the expiration date, or until it gets removed manually

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/67400759-69d21100-f5ae-11e9-8317-45c0dd2dad47.png)

**Comment by bjost2s** [comment]
will be solved with #828
