### ISSUE TITLE
Can not load the NEPO4Arduino background image

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#279]
**Describe the bug**
The NEPO4Arduino background image can not be loaded.

**To Reproduce**
1. Go to the Open Roberta Lab and select Uno, Nano or Mega as robot
4. See error (White background)

**Expected behavior**
 - A transparent image of an arduino in the programming background

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/67482840-bd069b00-f664-11e9-9688-7937a2421514.png)

**Device information**
 - Laptop with Windows 10
 - FireFox 60.9 esr

**Comment by bjost2s** [comment]
This is because we have not had  this background pictures yet. They could be generated from the pictures for the startup popup, nano.png, uno.png and mego.png located here https://github.com/OpenRoberta/openroberta-lab/tree/develop/OpenRobertaServer/staticResources/css/img

**Comment by Ramanjs** [comment]
please see #374

**Comment by boonto** [comment]
The background image is currently being created.

**Comment by Ramanjs** [comment]
please see #382

**Comment by boonto** [comment]
Resolved by GCI student.
