### ISSUE TITLE
[test only] Bob3 should work with create-agent on develop branch

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#281]
There is an issue with determining whether the robot is connected with a token or auto connected for bob3, since it can be both and when the robot is connected with create agent the return key is wrong, so the FE thinks that the robot is not connected, when is should just use the returned hex to flash.

current solution just checks whether it is bob3 server side and says "ok", this should be refactored. See f895bd1f1a3cc80b643f3114c13368dd780151ab for the dirty fix

**Comment by boonto** [comment]
I tested it on Linux and Android, both worked.

**Comment by bjost2s** [comment]
Seems to work for BLE as well, tested by Nils
