### ISSUE TITLE
Support for Makeblock Me LED Matrix 8 X 16

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#282]
**Is your feature request related to a problem? Please describe.**
 - Currently it is not possible to program this LED Matrix, but a new Mbot comes with it

**Describe the solution you'd like**
 - A block, similar to the LED block for the calliope display should be integrated

**Additional context**
 - I think this is already partially integrated

**Comment by boonto** [comment]
Using "invert" with a image variable works but it doesn't work when entering a new image directly.

Another note: shifting images out of the display and back in again removes the data that was "outside" of the image:
![image](https://user-images.githubusercontent.com/7438960/72242000-91061080-35e8-11ea-8942-1c67e0b95397.png)
But that is expected unless we want to keep a copy of each image around at all times.

**Comment by boonto** [comment]
Invert works with the latest resources and the second note was not really a problem.
