### ISSUE TITLE
Make the program transfer to Edison faster

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#290]
**Is your feature request related to a problem? Please describe.**
It takes about 40 seconds to transfer a 7 block program to the Edison.

**Describe the solution you'd like**
Transfering a program to the robot should not take longer than 20 seconds

**Describe alternatives you've considered**
It takes way less time with EdBlocks, so it should be possible to fasten the transfer.

**Comment by bjost2s** [comment]
solved with #1632
