### ISSUE TITLE
You can not see the users, you have shared your program with, in the program list

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#293]
**Describe the bug**
In the "my programs" list is a column that shows the users you have shared a program with. Only the last user you have shared a program with is shown there and a dropdown icon, which indicates that you can see the rest if you click on it. 
If you click on the dropdown icon, the list pop ups, but the "my programs" view gets closed simultaneously and the program loads, as if you wold have clicked somewhere else on the list entry.

**To Reproduce**
1. Log into an account in the Open Roberta Lab, which has at least one saved program.
2. Open the "my programs" view and share your program with at least two users.
3. Go back to the "my programs" view and try to click on the  dropdown icon near the name of the last person you have shared your program with.

**Expected behavior**
The list of the users you shared your program with should expand and the program should not be loaded into your program pane.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/68486232-f7656000-0240-11ea-9db2-2221fe925b4b.png)

**Device information**
 - Desktop
 - Windows 10
 - FireFox 60.9

**Comment by boonto** [comment]
Resolved by a GCI student in 25afe178491c48ff48ca5abdbe3b900b17583e49.

**Comment by KevinL10** [comment]
The dropdown will now show the users without closing, but there is an issue if you have more than one program. If you toggle only one of the user dropdowns, all of the black "collapse triangles" will be toggled, as shown in this attachment. The main lab does not exhibit this behaviour.
![dropdownworkingv2!!](https://user-images.githubusercontent.com/58920989/72690867-2287ed80-3ad5-11ea-8033-6c2b77f30f8a.PNG)
