### ISSUE TITLE
Share view closes when adding a new user

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#294]
**Describe the bug**
When you add a new user to the list of users whom you share your program with, the share view closes automatically.

**To Reproduce**
1. Log into an account in the Open Roberta Lab, which has at least one saved program.
2. Open the "my programs" view.
3. Open the share view for a program.
4. Add a user to the share list.
5. See error

**Expected behavior**
The share view should stay opened, so that you can add more users immediately.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/68486707-f54fd100-0241-11ea-9173-560df1baf1cb.png)

**Device information**
 - Desktop
 - Windows 10
 - FireFox 60.9

**Comment by boonto** [comment]
Share view is not closed anymore.
