### ISSUE TITLE
Share view does not react at all if you add a non existing user

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#295]
**Describe the bug**
If you try to add a non exisiting user to the list of users you share your program with, the frontend will not react at all. You therefore do not know, whether or not it worked or not.

**To Reproduce**
1. Log into an account in the Open Roberta Lab, which has at least one saved program.
2. Open the "my programs" view.
3. Open the share view for a program.
4. Add a username to the share list, that does not exist.
4. See that you are not shown anything

**Expected behavior**
Any sort of indication that the frontend received my request to share with such a user, but it did not go well. For example an effect, an error message, a notification or a hover text.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/68487020-9dfe3080-0242-11ea-8718-079a0ea7d189.png)

**Device information**
 - Desktop
 - Windows 10
 - FireFox 60.9

**Comment by bjost2s** [comment]
Popup couldn't be displayed because of the error fixed with 327fe0fe973d3508e751619638e2419179ef04ad
![image](https://user-images.githubusercontent.com/1613069/68513942-a6735d00-027c-11ea-9512-f7484003b6ec.png)
