### ISSUE TITLE
Small remaining issues from refactoring

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#296]
This issue is for dc76259f4d9efd09a821647c2e9e38ba715e0eb8, to make sure it will be reviewed.
@boonto, please provide a title and some information!

**Comment by boonto** [comment]
3 things were tackled in this issue:
- fix compile program (CTRL-2)
- blockly program is now returned even if project fails / server error
- no wrong program is loaded from the GUI state on reload program
