### ISSUE TITLE
Lists comparison in simulation always returns false

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#300]
**To Reproduce**
Create a program like in the screenshot and execute it in the simulation, here Calliope

**Expected behavior**
 output true

**Screenshots**
![image](https://user-images.githubusercontent.com/1613069/68654598-8cf93c00-052e-11ea-84fb-76c22a8f0215.png)

**Comment by rbudde** [comment]
done

**Comment by boonto** [comment]
Works as expected. Another error I noticed when testing is that the simulation does not run at all if a connection list variable is declared.
