### ISSUE TITLE
Simulation: "In list ... insert at last" wrong order

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#301]
**Describe the bug**
The following programm's output is b, c, a

**To Reproduce**
Create a program like the one in the screenshot (EV3) and execute it in the simulation

**Expected behavior**
 output a, b, c

**Screenshots**
 - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1613069/68655207-e746cc80-052f-11ea-8bcd-181171d67cd9.png)

**Comment by rbudde** [comment]
done

**Comment by bjost2s** [comment]
Tested with the following user program 
![image](https://user-images.githubusercontent.com/1613069/70162901-cc92ee00-16be-11ea-89ca-7424610d672a.png)
