### ISSUE TITLE
Integrate Festo Bionics4Education

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#302]
[Bionics4Education](https://www.bionics4education.com/web/lang/en/1_education.html) by Festo is a robot set based on ESP32, the set includes parts to build 3 different models (Elephant trunk, fish and chameleon tongue). A general explanation can be found [here](https://www.festo.com/group/en/cms/13131.htm).
4 Motors can be used to actuate the flexible grippers/fins.
On the website the default firmware is available.
We want to integrate this set into the Lab, it will be in the subgroup of Arduinos.

- [x] Check capabilities
- [x] Add project
- [x] Adapt compiler workers
- [x] Add crosscompiler resources
- [x] Add code generation
- [x] Compiler
  - [x] Linux x86
  - [x] Linux ARM
  - [x] Windows -> Compiler available
  - [x] OSX -> Compiler available
- [x] Add reset worker
- [x] Add transfer/detection capabilities to [Connector](https://github.com/OpenRoberta/openroberta-connector)
  - [x] Linux x86
  - [x] Linux ARM
  - [x] Windows
  - [x] OSX
- [x] Simplify Python & `pyserial` requirements install
- [x] User feedback when Python is not found
- [x] Pack everything into zip file to reduce spread of robot resources
- [x] Find solution for 50 MB build directories -> #547!
- [x] Add tests
- [x] Add background image
- [x] Add icon
- [x] Add tutorial
- [x] Add wiki entries/help files

**Comment by boonto** [comment]
First integration is done, works on Ubuntu 18.04 with Connector on `develop` branch.
To install xtensa compiler follow [this](https://gitdemo.readthedocs.io/en/latest/linux-setup.html).
I did these steps on my machine:
```
sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial
cd ~
wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz
mkdir -p ~/esp
cd ~/esp
tar -xzf ~/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz
rm ~/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz
echo "export PATH=\$PATH:\$HOME/esp/xtensa-esp32-elf/bin" >> ~/.profile
```

**Comment by boonto** [comment]
Currently the servo block contains reference to the "SG90" servo from Arduino, this should be removed.

**Comment by boonto** [comment]
Was handled in 772c58e375e3f4a53ebb0d3cbd6a765844ce1f23.

**Comment by boonto** [comment]
To build the necessary compiler for Raspberry Pi I was able to follow the "Alternative Step 1" instructions [here](https://gitdemo.readthedocs.io/en/latest/linux-setup.html).
However, `libtool` is necessary as well which can be installed using `sudo apt-get install libtool-bin`.

Afterwards, I copied the built compiler to the home directory and added it to the path, similar to before.

**Comment by boonto** [comment]
Transfer on a Windows 10 device works as well.
Requirements are a Python installation and the `pyserial` module.
I installed it in an admin powershell using `python -m pip install pyserial`.

We will have to think of a way to simplify this for end users.

**Comment by boonto** [comment]
I improved/simplified the Python requirement and packing of esptool by automatically checking for Python install via PATH and registry (on Windows) and installing it on demand. This way less resources are spread across all projects. With the same background, everything necessary will be sent in the packed zip file, instead of adding it to the resources.

**Comment by bjost2s** [comment]
will be published soon with beta label, for remaining bugs please create a separate issue
