### ISSUE TITLE
Refactoring of the data processing in backend. Workers. Workflows. REST.

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#303]
Processing of data was largely refactored in the backend lately. It was needed for creation of validators/checkers #114 #180, source code editor #284, configuration annotation #182 and extendibility of the platform.  Here is the summary:

- A Project class was introduced. This is the central data storage for further processing. To this class we disassemble incoming requests for code generation, compilation, simulation and running on the robot. It contains program and configuration ASTs, generated source code, compiled binary, robotCommunicator for uploading the program to the robot, string builders that are injected into code generation visitors and so on. Most probably that if you are looking for something it is here.
- Workers were introduced. These are simple classes that have one method - execute(Project), they can instantiate Visitors and provide them with Bean builders, so they would fill them up and save in workerResults in project, or do the opposite and source Visitors with Beans, so they could use the results of previous Visitors. This should be further explored and extended to, probably, annotating Visitors to mark whether they consume or produce a Bean and if so, which exactly. Check de.fhg.iais.roberta.worker.* package in OpenRobertaRobot project for Abstract and common Workers.
- Beans were introduced that hold the results of the execution of the Visitors by Workers, currently there is a deficiency in UsedHardwareBean as it contains too much data, which should be shared with CodeGeneratorBean, but this is a small refactoring.
- Visitors were made as stateless as possible, and all their fields (except for those that are used only internally) were moved to Project.
- Workflows were introduced. In general a workflow is a sequence of Worker names that should be consequently executed. If a Worker fails a Workflow is interrupted. We should think of a better strategy for interrupting the Workflow to make it less disruptive.
- Introduction of Workers and Workflows had an effect, that new properties were introduced, namely robot.plugin.worker. and robot.plugin.workflow.. Workflows and Workers are automatically loaded and by using the executeWorkflow method they are run. What was not implemented - nesting of Workflows which can come in handy, since most of the workflows are extensions of the previous one with an additional Worker.
CompilerWorkflows were removed and replaced by a CompilerWorkers, that do not do any checking, configuration generation, Visitor instantiation and what not and simply compile the source from the project and deliver a binary.
- REST API was altered in a way that there is no single method that switches on the cmd from the request, instead there are different methods that execute different Workflows. The overall idea is that we get the request, take the data part from it, disassemble it into the Project, pass it to the executeWorkflow method from ProjectService and then assemble the response back from the project. New methods can be found in ProjectWorkflowRestController. Those methods that were simply using Processors to manipulate DB entries reside now in ClientProgramController class from which implementation should still be factored out to ClientProgramService.
- New robot plugins will most probably have at least showsource, compile and run workflows and collect, generate, setup, compile and transfer Workers. More workers may be needed for different kinds of validation, collection or in case of simulation - simulation specific code generation.

Based on this further functionality can be developed, e.g. configuration-program correspondence validators.

**Comment by rbudde** [comment]
was tested. Remaining work put into new issue #306
