### ISSUE TITLE
Simulation: arrays as function parameters cause "server error"

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#305]
**To Reproduce**
Create a program like in the screenshot and execute it in the simulation, here Calliope

**Expected behavior**
 - no server error

**Screenshots**
 - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1613069/68665438-53323080-0542-11ea-8a41-2b1702468ea6.png)

**Comment by rbudde** [comment]
empty expr problem: parameter are kept without inits, i.e. they are empty and need a case label in code generation.

Will popup again, if empty check worker will be implemented.

Done

**Comment by boonto** [comment]
Does not cause a server error anymore.
