### ISSUE TITLE
Quality Assurance For Empty + Consistency Workers/Visitors For All Robots

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#306]
- find a proper way to send beans to and accept beans from workers. Probably using @nnotations on setter/getter in the workers is the best way. Should beans stored in the project using the full class name as key?
- check whether package names are graspable.
- design (prototype!) an empty block checker. Starting with an abstract class for the common parts and extend in the robot projects by robot specific additions. Make sure, that the visitors visit the whole tree, that error messages are sensible, that common parts are made final to avoid erreneous overwrites.
- empty block checker implemented for:
- [ ] abstract checker implemented in the robot project
- [ ] sim
- [ ] wedo
- [ ] ev3lejosv1
- [ ] ev3lejosv0
- [ ] ev3dev
- [ ] nxt
- [ ] vorwerk
- [ ] microbit
- [ ] botnroll
- [ ] nao
- [ ] bob3
- [ ] uno
- [ ] nano
- [ ] mega
- [ ] sensebox
- [ ] mbot
- [ ] calliope2017
- [ ] calliope2016
- [ ] calliopeSim
- do the same for a checker, that guarantees, that program and configuration match. All robots need a configuration before this part can be started. We should prototype this for one robot and then evaluate the design and then implement this for other robots.
- consistency checker implemented for:
- [ ] abstract checker implemented in the robot project- [ ] abstract checker implemented in the robot project
- [ ] sim
- [ ] wedo
- [ ] ev3lejosv1
- [ ] ev3lejosv0
- [ ] ev3dev
- [ ] nxt
- [ ] vorwerk
- [ ] microbit
- [ ] botnroll
- [ ] nao
- [ ] bob3
- [ ] uno
- [ ] nano
- [ ] mega
- [ ] sensebox
- [ ] mbot
- [ ] calliope2017
- [ ] calliope2016
- [ ] calliopeSim

**Comment by bjost2s** [comment]
relevant part is done in #1256
