### ISSUE TITLE
Wait until block does not work for sensebox

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#308]
**Describe the bug**
 - wait until block does not recognise the port to which a sensor is connected, so no code generation is possibel

**To Reproduce**
1. Use wait until block with sensebox
2. get server error

**Expected behavior**
 - block could be used

**Comment by VinArt** [comment]
Only for certain sensors though

**Comment by boonto** [comment]
Cannot test as a server error is produced by I guess the configuration: [waitUntil.zip](https://github.com/OpenRoberta/openroberta-lab/files/3982680/waitUntil.zip).

**Comment by boonto** [comment]
Program with all wait untils does not produce a server error and compiles.
