### ISSUE TITLE
Visible/UV light sensor returns values not in percent in sensebox

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#310]
**Describe the bug**
 - Said sensor returns values in a different unit

**To Reproduce**
1. use light/uv light sensor with sensebox
2. observe values e.g. on screen

**Expected behavior**
 - values should be in percent

**Comment by bjost2s** [comment]
The values shouldn't  be in percent, but the sensor should be labeled with the correct units, see
![image](https://user-images.githubusercontent.com/1613069/68796887-ddb68500-0653-11ea-8fbe-5d538176b2bb.png)

**Comment by boonto** [comment]
Blocks and tooltips show the unit of measurement. As far as I can tell return values seem to be correct as well.
