### ISSUE TITLE
Code for opensense map should be generated only when send block is used

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#311]
**Describe the bug**
 - code for connecting to wifi is generated when wifi configuration block is used

**To Reproduce**
1. sensebox configuration and use wifi block
2. do not use send block in program
3. generate code and see empty wifi credentials and init of wifi
4. program stalls at connecting

**Expected behavior**
 - wifi code would not be generated when send block not used

**Comment by boonto** [comment]
Code is only generated when the block is used with openSenseMap mode.
