### ISSUE TITLE
Tooltips for sensors and actors should be revised for sensebox

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#312]
tooltips need to contain information on return value and units for sensors and a description of the action for actors

**Comment by bjost2s** [comment]
There are a couple of  issues with the tooltips:
1. we write tooltips in sentences
2. a tooltip should contain the name of the sensor, the mode with the unit and the range of the possible values
3. for each mode we have to provide a dedicated tooltip
This can be done easily for sensors: only the correct tooltip key has to be available. For actuators one has to implement a tooltip function.

A good example is the infrared sensor from Lego EV3
