### ISSUE TITLE
No null check present for SD card configuration component in visitDataSendAction for sensebox

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#316]
**Describe the bug**
 - if send data to SD card is used without a corresponding configuration block an exception is thrown

**To Reproduce**
1. use send data to SD card block with no configuration block and see server error message

**Expected behavior**
 - an error popup message should be put on the block as for openSenseMap

**Comment by boonto** [comment]
User gets a suitable error message when used without configuration block.
