### ISSUE TITLE
Uploading background images with large width produces visual artifacts

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#319]
**Describe the bug**
Uploaded background images with width > 2000 produce visual artifacts.

**To Reproduce**
1. Open Simulation
2. Upload > 2000 width image
4. Observe visual artifacts on the right hand side of the simulation

**Expected behavior**
 - No visual artifacts.

**Screenshots**
![image](https://user-images.githubusercontent.com/7438960/68943383-5aa84280-07ab-11ea-8460-16b5c08b6102.png)

**Device information**
 - Type: Desktop
 - Browser: Chrome/Firefox

**Comment by VinArt** [comment]
Works, but chrome allows the upload of any file type, probably this should be described in a different issue.
