### ISSUE TITLE
Changing background 4 times freezes simulation on IOS

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#320]
**Describe the bug**
 - Simulation freezes when changing the background 4 times independent of the browser.

**To Reproduce**
1. Open Simulation
2. Cycle Background 4 times
3. Observe frozen simulation

**Expected behavior**
 - Simulation does not freeze.

**Device information**
 - Type: iPad Pro (9.7 inch)
 - OS: IOS 13.1.3
 - Browser: Safari/Chrome/Firefox

**Comment by bjost2s** [comment]
output "TypeError: null is not an object (evaluating 'context.createOscillator')" 
IOS only allows 1 or 2 instances of AudioContext objects

**Comment by boonto** [comment]
Even after many background changes the simulation does not freeze.
