### ISSUE TITLE
Unable to read No matching record found

### ISSUE THREAD

**Issue by rishabhdeepsingh** [OpenRoberta/openroberta-lab#321]
**Describe the bug**
 - In the tutorials page, the text is the same colour as the background which should be black in colour.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the [lab](https://lab.open-roberta.org/#)
2. Click on 'tutorials'
3. No matching records found the text is not visible at all.

**Expected behaviour**
 - The colour should be black.

**Screenshots**
 
<img width="1676" alt="Screenshot 2019-11-18 at 9 07 46 PM" src="https://user-images.githubusercontent.com/28526643/69066954-446ae280-0a48-11ea-8d7e-bc190fdcd2cd.png">

**Device information**
 - Type Desktop
 - OS: MacOs Catalina Version 10.15.1
 - Browser chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by ArcSlayer121** [comment]
So I have found a way to solve this issue. We can change the background color of the table data by adding a style attribute in the class "no -records- found" and change the background color of the data.Kindly find the attatched screenshot of the same.We can do this by tr.no-records-found{ background-color : Black;
![task1](https://user-images.githubusercontent.com/57980712/70196158-d7d13280-172d-11ea-893d-f721686fd4d0.JPG)

**Comment by rishabhdeepsingh** [comment]
@ArcSlayer121  Would you like to work on this one?
You can submit a PR for the same.

**Comment by nishanth1232** [comment]
Found a simple fix.
We can change the element concerned with the title to:
`<td colspan="9" style="color:black;">No matching records found</td>`
It should look like this:
<img width="950" alt="BugFix" src="https://user-images.githubusercontent.com/44456350/70298263-08d96200-1817-11ea-9173-eb5c9366cd13.png">

**Comment by nishanth1232** [comment]
@rishabhdeepsingh 
I claimed a task based on this issue in Google Code-In and opened a pull request for a fix.
Link - "https://github.com/OpenRoberta/openroberta-lab/pull/345/files"

**Comment by boonto** [comment]
Resolved by a GCI student.

**Comment by rishabhdeepsingh** [comment]
@nishanth1232  Really great. Hope to get more issues resolved soon.

**Comment by boonto** [comment]
The text is readable now.
