### ISSUE TITLE
Wait bluetooth connection block causes "server error" in simulation

### ISSUE THREAD

**Issue by simonedegiacomi** [OpenRoberta/openroberta-lab#323]
**Describe the bug**
It's not possible to open the simulator if a program contains the "wait connection" block. The error that appears says that there is a server error.

**To Reproduce**
1. Create a new program
2. Create a Connection variable
3. Assign to the Connection variable the result of the wait connection block
4. Open the simulator

**Expected behavior**
If the simulator can simulate a bluetooth connection, then the simulator should open. Otherwise the error should provide more details to the users (ex: remove the bluetooth related blocks from the program).

Related to #224 

**Screenshots**
![image](https://user-images.githubusercontent.com/15476739/69157077-babd2280-0ae4-11ea-91db-4061427da60d.png)

**Device information**
 - Type: Desktop
 - OS: Ubuntu 19.10
 - Browser: Firefox 70.0.1

**Comment by boonto** [comment]
Currently in progress by a GCI student.

**Comment by boonto** [comment]
Resolved by a GCI student.
