### ISSUE TITLE
Analyse and correct problem with robot protocol

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#324]
**Describe the bug**
The Rest-Call `https://lab.open-roberta.org/rest/data/robot/summary` shows, for instance:
```
number of robots connected: 308
max time a robot is waiting: 435913586
state distribution:
ROBOT_IS_BUSY                            : 39
GARBAGE                                  : 36
ROBOT_WAITING_FOR_PUSH_FROM_SERVER       : 5
WAIT_FOR_TOKENAPPROVAL_FROM_USER         : 0
WAIT_FOR_PUSH_CMD_FROM_ROBOT             : 228
```
Especially the max time show, that there could be a bug in the protocol. The problem should be analysed and solved.

See also the issues #165 and #248 which are related to the protocol.

**Comment by bjost2s** [comment]
no real problem
