### ISSUE TITLE
Add romanian translation

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#325]
**Describe the feature you'd like**
Add the romanian translations from the Open Roberta Translation Sheet to the Open Roberta Lab.

**Additional context**
Link to the translation sheet (read only), over which the .json file can be generated.
https://docs.google.com/spreadsheets/d/18lcfyYL2UsNJEWJYEcxSujWGMCSKYDomif2Xmvz-RFM/edit?usp=sharing

**Comment by boonto** [comment]
Romanian translation is available to be selected and changes accordingly.
