### ISSUE TITLE
The lab does not switch to lejos when starting the tour

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#331]
**Describe the bug**
If you select a robot first and press the "start the tour" button afterwards, the tour will start with the previously selected robot, instead of the EV3 robot. If the selected robot has no simulation, the tour will not be solvable as soon as the simulation shall be opened. 

**To Reproduce**
1. Select a robot in the Open Roberta Lab, that is not an EV3 (and optionally does not have a simulation)
2. Click on the NEPO logo to open the start hint
3. Press the "start the tour" icon
4. See, that all texts, highlights and buttons are made for EV3
5. If the selected robot does not have a simulation, you will not be able to finish the tour, because the button is missing.

**Expected behavior**
 - The lab should switch to EV3 and start the tour then

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/69545550-5b528d00-0f92-11ea-862b-cbb418af6342.png)

![grafik](https://user-images.githubusercontent.com/10925094/69545540-555cac00-0f92-11ea-952e-3c5175bd2b0c.png)

**Device information**
 - Desktop
 - WIndows 10
 - FireFox 60.9 ESR

**Additional context**
 - This also happens, if you preselect a robot via a cookie and call https://lab.open-roberta.org#overview

**Comment by boonto** [comment]
Resolved by a GCI student.
