### ISSUE TITLE
Integrate Arduino Uno Wifi Rev2

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#332]
As the Wifi Rev2 edition of Arduino seems not to work with our current Uno plugin we have to adapt a specific one for the Wifi Rev2 edition.

- [x] Add as Arduino group plugin
- [x] Adapt CompilerSetupWorker
- [x] Add resources
- [x] Compiler
  - [x] Linux tested
  - [x] Linux ARM tested
  - [x] Windows tested
  - [x] OSX available
- [x] Add to Connector
  - [x] Linux
  - [x] Linux ARM
  - [x] Windows
  - [x] OSX
- [x] Add to robot specific integration tests
- [ ] <strike>Add additional blocks for Wifi functionality</strike>
- [x] Add blocks for IMU
  - [x] Accelerometer
  - [x] Gyroscope
  - [ ] <strike>Temperature</strike>
- [x] Test for IMU sensors
- [x] Update base image of containers
- [x] Update README / install instructions with new compiler
- [x] Add image for robot selection popup

**Comment by boonto** [comment]
Similar to the festobionic implementation a different compiler is needed.
As the atmega4809 specs and libs are not part of the default `avr-gcc` implementation of Ubuntu, we need the modified one from Arduino. A link to the compiler can be found [here](https://github.com/arduino/Arduino/blob/master/hardware/package_index_bundled.json#L116) in the ArduinoIDE packages.
With these commands I added it to my path:
```
cd ~
wget http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-pc-linux-gnu.tar.bz2
mkdir -p ~/avr-gcc
cd ~/avr-gcc
tar -xf ~/avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-pc-linux-gnu.tar.bz2
rm ~/avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-pc-linux-gnu.tar.bz2
echo "export PATH=\$PATH:\$HOME/avr-gcc/avr/bin" >> ~/.profile
```
Next, I uninstalled our recommended `avr-gcc` to use the custom one instead.

I also added functionality to the `robot.plugin.compiler.linux.dir` property which can be used to have both compilers running at the same time.
However, all of our integration tests run with the newer compiler version as well so we could replace it altogether (after more testing of course).

As the Arduino Uno Wifi Rev2 inbuilt LED is not on pin 13 but on 25 and 25 is not available on the board, I also added a new entry to the LED dropdown `BUILTIN_LED`, similar to the Arduino constant used in e.g. the Blink example.

**Comment by boonto** [comment]
The avrdudes working with the Wifi Rev2 are also linked in the package index:
- [Linux ARM 32](http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-armhf-pc-linux-gnu.tar.bz2)
- [OSX](http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-x86_64-apple-darwin12.tar.bz2)
- [Linux 64](http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-x86_64-pc-linux-gnu.tar.bz2)
- [Linux 32](http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-i686-pc-linux-gnu.tar.bz2)
- [Windows](http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-i686-w64-mingw32.zip)

**Comment by boonto** [comment]
Compilers for [OSX](http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-apple-darwin14.tar.bz2), [Windows](http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-w64-mingw32.zip) and [Linux ARM 32](http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-arm-linux-gnueabihf.tar.bz2) can also be found there.

**Comment by boonto** [comment]
I tested the compiler and avrdude on Windows, both worked with standard Uno and Uno Wifi Rev 2. Additional compiler resources are not needed.

**Comment by boonto** [comment]
Linux ARM compiler also seems to work, tested on a Raspberry Pi 4 and compiled for all avr-gcc robots.

**Comment by boonto** [comment]
Connecting via Raspberry also works.

For the [IMU](https://www.arduino.cc/en/Guide/ArduinoUnoWiFiRev2#toc13) the additional library [Ardunio_LSM6DS3](https://www.arduino.cc/en/Reference/Arduino_LSM6DS3) is necessary.

**Comment by boonto** [comment]
The previously mentioned library does not include the inbuilt temperature sensor, because of that the [library by SparkFun](https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library) will be used instead.

**Comment by boonto** [comment]
The gyro and accelerometer blocks can be added to the program with CTRL-6. This will create the two program and config blocks.

**Comment by bjost2s** [comment]
works fine with latest openroberta-connector
