### ISSUE TITLE
Calliope: wrong error handling for some sensors in simulation

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#333]
When you try to execute a program with the ultrasonic sensor in the simulation you get the following:
![image](https://user-images.githubusercontent.com/1613069/69666316-583bc780-108c-11ea-9139-504ea2ad6182.png)
expected behaviour
![image](https://user-images.githubusercontent.com/1613069/69665859-8240ba00-108b-11ea-9005-709e94c508f5.png)

As the configuration is still hidden (not present) it is not clear why we have a checker for this (at the wrong place)

**Comment by bjost2s** [comment]
Please check **all** sensors for calliope!

**Comment by boonto** [comment]
Currently in progress by a GCI student.

**Comment by boonto** [comment]
Has been resolved by a GCI student.
