### ISSUE TITLE
SenseBox: LCD Display 1602 is not available ... 

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#335]
**Describe the bug**
 LCD Display 1602 is not available and should be renamed to OLED-Display

**Screenshots**
LCD Display 1602 is not available
![image](https://user-images.githubusercontent.com/1613069/69811079-94d30480-11ed-11ea-9674-89e0a5eb5eef.png)

**Additional context**
 Connection to related Configuration Block seems to work.

**Comment by boonto** [comment]
Clear display now contains the correct name.
