### ISSUE TITLE
Check BMX055 output values for sensebox for all blocks

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#337]
- methods from the sensebox library for bmx055 sensor may return unexpected values
 - values in general need to be scaled and converted to correct units

**Comment by VinArt** [comment]
- accelerometer gives back values from -1 to 1 on each axis, the unit is g.
- gyro gives back the rate from -32767 to 32767 on each axis, the unit is deg/s
- compass gives back values from -4096 to 4095 on each axis, the unit is uT

- gyro and compass do not work unless accelerometer is used, because Wire1.begin() is not called.

**Comment by VinArt** [comment]
- gyro and compass will be currently dropped.

**Comment by boonto** [comment]
Seems to work fine.
