### ISSUE TITLE
Pre-compilation of Arduino libraries

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#34]
Since version 1.8.6 of Arduino IDE and 1.4.0 of arduino builder the library spec file allows setting the pre-compiled flag and linker flags:

 - precompiled - (available from Arduino IDE 1.8.6/arduino-builder 1.4.0) (optional) set to true to allow the use of .a (archive) and .so (shared object) files. The .a/.so file must be located at src/{build.mcu} where {build.mcu} is the architecture name of the target the file was compiled for. Ex: cortex-m3 for the Arduino DUE. The static library should be linked as an ldflag.
 - ldflags - (available from Arduino IDE 1.8.6/arduino-builder 1.4.0) (optional) the linker flags to be added. Ex: ldflags=-lm

So in order so speed-up the compilation process and do not waste time to compile the same library for different users individually, we can supply pre-built libraries when possible.

[docs](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format)

**Comment by rbudde** [comment]
This issue is about precompilation. The commit replaces the arduino-builder.
