### ISSUE TITLE
SenseBox: Nova SDS011 Feinstaub-Modul support

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#343]
more information here: https://shop.watterott.com/Nova-SDS011-Feinstaub-Sensor-Modul

**Comment by VinArt** [comment]
- create a configuration block where the port is selectable: Serial1 or Serial2
- create a sensor block where the mode is selectable: PM2.5 or PM10
- provide code generation for configuration and for the sensor block

**Comment by bjost2s** [comment]
ACCELEROMETER_TOOLTIP is declared twice in de.json and leads to an error

**Comment by VinArt** [comment]
duplication removed in 879163d54fb1b58304975cd1543279135a1dc745

**Comment by boonto** [comment]
Cannot test together with display as a line break is missing: [missingLineBreak.zip](https://github.com/OpenRoberta/openroberta-lab/files/3982778/missingLineBreak.zip)

**Comment by boonto** [comment]
Seems to work, higher values are produced when dust is stirred up by beating a office chair.
