### ISSUE TITLE
Gallery Loading 

### ISSUE THREAD

**Issue by rishabhdeepsingh** [OpenRoberta/openroberta-lab#349]
**Is your feature request related to a problem? Please describe.**
 - Whenever we open the gallery it takes some time to show up the results. While in the background it fetches for the files. But the user doesn't actually know that it is even loading.

**Describe the solution you'd like**
 - It will be great if we can implement some loading logo/ dialog box.

**Describe alternatives you've considered**
-  We can also reduce the requests to up to a single page only showing only around 50 results.

**Additional context**
 - Here is the result whenever we open up the gallery it takes around 11 seconds.
<img width="1680" alt="Screenshot 2019-12-09 at 7 38 13 PM" src="https://user-images.githubusercontent.com/28526643/70442461-68a46700-1abc-11ea-9396-dd390232e9e4.png">

**Comment by boonto** [comment]
rbudde improved the database calls, which should speed things up.
Additionally, the spinning logo was added with e1871d914c82d979bcd49b8379d8dde866dfe9cd.

**Comment by rbudde** [comment]
works. The bottom text of the table, e.g. "Showing 1 to 11 of 11 rows" is bad. Instead of "rows" the text should use "items". Rows is ok in a traditional row format only.

**Comment by bjost2s** [comment]
Not solved, spinning logo is still visible when gallery already is loaded.

**Comment by boonto** [comment]
Spinning logo does not show up after the gallery is already loaded.
