### ISSUE TITLE
EV3 and NXT simulation do not do the "motor on speed [number]% [rotation|degree]" block

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#351]
**Describe the bug**
If you use the "motor on speed [number]% [rotation|degree]" block in the EV3 or NXT simulation, the wheel will only drive for a super short distance, no matter what degrees / rotations you enter.
In addition to that, the block ignores the robot configuration and assumes that the motor at port B is always the right motor and that the motor at port C is always the left motor.

**To Reproduce**
1. Create a program that uses the "motor on speed [number]% [rotation|degree]" block for NXT or EV3
2. Open the simulation and run your program

**Screenshot**
![grafik](https://user-images.githubusercontent.com/10925094/70517115-5ec04980-1b38-11ea-95b2-786aec9a1e5f.png)

**Expected behavior**
The robot should do what is says in the block and respect the robot configuration.

**Comment by corvus-albus** [comment]
Hi,
I'm not an developer but had a similar issue: https://github.com/OpenRoberta/openroberta-lab/issues/155 

To cite bjost2s:
> The simulation always uses the standard configuration (or less) of a robot system. You can not configure anything.
Once we decide (or someone provides) a full customizable simulation this will definitely a feature of this.
For now we offer the simulation only as a first step to try the lap. Once you really want to go deeper into programming you should use the real robot.

I think you have to deal with it. In fact I'm so happy to have a simulation for teaching that it is easy for me to accept it.
Cheers corvus-albus

**Comment by boonto** [comment]
Yes the B <-> C thing with the motors is intended behavior for now.

The degree thing seems to be a bug though.
