### ISSUE TITLE
admin.sh tells you to use -rdbg but searchs for -rdg

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/openroberta-lab#353]
If you start admin.sh you get echoed to console (line 46):
  echo '-rdbg               enable remote debug using port 8000; default: no remote debug'
but the corresponding while-loop fetching the options searches for -rdg (line 29):
    -rdg)          RDBG='-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y'
                   shift ;;
Probably just a typo.

Cheers 
corvus-albus

**Comment by boonto** [comment]
Fixed in bf83ef56c25272f8f0ed3f3d78dbf8ebc3c968e2.
