### ISSUE TITLE
OpenRoberta Connector: wrong install script name

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#356]
**Describe the bug**
 In v1.1.0 the install.sh script has been renamed to install-connector. Now people follow the wiki and try to execute "sudo install.sh" but it is not working anymore.

**Comment by bjost2s** [comment]
Please comment your solutlion

**Comment by boonto** [comment]
Install script calling in German and English versions updated to
```
./install-connector
```
with an additional hint that the script will ask for admin rights if necessary.
