### ISSUE TITLE
Break out of loop block outside of loop produces server error

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#359]
**Describe the bug**
- Using the "break out of loop" block outside of a loop produces a server error.
- A warning is shown on the block but it does not prevent the server error

**To Reproduce**
1. Use break out of loop block outside of a loop
2. Open simulation, source code view or similar actions

**Expected behavior**
Either
- You get notified there are errors in your program with a popup, or
- a warning is shown on the block and and it is ignored in further processing

**Screenshots**
![image](https://user-images.githubusercontent.com/7438960/70708420-bdbdc400-1cda-11ea-8c8d-2f93e9e2e4f3.png)

**Comment by boonto** [comment]
In default blockly it is disabled if it is outside of a loop, for our blockly this does not seem to be the case. If it is disabled it will be ignored by the code generation and no error will be generated.

I think it was disabled in our blockly as well at some point and this probably changed.

**Comment by boonto** [comment]
I tested the check similar to [original blockly]. It works, but there are still some visual errors with the block being active but not shown as active.

**Comment by boonto** [comment]
Works with the following changes in loops.js:
```
...
     } while (block);
     if (legal) {
       this.setWarningText(null);
+      this.setDisabled(false);
     } else {
       this.setWarningText(Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING);
+      if (!this.isInFlyout && !this.getInheritedDisabled()) {
+        this.setDisable(true);
+      }
     }
...
```
@bjost2s what do you think? Is there any reason not to do this?

**Comment by VinArt** [comment]
Block becomes inactive outside the loop and active back when put into loop.
