### ISSUE TITLE
Some Calliope blocks produce server errors in simulation

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#360]
**Describe the bug**
- The blocks "set LED Bar", "clear 4 Digit Display" and "set 4 Digit Display" (maybe more, will test) produce a server error when opening the simulation. 

**To Reproduce**
1. Add one of the mentioned blocks
2. Open simulation

**Expected behavior**
 - No errors, a warning on the block that it cannot be used in simulation.

**Additional context**
 - Should be covered by workflows integration tests.

**Comment by boonto** [comment]
In this context I will create Calliope integration tests with all action and sensor blocks.

**Comment by boonto** [comment]
There already are fractured integration tests for the blocks, but the robot specific ones do not have the workflow tests. I'll add the workflow tests to the robot specific tests and combine the fractured tests into one with all blocks.

**Comment by boonto** [comment]
Workflow and simulation tests will be tracked in #364.

**Comment by VinArt** [comment]
Now warning signs are shown, but no server error.
