### ISSUE TITLE
Prevent illegal list operations for C robots

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#363]
Currently we allow some list operations that don't make much sense and would need temporary variables to function properly for the C robots.

![image](https://user-images.githubusercontent.com/7438960/70809913-136d9b80-1dc3-11ea-85ef-84232f3cb0fa.png)

As this would not work we have some "defaults" across the project which append "null" (which does not exist in C) in these cases. These programs will not compile.

To prevent this we should move these checks in the code generators which append the "null" into the appropriate checkers to show an error message.

**Comment by rbudde** [comment]
seems ok.
