### ISSUE TITLE
Calliope: wrong simulation warning for "switch LED matrix"

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#366]
![image](https://user-images.githubusercontent.com/1613069/70854726-fe2a6700-1ebf-11ea-9d6d-fa123de84436.png)

**To Reproduce**
1. Create a program with the "switch LED matrix ..." block
2. Click on "run on Calliope Mini"
3. See error

**Expected behavior**
 - No warning

**Comment by boonto** [comment]
Resolved by a GCI student.
