### ISSUE TITLE
WeDo Iphone App returns always false for the gyro sensor exept for "any"

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#37]
**To Reproduce**
1. Go to WeDo
2. Create any program which is waiting for e.g. gyro "up" state
3. Run the program on WeDo
4. Move the connected gyro in different orientations

**Expected behavior**
 - Program should recognize the state "up" and terminate

**Device information**
 - Type iPhone XR
 - OS: IOS 12.1.4
 - Open Roberta Mobile

**Comment by rbudde** [comment]
needs to be tested with the IOS + Android app. Changes were in the wedo.model.js, which applies to both apps.
