### ISSUE TITLE
C4EV3: Compiler error due to order of function definitions

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#377]
Attention, this error only appears for C4EV3, EV3Dev and Lejos works fine!
this works:
![image](https://user-images.githubusercontent.com/1613069/70984238-66449d00-20ba-11ea-996a-6f6934e9b08e.png)
this doesn't
![image](https://user-images.githubusercontent.com/1613069/70984304-82e0d500-20ba-11ea-82cd-d1aa7adbb1f6.png)

**Expected behavior**
 Compilation succeeds.

Function declaration may help here.

**Comment by RohanCheri** [comment]
Oh I used the wrong Issue number my bad

**Comment by RohanCheri** [comment]
I meant to put Issue #390

**Comment by Blippy2019** [comment]
Hi, I was looking at this issue and tested it on the lab, test server and my local one but the issue didn't come up. I used the exact same code and tried it both chrome and firefox with the C4EV3. Wondering if this issues is already fixed?
![image](https://user-images.githubusercontent.com/58810680/71656295-eb080a00-2d8e-11ea-8407-848b2c27f68d.png)

**Comment by boonto** [comment]
It cannot be compiled if you try to compile the program for the real robot. As can be seen in the source code view "macheEtwas2" is used inside "macheEtwas" before it is declared.

**Comment by boonto** [comment]
Resolved by GCI student.
