### ISSUE TITLE
Arduino: List create block creates "null" which leads to compiler error!

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#388]
**Describe the bug**
see screenshot
![image](https://user-images.githubusercontent.com/1613069/71172907-c0339700-2261-11ea-87d6-94a5929867b3.png)

**Expected behavior**
correct implementation of list create block in all places 
or
concrete error message for the user (from validator)
or/and
blockly rejects this connection!

**Comment by boonto** [comment]
Should be duplicate of #363.
