### ISSUE TITLE
Remove Arduino RobertaFunctions

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#389]
There still is RobertaFunctions.h and .cpp in the resources. However, it was already mostly replaced by NEPODefs.h, the only remaining method used by Arduinos is `clamp`.

- [x] Change to inline function with std::min/max (we support STL either with ArduinoSTL or inbuilt by the system)
- [x] Remove include & definition from code generation
- [x] Change tests
- [x] Test robots
  - [x] Arduino
  - [x] mBot
  - [x] senseBox

**Comment by bjost2s** [comment]
Yeah!
