### ISSUE TITLE
Certain Arrangements of the 'play note' block in Calliope Mini do not work as intended

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#395]
**Describe the bug**
 When multiple 'play note' blocks are used, the pauses between notes are inconsistent. Additionally sometimes the last note of the arrangement is not played. 

**To Reproduce**
1. Create a new program in Calliope Mini
2. Click on the sound category
3. Use multiple 'play note' blocks
4. Run the simulation

**Expected behavior**
 - All the notes should play one after the other with regular pauses between the notes.

**Example program**
<img width="611" alt="Screen Shot 2019-12-21 at 8 14 17 PM" src="https://user-images.githubusercontent.com/9400738/71309516-94b1d780-242e-11ea-82da-3be17f4d190e.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Comment by boonto** [comment]
Works as expected now, all sounds are played with equal pauses.
