### ISSUE TITLE
The HT infrared sensor in EV3 robots produces server error

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#396]
**Describe the bug**
 - When the HT infrared sensor block is used in the program and simulation is opened, the user receives a server error.

**To Reproduce**
1. Create a program in one of the EV3 robots.
2. Click on the Sensors category
3. Use the HT infrared sensor block.
4. Open the simulation

**Expected behavior**
 - When the HT infrared sensor is used and the simulation is opened, a warning that states "Unfortunately you cannot use this block in the simulation" must be displayed instead of the server error.

**Screenshots**
 - 
<img width="1280" alt="Screen Shot 2019-12-21 at 8 41 25 PM" src="https://user-images.githubusercontent.com/9400738/71309797-4acaf080-2432-11ea-96e9-d6b27f2d7497.png">

**Device information**
 - Type : Desktop
 - OS : MacOS
 - Browser: Chrome

**Comment by boonto** [comment]
Resolved by a GCI student.
