### ISSUE TITLE
The blocks in the 'Messages' category in the NXT robot produce server errors

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#397]
**Describe the bug**
 - The blocks belonging to the category 'Messages' produce server errors when they are used in the program and the simulation is opened.

**To Reproduce**
1. Create a new program in the NXT robot.
2. Click on the category 'Messages'.
3. Use any of the blocks in the  'Messages'  category.
4. Open the simulation.

**Expected behavior**
 - When blocks in the 'Messages' category are used and the simulation is opened, a warning that states "Unfortunately you cannot use this block in the simulation" must be displayed instead of the server error.

**Screenshots**
 -
<img width="935" alt="Screen Shot 2019-12-21 at 8 53 52 PM" src="https://user-images.githubusercontent.com/9400738/71309986-6b944580-2434-11ea-99af-abf2b0f25795.png">

**Device information**
 - Type : Desktop
 - OS : MacOS
 - Browser: Chrome

**Comment by boonto** [comment]
Resolved by GCI student.
