### ISSUE TITLE
Timer blocks in EV3 produce server error

### ISSUE THREAD

**Issue by KevinLiu1010** [OpenRoberta/openroberta-lab#398]
**Describe the bug**
 - When the reset timer block or the get value timer block is used and the source code is opened, a server error is produced.

**To Reproduce**
1. Create an EV3 Program.
2. Add the reset timer block to the start of the program (found in sensors).
3. Open the source code.

**Expected behavior**
 - Shows the generated source code

**Screenshots**
 
![ResetTimerError](https://user-images.githubusercontent.com/45927124/71318375-e9604d00-2444-11ea-9a91-bdc235506285.PNG)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Additional Information**
 - The program will run normally in the simulation view.

**Comment by boonto** [comment]
Fixed by a GCI student in 08727afe28c5e4a17a151600f9e7513223240c0d.
