### ISSUE TITLE
StringOutOfBoundsException in EV3JavaVisitor

### ISSUE THREAD

**Issue by KevinLiu1010** [OpenRoberta/openroberta-lab#399]
**Describe the bug**
 - When creating tests with no sensors involved, the JUnit test will return a StringOutOfBoundsException. 

**To Reproduce**
1. Go to AstToLejosJavaVisitorTest.java
2. Add a test that involves no sensors
3. Run the program

**Expected behavior**
 - There should not be an StringIndexOutOfBoundsException, but rather a failure due to the incorrect test or no failures.

**Screenshots**.
![Screenshot (25)](https://user-images.githubusercontent.com/45927124/71324990-ff006180-249a-11ea-9784-798416813e50.png)

**Device information**
 - Type Desktop
 - OS: Windows 10
- IDE: Eclipse 2019-12

**Comment by boonto** [comment]
Resolved by GCI student.
