### ISSUE TITLE
Debug and Assert Block

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#4]
**Is your feature request related to a problem? Please describe.**
For all common blocks we would like to generate integration test programs more or less automatically. For this it would make things much easier, if we would have a common debug block and a common assert block, so that we do not have to distinguish between the different plugins/systems.

**Describe the solution you'd like**
 The common debug block should generate some output, depending on the system. E.g. for Calliope it could be easily mapped to the "write serial", for EV3 there is afaik no similar block availabe, so a new implementation like "System.out.print(...)" could be necessary.
The common block "assert" should take two arguments very similar to 
the "logic_compare" block, but as a statement with the result going automatically into the new debug block!

**Comment by rbudde** [comment]
available as CTRL-4 and CTRL-5 to be used in the test automation
