### ISSUE TITLE
Add "create text with" block for NXT

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#43]
**Describe the solution you'd like**
Some robots, like the EV3, Calliope and NAO, have the "create text with" block. Eventhough the "Append text to" block exists for the NXT, the "create text with" block does not.
![Screenshot-2019-5-22 Open Roberta Lab(1)](https://user-images.githubusercontent.com/10925094/58461146-42763580-812f-11e9-8f26-5a42a36a18d7.png)

**Describe alternatives you've considered**
Using the "append text to" block equivalently in combination with a string variable works the same way, but creates more code overhead.
![Screenshot-2019-5-22 Open Roberta Lab(2)](https://user-images.githubusercontent.com/10925094/58461158-473ae980-812f-11e9-974b-f8a2e2f55f8a.png)

**Comment by bjost2s** [comment]
Unfortunately c for NXT (NXC) does not support the same features like cpp, java or python. There are a couple of blocks not supported by NXT e.g. this one, but also certain list blocks ...
