### ISSUE TITLE
NXT: After uploading background, robotic view becomes that of EV3's

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#438]
**Describe the bug**
 - After uploading a custom background or switching backgrounds, when clicking robotic's view, an EV3 brick is shown instead of the NXT. Sometimes there is only one EV3 brick, sometimes there are multiple EV3 views

**To Reproduce**
1. Go to simulator
2. Upload a background or switch backgrounds
2. Click on robot's view

**Expected behavior**
 - A single NXT brick

**Screenshots**
 - Gif is shown below with multiple EV3 bricks
![First](https://user-images.githubusercontent.com/58810680/71552282-1ff22500-2a4e-11ea-88a1-4a0286215b6a.gif)

**Device information**
 - Desktop
 - Windows 10
 - Chrome

**Comment by boonto** [comment]
Resolved by a GCI student.
