### ISSUE TITLE
Allow to change the content of the right menu without closing and reopening

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#443]
**Is your feature request related to a problem? Please describe.**
 When users would like to follow a tutorial they would like to easily test there program in the simulation. To do that in the moment, one have to close the tutorial view and open the simulation view and vice versa to continue with the tutorial.

**Describe the solution you'd like**
Once any of the right menu views is open, one can switch the content by simply clicking on another right menu button. Closing the right menu view is then only possible if one click the current view button again.

**Describe alternatives you've considered**
 Allow to open the simulation view next to the tutorial view. Problem here is that the program is invisible then.

**Additional context**
The proposed solution is not only for tutorials but for general use of the right menu views.

**Comment by boonto** [comment]
Seems to work fine on Chrome, Firefox, IE, Edge, Safari, IOS Safari and Android Chrome.
