### ISSUE TITLE
Arduino: wrong code generation for infrared, ultrasonic and rfid sensors

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#450]
**Describe the bug**
 see screenshot, it is obvious that always one of the two sensor values are returned.

![image](https://user-images.githubusercontent.com/1613069/71574527-634da180-2ae9-11ea-898c-2c3d586b59e8.png)

**Expected behavior**
The corresponding sensor (identified via the name given in the configuration) should be passed to functions.

**Additional context**
Related to #306!

**Comment by bjost2s** [comment]
related to #278, don't forget to integrate this corrected functions later into the yaml files ;-)

**Comment by bjost2s** [comment]
The fix works for ultrasonic and rfid. The infrared sensor still doesn't work properly with more than one sensor attached, might be a problem of the library, see https://arduino.stackexchange.com/questions/52090/can-i-connect-more-than-one-ir-receiver-to-an-arduino-uno e.g.

**Comment by boonto** [comment]
Generated code contains the different sensors now.
