### ISSUE TITLE
EV3: Say block doesn't work with some inputs

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#455]
**Describe the bug**
 - When using the say block, some values won't work, such as 0, empty text, false. When these inputs are added, the program will still run but never finish. Any sensor with a false value also won't work.

**To Reproduce**
1. Add a "say" block
2. Set the parameter to any of the mentioned values
3. Run the program

**Expected behavior**
 - Program says the given input

**Screenshots**
 - 
![image](https://user-images.githubusercontent.com/58810680/71606511-7e8ddf00-2bc5-11ea-9062-93cd1a42cd8f.png)
None of the say blocks in the above screenshot works, the program never finishes and the bot never plays the C note.

**Device information**
 - Desktop
 - Windows 10
 - Chrome

**Additional context**
 - The program can say True but not False
 - Connecting the block "wait for connection" to the "say" block generates a server error 
 - There is no information on what inputs can be attached to the "say" block

**Comment by boonto** [comment]
Needs testing whether this is the case for the real robot as well.

**Comment by boonto** [comment]
Resolved by a GCI student.
