### ISSUE TITLE
WeDo: 'play no port frequency Hz' block causes a server error

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#459]
**Describe the bug**
 - When the buzzer action in the robot configuration is removed, and the 'play frequency Hz' block is used, the user receives a server error.

**To Reproduce**
1. Create a new WeDo program.
2. Go to the 'Robot Configuration' section.
3. Delete the 'Buzzer' block.
4. Go to the Program NEPOProg section and click on the 'Sounds' category.
5. Use the 'play frequency Hz' block.
6. Open the source code view.

**Expected behavior**
 - In such a scenario when the corresponding block in the Robot Configuration is deleted, the 'play frequency Hz' should demonstrate behaviour similar to the the other blocks.
 Instead of the server error, a warning that says 'The actuator is not set to the port'  and an alert that says "There are errors in your program. Please check the messages" should be displayed.

**Screenshots**
<img width="1278" alt="Screen Shot 2019-12-31 at 10 04 27 PM" src="https://user-images.githubusercontent.com/9400738/71627652-bd4d8480-2c19-11ea-81e2-ad41658ba3ac.png">

Expected behaviour(as in the Arduino robot)
<img width="928" alt="Screen Shot 2019-12-31 at 10 24 13 PM" src="https://user-images.githubusercontent.com/9400738/71628112-5da4a880-2c1c-11ea-9a5b-7ab50ac49ceb.png">

**Device information**
 - Type : Desktop
 - OS: MacOS
 - Browser : Chrome

**Comment by boonto** [comment]
Resolved by a GCI student.
