### ISSUE TITLE
Refactoring ConfigurationComponent to have categories instead of "isActor"

### ISSUE THREAD

**Issue by varunshankar** [OpenRoberta/openroberta-lab#46]
Refactoring configuration component to have subclasses for Actor/Sensor/Asset.

The code in this package: https://github.com/OpenRoberta/openroberta-lab/tree/master/OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/components has the Configuration class which has a map of port-name (as a string) to ConfigurationComponent instances.

Now the ConfigurationComponent class has members like `isActor` and methods that are specific to Actors (isRegulated(), isReverse(), getSide()).

The proposal here is to first do some cleanups in ConfigurationComponent (typo fixes, better javadoc comment, and removing the unused code related to `slots`) (see #44). Then as a follow up the code would be refactored into Configuration{Actor,Sensor}Component to pave the way for adding a ConfigurationAssetComponent.

**Comment by ensonic** [comment]
According to gitter discussion, the way forward will be:
1.) Create one pull request that does the refactoring. This can be two changes - one for extracting Actor/Sensor subclasses from ConfigurationComponent and making ConfigurationComponent a baseclass. The 2nd change on this PR will make the rewrites of all the constructor calls. Ideally this is does with a script (eg "git grep" + "sed"). This is to make sure if the that the 2nd part can be redone as needed.

2.) If the previous PR is merged, a new subclass for ConfigurationAssetComponent can be added

**Comment by rbudde** [comment]
a large commit. Parts have been reviewed.
