### ISSUE TITLE
Edison:  Motor and drive blocks do not compile 

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#464]
**Describe the bug**
 - When the 'motor on speed %' block is used with the IR Seeker sensor or with the 'receive message' block and the compile button is pressed, it causes an error. 

**To Reproduce**
1. Create a new program in Edison.
2. Use the 'motor on speed %' block
3. Use the 'IR Seeker' sensor or the 'receive message' block in association with the motor block.
4. Compile the nepo program.
5. See error.

**Expected behavior**
 - The program should compile without errors as it does for the 'play frequency' block.

**Screenshots**
<img width="1276" alt="Screen Shot 2020-01-01 at 5 58 23 PM" src="https://user-images.githubusercontent.com/9400738/71641363-b0d03700-2cc0-11ea-9cb9-f9fa4376277e.png">

<img width="1062" alt="Screen Shot 2020-01-01 at 6 24 10 PM" src="https://user-images.githubusercontent.com/9400738/71641559-0b1ec700-2cc4-11ea-9fa1-f123aad3027a.png">

<img width="1005" alt="Screen Shot 2020-01-01 at 6 29 38 PM" src="https://user-images.githubusercontent.com/9400738/71641606-baf43480-2cc4-11ea-867f-24c5942e7dd2.png">

**Device information**
 - Type : Desktop
 - OS: MacOS
 - Browser : Chrome

**Additional context**
- This bug also happens for the 'drive forwards', 'turn' and 'steer' blocks.

**Comment by boonto** [comment]
Resolved by a GCI student in 1fd1eceb6da58d61440523b83f6b29dc78ae4f13.
Similar implementation in super class was not used because Edison has no configuration components set up.
