### ISSUE TITLE
Wedo: Comment blocks not working

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#468]
**Describe the bug**
 - Comment block does not generate comment in source code

**To Reproduce**
1. Go to Wedo
2. Type anything into a comment block
3. Go to source code view

**Expected behavior**
 - A generated comment in the source code

**Screenshots**
 - 
![image](https://user-images.githubusercontent.com/58810680/71662743-a8eac280-2da6-11ea-8531-7775c9c79225.png)

Usually a comment is generated automatically, see EV3 example:
![image](https://user-images.githubusercontent.com/58810680/71662821-e7807d00-2da6-11ea-8d07-e80ea3542315.png)

**Device information**
 - Desktop
 - Windows10
 - Chrome

**Comment by rbudde** [comment]
tested with both simulation and a real wedo: works as expected
