### ISSUE TITLE
Sensebox: Sensors used with List variable throws error when program is compiled

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#471]
**Describe the bug**
 - When the List variable is used to store sensor values, and the program is compiled, an error is thrown.

**To Reproduce**
1. Create a new nepo program.
2. Create a new List Number variable.
3. Use sensors(which return numerical values) such as gyroscope, compass sensor and accelerometer as the elements of the list variable.
4. Press the compile button.
5. See error.

**Expected behavior**
Program should compile without errors.

**Screenshots**
<img width="937" alt="Screen Shot 2020-01-02 at 9 59 34 PM" src="https://user-images.githubusercontent.com/9400738/71678471-3d572400-2dab-11ea-8b1f-2da101e0b472.png">
<img width="1280" alt="Screen Shot 2020-01-02 at 9 59 49 PM" src="https://user-images.githubusercontent.com/9400738/71678476-41834180-2dab-11ea-8f3c-300becceca18.png">

**Device information**
 - Type : Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional context**
Problem happens for the gyroscope, accelerometer and compass sensor.

**Comment by VinArt** [comment]
Seems to be already patched on develop

**Comment by bjost2s** [comment]
@VinArt , please provide the related issue

**Comment by RaghuvirShirodkar** [comment]
Seems to be solved. Cross compilation tested successful on `lab.open-roberta.org`.
Here is a [sample program](<https://lab.open-roberta.org/#loadProgram&&sensebox&&NEPOprog&&%3Cexport%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%3E%3Cprogram%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22sensebox%22%20xmlversion=%223.1%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%22384%22%20y=%2250%22%3E%3Cblock%20type=%22robControls_start_ardu%22%20id=%22l9Lp%60gNd%5DGQJ_0PBfA?z%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cmutation%20declare=%22true%22%3E%3C/mutation%3E%3Cfield%20name=%22DEBUG%22%3E%3C/field%3E%3Cstatement%20name=%22ST%22%3E%3Cblock%20type=%22robGlobalVariables_declare%22%20id=%2229yb@z%259%7CmaTv.%60,GM?7%22%20intask=%22true%22%20deletable=%22false%22%20movable=%22false%22%3E%3Cmutation%20next=%22false%22%20declaration_type=%22Array_Number%22%3E%3C/mutation%3E%3Cfield%20name=%22VAR%22%3Eitem%3C/field%3E%3Cfield%20name=%22TYPE%22%3EArray_Number%3C/field%3E%3Cvalue%20name=%22VALUE%22%3E%3Cblock%20type=%22robLists_create_with%22%20id=%22e6rLmt%5EkP~j.%7DaALRR;V%22%20intask=%22true%22%3E%3Cmutation%20items=%2210%22%20list_type=%22Number%22%3E%3C/mutation%3E%3Cfield%20name=%22LIST_TYPE%22%3ENumber%3C/field%3E%3Cvalue%20name=%22ADD0%22%3E%3Cblock%20type=%22robSensors_light_getSample%22%20id=%22pK:!S%7C=To(e(Fov)uBJP%22%20intask=%22true%22%3E%3Cmutation%20mode=%22LIGHT%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ELIGHT%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3EL%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD1%22%3E%3Cblock%20type=%22robSensors_sound_getSample%22%20id=%22Ha0x5V%7CYtrJJz:5qq%7CZj%22%20intask=%22true%22%3E%3Cmutation%20mode=%22SOUND%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ESOUND%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3ES2%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD2%22%3E%3Cblock%20type=%22robSensors_ultrasonic_getSample%22%20id=%22lEHDuax%7D/#OW-?Cdisuv%22%20intask=%22true%22%3E%3Cmutation%20mode=%22DISTANCE%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3EDISTANCE%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3EU%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD3%22%3E%3Cblock%20type=%22robSensors_humidity_getSample%22%20id=%22lW_~LIcR!(p7yzEWplie%22%20intask=%22true%22%3E%3Cmutation%20mode=%22HUMIDITY%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3EHUMIDITY%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3EH%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD4%22%3E%3Cblock%20type=%22robSensors_temperature_getSample%22%20id=%22%5Ds=N0zDTnA81n02%7D~_th%22%20intask=%22true%22%3E%3Cmutation%20mode=%22TEMPERATURE%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ETEMPERATURE%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3ET%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD5%22%3E%3Cblock%20type=%22robSensors_lightveml_getSample%22%20id=%22!AZ~%5Dc3Q)/ML%7C.4G*6PW%22%20intask=%22true%22%3E%3Cmutation%20mode=%22LIGHT%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ELIGHT%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3EV%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD6%22%3E%3Cblock%20type=%22robSensors_accelerometer_getSample%22%20id=%2223rfL!9/R2U8Dat1)fLE%22%20intask=%22true%22%3E%3Cmutation%20mode=%22X%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3EX%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3EB%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD7%22%3E%3Cblock%20type=%22robSensors_particle_getSample%22%20id=%22!=,h5xZp%7C=--B%5ESQ.fbO%22%20intask=%22true%22%3E%3Cmutation%20mode=%22PM25%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3EPM25%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3ES%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD8%22%3E%3Cblock%20type=%22robSensors_gps_getSample%22%20id=%22jhMcqVZ;n%25r7,uu)97f1%22%20intask=%22true%22%3E%3Cmutation%20mode=%22LATITUDE%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ELATITUDE%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3EG2%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22ADD9%22%3E%3Cblock%20type=%22robSensors_environmental_getSample%22%20id=%22%60j@#r)!F?Jm%5Bc-KE%5DH=i%22%20intask=%22true%22%3E%3Cmutation%20mode=%22TEMPERATURE%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ETEMPERATURE%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3EE%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3Cblock%20type=%22robControls_loopForever_ardu%22%20id=%22%60mIJB4z:(3D;T%25:%5D?%5EIz%22%20intask=%22true%22%20deletable=%22false%22%20movable=%22false%22%3E%3Cstatement%20name=%22DO%22%3E%3Cblock%20type=%22robControls_forEach%22%20id=%22C#R7i_!,K=#Ae%25*v?@eW%22%20intask=%22true%22%3E%3Cmutation%20list_type=%22Number%22%3E%3C/mutation%3E%3Cfield%20name=%22TYPE%22%3ENumber%3C/field%3E%3Cfield%20name=%22VAR%22%3Eitem2%3C/field%3E%3Cvalue%20name=%22LIST%22%3E%3Cblock%20type=%22variables_get%22%20id=%22YNDT7Ae%7BAgMurHirXGrA%22%20intask=%22true%22%3E%3Cmutation%20datatype=%22Array_Number%22%3E%3C/mutation%3E%3Cfield%20name=%22VAR%22%3Eitem%3C/field%3E%3C/block%3E%3C/value%3E%3Cstatement%20name=%22DO%22%3E%3Cblock%20type=%22robActions_serial_print%22%20id=%22h.-!Z@FF6b3@5pO,R3Jq%22%20intask=%22true%22%3E%3Cvalue%20name=%22OUT%22%3E%3Cblock%20type=%22variables_get%22%20id=%22MU1ScLZa8ByDTt#Y8@YH%22%20intask=%22true%22%3E%3Cmutation%20datatype=%22Number%22%3E%3C/mutation%3E%3Cfield%20name=%22VAR%22%3Eitem2%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/program%3E%3Cconfig%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22sensebox%22%20xmlversion=%223.1%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%2222%22%20y=%2243%22%3E%3Cblock%20type=%22robConf_light%22%20id=%22m%7C3RK=0gPuYq6@)SZLi!%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3EL%3C/field%3E%3Cfield%20name=%22OUTPUT%22%3E3%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%22250%22%20y=%2285%22%3E%3Cblock%20type=%22robBrick_senseBox-Brick%22%20id=%22DC@kFZs8?McKYe+9Bl3y%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cmutation%20items=%221%22%3E%3C/mutation%3E%3Cfield%20name=%22BOX_ID%22%3E%3C/field%3E%3Cfield%20name=%22NAME1%22%3EID1%3C/field%3E%3Cfield%20name=%22ID1%22%3E%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2216%22%20y=%22149%22%3E%3Cblock%20type=%22robConf_sound%22%20id=%22%5E(yzR0EzAE=eNe.J%25:k/%22%20error_attribute=%22true%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3ES2%3C/field%3E%3Cfield%20name=%22OUT%22%3E4%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%22250%22%20y=%22191%22%3E%3Cblock%20type=%22robConf_led%22%20id=%22Tris)a2:6F0Y.;)LAiy%7C%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cfield%20name=%22NAME%22%3ER%3C/field%3E%3Cfield%20name=%22INPUT%22%3E7%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%22500%22%20y=%22250%22%3E%3Cblock%20type=%22robConf_robot%22%20id=%22robot%22%20intask=%22false%22%20deletable=%22false%22%3E%3Cfield%20name=%22ROBOT%22%3Eundefined%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2216%22%20y=%22276%22%3E%3Cblock%20type=%22robConf_ultrasonic%22%20id=%22%5E%7C~F*Er0%5E%7Bx@_M-%7DdPEL%22%20error_attribute=%22true%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3EU%3C/field%3E%3Cfield%20name=%22TRIG%22%3E1%3C/field%3E%3Cfield%20name=%22ECHO%22%3E2%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%22250%22%20y=%22299%22%3E%3Cblock%20type=%22robConf_led%22%20id=%22O)bMmWN5:W1%60T:0!R@-a%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cfield%20name=%22NAME%22%3EG%3C/field%3E%3Cfield%20name=%22INPUT%22%3E8%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%22250%22%20y=%22407%22%3E%3Cblock%20type=%22robConf_accelerometer%22%20id=%229L:HO%7C%7CCjNS(,!YiSk%5BP%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cfield%20name=%22NAME%22%3EB%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2216%22%20y=%22439%22%3E%3Cblock%20type=%22robConf_humidity%22%20id=%228lPB;%5BfLv!cw;gq..vc%5B%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3EH%3C/field%3E%3Cfield%20name=%22I2C%22%3EI2C%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2216%22%20y=%22505%22%3E%3Cblock%20type=%22robConf_temperature%22%20id=%22%7D+-??%606,K0nY_%60/%5Enu+x%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3ET%3C/field%3E%3Cfield%20name=%22I2C%22%3EI2C%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2216%22%20y=%22582%22%3E%3Cblock%20type=%22robConf_lightveml%22%20id=%22TeGX,YSuYGN%7Dp3?xa;zD%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3EV%3C/field%3E%3Cfield%20name=%22I2C%22%3EI2C%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2216%22%20y=%22659%22%3E%3Cblock%20type=%22robConf_particle%22%20id=%227!TbQ5F*1L13m8nA+ESX%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3ES%3C/field%3E%3Cfield%20name=%22SERIAL%22%3ESerial1%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2216%22%20y=%22736%22%3E%3Cblock%20type=%22robConf_gps%22%20id=%22K_XC-;gG?QdV5%60=BZe;D%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3EG2%3C/field%3E%3Cfield%20name=%22I2C%22%3EI2C%3C/field%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%2218%22%20y=%22810%22%3E%3Cblock%20type=%22robConf_environmental%22%20id=%22_l%5EceCPsa)yKN6:%5EPNo%5D%22%20intask=%22true%22%3E%3Cfield%20name=%22NAME%22%3EE%3C/field%3E%3Cfield%20name=%22I2C%22%3EI2C%3C/field%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/config%3E%3C/export%3E>) for testing.
