### ISSUE TITLE
Calliope: Set brightness with parameter 0 not working

### ISSUE THREAD

**Issue by KevinL10** [OpenRoberta/openroberta-lab#473]
**Describe the bug**
 - The description of the block "setBrightness" says that "0 means all leds are turned off, 9 is the brightest value." However, when the brightness is set to 0, it has the same brightness as if the brightness was set to 9. 

**To Reproduce**
1. Go to a calliope program
2. Add a setBrightness block with brightness 0
3. Display a text

**Expected behavior**
 - Since "0 means all leds are turned off" a setBrightness block with parameter 0 should have all leds turned off. 

**Screenshots**
 - This program will produce the error 
![brightnesserror](https://user-images.githubusercontent.com/58920989/71697028-87201a00-2d6b-11ea-86c4-a11573139b16.PNG)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
 - Note that there is a similar block, which sets the brightness for a specific LED. That block will 
 work correctly(not display anything) when brightness is set to 0.
- This program will work correctly 
![brightnesscorrectlyworking](https://user-images.githubusercontent.com/58920989/71697068-af0f7d80-2d6b-11ea-8d4f-1d985c2150ec.PNG)

**Comment by boonto** [comment]
Needs testing whether this is the case for the real robot as well.

**Comment by boonto** [comment]
0 brightness works correctly on the real Calliope.

**Comment by boonto** [comment]
Resolved by GCI student in 4b71015.
