### ISSUE TITLE
EV3 sound sensor does not show up in wait until block

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#479]
**Describe the bug**
 - The EV3 sound sensor does not have an entry in the generic wait until sensor block.

**To Reproduce**
1. Add wait until sensor block to program
2. Open the dropdown menu
4. Observe that no sound sensor entry is available

**Expected behavior**
 - Sound sensor is available to be selected.

**Comment by rbudde** [comment]
shows up now, works.
