### ISSUE TITLE
EV3: Negative Volumes Being Stored

### ISSUE THREAD

**Issue by RohanCheri** [OpenRoberta/openroberta-lab#480]
**Describe the bug**
When setting the volume to a negative number and using get volume, a negative number is displayed, which shouldn't be possible

**To Reproduce**
1. Go to Action -> Sounds
2. Set Volume to a negative number
3. Display the Volume
4. Observe the negative value

**Expected behavior**
 The volume value being clipped to a range between 0 and 100 (The program would display 0) OR not allowing negative values entirely in the set volume block.

**Screenshots**
![NegativeVolume](https://user-images.githubusercontent.com/34838212/71723383-75398800-2dfa-11ea-81b3-322f441d1304.gif)

**Device information**
 - Type Desktop
 - OS: Windows 10
 - Browser Chrome 70.0.3945.88

**Additional context**
The problem occurs in all EV3 Devices.

**Comment by boonto** [comment]
Needs testing whether this is the case for the real robot as well.

**Comment by boonto** [comment]
Does not happen on dev or lejos.

**Comment by rbudde** [comment]
works in the simulation
