### ISSUE TITLE
EV3: Ultrasound Sensor and Sensor View Not Agreeing

### ISSUE THREAD

**Issue by RohanCheri** [OpenRoberta/openroberta-lab#482]
**Describe the bug**
When the robot is at a distance of more than 255, the ultrasound sensor's range, from the surface that it is measuring from, the sensor view displays the actual distance from the robot to the surface while the actual reading of the ultrasound sensor caps out at 255 (any value over 255 is displayed as 255).

**To Reproduce**
1. Use a repeat indefinitely block with a block that displays the distance reading of the ultrasound sensor, then a block that waits small amount of time, and then a block that clears the display. (shown below)
2. Compile the program
3. Navigate to the 3rd Scene
4. Move the obstacle to the bottom left corner
5. Move the robot to the middle of the left edge and as far back as possible without hitting the left boundary
6. Open sensor view
7. Run the program and observe the differences between the sensor view and display.

**Expected behavior**
The sensor view and displayed/stored reading of the ultrasound sensor reading being equal.

**Screenshots**
Observe the difference between the value in the sensor view and displayed value in the simulation.
![UltrasoundVsSensorView](https://user-images.githubusercontent.com/34838212/71725091-b896f500-2e00-11ea-8c72-8336de2f1e34.gif)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome 79.0.3945.88

**Additional context**
- One way this could be fixed is to just implement a higher and lower bound on the ultrasound reading on the sensor view
- Additionally, the distance is displayed to 14 decimal places which seems quite excessive as the reading on the actual sensor has an uncertainty of 1 cm. (I would recommend rounding this value to 3 decimal places)
- This problem appears in all EV3 Devices

**Comment by boonto** [comment]
Resolved by a GCI student in 8b132c30dfcd17d64a268c275a28500fcc23e761.
