### ISSUE TITLE
EV3dev ultrasonic presence does not work

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#485]
**Describe the bug**
 - When selecting the ultrasonic sensor's presence mode the output is not as expected
- When connecting it to a show text block it shows (I assume) the initial distance reading without updates

**To Reproduce**
1. Use ultrasonic presence in a show text block
2. See numeric return value

**Expected behavior**
 - A boolean response value as depicted by the block.

**Comment by ensonic** [comment]
It also uses the wrong mode. I'll fix it.

**Comment by bjost2s** [comment]
It is not clear if users do get the updated hal. We should check if we can put this into the helper methods

**Comment by bjost2s** [comment]
solved
