### ISSUE TITLE
EV3: Wrong behaviour of the turn blocks when degree is set to 0 and some trigonometric functions

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#492]
**Describe the bug**
 - When the turn blocks are used , even if degree is set to 0 , the robot turns.
Similarly if degree is set to 'asin 0', even then the robot turns.

**To Reproduce**
1. Create a new EV3 program
2. Click on Action -> Drive.
3. Use the turn blocks.
4. Set the degree to 0
5. Use this block inside a loop to repeat it a certain number of times so that movement of the robot is visible.

**Expected behavior**
 - When degree is 0, the robot should not turn.

**Screenshots**
 -
![nepo-2](https://user-images.githubusercontent.com/9400738/71767069-acf51c80-2f2d-11ea-9d90-02dff8f86eba.gif)

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional Context**
When the degree is set to value of trigonometric functions such as 'asin 0', 'sin 0', 'tan 0',etc. ,  movement is again seen in the robot which should not be the case.

**Comment by boonto** [comment]
Fixed by RohanCheri, thanks!
