### ISSUE TITLE
As a group admin I'd like to be able to remove users from my group

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/openroberta-lab#50]
Precondition: the user is logged in, the user is a group admin

People: group admin, users to be deleted

Subjects: group

1. From the menu "user" user chooses "go to groups" and chooses the group with which he/she would like to work by double click or pressing the corresponding button.
2. User is redirected to a group members tab with the list of the group members.
3. User can remove one, several or all the users from the chosen group:
- to delete one user admin presses a delete button in the line of this user in the table
- to delete several users admin ticks the users to be removed and presses delete button on the top of the table
- to delete all the users those belong to the group, admin ticks a checkbox on the top of the table and presses delete on the top of the table.
4. The system responses with a popup that contains the following:
- question if the admin really wants to remove the user(s)
- name of the user / list of the names of the users
- button to confirm and button to abort.
5. The admin confirms the deletion by pressing the corresponding button.
6. The system checks if everything is correct and returns:
- a message that the user(s) was(were) removed if everything is fine; admin will also immediately see that the user(s) disappeared from the group members list
- a popup with the error description in case if user removal cannot be performed. This case is unlikely and can happen only because of some database or server error.
7. The deleted users will see a popup that informs them about their removal from the group when they log in for the first time after their removal. The group will disappear from their group list as well.
8. The programs shared in the group are not shared with the removed users anymore. If people want to keep the programs they have to save it to they own programs in advance -- that can be explained in a pop-up.  The programs shared by the removed users are not shared with the group anymore.

This can also be used as a test case.

This issue is related to #384

**Comment by bjost2s** [comment]
@vlebedynska, I close this issue for you
