### ISSUE TITLE
EV3: Set variable block with missing arguments throws a server error

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#502]
**Describe the bug**
 - When a variable is created and the 'set' block for that variable is used without an input, the user receives a server error.

**To Reproduce**
1. Create a new nepo program.
2. Create a new variable.
3. Use the 'set' variable block without an input.
4. Open the simulation
5. See error

**Expected behavior**
 - Opening the simulation should not produce an error.

**Screenshots**
 - 
<img width="983" alt="Screen Shot 2020-01-05 at 1 01 54 PM" src="https://user-images.githubusercontent.com/9400738/71776767-a9f53d00-2fbc-11ea-82ea-059d46b0ab2e.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional context**
 - The error is also seen in other Calliope, NXT and Micro:bit.

**Comment by boonto** [comment]
Will probably be solved by #306.

**Comment by boonto** [comment]
Server error for now is resolved by a GCI student.
