### ISSUE TITLE
As a user I'd like to invite people to the group and create new users

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/openroberta-lab#51]
Precondition: the user is logged in, the user is an admin of the group, group exists

People: user, potential group members

Subjects: the group, users to be created

1. From the menu "user" user chooses "go to groups" and chooses the group with which he/she would like to work by double click or pressing the corresponding button.
2. User is redirected to a group members tab with the list of the group members.
3. User presses a button for adding user.
4. The system responses with a popup that contains the following:
- a text input field for the program name
- button to confirm and button to abort.
5. The user types a name of the user and confirms adding by pressing the corresponding button.
6. The system checks the user's input and returns:
- a message that the invitation to user was sent if the user exists
- a popup with a question if the user would like to create a new user with this name if the user doesn't exist, and button to confirm and button to abort. The user presses the corresponding button and gets a user creation popup with already filled name. As soon as the user is created, he/she appears in a group members list
- a message that the name contains prohibited symbols in case the name contains potentially dangerous symbols.
7. Invited users will receive an invitation popup when they log in next time. The popup contains the following:
- question if they agree to join the group
- name of the group
- button to accept and a button to decline the invitation.
8. If the potential group member confirms the invitation, he/she appears in the group group member list and can see the group in their group list. Otherwise, group admin receives a popup with a message that the invitation was declined by the user.

This can also be used as a test case.

This issue is related to #384

**Comment by bjost2s** [comment]
@vlebedynska, I close this issue for you
