### ISSUE TITLE
As a user I would like to share programs with a group I belong to

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/openroberta-lab#52]
Precondition: the user is logged in, the user belongs to the group, the program to share is in "my programs", user is in "my programs" tab

People: user, group members

Subjects: group, program

1. User presses "share" button in the table line of the corresponding program.
2. The system response is a popup with the following information:
- name of the program to share
- text input field with the username
- list of the groups to which user belong with check boxes
- button to confirm and button to abort.
3. The user ticks the groups with which he/she would like to share the programs and presses a corresponding button.
4. The system checks if everything is correct and returns:
- a popup that sharing was successful if everything is fine; in this case user will immediately see the name of the group(s) in a "shared" column
- a popup with the error description in case if group deletion cannot be performed. This case is unlikely and can happen only because of some database or server error.
5. Users who belong to the group will see the shared program in their program list as shared in the group.

This can also be used as a test case.

This issue is related to #384

**Comment by bjost2s** [comment]
@vlebedynska, I close this issue for you
