### ISSUE TITLE
As a user I'd like to be able to delete groups

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/openroberta-lab#53]
Precondition: the user is logged in, the user is an admin of the group, group to be deleted exists

People: user, group members

Subjects: the group to be deleted, programs shared in the group

1. From the menu "user" user chooses "go to groups".
2. User is redirected to a groups tab with the list of the groups with groups' creators' names -- the ones admined by user and the ones to which the user belongs.
3. User can delete one, several or all the groups those belong to the user:
- to delete one group user presses a delete button in the line of this group in the table
- to delete several groups user ticks the groups to be deleted and presses delete button on the top of the table
- to delete all the groups those belong to the user, user ticks a checkbox on the top of the table and presses delete on the top of the table.
4. The system responses with a popup that contains the following:
- question if the user really wants to delete the group(s)
- name of the group / list of the names of the groups
- button to confirm and button to abort.
5. The user confirms the deletion by pressing the corresponding button.
6. The system checks if everything is correct and returns:
- a message that the group was deleted if everything is fine; user will also immediately see that the group disappeared from the group list
- a popup with the error description in case if group deletion cannot be performed. This case is unlikely and can happen only because of some database or server error.
7. The non-admin members of the group will see a popup that informs them about group deletion when they log in for the first time after the deletion of the group. The group will disappear from their group list as well.
8. The programs shared in the group will be deleted after group deletion. If people want to keep the programs they have to save it to they own programs in advance -- that can be explained in a pop-up.

This can also be used as a test case.

This issue is related to #384

**Comment by bjost2s** [comment]
@vlebedynska, I close this issue for you
