### ISSUE TITLE
Source Code Editor: scrollbars are covered by the text area

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#537]
**Describe the bug**
 see screenshot

**To Reproduce**
1. Open the "Edit" menu (far left in the corner)
1. Go to 'open source code editor'
2. Make your window smaller, so that the vertical and the horizontal scrollbars appear
3. scroll until you observe what is in the screenshot

**Expected behavior**
 Scrollbars should be outside the text area

**Screenshots**
![image](https://user-images.githubusercontent.com/1613069/72318951-067fe880-369e-11ea-9d3f-20724d6bb57f.png)

Ubuntu Chrome + Firefox, others not tested yet

**Comment by harshitmalik03** [comment]
Can you show me the file to work on this.

**Comment by KishkinJ10** [comment]
i am a beginner cna i work on this issue ? can you  tell me from where should i start

**Comment by CarefoDragneel** [comment]
I would like to work on this issue. Actually, I am an open-source enthusiast but I am new in this field. So, can you please guide me on how to understand the codebase and exactly how to make my contribution here?

**Comment by bjost2s** [comment]
@CarefoDragneel , it seems to be an issue of bad / wrong css, Are you familiar with debugging in a browser? That might help a lot

**Comment by spandit230496** [comment]
i am interested can you assign this issue to me

**Comment by bjost2s** [comment]
works as expected
