### ISSUE TITLE
As a user I'd like to be able to create groups for sharing programs

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/openroberta-lab#54]
Precondition: the user is logged in

People: user -- admin of the group

Group: the group to be created

1. From the menu "user" user chooses "go to groups".
2. User is redirected to a groups tab with the list of the groups with groups' creators' names -- the ones admined by user and the ones to which the user belongs.
3. User presses a button for group creation.
4. The system responses with a popup that contains the following:
- a text input field for the program name
- button to confirm and button to abort.
5. The user types a name of the group and confirms the creation by pressing the corresponding button.
6. The system checks the user's input and returns:
- a message that the group was created if everything is fine; user will also immediately see the created group in the group list
- a popup that the group already exist if the name has already been taken
- a message that the name contains prohibited symbols in case the name contains potentially dangerous symbols

This can also be used as a test case.

**Comment by bjost2s** [comment]
@vlebedynska, I close this issue for you
