### ISSUE TITLE
Add control for internal RGB Led, Arduino Uno Wifi Rev2

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#549]
**Describe the solution you'd like**
Support for inbuild RGB Led

**Describe alternatives you've considered**
here people tried to find a solution
https://github.com/arduino-libraries/ArduinoBLE/issues/3

**Additional context**
Always good to support in build features from small devices

**Comment by boonto** [comment]
I also added an error message when the internal port is used for non unowifirev2 Arduinos.
