### ISSUE TITLE
Edison round function not needed

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#550]
**Describe the bug**
 - The Edison bot does not support decimal values, so the block round, round up and round down are not needed as they cause confusion.

**To Reproduce**
1. Go to Edison robot
2. Go to math experts

**Fix**
 - Remove the round blocks as they are not needed

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by boonto** [comment]
The round block was removed from the toolbox.
