### ISSUE TITLE
Persistent pin state for Calliope/micro:bit simulation

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#552]
**Is your feature request related to a problem? Please describe.**
 - Currently the state of the pins (analog/digital in) in the Calliope/micro:bit simulation is reset every simulation start. This is sometimes unexpected for users and may not accurately reflect usage of the pins in real situations.

**Describe the solution you'd like**
- PIN states are persistent for the session.

**Comment by PamoCurtis** [comment]
Since the release of the new simulation, this issue in not present anymore. But quite the opposite issue is now present: The pins for __analog/digital out__ from the calliope/micro:bit(v2) aren't resetted after every simulation start.

**Comment by bjost2s** [comment]
tested
