### ISSUE TITLE
Multiple Bot Simulation: Robot spawns offscreen

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#553]
**Describe the bug**
 - In some backgrounds where there are more than 3 bots in the simulation, some robots spawn offscreen or on the edge of the boundary. Bots offscreen cannot be moved back.

**To Reproduce**
1. Go to multiple bot simulation
2. Select 3 or more bots to simulate
3. See error

**Expected behavior**
 - All bots should spawn in view regardless of background
 - Maybe if there are more than 3 bots, spawn them in the center of each background

**Screenshots**
A simulation with 5 robots, one is clipped on the edge of the background and another is off screen. 

![image](https://user-images.githubusercontent.com/58810680/72603657-8f807380-396d-11ea-960b-e237c687404d.png)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by boonto** [comment]
Merged in dfe29c69ea65e2614eb4a88e6e04d04d06bd7b16.
