### ISSUE TITLE
Multiple Robot Simulation: FPS showing incorrect value

### ISSUE THREAD

**Issue by KevinL10** [OpenRoberta/openroberta-lab#556]
**Describe the bug**
 - If you create a multiple robot simulation with over 3 robots, the FPS in the sensor data section will show an alternation between 500 and 1000 fps. If you then create another multiple robot simulation, the fps will alternate between Na, 500, and 1000 fps.

**To Reproduce**
1. Create a multiple robot simulation program with over 2 robots
2. Open sensor data
3. See error
4. Create another multiple robot simulation with over 2 robots
5. Open sensor data
6. See new error

**Expected behavior**
 -  The actual fps should be shown.

**Screenshots**
 - 
![fpsglitch](https://user-images.githubusercontent.com/58920989/72626089-e26f1200-38fe-11ea-879a-843487d49298.PNG)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by kuruma99** [comment]
Hi, I would like to work on this as my first bug.

**Comment by kuruma99** [comment]
Hi @bjost2s , sorry could not work on this due to some issues. Will start working on this right away. Is there any more info regarding this that I should know. Thanks.

**Comment by roffinator3000** [comment]
Please assign me

**Comment by rbudde** [comment]
works as expected
