### ISSUE TITLE
Multiple Robot Simulation: Opening new multi sim error

### ISSUE THREAD

**Issue by KevinL10** [OpenRoberta/openroberta-lab#557]
**Describe the bug**
 - If you create a multiple robot simulation and afterwards you open a new program, the dropdown in sensor data will still contain the multiple colours of robots.

**To Reproduce**
1. Create a multiple robot simulation with over 1 robot.
2. Close that multiple simulation by opening source code or going to "edit" -> "my programs" and selecting any program.
3. Open the sensor data

**Expected behavior**
 - There should only be one colour for that one robot.

**Screenshots**
 - 
![Screenshot (99)](https://user-images.githubusercontent.com/58920989/72626488-a4beb900-38ff-11ea-9ca9-c419ced5063b.png)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by boonto** [comment]
There should actually be no dropdown at all.

**Comment by ykabusalah** [comment]
Can I try doing this?

**Comment by boonto** [comment]
Sure!

**Comment by ykabusalah** [comment]
> Sure!

I'll try to get it done soon! Can I get assigned this?
