### ISSUE TITLE
Refreshing the page causes user to get logged out

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#559]
**Is your feature request related to a problem? Please describe.**
 - Whenever a logged-in user refreshes the page, the user gets logged out and needs to login again.

**Describe the solution you'd like**
 - The user should stay signed in even after refreshing the page.

**To reproduce**
1. Login to open-roberta.org
2. Refresh the page
3. You will need to log in again.

**Comment by boonto** [comment]
As we just got rid of cookies and want to keep it that way, I think this would be very hard thing to accomplish.

**Comment by boonto** [comment]
Thanks, but we decided against this, see #566.
