### ISSUE TITLE
USBProgram: Firmware update does not work

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#56]
**Describe the bug**
 - Updating the EV3 to a newer firmware version through the USBProgram does not work.

**Expected behavior**
 - It works.

**Comment by boonto** [comment]
In the course of OpenRoberta/robertalab#1108 the update address was incorrectly modified.

**Comment by boonto** [comment]
Another note: when the firmware does not match the server, the client outputs a logging message using the server version as the desired firmware version. E.g.:
`The firmware version '3.3.1' on the server is newer than the firmware version '2.6.2' on the robot`

**Comment by bjost2s** [comment]
Closed because already released!
