### ISSUE TITLE
Multiple Robot Simulation: Button Re-positions All Robots Instead of a Single Robot

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#562]
**Describe the bug**
In the multiple robot simulation, if both the robots are moved elsewhere and the 'Move the Robot to its initial postion' button is pressed, both the robots are re-positioned.

**To Reproduce**
1. Start multiple robot simulation.
2. Move the robots elsewhere.
3. Press the 'Move the Robot to its initial position' button.
4. See the bug.

**Expected behavior**
 Instead of all the robots returning to initial position, only the selected robot should return to the initial position.

**GIF**
 - 
![Screen Recording 2020-01-18 at 01 53 30 52 AM](https://user-images.githubusercontent.com/44456350/72643724-607df800-3995-11ea-9404-9d0c3c5527f8.gif)

**Device information**
 - Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
Thanks, but this is intended behaviour. May reopen this in case anything changes.
