### ISSUE TITLE
Multiple Robot Simulation: Gallery Programs

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#564]
**Is your feature request related to a problem? Please describe.**
 - While setting up the robots for the multiple robot simulation, the user can only set up a simulation with their own programs and not gallery programs.

**Describe the solution you'd like**
 - An option for setting up multiple robot simulation with supported gallery programs.

**Describe alternatives you've considered**
 - A button in the program selection that switches between user programs and gallery programs.

**Additional context**
 - It would be nice to have the gallery programs along with their authors and the robot model in a list as well.

**Comment by bjost2s** [comment]
We prefer to get a local copy from the galery program and use it.
