### ISSUE TITLE
Multiple robot views in EV3 when new backgrounds are uploaded

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#565]
**Describe the bug**
 - When two or more backgrounds are uploaded for EV3,  multiple robot views are displayed.

**To Reproduce**
1. Create a new EV3 program
2. Upload two or more new backgrounds
3. Open the simulation window.
4. Open the robot view.
5. See error.

**Expected behavior**
 - Only one robot view should show up.

**Screenshots**
 - 
<img width="1278" alt="Screen Shot 2020-01-18 at 11 30 44 AM" src="https://user-images.githubusercontent.com/9400738/72659489-5506ed00-39e6-11ea-8953-67df5c888ae8.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional context**
 - The issue appears in EV3 but is solved for NXT.

**Comment by boonto** [comment]
Resolved by a GCI student.

**Comment by boonto** [comment]
The current implementation leads to #560.

**Comment by boonto** [comment]
Does not happen anymore.
