### ISSUE TITLE
'Square' Mathematical Function

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#567]
**Is your feature request related to a problem? Please describe.**
 - For all the robots, the 'math' blocks contain the square root function but not the square function.

**Describe the solution you'd like**
 - A block with the square function.

**Describe alternatives you've considered**
 - A square function added to the drop-down list in the square root 
 block.

**Additional context**
 - The list contains the square-root function but not the 'square' function.
![Capture](https://user-images.githubusercontent.com/44456350/72659711-0f4c2380-39ea-11ea-8a8a-8a1fc930a1bf.PNG)

Additionally, there could be an exponent function that raises a number's power by a certain value.

**Comment by rbudde** [comment]
seems to work, tested for Calliope, ev3 all variants

**Comment by bjost2s** [comment]
also tested on micro:bit
