### ISSUE TITLE
Mathematical Functions on Number Lists

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#569]
**Is your feature request related to a problem? Please describe.**
 - There should be a list block that allows the user to carry out various mathematical functions on lists. For example, the block should add, subtract, multiply, divide the numbers present in the same positions and create a new list with the result.

**Describe the solution you'd like**
 - A list block that carries out mathematical functions for numbered lists.

**Describe alternatives you've considered**
 - Allowing number lists to be attached to the mathematical function block.

**Additional context**
 - This would help in making complex programs such as converting binary numbers to decimals.

**Comment by boonto** [comment]
After some consideration we decided against this. As lists and math operations should stay mostly based on the original Blockly setup.
