### ISSUE TITLE
Robot Configuration Labels

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#571]
**Describe the bug**
 - Certain robot configurations such as Calliope Mini have the robot blueprints labelled in German.

**To Reproduce**
1. Switch to Calliope Mini.
2. Click on Robot Configuration.
3. It is in German.

**Expected behavior**
 - The labels should be in the language that the user has selected.

**Screenshots**
 - 
![Capture](https://user-images.githubusercontent.com/44456350/72660175-ee86cc80-39ef-11ea-9b17-e9a099dd8eb2.PNG)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
Thanks! The images will be replaced by actual configurations with #109.
