### ISSUE TITLE
Calliope: Compass Sensor Input

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#572]
**Describe the bug**
 - The slider for the compass sensor of calliope is difficult to be accurate with.

**To Reproduce**
1. Switch to Calliope.
2. Open Robot's view.
3. Use the compass sensor slider to get the value to a number like 128.

**Fix**
 - An input box that allows the user to input a number.

**GIF**
 - 
![Screen Recording 2020-01-18 at 12 51 05 68 PM](https://user-images.githubusercontent.com/44456350/72660258-42de7c00-39f1-11ea-9f62-318f270288d5.gif)

**Additional Information**
The value shown does not change dynamically with the slider as well.

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by rbudde** [comment]
works nice.
