### ISSUE TITLE
Incorrect Robot Information in Welcome Screen

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#582]
**Describe the bug**
 - When the information for some robots is opened from the welcome note in the lab, it either redirects to the German version of the manufacturer's website or redirects to a closed website.

**Robot List**
Sensebox
Bot'n Roll
WeDo
BOB3
NXT
Micro:Bit

**To Reproduce**
1. Go to the welcome note.
2. Click on the "_i_" in SenseBox. 
3. See website in German.

**Expected behavior**
 - It should redirect to the manufacturer's website in the language the user has selected.

**GIF**
 - 
![Screen Recording 2020-01-18 at 05 01 59 30 PM](https://user-images.githubusercontent.com/44456350/72663071-49cab600-3a14-11ea-902f-72e0dd8824e3.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
As we have most of our users in Germany the best solution would actually be a link based on the selected language.

**Comment by nishanth1232** [comment]
@boonto 
But, the user cannot select the language in the welcome screen since it is the first screen to open. So, a redirection to the English website should be fine I think. If there is a German version of the website, the user can switch to it as the manufacturer's website will probably have an option to do so.

**Comment by boonto** [comment]
The initial language is the one set by the browser or operating system.

**Comment by nishanth1232** [comment]
Made the changes in the 'Expected Behaviour' Section.

**Comment by boonto** [comment]
Thanks :)

**Comment by boonto** [comment]
Fixed in previous release.
