### ISSUE TITLE
Calliope: Different Gesture Positions

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#583]
**Describe the bug**
 - In the calliope simulation, if the robot view is opened and the order of the gestures is checked, it is different to that of the order of gestures in the gesture sensor.

**To Reproduce**
1. Switch to Calliope
2. Click on robot's view in simulation.
3. Check order of gestures.
4. Check order of gestures in gesture sensor.

**Expected behavior**
 - The order of gestures should be the same in both the robot's view and gesture sensor.

**GIF**
 - 
![Screen Recording 2020-01-18 at 05 07 39 66 PM](https://user-images.githubusercontent.com/44456350/72663147-163c5b80-3a15-11ea-98ec-8cb707e2d9d9.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by iamyashm** [comment]
Hi. How do I edit the gesture menu in the robot's view?
