### ISSUE TITLE
NXT: Missing Sensor Block

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#587]
**Describe the bug**
 - The HiTechnic Color Sensor of the NXT robot is not present as a block in the sensors category.

**To Reproduce**
1. Switch to NXT.
2. See the sensor's list in Robot Configuration.
3. See the sensor's list in the program.
4. See missing sensor.

**Expected behavior**
 - Addition of the sensor.

**GIF**
 - 
![Screen Recording 2020-01-18 at 09 12 15 04 PM](https://user-images.githubusercontent.com/44456350/72666366-6b896480-3a37-11ea-96bf-2a3fa1b05e53.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by rbudde** [comment]
sensor visible in both program and configuration.
