### ISSUE TITLE
Calliope: Make the Simulation React to Inputs

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#590]
**Is your feature request related to a problem? Please describe.**
 - In the calliope simulation, if the compass sensor value is changed to a certain value, the robot does not react to it.

**Describe the solution you'd like**
 - When a certain value for the compass sensor is defined, have the robot react to it in some way.

**Describe alternatives you've considered**
 - Make the robot rotate by the same value as the value of the compass sensor.

**Comment by boonto** [comment]
Thanks for the request, but after some discussion we decided against this, as it would make text hard to read. We might reconsider and reopen in the future.
