### ISSUE TITLE
WeDo: Help View in German

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#591]
**Describe the bug**
 - The help view of the WeDo robot is in German.

**To Reproduce**
1. Switch to WeDo.
2. Click on Help View.
3. See Help View in German.

**Expected behavior**
 - Help View should be in English.

**Screenshots**
 - 
![Capture](https://user-images.githubusercontent.com/44456350/72676671-edba6d00-3ab9-11ea-8c80-76956058c28f.PNG)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by bjost2s** [comment]
The help view 's content is generated from our wiki. We track that outside of github. Thank you very much.
