### ISSUE TITLE
MicroBit: Robot Configuration

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#595]
**Describe the bug**
 - The robot configuration of MicroBit only shows its front and labels the parts present in the front only and not the back which contains all the sensors.

**To Reproduce**
1. Switch to MicroBit.
2. Click on Robot Configuration.
3. See only front side.

**Expected behavior**
 - Both sides should be shown along with labels in the robot configuration.
Such a picture can be found in the manufacturer's website:
 
![image](https://user-images.githubusercontent.com/44456350/72683098-56293e80-3afa-11ea-81e5-fee657973c22.png)

**Screenshots**
 - 
![Capture](https://user-images.githubusercontent.com/44456350/72683067-1c583800-3afa-11ea-959d-86f793894f87.PNG)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
Thanks, this will be solved with the configuration that will be added in the course of #109.
