### ISSUE TITLE
MicroBit: Missing Sensor

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#596]
**Describe the bug**
 - According to the manufacturer(https://microbit.org/guide/features/), the MicroBit robot has a light sensor in it but the option for the sensor is not available in the lab.

**To Reproduce**
1. Switch to MicroBit.
2. Click on Sensor's category.
3. See missing light sensor.

**Expected behavior**
 - Availability of light sensor in the sensor's list.

**Screenshots**
 - 
![Capture](https://user-images.githubusercontent.com/44456350/72683175-f97a5380-3afa-11ea-85d5-605c24a90820.PNG)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by rbudde** [comment]
works. But the light sensor returns always 100% light. It should be possibile to set the value in the sensor data panel in the same way as for other sensors.

**Comment by bjost2s** [comment]
Please try to hover with the mouse over the led matrix, the value is then 50 (like shadowed) , if you touch down with the mouse on the led matrix, light becomes brighter and the value is 150. This was the first sensor implemented in the simulation (no extra panel available at that time ).
