### ISSUE TITLE
Edison: No Robot Configuration Block

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#600]
**Describe the bug**
 - According to the manufacturer (https://meetedison.com/edison-robots-sensors/), the Edison robot has detachable wheels but in the lab, the robot cannot be configured to have only one wheel attached to it.

**To Reproduce**
1. Switch to Edison.
2. Click on Robot Configuration.
3. See that the robot cannot be configured.

**Expected behavior**
 - A robot configuration menu that lets the user detach/attach wheels.

**Screenshots**
 - 
![Capture](https://user-images.githubusercontent.com/44456350/72683587-a1455080-3afe-11ea-8364-25163ecc15fb.PNG)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
This should be covered in #109.
