### ISSUE TITLE
Lab Shows Project Information in German

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#601]
**Describe the bug**
 - In the lab, if the help button is clicked and the 'about the Open Roberta Project' option is clicked, it opens a website in German.

**To Reproduce**
1. Go to the lab.
2. Click on the 'Help' button.
3. Click on 'about the Open Roberta Project' option.
4. See page in German.

**Expected behavior**
 - Page should be in English.

**GIF**
 - 
![Screen Recording 2020-01-19 at 09 14 11 13 PM](https://user-images.githubusercontent.com/44456350/72683809-b0c59900-3b00-11ea-98fe-ffdaedd821b7.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by rohit-bindal** [comment]
I'll work on this!

**Comment by boonto** [comment]
Thanks for the find, will be tracked in another issue tracker.
