### ISSUE TITLE
Addition of Example Programs

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#602]
**Is your feature request related to a problem? Please describe.**
 - There are no example programs that can be loaded up instantly in the lab. They have to be created from "https://jira.iais.fraunhofer.de/wiki/pages/viewpage.action?pageId=31654972"

**Describe the solution you'd like**
 - Addition of example programs to the example programs list.

**Describe alternatives you've considered**
 - The same programs from "https://jira.iais.fraunhofer.de/wiki/pages/viewpage.action?pageId=31654972" can be added in.

**Comment by boonto** [comment]
Thanks! Example programs are in the works, but tracked in another issue tracker.
These programs are actually just the programs of a special user and will be in the database directly, no code changes needed.
