### ISSUE TITLE
Edison: Robot Configuration Schematic

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#605]
**Describe the bug**
 - The robot configuration of Edison has the top of the robot labelled, but the picture of the bottom of the robot containing the power switch and line tracking sensor is not shown.

**To Reproduce**
1. Switch to Edison.
2. Click on Robot Configuration.
3. See that only the top of the robot is shown and labelled.

**Expected behavior**
 - Both the top and bottom of the robot should be labelled.
It should look like this:

![image](https://user-images.githubusercontent.com/44456350/72684452-91316f00-3b06-11ea-8aac-b1e5814ef691.png)

![image](https://user-images.githubusercontent.com/44456350/72684462-9f7f8b00-3b06-11ea-867e-90980fdd5385.png)

**Screenshots**
 - 
![image](https://user-images.githubusercontent.com/44456350/72684482-c3db6780-3b06-11ea-9cea-1858f767b12e.png)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
Just the power switch is missing, which is not a huge problem. I think the real problem is that it is only available in german.

**Comment by nishanth1232** [comment]
I guess this issue can be closed if it is not a problem. It is related to #571
