### ISSUE TITLE
Deleting source code in source code editor causes server error

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#611]
**Describe the bug**
 - In the source code editor, if the code is deleted, and you try to build the program, a server error is produced.

**To Reproduce**
1. Create a new Nepo program
2. Open the source code editor
3. Delete all the current code in the editor
4. Click on the 'Build' button
5. See error

**Expected behavior**
 - A message that says 'Build failed' along with the correct error message.

**Screenshots**
 - 
<img width="1280" alt="Screen Shot 2020-01-20 at 2 30 31 PM" src="https://user-images.githubusercontent.com/9400738/72712628-6fc99500-3b91-11ea-9b99-3f1228a133d3.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional Context**
This issue is present in EV3 leJOS

**Comment by rbudde** [comment]
works with a sensible error message
