### ISSUE TITLE
Documentation View: Font Size Does Not Work

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#617]
**Describe the bug**
 - In the documentation view, if the font size is changed, the font does not change.

**To Reproduce**
1. Go to the lab.
2. Click on Documentation View.
3. Switch to different font sizes and check the font.
4. See the bug.

**Expected behavior**
 - Font size should change.

**GIF**
 - 
![Screen Recording 2020-01-21 at 10 40 58 08 AM](https://user-images.githubusercontent.com/44456350/72777120-968fd600-3c3a-11ea-8fc9-bcc31f53e306.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
Merged with #618.
