### ISSUE TITLE
Documentation View: Font Color/Size Does Not Work

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#618]
**Describe the bug**
 - In the documentation view, if the font color/size is changed, the font does not change.

**To Reproduce**
1. Go to the lab.
2. Click on Documentation View.
3. Switch to different font colors/sizes and check the font.
4. See the bug.

**Expected behavior**
 - Font color/size should change.

**GIF**
 - 
![Screen Recording 2020-01-21 at 10 43 16 87 AM](https://user-images.githubusercontent.com/44456350/72777225-ef5f6e80-3c3a-11ea-9413-8a00874abc72.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
A text needs to selected beforehand, then the selected changes will be applied to the selected text and the text written afterwards.

**Comment by rohit-bindal** [comment]
I've fixed #593 issue opened by you. Have a look!
And I'll work on this issue also :)

**Comment by boonto** [comment]
This seems to be a bug of the WYSIWYG library we currently use. A fix in that or using another library entirely would be necessary. We might reopen in the future.
