### ISSUE TITLE
Documentation View: Addition of Font Size Input Box

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#619]
**Is your feature request related to a problem? Please describe.**
 - In the documentation view, the font size can only be changed to three options.

**Describe the solution you'd like**
 - Addition of more font sizes.

**Describe alternatives you've considered**
 - An input box or drop-down list through which the user can type/select font size.

**Comment by boonto** [comment]
This would be a nice addition, but requires a lot of changes to the WYSIWYG library we currently use or another library entirely. As this is such a niche feature we will not work on this for now. We might reopen in the future.
