### ISSUE TITLE
Documentation View: Addition of Font Colors

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#620]
**Is your feature request related to a problem? Please describe.**
 - In the documentation view, the user can only select upto six different font colors.

**Describe the solution you'd like**
 - Addition of more font colors to the list.

**Describe alternatives you've considered**
 - An RGB Mixer through which the user can create their own colors and change the font to that color.

**Comment by boonto** [comment]
This would be a nice addition, but requires a lot of changes to the WYSIWYG library we currently use or another library entirely. As this is such a niche feature we will not work on this for now. We might reopen in the future.
