### ISSUE TITLE
Documentation View: Bullet List and Number List Cannot Be Used Together

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#621]
**Describe the bug**
 - In the documentation view, the bullet list and number list cannot be used together. For example, if a list has to be made with a title in number list and subtitles in bullet list, it cannot be done.

**To Reproduce**
1. Go to documentation view.
2. Create a title with the number list.
3. Create subtitles with the bullet list.
4. Try to create another title with the number list.

**Expected behavior**
 - The number list should show '2' but shows '1'

**GIF**
 - 
![Screen Recording 2020-01-21 at 10 57 59 51 AM](https://user-images.githubusercontent.com/44456350/72777809-ebcce700-3c3c-11ea-9619-770696f9682d.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
This would be a nice addition, but requires a lot of changes to the WYSIWYG library we currently use or another library entirely. As this is such a niche feature we will not work on this for now. We might reopen in the future.
