### ISSUE TITLE
Documentation View: Addition of Font Types

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#622]
**Is your feature request related to a problem? Please describe.**
 - In the documentation view, the font type cannot be changed.

**Describe the solution you'd like**
 - A box which changes font type.

**Describe alternatives you've considered**
 - A drop-down list which changes font type.

**Comment by boonto** [comment]
This would be a nice addition, but requires a lot of changes to the WYSIWYG library we currently use or another library entirely. As this is such a niche feature we will not work on this for now. We might reopen in the future.
