### ISSUE TITLE
No Robot-Specific Help Views

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#623]
**Describe the bug**
 - Robot-specific help views are not present in the lab which makes it confusing to understand them. For example, for micro:bit, if the help view is checked, under 'action' it shows categories that are not even present in it. Another example is that under 'gesture active?', it describes the robot as calliope.

**To Reproduce**
1. Go to Micro:Bit
2. Click on Help View.
3. See that it describes another robot.

**Expected behavior**
 - A Micro:Bit specific Help View

**GIF**
 - 
![Screen Recording 2020-01-21 at 11 06 24 14 AM](https://user-images.githubusercontent.com/44456350/72778183-25522200-3c3e-11ea-9ba8-a3cff549472f.gif)

**Additional Information**
It's worth checking the 'help' view of other robots as well for inconsistencies. Also, some robots in the lab such as BOB3 do not have a Help view to describe what each block does. A 'help' view should be added to these robots (or) A button that redirects the user to the manufacturer's robot guide. The help view of basic blocks can be added from other robots while those specific to the robot can be added from the manufacturer's website.

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by bjost2s** [comment]
The help view 's content is generated from our wiki. We track that outside of github. Thank you very much.
