### ISSUE TITLE
Pressing 'Help' Does Not Do Anything

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#624]
**Describe the bug**
 - In the lab, pressing 'Help' on certain blocks does not do anything.

**To Reproduce** (One Example)
1. Go to the lab.
2. Click on images.
3. Spawn the 'shift image' block, right-click it, and press 'Help'
4. See incorrect redirection.

**Expected behavior**
 - It should redirect to the correct title in the 'Help' View.

**GIF**
 - 
![Screen Recording 2020-01-21 at 11 14 24 98 AM](https://user-images.githubusercontent.com/44456350/72778524-394a5380-3c3f-11ea-9a66-2ced9a9bc2ad.gif)

**Additional GIF's**

- EV3: Configuration Block
![72660044-47556580-39ee-11ea-8e34-51b37850bfde](https://user-images.githubusercontent.com/44456350/72795852-55142080-3c64-11ea-881c-d0514126d154.gif)

- Arduino: Configuration
![72683283-f6339780-3afb-11ea-8bb0-c7bfc8be78c2](https://user-images.githubusercontent.com/44456350/72795932-7412b280-3c64-11ea-8a12-b6273c14d042.gif)

- Color Blocks
![72776947-ee7a0d00-3c39-11ea-8b26-ff6a02d4b5b9](https://user-images.githubusercontent.com/44456350/72795981-8b51a000-3c64-11ea-825c-af9f702b26a5.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by nishanth1232** [comment]
#570 
#597 
#616

**Comment by bjost2s** [comment]
The help view 's content is generated from our wiki. We track that outside of github. Thank you very much.
