### ISSUE TITLE
Custom Background Options

### ISSUE THREAD

**Issue by RohanCheri** [OpenRoberta/openroberta-lab#625]
**Is your feature request related to a problem? Please describe.**
 - Currently, when a custom background is uploaded, there are no options to customize it

**Describe the solution you'd like**
 - Allow the user to choose whether or not they would like the robot to produce drawable lines on the background (similar to how they do on specific backgrounds)

**Additional context**
 - Future Options: Also give the user customizable options to change the color and width of the robot's track.

**Comment by boonto** [comment]
Thanks for the request, we are planning to implement this feature in a general way, independent of the background. It will be handled in its own issue in the future.
