### ISSUE TITLE
Dislike option in gallery causes server error

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#629]
**Describe the bug**
 - When the dislike option is double clicked, a server error is produced.

**To Reproduce**
1. Go to the gallery
2. Double click the dislike option.
3. See error

**Expected behavior**
 - The server error should not be produced.

**Screenshots**
 - 
<img width="1270" alt="Screen Shot 2020-01-21 at 7 05 57 PM" src="https://user-images.githubusercontent.com/9400738/72809921-a59a7680-3c82-11ea-9a97-a16455080e39.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional context**
 - When the dislike option is clicked once, some time is taken for it to change to 'like'. However, in this case no server error is produced.

**Comment by boonto** [comment]
The server error does not show up anymore.
