### ISSUE TITLE
Stop option does not work 

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#630]
**Describe the bug**
 - The stop option does not work.

**To Reproduce**
1. Create a new EV3 program
2. Open the simulation
3. Start the simulation
4. Open the background navigation dropdown.
5. Click on the stop option
6. See error

**Expected behavior**
 - The simulation should stop.

**Screenshots**
 - 
![gif-issue1](https://user-images.githubusercontent.com/9400738/72811671-1d1dd500-3c86-11ea-88a0-21c945da9c7d.gif)

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional context**
 - Additional information for the dropdown options should be given through a tooltip.

**Comment by KevinL10** [comment]
@boonto Is the purpose of the stop button to stop the program? If so, can we export the function of the "start the program in simulation" and use it for the stop button?

**Comment by boonto** [comment]
I believe it should have the same behaviour as clicking the stop button in the bottom left of the simulation, which appears while the program is running.

**Comment by boonto** [comment]
Sorry again, the whole menu should be removed, see #745.
