### ISSUE TITLE
'Back' option does not work

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#631]
**Describe the bug**
 - The 'Back' option in the background navigation dropdown does not work.

1. Create a new EV3 program
2. Open the simulation
3. Open the background navigation dropdown (simulation scene shortcuts)
4. Change the backgrounds using the background navigation view.
5. Click on the 'Back' option
6. See error

**Expected behavior**
 - The background should switch to the previous background.

**Screenshots**
 -
![issue2](https://user-images.githubusercontent.com/9400738/72812338-5145c580-3c87-11ea-94dc-b3ba66d317c4.gif)

**Device information**
 - Type : Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional context**
More information should be provided on the function of these options in the form of a tooltip or help option.

**Comment by KevinL10** [comment]
Could I create a stack variable and add to the stack everytime there is a new background, and pop from the stack everytime the back button is pressed? And if the stack has size 0 then the back button should be 'disabled' and not be able to be clicked? @boonto

**Comment by boonto** [comment]
We decided it would be best to just remove the back button, as it does not fit with the current usage of the simulation.

**Comment by boonto** [comment]
Sorry for the back and forth but we decided to remove the whole menu, see #745.
