### ISSUE TITLE
Documentation View: Have Special Notations for Variables

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#635]
**Is your feature request related to a problem? Please describe.**
 - In the documentation view, there are no special notations for describing variables in the program.
It would be nice if variables were shown differently than normal text to help understand the program better. Something like `Variable` would work.

**Describe the solution you'd like**
 - An option to distinguish variables.

**Describe alternatives you've considered**
 - A list containing all the defined variables which can be selected and added to the documentation.

**Comment by boonto** [comment]
This would be a nice addition, but requires a lot of changes to the WYSIWYG library we currently use or another library entirely. As this is such a niche feature we will not work on this for now. We might reopen in the future.
