### ISSUE TITLE
Arduino: Sensor "No Port" Configuration Not Showing Error

### ISSUE THREAD

**Issue by RohanCheri** [OpenRoberta/openroberta-lab#636]
**Describe the bug**
 - When running the Arduino robot, the user is able to open the code view/compile the code without any errors even when the sensor port is not recognized / it hasn't been added to the configuration file.

**To Reproduce**
1. Go to an Arduino robot
2. Add a "Show on serial monitor" block and attach any sensor block to it
3. Observe that there is no port for the sensor
4. Open the code view/compile the code and observe that no error occurs

**Expected behavior**
 - For the program to throw an error and indicate that the configuration is missing.

**Screenshots**
![Infared Sensor](https://user-images.githubusercontent.com/34838212/72820955-cee4e380-3c3d-11ea-92c1-f22ca82a0a1e.gif)
![Other Sensor](https://user-images.githubusercontent.com/34838212/72820957-cee4e380-3c3d-11ea-9a6f-709d471551e7.gif)

**Device information**
 - Type Desktop
 - OS: Windows 10
 - Browser Chrome 79

**Additional context**
 - If a motor block is attempted to be compiled without a port, the program properly throws an error.

**Comment by boonto** [comment]
This seems to have been mostly fixed beforehand, the only missing blocks were "get value sensor" and "write value actuator".

**Comment by bjost2s** [comment]
works fine now, also for the named blocks above!
