### ISSUE TITLE
WeDo: Missing Motion Sensor

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#639]
**Describe the bug**
 - For the WeDo robot, the motion sensor is missing from the sensor list in robot configuration and the programming block list. According to "http://www.legoengineering.com/wedo-sensors/", the WeDo robot contains a motion sensor that is an active IR sensor. So, instead of adding the motion sensor separately, the current IR sensor can be programmed to detect motion as well as distance. The block can be taken from the calliope robot.

**To Reproduce**
1. Switch to WeDo.
2. Click on Robot Configuration.
3. See missing motion sensor.

**Expected behavior**
 - Availability of the motion sensor for WeDo.

**Screenshots**
 - 
![image](https://user-images.githubusercontent.com/44456350/72822875-d685a600-3c98-11ea-959d-8d7d08b9f112.png)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
The motion sensor is the "infrared" sensor, so we already have it implemented.
