### ISSUE TITLE
Block "in list get # variable" doesn't work

### ISSUE THREAD

**Issue by the-matzup** [OpenRoberta/openroberta-lab#64]
**Describe the bug**
While using the block "in list get #" with a variable, it will create an error-message, if i want to run on EV3 leJOS 0.9.0 

**To Reproduce**
1. Create List
2. Create a number-variable
3. Use "in list get # variable" wherever you want
4. Connect to an EV3
5. Click on "run"
6. See the error-message

**Expected behavior**
Run the Code on EV3 without errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47818886/53331760-f29a8f00-38f1-11e9-8821-37fa2c47e8df.png)

**Device information**
 - Chrome, MacOS, 
- EV3 leJOS 0.9.0 (2018-04-11), OpenRoberta 2.6.2,

**Additional context**
- Works fine without errors in simulation view!
- Doesn't work to run on real EV3.

**Comment by boonto** [comment]
No errors when running a program with "in list get # variable" on the EV3.
