### ISSUE TITLE
Some Robots Do Not Have the RGB Mixer Block

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#640]
**Describe the bug**
 - In the lab, some robots do not have the RGB Mixer Block (such as WeDo).

**To Reproduce**
1. Switch to WeDo.
2. Click on Colors Category
3. See missing block.

**Expected behavior**
 - Availability of the RGB Mixer Block.

**Screenshots**
 - 
![image](https://user-images.githubusercontent.com/44456350/72823717-23b64780-3c9a-11ea-8999-bae5bb1b2f9e.png)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
The colours each of the robots support are determined by the specific API (e.g. specific colours in an Enum). Each robot should already support all capabilities available on the robot itself.
