### ISSUE TITLE
Addition of Tutorials For Robots

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#641]
**Is your feature request related to a problem? Please describe.**
 - Currently, there are no tutorials for robots in the lab.

**Describe the solution you'd like**
 - Addition of tutorials such as 'Your first program' to the tutorial list.

**Describe alternatives you've considered**
 - Addition of tutorials from "https://jira.iais.fraunhofer.de/wiki/display/ORInfo/Programming+EV3"
under 'Your first program'

**Comment by boonto** [comment]
Thanks for the suggestion, this is currently being worked on and tracked in a different system. I'll close this as it does not make sense to track it in both systems.
