### ISSUE TITLE
Calliope: Missing Sensor

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#652]
**Describe the bug**
 - For the calliope robot, the magnetometer sensor is missing in the sensors category.
According to "https://en.wikipedia.org/wiki/Calliope_mini", it contains a magnetometer sensor.

**To Reproduce**
1. Switch to Calliope.
2. Click on Sensors.
3. See missing sensor.

**Expected behavior**
 - Availability of magnetometer sensor.

**Screenshots**
 - 
![image](https://user-images.githubusercontent.com/44456350/72832180-641dc180-3caa-11ea-9280-331308eb696a.png)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
The compass sensor is the magnetometer.
