### ISSUE TITLE
Calliope: Does Not Show Models in Welcome Note

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#653]
**Describe the bug**
 - The calliope robot, when selected in the welcome note, automatically selects one model and does not show the option for selecting the three different models. This is present in EV3 and Arduino but not in Calliope.

**To Reproduce**
1. Go to the lab.
2. Click on Calliope in the Welcome Note.
3. See that it automatically selects a model.

**Expected behavior**
 - It should show the list of available models similar to that of EV3 and Arduino.

**GIF**
 - 
![Screen Recording 2020-01-22 at 12 11 03 61 AM](https://user-images.githubusercontent.com/44456350/72832903-bf9c7f00-3cab-11ea-965e-991b9a0df1aa.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
This is intended behaviour as most of our users use the same Calliope.
