### ISSUE TITLE
Addition of a Button To Edit Source Code

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#654]
**Is your feature request related to a problem? Please describe.**
 - The source code for a program cannot be edited directly from the source code view. The source code editor should be opened separately.

**Describe the solution you'd like**
 - A button to open source code editor within source code view.

**Describe alternatives you've considered**
 - A button that allows the user to edit the code directly.

**Comment by boonto** [comment]
During implementation we talked about this, but decided against it.
As changes in the source code cannot be conveyed back to the blocks we wanted to have a clear separation between block workspace and source editor workspace.
