### ISSUE TITLE
Addition of Separate Categories For Different Sensors

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#655]
**Is your feature request related to a problem? Please describe.**
 - The sensors for a robot are all under one category and are not categorized based on their features. 

**Describe the solution you'd like**
 - A sensor's category that divides into different categories for different sensors. For example, there could be three categories:

Robot Sensors consisting of the robot's sensors
Clickable's consisting of buttons and clickable/interact-able sensors.
Timers

**Describe alternatives you've considered**
 - Have a feature that categorizes them for all robots.

**Comment by boonto** [comment]
We would like to categorize them as well, but currently there is really no nice categorization possible for the sensors.
Maybe in the future (if we have a lot more sensors, and categories can be well defined) we might think about this again and reopen.
