### ISSUE TITLE
EV3: The Calibrate Block is Not Considered As a Blocking Block

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#662]
**Describe the bug**
 - For the EV3, the 'calibrate HT compass sensor' block is not considered as a blocking block even though it takes 40 seconds to complete.

**To Reproduce**
1. Switch to EV3.
2. Spawn the 'calibrate HT compass sensor' block.
3. See that it is not considered as a blocking block.

**Expected behavior**
 - A warning showing that it is a blocking block.

**GIF**
 - 
![Screen Recording 2020-01-22 at 12 34 37 53 PM](https://user-images.githubusercontent.com/44456350/72872530-99aac500-3d13-11ea-8fe6-85e8d3bde4d5.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by iamyashm** [comment]
I would like to work on this. Is this a purely frontend bug?

**Comment by boonto** [comment]
Sure, block related changes need to be done over in our [blockly](https://github.com/OpenRoberta/blockly) repo and then built as described and copied over to the static resources of the server.

For first quick tests you can use your browser developer tools to edit the files and immediately see the changes.

**Comment by iamyashm** [comment]
I've figured out code changes. Where can I find the build instructions for the blockly repo?

**Comment by boonto** [comment]
It was previously documented in the upstream repo or the link, but as that changed a lot we should add it to our repo.
You can just run `python build.py` in the blockly directory while having the closure library on the same level as the blockly directory.
![image](https://user-images.githubusercontent.com/7438960/76310594-5ca08f00-62cf-11ea-9752-f9322229325f.png)

**Comment by iamyashm** [comment]
I tried that but build.py in running into an exception.

![errorinbuild](https://user-images.githubusercontent.com/43318499/76311562-40184d00-62f7-11ea-9af1-0c26791454ef.png)

**Comment by boonto** [comment]
You should be able to try again, sometimes the build server is unreliable.

**Comment by iamyashm** [comment]
Should I directly make the required change in staticResources/blockly instead of building and copying, since doing so seems to be working locally?

**Comment by iamyashm** [comment]
Yes, it worked. Thank you.

**Comment by boonto** [comment]
Fix merged in https://github.com/OpenRoberta/blockly/commit/a7b5caffd53f9879e88d2f10f4dc630b6ebf592a. Is resolved once blocky is rebuilt.
