### ISSUE TITLE
Differentiate Between Simulation Blocks and Other Blocks

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#663]
**Is your feature request related to a problem? Please describe.**
 - In the lab, the blocks that are not supported in the simulation are not differentiated from the blocks that support it.

**Describe the solution you'd like**
 - A button that filters out all blocks that are not supported in the simulation.

**Describe alternatives you've considered**
 - A mode switcher that switches modes from 'Simulation Mode' to 'Robot Mode'.

**Comment by bjost2s** [comment]
We mainly concentrate on real robots, so adding warnings to the not supported blocks in the simulation should be enough.
