### ISSUE TITLE
'Show Sensor Data' Shows Sensor Data For Disconnected Blocks

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#664]
**Describe the bug**
 - The 'show sensor data' checkbox in the start block is supposed to show sensor data of connected blocks only but it shows sensor data of disconnected blocks as well.

**To Reproduce**
1. Go to the lab.
2. Check the 'show sensor data' checkbox.
3. Disconnect all sensors except any one sensor.
4. See that it shows the reading of disconnected sensors.

**Expected behavior**
 - It should say 'Not Connected' for readings of disconnected sensors.

**GIF**
 - 
![Screen Recording 2020-01-22 at 12 47 50 20 PM](https://user-images.githubusercontent.com/44456350/72873288-754fe800-3d15-11ea-8290-ff0712dd86fb.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
The "show sensor data" is a functionality that is mainly supported on the real robots. It does not have any correlation to the "sensor view" in the simulation.
