### ISSUE TITLE
Embed program simulations

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#666]
**Is your feature request related to a problem? Please describe.**
 - It would be great if there was an embed feature which would allow users to embed the simulation of their program in other web pages.

**Describe the solution you'd like**
 - When you go to the 'Program' dropdown in the menu bar, there should be an 'Embed' option which provides the corresponding code for their simulation. This can be used to embed the simulations of programs in other web pages.

**Additional context**
 - A share feature which enables users to share programs through social media would also be nice.

**Comment by bjost2s** [comment]
Thank you, but we do not want to support this feature.
