### ISSUE TITLE
Different Robots Have Different Blocks for Beginner Mode

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#669]
**Describe the bug**
 - The robots in the lab have different blocks in beginner mode. For example, the WeDo robot has the 'random integer' block in beginner mode whereas the EV3 robot does not.

**To Reproduce**
1. Switch to WeDo and check available beginner blocks.
2. Switch to EV3 and check available beginner blocks.
3. See the difference.

**Expected behavior**
 - The same blocks in beginner mode.

**Screenshots**
 - EV3:
![image](https://user-images.githubusercontent.com/44456350/72889478-c53ea700-3d35-11ea-9a91-4d4d1431daf3.png)

- WeDo:
![image](https://user-images.githubusercontent.com/44456350/72889416-a6401500-3d35-11ea-94f6-0d3a9a9887a5.png)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by KevinL10** [comment]
For other robot types the random integer block is in expert. In WeDo and mbed, it is in both expert and beginner, so removing that block from beginner would make more sense than adding it to Ev3.

**Comment by boonto** [comment]
This is actually intended due to some requests from the users' side. Mbed and WeDo should have these blocks in the beginner toolbox.
