### ISSUE TITLE
Wedo: Can't select note on ipad

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/openroberta-lab#67]
**Describe the bug**
 - you can't select another not than c1 on Ipad

**To Reproduce**
1. Open the open roberta mobile app
2. get the play note block
3. try to select another note
4. you can't.

**Expected behavior**
 - You can select another note

**Screenshots**
 - If applicable, add screenshots to help explain your problem.
![grafik](https://user-images.githubusercontent.com/25958792/49739033-2a9a1a80-fc91-11e8-8124-11321cc1345e.png)

**Device information**
 - Thorstens IPad 4
 - Open Roberta Mobile App Version 1.0.0

**Comment by philippmaurer** [comment]
I just reproduced this bug on the Roberta Mobile App and mobile Safari.
iPad 4th. Gen.
iOS: 10.3.3 (14G60)

**Comment by bjost2s** [comment]
solved for mobile safari, web view in open roberta app can't be changed anymore.
