### ISSUE TITLE
Documentation View: GIF's and Images Cannot Be Re-positioned or Re-sized

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#675]
**Describe the bug**
 - In the documentation view, when a GIF/Image is added, there is no option to re-size it or re-position it.

**To Reproduce**
1. Go to documentation view in the lab.
2. Paste a GIF/Image.
3. See that it cannot be re-sized or re-positioned.

**Expected behavior**
 - A GIF/Image that can be re-positioned and re-sized.

**GIF**
 - 
![Screen Recording 2020-01-22 at 09 06 24 55 PM](https://user-images.githubusercontent.com/44456350/72908139-17de8a00-3d5b-11ea-9637-9a8b38cde0d0.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
Actually, dragging images into the view should not be possible at all, see #744.
