### ISSUE TITLE
EV3 type checking in nested ternary operator is not working

### ISSUE THREAD

**Issue by rhasel4s** [OpenRoberta/openroberta-lab#68]
**Describe the bug**
In the nested operator the true and false condition can have different types, for example boolean and float. The program runs fine in simulation but cannot be compiled

**To Reproduce**
1. Create a boolean variable and assign a value 
2. Click on 'logic'
3. Add two ternary operators 
4. Add to the nested operator a boolean and a float value as the return type

**Expected behavior**
 - it should not allow adding of different variables. Either detach the whole nested block or refuse to add the variable

**Screenshots**
 ![type_check_error](https://user-images.githubusercontent.com/15631864/53099365-f1e6af00-3525-11e9-8cb2-339a8960c173.png)

**Device information**
 - Type [Desktop]
 - OS: OS: [Linux]
 - Browser[firefox 64.0]

[ev3_logic_test_compile_error.xml.zip](https://github.com/OpenRoberta/robertalab/files/2885098/ev3_logic_test_compile_error.xml.zip)

**Comment by boonto** [comment]
Wrong types cannot be connected to ternary operators anymore.
