### ISSUE TITLE
Addition of Prime and Composite Number Checking to 'Check x is ...' Block

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#681]
**Is your feature request related to a problem? Please describe.**
 - There is no option to check whether a number is prime or composite for the 'check x is ...' block in the lab.

**Describe the solution you'd like**
 - Addition of the prime and composite options in the drop-down list.

**Additional context**
 - This would help in creating programs that involve the process of checking prime or composite numbers such as finding HCF and LCM.

**Comment by boonto** [comment]
There is a "is prime" block for all robots that support it.
![image](https://user-images.githubusercontent.com/7438960/72968942-d256a700-3dc4-11ea-841a-da70c0c2f4b7.png)
I don't think "is composite" is necessary as that can be constructed easily with the "is prime" block.
