### ISSUE TITLE
Addition of 'Re-position' Button to Simulation View

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#682]
**Is your feature request related to a problem? Please describe.**
 - In the simulation view, robots like Micro:Bit do not have a re-position button like the EV3.

**Describe the solution you'd like**
 - Addition of the button.

**Additional context**
 - When the robot is dragged out of the screen, it cannot be brought back to its original position in any way other than resizing the view which is a bit unconventional.

**Comment by bjost2s** [comment]
Please close and reopen the simulation view to reset the position. We want to avoid more buttons in the simulation view.
