### ISSUE TITLE
Bot'n Roll: Configuration Cannot Be Changed

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#684]
**Describe the bug**
 - For the Bot'n Roll robot, the robot configuration blocks cannot be removed from the main block.

**To Reproduce**
1. Switch to Bot'n Roll.
2. Click on Robot Configuration.
3. Try to disconnect sensors/motors.
4. See that they cannot be disconnected.

**Expected behavior**
 - The sensor's/motors should be removable.

**GIF**
 - 
![Screen Recording 2020-01-23 at 01 32 56 08 PM](https://user-images.githubusercontent.com/44456350/72966410-ea3e2300-3de4-11ea-8aeb-8d114a4f2d18.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment]
As all of the sensors and actors for Bot'n Roll are pretty much static the configuration does not need to be changed. That's why you cannot modify it.
In case it changes or we get additional optional actors/sensors we can look at this again.
