### ISSUE TITLE
Changing the EV3 Display

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#686]
**Is your feature request related to a problem? Please describe.**
 - The EV3 robot display in the lab has a red block at the bottom that does nothing and it is missing the text 'EV3' which the LEGO EV3 has.

**Describe the solution you'd like**
 - Addition of changes to the EV3 Display Block to make it look similar to the LEGO EV3 display.

**Additional context**
 - LEGO EV3 Display:
Ignore the labeling and numbers.
![image](https://user-images.githubusercontent.com/44456350/72970137-fa5a0080-3dec-11ea-942b-c8394cee9eea.png)

- Lab EV3 Display:
![image](https://user-images.githubusercontent.com/44456350/72970174-0a71e000-3ded-11ea-80ba-3b3a7ead4bc6.png)

**Comment by boonto** [comment]
I think the representation is close enough. Using the actual logos could be a trademark/copyright problem.
