### ISSUE TITLE
Nepo: Function behaviour when deleted

### ISSUE THREAD

**Issue by pablopoo** [OpenRoberta/openroberta-lab#69]
**Is your feature request related to a problem? Please describe.**
In a program that use functions. When a function is deleted, all the references to that function in the program are still there.

**Describe the solution you'd like**
-When a function is deleted all the references to that function must be deleted.

**Describe alternatives you've considered**
or throw a warning indicating that the reference(s) must be removed. Is better than a generic "can`t be compiled".

**Additional context**
 
![imagen](https://user-images.githubusercontent.com/13492043/50122049-a10ebd80-0239-11e9-984a-c804c2f26281.png)

**Comment by boonto** [comment]
The function calls are now deleted when the function definition is deleted.
