### ISSUE TITLE
Find liked programs in the gallery

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#690]
**Is your feature request related to a problem? Please describe.**
 - It would be great if there was a feature where users could view all the programs they have liked in the gallery.

**Describe the solution you'd like**
 - An option in the dropdown menu to view so that users can view their liked programs.

**Describe alternatives you've considered**
 -An additional button could be added in the gallery for users to view their liked programs.

**Comment by bjost2s** [comment]
related to #719

**Comment by boonto** [comment]
I added a comment with this feature request to the more general #719.
