### ISSUE TITLE
Background images when sharing to gallery

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#696]
**Is your feature request related to a problem? Please describe.**
A custom background for the program cannot be used along with the program when shared with the gallery.

**To Reproduce**
1. Create a Nepo program. 
2. Upload a custom background (your own simulation background) for that program.
3. Share to gallery
4. The program when viewed from gallery by another user will not have the custom background.

**Describe the solution you'd like**
 - If a user adds a custom background to her program, and shares on gallery, other users who use that program must be able to run the simulation with that same custom background

**Comment by boonto** [comment]
This could lead to huge potential issues regarding copyright.
It would really be a nice feature, but right now this is too problematic.
We might reopen if anything changes.
