### ISSUE TITLE
EV3 and NXT: Entering a decimal value as speed in the drive blocks causes a server error

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#699]
**Describe the bug**
 - When a double is entered as speed in a block from the 'Drive' category, a server error is produced.

**To Reproduce**
1. Create a new EV3 or NXT program
2. Use a block from the drive category
3. Enter a decimal value as speed
4. Open the simulation 
5. See error

**Expected behavior**
 - A server error should not be produced.

**Screenshots**
 - 
<img width="1280" alt="Screen Shot 2020-01-24 at 5 11 17 PM" src="https://user-images.githubusercontent.com/9400738/73066817-159c3d00-3ecd-11ea-9bbf-12f081617faf.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional Context**
This happens for the drive and turn blocks

**Comment by boonto** [comment]
Fixed by Caffetaria.
