### ISSUE TITLE
Robot configuration. My configurations item click.

### ISSUE THREAD

**Issue by pablopoo** [OpenRoberta/openroberta-lab#70]
**Is your feature request related to a problem? Please describe.**
In the list of my saved programs, when a item is clicked anywhere but the action buttons, the program execute the open command. In the "My configurations" list, it doesn't.

**Describe the solution you'd like**
Replicate the behaviour of "my programs". When a item is clicked, execute the open command.

**Describe alternatives you've considered**
 Remove the behavior in "my programs", so the user experience is consistent in both sides.

**Additional context**
Robot configuration - > my configuration -> list item selected.
![imagen](https://user-images.githubusercontent.com/13492043/50699827-b8b2b800-1027-11e9-9532-1af39f65e910.png)

**Comment by boonto** [comment]
Both open when clicked anywhere now.
