### ISSUE TITLE
A Scrollbar should be added!

### ISSUE THREAD

**Issue by rohit-bindal** [OpenRoberta/openroberta-lab#704]
Is your feature request related to a problem? Please describe.
 - It would be great if a Scrollbar appears whenever blocks added covers the complete screen.

Describe the solution you'd like
 - If code is large then general tendency is to press the down arrow key to see the remaining code but it doesn't work here.
![orlll](https://user-images.githubusercontent.com/56409926/73117558-85fa9b00-3f6d-11ea-8d62-36be4a223573.png)

You can see as there is no any Scrollbar and also down arrow key don't work. To see the code below the screen we have to Drag Up which is not quite good in regular use!

**Comment by boonto** [comment]
We have decided at some point to remove the scroll bars to keep a consistent behaviour across platforms. The navigation in the programs will remain by dragging the background.
