### ISSUE TITLE
serial write/read for Calliope, microbit and arduino

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#71]
we need serial write/read for Calliope, microbit and arduino, see #1007

Still missing:
- [x] Write serial implementation in Calliope visitor
- [x] Write serial implementation in Microbit visitor
- [x] Write serial implementation in arduino visitor
- [ ] Write serial implementation in simulation visitor
- [ ] Adding read serial block to all toolboxes
- [ ] Read serial implementation in Calliope visitor 
- [ ] Read serial implementation in Microbit visitor 
- [ ] Read serial implementation in arduino visitor 
- [ ] Read serial implementation in simulation visitor 
- [ ] Tests

**Comment by bjost2s** [comment]
Reopen because several users are asking for serial read(). 

This would add a convenient option to interact with the devices.

**Comment by bjost2s** [comment]
no time to work on it
