### ISSUE TITLE
Calliope support for Tiny Super Lab Motionkit

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#717]
The Tiny Super Lab Motionkit provides "drive" functionality for calliope, very similar to what the calli:bot does, so support should be similar (see motor block with "Calli:bot" port)

Additional information:
https://github.com/tinysuperlab/motionkit

**Comment by rbudde** [comment]
These changes will be deployed today, in spite of the fact, that it is not really clear, how we have to support this kit. I believe, that this is unfortunate.
