### ISSUE TITLE
Adding a custom map inside the menu tab

### ISSUE THREAD

**Issue by RichardBotez** [OpenRoberta/openroberta-lab#720]
- If a user decides to insert a custom map in the simulation, it might as well appear in the top menu next to the original maps as a quick selection option;

- After selecting the map, a new tab can appear under the last official map (Math Scene in this case);

![New_Tab_Scene](https://user-images.githubusercontent.com/34100979/73398011-4f19e180-42ed-11ea-9c6e-5fe0886ea373.PNG)

**Comment by bjost2s** [comment]
Thanks for your suggestion, but we would like to remove this menu item completely.

**Comment by boonto** [comment]
See #745.
