### ISSUE TITLE
Addition of Block Changers

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#724]
**Is your feature request related to a problem? Please describe.**
 - Certain blocks which are identical such as the repeat indefinitely, repeat until and repeat 'x' times and also the if and if else blocks cannot be inter-converted. So if the block type has to be changed, all the blocks inside should be removed and then the new block should be added along with the blocks inside of it.

**Describe the solution you'd like**
 - Addition of an option that can convert identical blocks.

**Describe alternatives you've considered**
 - An option when the block is right-clicked called 'Change Block Type' that changes the type of the block.

**Comment by boonto** [comment]
I think that is a too generic feature request for us. Maybe check over at the [Blockly repo](https://github.com/google/blockly).
