### ISSUE TITLE
Take a tour

### ISSUE THREAD

**Issue by RichardBotez** [OpenRoberta/openroberta-lab#727]
**Describe the bug**
- Opening the gallery tab and starting the "take a tour" function will keep the background and overlap the tutorial.

**To Reproduce**
1. Open the gallery tab;
2. Click on NEPO;
3. Take a tour;
4. See error;

**Expected behavior**
 - The background should change to the EV3 robot;

**Screenshots**
![bug_take a tour](https://user-images.githubusercontent.com/34100979/73479742-3965f400-43a1-11ea-9994-483a46d8c086.PNG)

**Device information**
 - Type Desktop
 - OS: Windows 10
 - Browser Chrome

**Additional context**
- The same problem occurs if I open: my programs, example programs, open/close source code view and open source code editor tab.

**Comment by boonto** [comment]
Now, when starting the tour the view is switched to the program view.
