### ISSUE TITLE
Improve bookmark message wording

### ISSUE THREAD

**Issue by RichardBotez** [OpenRoberta/openroberta-lab#728]
- The bookmark selection box found at the bottom of the NEPO tab does not appear to complete its purpose and the bookmark option cannot be found afterwards.

** Describe the solution you would like **
- A more concise description of this function will be handy.

**Additional context**
![bookmarkissue1](https://user-images.githubusercontent.com/34100979/73483675-81d4e000-43a8-11ea-9ab3-2152df1a1d38.PNG)
![bookmarkissue2](https://user-images.githubusercontent.com/34100979/73483677-81d4e000-43a8-11ea-9826-e097f27ef2c9.PNG)

**Comment by boonto** [comment]
At that point you are supposed to create a bookmark using your browser.
As this cannot be done automatically, we can only do it that way.

Is the message unclear?

**Comment by RichardBotez** [comment]
The bookmark to which it refers is unclear. I think adding "chosen browser bookmark" to the message will help.
