### ISSUE TITLE
Arduino "write value to pin" mutator missing

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#733]
**Describe the bug**
See screenshot, ports for "write value to pin" are not updated with dropdown (mutator is missing), always only analog configuration blocks are evaluated.

**To Reproduce**
create a program with two "analog" pins configured
![image](https://user-images.githubusercontent.com/1613069/73608522-69411180-45c4-11ea-8ff3-e094bc421637.png)

**Expected behavior**
 Dropdowns are available after import (or reload)
![image](https://user-images.githubusercontent.com/1613069/73608584-19167f00-45c5-11ea-9c08-aba862f88b80.png)

**Comment by boonto** [comment]
Dropdowns are available as soon as the actors are added to the configuration.
