### ISSUE TITLE
mBot: Simulation

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#736]
**Describe the solution you'd like**
I would like to have the simulation feature for mBot, equivalent to the NXT and EV3 simulation.

**Describe alternatives you've considered**
No alternative available

**Additional context**
In relation to the NXT and EV3, the mBot is mostly equivalent, without the infrared sensor at its bottom, with which it detects lines on the floor. There are two of these present on the bottom front of the robot, which both give indivdual values.
Was asked through support.

**Comment by bjost2s** [comment]
multiple robot simulation is not implemented yet, see #908
