### ISSUE TITLE
Rewrite simulation code generation and execution in the WeDo style

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#74]
**Is your feature request related to a problem? Please describe.**
 - We have a couple of open issue in simulation execution: #1116, #1053, #1008, #1153, #1003, #1002, #981, #903
**Describe the solution you'd like**
 - Rewrite the code generation and execution like we did it already for WeDo (not used for simulation but for steering/triggering WeDo via bluetooth). With this stack based way we expect to get rid of a couple of issues that we have with the old simulation. Also some issues we cannot fix with the old way.

**Additional context**
 - see and get more information from the [WeDo intepreter project](https://github.com/OpenRoberta/robertalab/tree/master/OpenRobertaParent/WedoInterpreter)

**Comment by rbudde** [comment]
see also #215 for a collection of errors

**Comment by rbudde** [comment]
all errors mentioned here are now linked in #215. This ticket is closed.
