### ISSUE TITLE
Old Logo usage in "about Open Roberta Lab" help popup

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#748]
**Describe the bug**
The "about the Open Roberta Lab" popup still shows the Open Roberta logo.

**To Reproduce**
1. Go to the ORLab
2. Open the help menu
3. Click on "about the Open Roberta Lab"
4. See the old logo

**Expected behavior**
The "new" logo should be shown.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/74665608-53287900-51a0-11ea-9e60-5b2fc3193ebd.png)

**Comment by bjost2s** [comment]
The open roberta lab logo is the actual one! Please undo!

**Comment by bjost2s** [comment]
new logo:
![image](https://user-images.githubusercontent.com/1613069/79836207-1fd8b500-83b0-11ea-8759-895aefada2d9.png)
