### ISSUE TITLE
SIM does not respect the local scope of recursive function calls

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#75]
**Describe the bug**
 - If a function that takes at least one parameter is called recursively with other parameter values, the values for all previous function calls get overriden with that of the last call.
- Only in simulation

**To Reproduce**
1. Go to the open roberta lab and choose either Calliope, NXT or EV3 (or any robot with a simulation)
2. Insert one of the programs of the attached zip or write any program that has recursive function calls and works with different values after the recursive call was triggered.
[ev3_faculty.zip](https://github.com/OpenRoberta/robertalab/files/2941906/ev3_faculty.zip)
3. Run it in the simulation

**Additional context for the attached programs**
 - The normal faculty program (ev3_faculty.xml) always returns 1. 
- The faculty with better bug visibility program returns -1. This shows the problem a bit better. 
While the inital call is called with x = 3, the recursive call gets called with x=-1. Because x is smaller than 1 in the recursive call, it returns 1. This gets multiplied with the initial parameter x then, which should be 3. Instead the returned value (1) is multiplied with -1. This shows, that the inital parameter gets overwritten by the inner call.

**Expected behavior**
 - The local scope of a function call should stay intact, even after the same function gets called during its own execution

**Comment by bjost2s** [comment]
see #74
