### ISSUE TITLE
Gallery improvements

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#752]
the number of programs in the gallery increases. The overview about all the entries is more and more difficult. Possible improvements:

- [x] restrict the programs shown to the robot actually selected (this may be a filter, that can be changed by the user. I'd prefer a hard restriction: why should a Calliope user see Ev3 programs? If he/she wishes to see them, a second tab with another robot is enough)
- [x] add "column" filter (as already supported by bootstrap tables)
- [x] add sorting (as already supported by bootstrap tables)

Issues #349 and #719 and #564 and #690 are related to this issue

**Comment by abhimnc** [comment]
hi, I am a newbie here and want to contribute. This is mentioned as a good first issue. Can anyone guide me on how to proceed further to resolve? Where to look for in the code base?Thanks!

**Comment by boonto** [comment]
Take a look at Bootstrap tables in general, then you can hack around in the `galleryList.controller.js` file to get a feel for the capabilities of the tables.

**Comment by ensonic** [comment]
+1 for having a default filter to the selected robot applied.

**Comment by ykabusalah** [comment]
can i get a shot at this?

**Comment by boonto** [comment]
Sure, what about #557? Should I remove your assignment there?

**Comment by rbudde** [comment]
some improvements have to be done, thus NOT closed.
Nevertheless the gallery is much better now.

**Comment by rbudde** [comment]
Moved to be done improvement to a new issue. Thus can be closed.
