### ISSUE TITLE
Cookie-Disclaimer does not dissappear, but increases the window height instead

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#76]
**Describe the bug**
 - When you accept the cookie disclaimer, the cookie disclaimer moves down. Instead of moving out of the window, the body size is increased accordingly to where the cookie disclaimer moves.
- Because of that behavior, the windows size doubles in its height, creating a scrollbar at the right and allows scrolling on the page.
- This bug only occurs upon first visit, on which the cookies are accepted

**To Reproduce**
1. Choose one of the following browsers: FireFox, Chrome, Safari
2. Visit https://lab.openroberta.org on a private browser window (So that the cookie disclaimer is shown)
3. Select any robot system, so that the welcome note is gone
4. Accept cookies via the button on the cookie disclaimer.

**Expected behavior**
 - The cookie disclaimer moves out of the window. The window size does not change due to that.

**Device information**
 - Browser: Chrome, FireFox, Safari. 
- (Also tested, but it works corretly: Internet Explorer, Edge)

**Additional context**
 - The body needs an "overflow: hidden" or the effect of the cookie disclaimer needs to be removed.

**Comment by boonto** [comment]
Does not happen on Firefox, Chrome or Safari anymore.
