### ISSUE TITLE
C4EV3 does not return compiler errors

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#762]
**Describe the bug**
 - When trying to compile programs with errors for the C4EV3 no compiler errors are returned.

**To Reproduce**
1. Open C4EV3
2. Open Source Code Editor
3. Remove vital code
4. Build
5. Observe that the returned error message is empty

**Expected behavior**
- The compiler errors are shown in the popup.

**Comment by rbudde** [comment]
error messages are shown now
