### ISSUE TITLE
EV3 test block generates incorrect source code

### ISSUE THREAD

**Issue by Heep042** [OpenRoberta/openroberta-lab#763]
**Describe the bug**
The test block is missing parenthesis, thus, when used inside arithmetic operations, incorrect result gets produced

**To Reproduce**
Print out such expression:
test(true, 0, 1) - 1

see that the java code produces something in the lines of:
true ? 0 : 1 - 1

**Expected behavior**
Result of -1, and properly parenthesised java code ((true ? 0 : 1) - 1)

**Comment by iamyashm** [comment]
Hi. I would love to work on this. Could you please assign this to me and, if possible, guide me regarding where I should start exploring the codebase from?

**Comment by boonto** [comment]
Hey, take a look at the code generation visitor for EV3 and the more generic Java visitor. You should be able to find it easily.

**Comment by iamyashm** [comment]
Could @Heep042 please give a test case where the output is not as expected? Because even though the source code generated does not have parentheses, the result of the expression is still as expected.

**Comment by iamyashm** [comment]
Would parenthesising the test block unconditionally be a good solution for this?

**Comment by Heep042** [comment]
It would be the simplest solution with no side-effects and potential bugs in the checks. I would say yes.

**Comment by iamyashm** [comment]
I've changed the code to add parentheses but as a result, a test is failing on build since it expects only 1 pair of parentheses. How do I fix this? Do I need to alter the test itself or is there a way to bypass it so that I can run my code?

**Comment by boonto** [comment]
Yes, you should change the test as well as now the parenthesis are expected to be there all the time.

**Comment by iamyashm** [comment]
Thank you for your help! I've made the necessary changes and submitted a PR.

**Comment by rbudde** [comment]
works as expected
