### ISSUE TITLE
As a teacher I would like to create groups for my classes to be better prepared in the lessons

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#785]
Preconditions: The teacher is logged in and his account is verified. 

- The teacher clicks in the "user" menu the corresponding item
-> The system shows an overview over the groups belonging tho the teacher's account
- The teacher clicks on a "plus" button to create a new group
-> A popup with a form appears
- The teacher fills in the form, name of the group, number of members, ... and confirms it
-> The overview (dashboard) shows now an additional group
- The teacher clicks on the row of the group to get more information
-> The view of the groups provides the teacher more insides of this specific new group, especially the newly created names of the accounts for the students and the corresponding one-time passwords
- The teacher can now export or copy & paste the information to allocate it to the students

Post-conditions: The new group and the corresponding user accounts are created and stored in the database

This procedure can be used as a test case.

**Comment by bjost2s** [comment]
@philippmaurer , currently there is an issue when I delete the user (teacher account) while one of the students is still logged in

1. The teacher can delete his account although he holds accounts for groups with active members
2. The student (while logged in) gets 
![image](https://user-images.githubusercontent.com/1613069/87023651-51effb00-c1d8-11ea-869f-37e06079ad79.png)
instead of a dedicated message about his account which does not exist anymore.

**Comment by rbudde** [comment]
Sorry for the german text ... its C&P from a discussion:
ich finde es SEHR irritierend, dass mein Gruppenaccountname z.B. g:03 ist (siehe Statusinformation) ist, ich aber 03 beim login eingeben muss (und nicht g:03), mein Passwort aber g:03 ist. Der Lehrer sieht ebenfalls in seiner Liste g:03 und wird dem Schüler bestimmt einen falschen Tipp geben, wenn der seine Accountnummer vergessen hat. Mein Vorschlag: im Gruppenlogin 'Name der Gruppe' WEGLASSEN und als Account g:03 eingeben (z.B. Klasse9:Reinhard).
