### ISSUE TITLE
Variable names should be defined properly

### ISSUE THREAD

**Issue by rishabhdeepsingh** [OpenRoberta/openroberta-lab#786]
This bug needs frontend and backend changes.
**To Reproduce**
1. Click on the <kbd>+</kbd> begore the start block on the main page.
2. type with two spaces "<kbd>space</kbd><kbd>space</kbd>for(int i = 0; i < 10; ++i)" without quotes.
3. Press Click anywhere on the screen.

**Expected behavior**
 - Error or warning showing that invalid variable name.

**Screenshots**
<img width="464" alt="Screenshot 2020-03-30 at 6 26 15 PM" src="https://user-images.githubusercontent.com/28526643/77914786-0ada9b80-72b4-11ea-92f7-070886a9a05a.png">
<img width="440" alt="Screenshot 2020-03-30 at 6 26 38 PM" src="https://user-images.githubusercontent.com/28526643/77914841-204fc580-72b4-11ea-97b6-c439d165a816.png">

**Device information**
 - Type Desktop
 - OS: Catalina 10.15.3
 - Browser chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
 - The possible workout would be to add a RegEx checker for the variable name, and if the variable name is not following RegEx a warning should be shown.

**Comment by bjost2s** [comment]
There are checkers, both on frontend and backend site. I cannot reproduce this behaviour. Will check it on browser stack

**Comment by bjost2s** [comment]
Could you please make a screenshot after clicking somewhere else than in the variables name field and put it in here?

**Comment by rishabhdeepsingh** [comment]
The error comes when you click anywhere on the. 
PS: I have updated that above.
<img width="523" alt="Screenshot 2020-04-01 at 4 07 31 AM" src="https://user-images.githubusercontent.com/28526643/78081593-8597d980-73ce-11ea-8327-1df9b0ad71be.png">

**Comment by bjost2s** [comment]
which robot have you chosen?

**Comment by rishabhdeepsingh** [comment]
I have selected the EV3.

**Comment by bjost2s** [comment]
Thank you very much, now I can reproduce it! Seems that validators in blockly are not triggered, but validators on backend side should catch this

**Comment by rishabhdeepsingh** [comment]
@bjost2s  Can you refer to some files where I can resolve this issue? 
I tried finding some files but could not find the direct link to the variable name checker.

**Comment by bjost2s** [comment]
@rishabhdeepsingh, it seems that we do not have a variable name tester at the backend yet. It should be implemented as part of the empty checker, see #306.

**Comment by rishabhdeepsingh** [comment]
Let me know If I can contribute on this one and where.

**Comment by bjost2s** [comment]
works
