### ISSUE TITLE
Multiple Robot Simulation : Open/Close Simulation, deselects all programs

### ISSUE THREAD

**Issue by sachinsshetty** [OpenRoberta/openroberta-lab#787]
**Describe the bug**
 - In multiple robot simulation, on click of Open/Close simulation , existing selected program gets reset 

**To Reproduce**
1. Login as User on OpenRoberta Lab. Create and save multiple programs.
2. Click on Edit, Select Multiple Robot Simulation
3. Select 2 or more programs. 
4. Observe that multiple robots are present. Run the simulation.
4. Click on sim button(Open/Close simulation window) twice
5. Observe that only single robot is present

**Expected behavior**
 - Multiple robots should be available for simulation

**Screenshots**
 - If applicable, add screenshots to help explain your problem.

**Device information**
 - Type : Desktop
 - OS: Ubuntu 18.04
 - Browser : firefox 74.0

**Additional context**
 - Observed the error, while preparing GSOC proposal and similar bugs [555](https://github.com/OpenRoberta/openroberta-lab/issues/555) and [557](https://github.com/OpenRoberta/openroberta-lab/issues/557)

* multiple robots shown
![multiple-robots](https://user-images.githubusercontent.com/26170834/78035273-80af3780-7386-11ea-8de3-6f62b2a64937.png)

* Single robot shown
![after-open-close](https://user-images.githubusercontent.com/26170834/78035265-7db44700-7386-11ea-86f9-5b9c15bb3126.png)

**Comment by bjost2s** [comment]
this is not bug. If you close and reopen the simulation window you are back in the single robots view like normal. If you would click on the start button, the program in the program editor  would be executed, this is the correct and common way.
