### ISSUE TITLE
NXT: toolbox expert is broken

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#790]
see screenshot
![image](https://user-images.githubusercontent.com/1613069/78638857-488b8580-78ad-11ea-93e1-a35bf2b1562e.png)

**Comment by boonto** [comment]
I just saw that I didn't push the commit I had made on the blockly repo and it broke after a rebuild of blockly.

**Comment by boonto** [comment]
No longer broken.
