### ISSUE TITLE
Extend the simulation to take the configuration into account

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#791]
Because of the corona crisis it would be nice to offer some more possibilities to work with the simulation. As a first step the ultrasonic and color/light sensors (only NXT and EV3) should be supported multiple times, like on a real robot e.g.
![image](https://user-images.githubusercontent.com/1613069/78662711-328fbc00-78d1-11ea-9621-f024f6b9dc5a.png)
This will make it much easier to create line follower robots. Multiple ultrasonic sensors could be used to determine locations of objects more precisely.

Only the robot's configuration will be extended, there will be no way to change the robot's geometry. Sensors will still have a predefined position on the robot, e.g.
![image](https://user-images.githubusercontent.com/1613069/78663239-0aed2380-78d2-11ea-83fe-bc0d2bfb6c09.png)

**Comment by boonto** [comment]
Simulation is now mostly configurable, specific amounts of sensors lead to different robot layouts.
