### ISSUE TITLE
New simulation evaluates touchsensor when not configured

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#793]
see screenshot
![image](https://user-images.githubusercontent.com/1613069/78890543-212be880-7a66-11ea-9b02-c4ee169c84c0.png)

this is not a blocking bug, but maybe confusing

**Comment by bjost2s** [comment]
looks now like this:
![image](https://user-images.githubusercontent.com/1613069/78906785-1716e380-7a80-11ea-9b0b-a9b0b86f56db.png)
fixed and released

**Comment by boonto** [comment]
Does not happen anymore, only the configured sensors are shown.
