### ISSUE TITLE
Calliope serial write cuts strings after 20 characters, colors break compilation

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#8]

**Comment by VinArt** [comment]
- strings are not cut-off 
- colour constants do not break the compilation
- RGBW colour breaks code generation with the following exception: `java.lang.ClassCastException: de.fhg.iais.roberta.syntax.lang.expr.RgbColor cannot be cast to de.fhg.iais.roberta.syntax.lang.expr.ColorConst`
![image](https://user-images.githubusercontent.com/3738015/58418336-d8ef1c00-8087-11e9-97cc-ab25e7393461.png)
