### ISSUE TITLE
EV3 - calling a return statement  is not working in Simulation 

### ISSUE THREAD

**Issue by rhasel4s** [OpenRoberta/openroberta-lab#80]
**Describe the bug**
 -  Using the return block to leave a repeat block inside a function is not working in the simulation.

**To Reproduce**
1. Switch to 'expert mode'
2. Click on 'Functions'
3. Create a 'Function'
5. Add a 'repeat block'
6. Add a condition to leave the 'repeat block' 

**Expected behavior**
 - The programm should leave the function and return to the normal programm.

**Screenshots**
 ![return_bug](https://user-images.githubusercontent.com/15631864/52476812-26f71700-2ba0-11e9-8220-8bb120bad3ea.png)

**Device information**
 - Type [Desktop]
 - OS: [Linux]
 - Browser [firefox 64.0]

**Comment by bjost2s** [comment]
see #74
