### ISSUE TITLE
Gallery View 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#800]
**Describe the bug**
 - It seems as if the representation of the tiles in the gallery is different from user to user. With me the representation is faulty (100% representation in the browser) with others the representation is correct. 

**To Reproduce**
1. Go to Open Roberta Lab
2. Click on Gallery

**Expected behavior**
 - A uniform representation of the gallery tiles on all screens

**Screenshots**
![image](https://user-images.githubusercontent.com/19221359/79345252-2b038f00-7f31-11ea-8fc4-53c22cc91499.png)
similar problem for long user names:
![image](https://user-images.githubusercontent.com/1613069/79563179-8f972900-80ac-11ea-9198-6f5442943a8c.png)

**Device information**
 - Typ: mac 
 - OS: mac
 - Browser chrome, safari,  - 

**Additional context**
 - WITH FIREFOX it works WELL!!!

**Comment by bjost2s** [comment]
The fix should also resolve the problem of English labels instead of translated labels and the following strange behaviour (smartphones only)

![image](https://user-images.githubusercontent.com/1613069/79633352-2c1d0200-8165-11ea-993d-ba7600ce2d13.png)

**Comment by boonto** [comment]
Works well with different screen widths. Tested with Safari and Chrome on Windows and Edge, IE, Firefox on Windows.
