### ISSUE TITLE
Close the simulation view whenever the configuration is touched

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#801]
Related to #791, a new or changed configuration takes only effect when the simulation initializes itself. Currently this happens when the simulation view is opening.
When we close the simulation view whenever the configuration becomes visible we ensure that the new configuration takes effect with opening the simulation view again. This will improve the user experience.

**Comment by rbudde** [comment]
works. Now errors are detected, when the configuration is changed to effect an error :-)
