### ISSUE TITLE
Arduinos: piezo buzzer tone is not blockling as for all other systems

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#805]
**Describe the bug**
 When using the "play frequency" block the tone is not played for the predefined time
**To Reproduce**
create a program like in the screenshot

**Expected behavior**
The execution of this block should be blocking
**Screenshots**
![image](https://user-images.githubusercontent.com/1613069/79552997-1db6e380-809c-11ea-99c9-ac5df826d29d.png)

**Comment by rbudde** [comment]
works. Limits parallelism, but acceptable to have a similiar behavior for all robots.
