### ISSUE TITLE
Show annotated configuration in frontend

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#806]
With #114 and #764 the backtransformed annotated configuration (currently only for Arduino) could be used in the frontend.

Here https://github.com/OpenRoberta/openroberta-lab/issues/114#issuecomment-516904543 we already described how this should look:
- [x] rename `data`/`programText` fields to `progXML`
- [x] rename `configuration`/`configText` fields to `confXML`
- [x] show recieved configuration in workspace
- [ ] ~rename workspaces to better reflect their content?~
- [x] add a visual cue to the configuration tab (flashing and/or icon)
- [x] adapt messages
- [x] slightly rework configuration validator worker
- [x] add check button to program + config? -> will be solved in the future in #818

**Comment by boonto** [comment]
Currently, the configuration checker for Arduino (the only one currently annotating the configuration) only checks for overlapping pins for some specific sensors/actors, that was extended to all available in the configuration.
However, this also brought up that sometimes overlapping pins are valid and might be what the users wants (e.g. 2 LEDs on one output). We discussed what to do here and decided that overlapping pins should not be allowed. This is more user-friendly for inexperienced users and experienced users may still use overlapping pins, but without having it represented in the configuration.
This may change depending on user feedback, but seems like the best decision for now.

**Comment by bjost2s** [comment]
Detailed and korrect error messages are available now in the annotated configuration blocks !
