### ISSUE TITLE
Arduino Stepper Motor not working

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#807]
**Describe the bug**
When configuring and programming a stepper motor, the motor does not work.

**To Reproduce**
Create the following test program
![image](https://user-images.githubusercontent.com/1613069/79698133-1869bc80-8287-11ea-960b-6ae472cb824c.png)

**Expected behavior**
The motor should rotate

**Additional context**
 Use a correct configuration!

The program works as expected if you exchange IN2 with IN3!

**Comment by rbudde** [comment]
this program failed when compiled, or not? The integration tests have to be extended?

**Comment by bjost2s** [comment]
No problem with compilation, only at runtime the motor does not rotate

**Comment by bjost2s** [comment]
Works with my stepper motor from the funduino set
