### ISSUE TITLE
Arduino LCD screen - allow change address 

### ISSUE THREAD

**Issue by pablopoo** [OpenRoberta/openroberta-lab#81]
**Is your feature request related to a problem? Please describe.**
 - the lcd config don’t allow set the lcd controller address. This limit the Arduino program to use only one lcd and won’t allow use ones with another address (there are also ones with a totally different address space)

**Describe the solution you'd like**
 - add an option to change the default lcd controller address.

**Comment by bjost2s** [comment]
it seems to be fixed for LCD 1602 i2c
