### ISSUE TITLE
Integrate ORB

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#813]
- [x] Create basic plugin structure based on EV3 and WeDo
- [x] Clarify old vs new configuration
- [x] Add `orb` to blockly sensor definitions
- [x] Implement new blocks for configuration
  - [x] Add new configuration-block for differential drive
  - [x] Add new configuration-block for motor
  - [x] Adapts all configuration-blocks of sensors for orb
  - [x] Adjusts all action and sensors blocks for orb (new configuration)
- [x] Add detection capability for `orb` to Android app
- [x] Implement code generation and interpretation
  - [x] Test complete workflow with one sensor and actor combo first
  - [x] Implement with new configuration
  - [x] Build up toolbox for orb
  - [x] Interpret generated programs in Android app
  - [x] Implement all sensors from EV3
    - [x] Implement touch sensor
    - [x] Implement ultrasonic sensor
    - [x] Implement color sensor
    - [x] Implement infrared sensor
    - [x] Implement encoder sensor
    - [x] Implement gyroscope sensor
    - [x] Implement timer
  - [x] Implement all action blocks for orb (first all blocks from EV3)
    - [x] Implement motor on block
    - [x] Implement motor on for block
    - [x] Implement stop motor  block
    - [x] Implement drive block
    - [x] Implement drive for block
    - [x] Implement stop block
    - [x] Implement turn block
    - [x] Implement turn for block
    - [x] Implement steer block
    - [x] Implement steer for block
    - [x] Implement show text block
   - [x] Implement validators for orb
   - [x] Implement Interationstest for orb
- [x] Build a robot with Lego blocks for orb
- [ ] Make a image for orb
- [ ] Update logo
- [ ] Update help (*i*) pages
- [ ] Add wiki entries
- [ ] Makes a final test for orb with all sensors and motors from EV3

**Comment by bjost2s** [comment]
not time to work on, in a different project there is some work based on microPython
