### ISSUE TITLE
Information box overlays text input fields

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#816]
**Is your feature request related to a problem? Please describe.**
I think the screenshot describes it best. 

![image](https://user-images.githubusercontent.com/19221359/80248032-70316a80-866f-11ea-9e87-041f20af3c10.png)

**Describe the solution you'd like**
The info box should be wider, then the info text could go over two lines. This way you can see the other text boxes and then click on them. 

**Describe alternatives you've considered**
 - A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
 - Add any other context or screenshots or a mockup about the feature request here.

**Comment by bjost2s** [comment]
Still a problem for small devices, because the hints are covered by the keyboard:
![image](https://user-images.githubusercontent.com/1613069/81281538-422e2c00-905a-11ea-9d70-ad16feae84fe.png)

**Comment by rbudde** [comment]
for large devices fine, for small devices much better as the solution before. I close the issue

**Comment by philippmaurer** [comment]
If there is an error message in the following form field, the error message looks like it is a part of the hint for the current form field.

![grafik](https://user-images.githubusercontent.com/10925094/81291513-2df22b00-906a-11ea-9035-7e6cfc34ac66.png)

**Comment by boonto** [comment]
I think all add the same behaviour to the `form-invalid` class. However, it is used in more places than the hints and has to be checked there as well.

**Comment by boonto** [comment]
Now the error messages should not overlap anymore.

**Comment by rbudde** [comment]
after entering the password again, you have to click the button `Jetzt registrieren` _twice_ to register. Not user-friendly.

**Comment by boonto** [comment]
You should only need to press the button once now. A hint will only disappear when opening another hint.
