### ISSUE TITLE
Add a build/check button to program and configuration view

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#818]
With #806 configurations may also include annotations which let users now about errors in the setup.
However, to recieve these annotations the user has to trigger showing the source code or run the program in the program tab. This results in a lot of unnecessary switching of tabs and cumbersome usage.
This should be solved with a build or check button similar to that present in the source code editor. This button should appear next to the run button in the blockly workspace.

- [ ] Add build/check button to program
- [ ] Add build/check button to configuration
- [ ] reuse the configuration tab visual cue for the program tab

**Comment by bjost2s** [comment]
Solved by the program and configuration checkers
