### ISSUE TITLE
Tutorial button showing without tutorials

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#819]
**Describe the bug**
 - The Tutorial button is shown even when no tutorials are available. This happens when loading up in a language different to German. The button disappears when switching from German to English.

**To Reproduce**
1. Set up a browser with a default language different to German
2. Open the Lab
4. See Tutorials button

**Expected behavior**
 - The Tutorial button should only appear when tutorials are available in the selected language, even on first startup.

**Comment by bjost2s** [comment]
Works now
