### ISSUE TITLE
Right view is empty when quickly switching between tabs

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#820]
**Describe the bug**
 - The right view is empty after quickly switching tabs while a right view is open.
- This also happens when opening another tutorial after finishing one.

**To Reproduce**
1. Select any robot
1. Open the source code view
2. Switch to the configuration
3. Quickly switch back to the configuration (you have 750 ms)
2. Open source code view again
4. See that is is empty

**Expected behavior**
 - The source code view shows up.

**Additional context**
 - This happens due to a race condition in animations which lead to an illegal state of the view.
 - Probably because in `guiState.controller.js` the currently active `rightMenuButton` is triggered, which is triggered twice when quickly swichting tabs, overlapping animations.

**Comment by bjost2s** [comment]
works fine now!
