### ISSUE TITLE
Track the tutorial progress and quiz results and adopt the final message

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#822]
Currently the final message is very prominent and shows the results of the quizzes (if quizzes).

- [x] The grade of the results should be less prominent next to the result
- [ ] Results (and grades) should only be shown if all quizzes are done
- [ ] Add closings when all steps are done.
- [x] Allow unlimited blocks in the workspace after leaving a tutorial

**Comment by rbudde** [comment]
1. and 4. tasks done and work.
