### ISSUE TITLE
Micro:Bit add a buzzer to enable play tone and play frequency

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#823]
Currently micro:bit has no possibility to "make" music. An integration of the two programming blocks would allow the user to work with a couple of sets for micro:bit where a buzzer is included.

**Comment by rajamanojkumar** [comment]
can you please explain the issue in detail with an image attached.

**Comment by bjost2s** [comment]
these are the two blocks, derived from calliope
![image](https://user-images.githubusercontent.com/1613069/81823648-cc7fff80-9534-11ea-9543-0b706e22fd04.png)

**Comment by rbudde** [comment]
works
