### ISSUE TITLE
wiki contains http-Links to "robertalab" (Installation)

### ISSUE THREAD

**Issue by KarstenRauch** [OpenRoberta/openroberta-lab#825]
**Description the bug**

The wiki-pages contains links to robertalab instead of openrobarta-la.
E.g. https://github.com/OpenRoberta/openroberta-lab/wiki/Installation contains a link to
https://github.com/OpenRoberta/robertalab/releases

**Comment by boonto** [comment]
Thanks for letting us know!
I went through all wiki pages and replaced the links with ones to the new repository, if applicable.
I left links to specific commits to the old repo on the [Refactoring](https://github.com/OpenRoberta/openroberta-lab/wiki/Refactoring) page.

I am also unsure on what to to with the wish list on the [Roadmap](https://github.com/OpenRoberta/openroberta-lab/wiki/Roadmap) as that does not exist anymore. @bjost2s @rbudde what do you think?
