### ISSUE TITLE
Improvement of providing the status text 

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#828]
The status text for the Lab is not stored permanently yet. Each time the server is restarted, the message is not available anymore.
In best case the status text and the expiring date is stored in the file system.

**Comment by boonto** [comment]
As a preliminary measure to improve communication of breaking changes for the last release I added a simple "release info" system. Currently the messages are hardcoded and not time limited, which should be improved for the full resolution of this issue.

**Comment by bjost2s** [comment]
This solution is not the final solution, so it will not be closed but forwarded to the next release
