### ISSUE TITLE
Pasted blocks inherit the 'inTask' property of the copied block

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#83]
**Describe the bug**
 - If an already attached block is copied and pasted, it stays active despite the fact that it is not connected anymore

**To Reproduce**
1. Copy-paste attached block
2. Block is active (not greyed out)
3. If at this point code is regenerated it is generated in a wrong way

**Expected behavior**
 - block would be grey

**Screenshots**
![image](https://user-images.githubusercontent.com/3738015/50154631-28a40d00-02ca-11e9-878d-a0b3b3c04f09.png)

**Comment by PamoCurtis** [comment]
This Issue is similar to [that one](https://github.com/OpenRoberta/openroberta-lab/issues/1204#issue-1110506038) and also should be fixed with this [pull request](https://github.com/OpenRoberta/blockly/pull/61#issue-1166201746)

**Comment by bjost2s** [comment]
fixed with #1204
