### ISSUE TITLE
Collision of python import names and user defined variables

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/openroberta-lab#84]
**Describe the bug**
 - in ev3dev it is possible to name the variables ev3dev, Hal, math, etc.
 - in microbit it is possible to name the variables microbit, math, etc.
 - in NAO situation is similar

**To Reproduce**
1. Go to one of the python based robots
2. Create a variable and name it with one of the import's names
3. Open code generation
4. A variable will overwrite the import

**Expected behavior**
- There should not be any collisions between variables and imports

**Possible solution**
 use import ... as _..., so to append underscore to the modules name, since variables starting with underscore are forbidden.

**Related problem**
 - additionally keywords such as sum, min, max, len, int, float, str, sorted, etc. (python [in-builts python 3](https://docs.python.org/3/library/functions.html); [in-builts python 2](https://docs.python.org/2/library/functions.html)) should be blacklisted

**Comment by bjost2s** [comment]
solved in #35
