### ISSUE TITLE
Arduino program blocks reset when switching between configuration and program

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#840]
**Describe the bug**
 - Arduino program blocks with multiple available configuration blocks reset to the "default" one when switching between program and configuration.

**To Reproduce**
1. Select Arduino Uno
1. Switch to configuration
1. Add a "LED" configuration block
1. Switch back to program
1. Add two "turn LED on" blocks
1. Change one of them to the new LED "L2"
1. Switch to configuration and back to program
1. See error: both blocks have reset to LED "L"

**Expected behavior**
 - The selected pins remain the same.

**Additional context**
 - No problem for blocks with only one configuration block.
 - This happens during the call to `bricklyWorkspace.clear()` in `reloadConf()`, here the connection between the blocks is lost, as the connected configuration block does not exist anymore.
 - This was introduced in #806, previously no additional calls to `reloadConf()` were necessary.

**Comment by rbudde** [comment]
ok
