### ISSUE TITLE
Docker Setup for Raspberry Pi

### ISSUE THREAD

**Issue by kraeml** [OpenRoberta/openroberta-lab#846]
What I have done and my setup for Pi4:

```bash
git --version
```

    git version 2.20.1

```bash
java -version
```

    openjdk version "11.0.7" 2020-04-14
    OpenJDK Runtime Environment (build 11.0.7+10-post-Raspbian-3deb10u1)
    OpenJDK Server VM (build 11.0.7+10-post-Raspbian-3deb10u1, mixed mode)

```bash
cat /etc/os-release
```

    PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="10"
    VERSION="10 (buster)"
    VERSION_CODENAME=buster
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```bash
uname -a
```

    Linux pi4-home 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

```bash
free
```

                  total        used        free      shared  buff/cache   available
    Mem:        3999744      389120     2814556        8996      796068     3460564
    Swap:       1048572           0     1048572

```bash
export ARCH=arm32v7
```

```bash
echo $ARCH
```

    arm32v7

```bash
id
```

    uid=1000(pirate) gid=1000(pirate) Gruppen=1000(pirate),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),105(input),109(netdev),996(docker),997(gpio),998(i2c),999(spi)

```bash
pwd
```

    /home/pirate/notebooks/openroberta-lab

```bash
nmap localhost
```

    Starting Nmap 7.70 ( https://nmap.org ) at 2020-06-08 21:03 CEST
    Nmap scan report for localhost (127.0.0.1)
    Host is up (0.00049s latency).
    Not shown: 993 closed ports
    PORT     STATE SERVICE
    22/tcp   open  ssh
    25/tcp   open  smtp
    3306/tcp open  mysql
    3389/tcp open  ms-wbt-server
    8181/tcp open  intermapper
    8888/tcp open  sun-answerbook
    9999/tcp open  abyss
    
    Nmap done: 1 IP address (1 host up) scanned in 0.24 seconds

```bash
git clone https://github.com/OpenRoberta/openroberta-lab.git
```

    Klone nach 'openroberta-lab' ...
    remote: Enumerating objects: 763, done.        
    remote: Counting objects: 100% (763/763), done.        
    remote: Compressing objects: 100% (405/405), done.        
    remote: Total 145011 (delta 271), reused 610 (delta 182), pack-reused 144248        
    Empfange Objekte: 100% (145011/145011), 388.36 MiB | 6.78 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (80678/80678), Fertig.
    Checke Dateien aus: 100% (4481/4481), Fertig.

```bash
ls -l openroberta-lab/ora.sh
```

    -rwxr-xr-x 1 pirate pirate 7199 Jun  8 21:04 openroberta-lab/ora.sh

```bash
cd openroberta-lab
./ora.sh new-docker-setup pi-ora
```

    New docker setup created in pi-ora. Edit 'decl.sh' and setup databases and servers now.
    Create servers by calling './ora.sh new-server-in-docker-setup pi-ora SERVER_NAME'

```bash
./ora.sh new-server-in-docker-setup pi-ora rdf-2020
```

    New server rdf-2020 created. Edit 'pi-ora/decl.sh' and 'pi-ora/server/rdf-2020/decl.sh'
    Copy an existing database or create an empty database after 'mvn clean install -DskipTests'
    by calling './ora.sh -dbParentdir pi-ora/db/rdf-2020 create-empty-db'

```bash
cat pi-ora/decl.sh
```

    # essential configuration variables. Be very carefull!
    
    INAME=''                # the (short, alphanumeric) name of this installation
    DATABASE_SERVER_PORT='' # one database server for all jetty server. It is listening on this port. Usually this is '9001'
    DOCKER_NETWORK_NAME=''  # the network for cooperation between jetty and database server. Usually this is 'ora-net'
    
    SERVERS=''              # these servers can run (used in start-all and stop-all), e.g. 'test dev dev4'
    SERVERSXMX='-Xmx1G'     # maximum of heap size for the jetty server. CURRENTLY UNUSED. Production server needs 1G, raspi 1G or 500M
    DATABASES=''            # these databases are served by the database server, e.g. 'test dev dev4'
    DATABASEXMX='-Xmx4G'    # maximum of heap size for the database server. Production server needs 4G, raspi 1G or 500M
    AUTODEPLOY=''           # these servers are deployed when new commits hit the git repo. See auto-deploy and cron, e.g. 'dev dev4'
    
    # for operating purposes
    ALIVE_ACTIVE=true                                               # set to false if not needed
      ALIVE_MAIL_SMTP_SERVER='smtps.iais.fraunhofer.de'               # smtp server
      ALIVE_MAIL_SMTP_PORT='25'                                       # smtp port
      ALIVE_MAIL_SENDER='lab-alive@open-roberta.org '                 # the name for the sender of the mail
      ALIVE_MAIL_RECEIVER=( 'name-1@address-1' 'name-2@address-2' )   # list of receivers for the mail, white-space separated
    
    PYTHON=/usr/bin/python3 # for log file evaluation

```bash
sed -Ei "s/(INAME=')/\1pi-ora/g" pi-ora/decl.sh
```

```bash
sed -Ei "s/(DATABASE_SERVER_PORT=')/\19001/g" pi-ora/decl.sh
sed -Ei "s/(DOCKER_NETWORK_NAME=')/\1ora-net/g" pi-ora/decl.sh
sed -Ei "s/(SERVERS=')/\1test/g" pi-ora/decl.sh
sed -Ei "s/(DATABASES=')/\1test/g" pi-ora/decl.sh
sed -Ei "s/(DATABASEXMX='-Xmx)4/\12/g" pi-ora/decl.sh
```

```bash
cat pi-ora/decl.sh
```

    # essential configuration variables. Be very carefull!
    
    INAME='pi-ora'                # the (short, alphanumeric) name of this installation
    DATABASE_SERVER_PORT='9001' # one database server for all jetty server. It is listening on this port. Usually this is '9001'
    DOCKER_NETWORK_NAME='ora-net'  # the network for cooperation between jetty and database server. Usually this is 'ora-net'
    
    SERVERS='test'              # these servers can run (used in start-all and stop-all), e.g. 'test dev dev4'
    SERVERSXMX='-Xmx1G'     # maximum of heap size for the jetty server. CURRENTLY UNUSED. Production server needs 1G, raspi 1G or 500M
    DATABASES='test'            # these databases are served by the database server, e.g. 'test dev dev4'
    DATABASEXMX='-Xmx2G'    # maximum of heap size for the database server. Production server needs 4G, raspi 1G or 500M
    AUTODEPLOY=''           # these servers are deployed when new commits hit the git repo. See auto-deploy and cron, e.g. 'dev dev4'
    
    # for operating purposes
    ALIVE_ACTIVE=true                                               # set to false if not needed
      ALIVE_MAIL_SMTP_SERVER='smtps.iais.fraunhofer.de'               # smtp server
      ALIVE_MAIL_SMTP_PORT='25'                                       # smtp port
      ALIVE_MAIL_SENDER='lab-alive@open-roberta.org '                 # the name for the sender of the mail
      ALIVE_MAIL_RECEIVER=( 'name-1@address-1' 'name-2@address-2' )   # list of receivers for the mail, white-space separated
    
    PYTHON=/usr/bin/python3 # for log file evaluation

```bash
find . -name decl.sh
```

    ./Docker/openroberta/decl.sh
    ./Docker/openroberta/server/_server-template/decl.sh
    ./pi-ora/decl.sh
    ./pi-ora/server/rdf-2020/decl.sh
    ./pi-ora/server/_server-template/decl.sh

```bash
cat pi-ora/server/rdf-2020/decl.sh
```

    BASE_VERSION=''           # the version of the docker base image, FROM which this server image is derived. Be careful to define the RIGHT number
    
    PORT=''                    # port the jetty server will listen to, very often 1999
    LOG_LEVEL=''               # the logging level of the root logger. From DEBUG to ERROR
    LOG_CONFIG_FILE=''         # logback configuration, very often /logback-prod.xml or /logback.xml
    
    BRANCH=''                  # the branch to be deployed on this server, e.g. 'develop'
    # COMMIT=''                # if a commit instead of a branch is deployed, e.g. '174db1b4f0'
    GIT_REPO=''                # the git repo where the branch is founf, e.g. 'openroberta-lab'
    GIT_PULL_BEFORE_BUILD=true # set to false ONLY, if you have a well-prepared, ready to use branch checked out. NEVER use such a git repo for other server deployments. NEVER.
    
    # START_ARGS='-d key1=val1 -d key2=val2' # use to supply parameter when container is started

```bash
sed -Ei "s/(BASE_VERSION=')/\116/g" pi-ora/server/rdf-2020/decl.sh
sed -Ei "s/(PORT=')/\11999/g" pi-ora/server/rdf-2020/decl.sh
sed -Ei "s/(LOG_LEVEL=')/\1DEBUG/g" pi-ora/server/rdf-2020/decl.sh
sed -Ei "s/(LOG_CONFIG_FILE=')/\1\/logback.xml/g" pi-ora/server/rdf-2020/decl.sh
sed -Ei "s/(GIT_REPO=')/\1openroberta-lab/g" pi-ora/server/rdf-2020/decl.sh
```

```bash
sed -Ei "s/(BRANCH=')/\1master/g" pi-ora/server/rdf-2020/decl.sh
```

```bash
cat pi-ora/server/rdf-2020/decl.sh
```

    BASE_VERSION='16'           # the version of the docker base image, FROM which this server image is derived. Be careful to define the RIGHT number
    
    PORT='1999'                    # port the jetty server will listen to, very often 1999
    LOG_LEVEL='DEBUG'               # the logging level of the root logger. From DEBUG to ERROR
    LOG_CONFIG_FILE='/logback.xml'         # logback configuration, very often /logback-prod.xml or /logback.xml
    
    BRANCH='master'                  # the branch to be deployed on this server, e.g. 'develop'
    # COMMIT=''                # if a commit instead of a branch is deployed, e.g. '174db1b4f0'
    GIT_REPO='openroberta-lab'                # the git repo where the branch is founf, e.g. 'openroberta-lab'
    GIT_PULL_BEFORE_BUILD=true # set to false ONLY, if you have a well-prepared, ready to use branch checked out. NEVER use such a git repo for other server deployments. NEVER.
    
    # START_ARGS='-d key1=val1 -d key2=val2' # use to supply parameter when container is started

```bash
cd pi-ora/git
```

```bash
git clone https://github.com/OpenRoberta/openroberta-lab.git
```

    Klone nach 'openroberta-lab' ...
    remote: Enumerating objects: 763, done.        
    remote: Counting objects: 100% (763/763), done.        
    remote: Compressing objects: 100% (405/405), done.        
    remote: Total 145011 (delta 271), reused 610 (delta 182), pack-reused 144248        
    Empfange Objekte: 100% (145011/145011), 388.36 MiB | 6.29 MiB/s, Fertig.
    Löse Unterschiede auf: 100% (80678/80678), Fertig.
    Checke Dateien aus: 100% (4481/4481), Fertig.

```bash
cd ../..
pwd
```

    /home/pirate/notebooks/openroberta-lab/openroberta-lab

```bash
ls
```

    admin.sh          OpenRobertaServer  Resources    RobotNXT
    Docker            ora-help.txt       RobotArdu    RobotRaspberryPi
    JaxbGenerator     ora.sh             RobotEdison  RobotVorwerk
    LICENSE           pi-ora             RobotEV3     RobotWeDo
    NOTICE            pom.xml            RobotMbed    src
    OpenRobertaRobot  README.md          RobotNAO     WedoInterpreter

```bash
docker network ls
```

    NETWORK ID          NAME                DRIVER              SCOPE
    62abbc60c016        bridge              bridge              local
    ec3caaa57eb5        host                host                local
    d5d27fda432a        none                null                local

```bash
pi-ora/scripts/run.sh -yes gen-net
```

    run.sh [-q] [-yes] [-D]                                              be quiet, answer all questions with 'y', debug mode
           help                                                          this text
           gen <server> | start <server> | stop <server>                 gen builds image; start first tries to stop, then (re-)starts the server; stop stops the server
           deploy <server>                                               deploy first calls gen, then calls start
           admin <server> <admin-cmd>                                    execute admin command on server, e.g. 'cleanup-temp-user-dirs'
           auto-deploy |                                                 check for git changes for servers found in variable AUTODEPLOY
           start-all | stop-all                                          start/stop db server and server found in variable SERVERS
           gen-dbc | start-dbc | stop-dbc | backup [<db>]                generate db server, start and stop db server using variable DATABASES, backup a db
           backup-save <dbBackup@<remote-host>:<from-path> <to-path>     save a db backup from a remote machine to this machine. <to-path> is relative to BASE-DIR
           alive <url> [mail={always|error}] [msg=<msg>]                 is the server alive? When to send mail (default: always). Set an additional mail header
           docker-info | network | logs | test-info                      container state, network and some log from running containers; info about deployed servers
    
           monthly-stat <server> [month]                                 run the monthly stats for a server. Optionally supply the month (e.g. '05' or '12')
           show-server                                                   some data about processes with many open file descriptors (FD)
           show-resources <server> [<file> [<lower> [<upper> [ <url> [<hours> [<pid>]]]]] show resource usage. Parameter description is in file helper/_showResources.sh
           show-activity-once <server> [<file> [ <url>]]                 show accumulated user activity. Parameter description is in file helper/_showActivityOnce.shs
    
    dangerous commands:
           prune                                                         rm as much unused data from docker as possible
           auto-restart <server> <url>                                   restart a container if <url>/rest/alive doesn't respond within 50 sec (url ~ https://dns:port)
           gen-net                                                       generate the docker network 
           start-export <server>                                         start a server from the export dir outside of docker
    working on host pi4-home for installation pi-ora at BASE_DIR /home/pirate/notebooks/openroberta-lab/openroberta-lab/pi-ora
    ******************** 2020-06-08 21:09:06 ********************
    -yes was set. Automatic 'y' for question: do you have double-checked, that the bridge network name 'ora-net' is NOT used elsewhere?
    2020-06-08 21:09:06: generating the openroberta bridge network 'ora-net'
    e0ef91bd1e3fd192f8ce32379cf9c442d2c0cdd5e63d313f8f1284c1602dfb77
    generating the openroberta bridge network 'ora-net' finished

```bash
docker network ls
```

    NETWORK ID          NAME                DRIVER              SCOPE
    62abbc60c016        bridge              bridge              local
    ec3caaa57eb5        host                host                local
    d5d27fda432a        none                null                local
    e0ef91bd1e3f        ora-net             bridge              local

```bash
./ora.sh -dbParentdir pi-ora/db/test create-empty-db
```

    creating an empty db using the url jdbc:hsqldb:file:pi-ora/db/test/openroberta-db - an existing db is NOT overwritten
    Fehler: Hauptklasse de.fhg.iais.roberta.main.Administration konnte nicht gefunden oder geladen werden
    Ursache: java.lang.ClassNotFoundException: de.fhg.iais.roberta.main.Administration

```bash

```

I'm not able do install the db on my Pi4. Any suggestions will help.

THX Kraeml

**Comment by rbudde** [comment]
thx for the detailed information. I'll add comments here to simplify our docker setup resp to help with your setup.

**Comment by rbudde** [comment]
you cannot create the empty database, because the libraries needed are not yet installed. You have to run 'mvn clean install -DskipTests' (rm the -D to see the unit tests executed). Then it should work.

As a consequence I'll make the following changes:
1. improve the first paragraph of the readme
2. add an empty database to allow a simple start w.o. generating a database
3. remove the INAME parameter to have simpler names in dockerhub. Consequence: only one installation on a machine. That seems ok. This will change the image names. The database image and the server images MUST be generated again. Do not forget to remove old images, they use up a lot of space!

I push the changes to the branch "docker-setup". Feel free to evaluate it.

**Comment by kraeml** [comment]
THX for your help. The pi docker setup is now working. The output of my [jupyter notebook is here](https://gist.github.com/kraeml/adc59bdc49c02ce43c0d2d7d11e9199f). I forgot the `mvn clean install -DskipTests`.

**Comment by bjost2s** [comment]
solved
