### ISSUE TITLE
Arduino: Multiple problems with the timer

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#848]
Problem 1:
The "get timer value" block only has "1" in the dropdown field whereas the "reset timer" block has 1 - 5 timers. Best solution is to have 1 - 5 timer to select.
Problem 2:
In the "wait until" block the timer is associated with a non existing configuration block, very confusing, but code generation works.
![image](https://user-images.githubusercontent.com/1613069/84492032-cdc45980-aca5-11ea-88a2-fe0f3b4ab738.png)

**Additional context**
Seems that we have different implementations in the arduino plugins, e.g. sensebox is working, but only with 1 timer.

**Comment by boonto** [comment]
There are 5 timers available through the "get timer", "wait until get timer" and the "reset timer" now.
