### ISSUE TITLE
Arduino: "Wait for" block is broken when plus icon is clicked

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#849]
![image](https://user-images.githubusercontent.com/1613069/84502893-77f9ac80-acb9-11ea-8c50-25b1cb0bde2e.png)

See screenshot, only the first "wait for" condition is created properly, additionally the first logic compare is not the predefined one (> 100)

**Comment by boonto** [comment]
When adding additional conditions the default entry stays consistent and does not pop out anymore.
