### ISSUE TITLE
NXT: ternary if with string fails in the NXC compiler

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#85]
**Describe the bug**
 - Code, that generates a ternary if for the NXC compiler fails, if the result is a string.

**To Reproduce**
1. create nxt program that uses the test block
2. if the result is a number, everything is fine
3. if the result is a string, the NXC compiler fails to compile the program

**Expected behavior**
 - the NXC compiler should compile

**Screenshots**
![image](https://user-images.githubusercontent.com/15834363/49750472-43172e80-fcab-11e8-9efe-45eab0c63f49.png)

**Additional context**

We need a user-friendly way to show in such situations, that cross-compilers fail (e.g. showing their messages). It must be obvious for the user, that not the lab, but the underlying tool failed.

**Comment by bjost2s** [comment]
Compiler error messages are now returned to the client.
