### ISSUE TITLE
fn3 Frontend ERROR to check

### ISSUE THREAD

**Issue by JanusMilan** [OpenRoberta/openroberta-lab#851]
- [ ] **fn3 caught an EXCEPTION**

> TypeError: Cannot read property 'reset' of undefined 
> TypeError: Unable to get property 'reset' of undefined or null reference
> TypeError: undefined is not an object (evaluating 'robots[i].reset') 
> TypeError: robots[i] is undefined
> TypeError: result is undefined 
> Error: Syntax error, unrecognized expression: \#escape[object Object] 
> TypeError: Cannot read property 'replaceState' of undefined 

**Bug description**
Wrap function fn3 (implementation in file wrap.js) outputs only part of the available information.
Therefore, the cause and location of the error is difficult to find out.

**Proposed solution**
Adjust the wrap function fn3 so that it outputs all available information.

**Comment by bjost2s** [comment]
works as expected
