### ISSUE TITLE
Integrate STM32 based boards

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#855]
We want to integrate STM32 based boards into the Lab, it should probably be under the RobotArdu project.
For the specific boards we want to support first, the transfer works over a storage device, similar to Calliope.

- [ ] Add project
- [ ] Adapt compiler workers
- [x] Add crosscompiler resources
- [ ] Add code generation
- [x] Compiler
  - [x] Linux x86
  - [ ] Linux ARM
  - [ ] Windows -> Compiler available
  - [ ] OSX -> Compiler available
- [ ] Add tests
- [ ] Add background image
- [ ] Add icon
- [ ] Add wiki entries/help files

**Comment by rbudde** [comment]
will be reopened, if really needed
