### ISSUE TITLE
Menue not clickable

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#859]
**Describe the bug**
 - A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/19221359/87856514-064bf880-c920-11ea-8ab1-db630892d73e.png)

**To Reproduce**

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**
 - If applicable, add screenshots to help explain your problem.

**Device information**
 - Type [Desktop/tablet/smartphone]: Mac
 - OS: [e.g. windows], including version: Mojave 10.16.4
 - Browser [e.g. chrome, firefox], including version: Firefox 

**Additional context**
 - Add any other context about the problem here.

**Comment by bjost2s** [comment]
strange, because it should look like:
![image](https://user-images.githubusercontent.com/1613069/87911122-63a09080-ca6b-11ea-875c-92046a67e2d7.png)
from browserstack.com MacOSX Mojave Chrome 83

**Comment by RaghuvirShirodkar** [comment]
Seems to be resolved. There is now an option to mention number of multiple sims.

Tested on BrowserStack (MacOS Mojave):
![image](https://user-images.githubusercontent.com/43172112/193760410-8e83f5ff-6893-4ae6-b4ac-b6f49fad002a.png)

**Comment by bjost2s** [comment]
@Thorlogy is the problem solved? Please check it again. If there is still an issue, please document it in reproducable way.

**Comment by Thorlogy** [comment]
problem seems to be solved. Thx.
