### ISSUE TITLE
Enhancements for multiple robot simulation (program selection)

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#861]
The improvements need a clear concept before starting implementing

These are the desired features:
- [ ] a program should be selectable for multiple runs

- [ ] the actual program should be selectable

- [x] filter for the list of selectable programs

- [x] selection should be remembered when paging/scrolling

If selected as a "good first issue" it may be good only to work on one or two items

**Comment by AhwiniMirajkar** [comment]
Can I work on this

**Comment by KishkinJ10** [comment]
hey i am a beginner can i work on this??

**Comment by RaghuvirShirodkar** [comment]
Solved
