### ISSUE TITLE
Multiple Robot Simulation should not be accessable from example program view

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#862]
1. Go to 'edit / example programs'
2. Click on 'example progams' then click on "multiple robot simulation" 

**Expected behavior**
 - The multiple robot sim should only be accesabble form program view and not from "example programs"
 - please check other views for erroneous behaviour

**Comment by bjost2s** [comment]
could not be reproduced, please provide more information or screenshot

**Comment by bjost2s** [comment]
seems to be already fixed
