### ISSUE TITLE
Blockly build fails or some time

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#866]
When trying to build the Open Roberta Lab [Blockly](https://github.com/OpenRoberta/blockly) it fails always with 
**Required namespace "goog.events.EventWrapper" never defined.**

It is not clear why this happens, but it might have to do with the usage of the online google closure compiler. The fix for this is therefor to use a local compiler. So no need for being online when working with blockly anymore.

**Comment by boonto** [comment]
Blockly can be built locally without issues now.
