### ISSUE TITLE
c4ev3 plugin depends on a forked version of the library

### ISSUE THREAD

**Issue by simonedegiacomi** [OpenRoberta/openroberta-lab#868]
**Describe the bug**

When the c4ev3 plugin was developed, the c4ev3 library needed to be modified to support more sensors, to allow to dynamically change the reading mode of a sensor, to share messages using bluetooth and etc...

This modified version of the library was stored my forked repository, and thus the c4ev3 plugin depends on it.

The changes made to the library were finally merged into the official c4ev3 repository, but in the meanwhile the interface of the library changed. Thus, to keep the openroberta software up to date and not dependent on a not-official repository, the code needs to be updated.

**Additional context**

Changes required to fix this issue are already ready, and I will send two PRs addressing this issue soon. The purpose of this issue is to document the need of the two PRs.

**Comment by bjost2s** [comment]
won't fix, plugin is deprecated
