### ISSUE TITLE
Sensebox RGB Led not working

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#871]
The generated code for the sensebox's RGB Led does not work. The led does nothing. 
We should access this led with the NeoPixel library, so that the RGB led is working as expected.

We might also use this library for other systems later.

**Comment by boonto** [comment]
The LED does some light flickering in the expected colors, but nothing as consistent as expected.

To do:
- [x] Blockly configuration block
- [ ] Change serverside to reflect Blockly changes
- [ ] Ensure backwards compatibility with older programs (at least with importing programs, as it didnt work before anyway)
- [ ] Change code generation to use library
- [ ] Add library in arduino-resources
- [ ] Pull up arduino-resources tag in ora-cc-rsc
