### ISSUE TITLE
Miscellaneous problems with sensebox blocks, only labeling 

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#872]
- [x] Die Beschreibung des „Lösche OLED Bildschirm Blocks“ spricht vom LCD 1602 Bildschirm.

- [x] Die Titel der Blöcke für das Zeichnen eines Diagramms, also „Zeichne einen Punkt“ und „Lösche Diagramm“ sind in der Beschreibung nur in Englisch verfügbar

- [x] Die Beschreibungen der Blöcke für den Temperatur-/Luftfeuchtigkeitssensor (HDC) und das Barometer (BMP) führen im Titel den genauen Sensortitel auf, also HDC1080, anstatt Temperatur- & Luftfeuchtigkeitssensor.

- [x] remove Beta label

**Comment by boonto** [comment]
The mentioned inconsistencies in the german description no longer exist.

The titles in the description of the HDC and BMP sensors now include the sensor type **and** the name.

The beta label is no longer visible.
