### ISSUE TITLE
[NXT] Optionally show compiler output / errors

### ISSUE THREAD

**Issue by Stex** [OpenRoberta/openroberta-lab#88]
**Is your feature request related to a problem? Please describe.**

I noticed a lot of strange behaviours / bugs involving the NXC code generation and compilation in the last days. To find out what exactly went wrong, I had to download the generated code and run it through `nbc` myself as orlab only gives me a general "could not be transformed to machine code" message.

While this might not be the most interesting feature for most people, it would help users who run into bugs that lead to failed compilations by giving them at least a hint to what exactly went wrong.
Currently, the only thing they can effectively do is remove block after block until the program compiles again - or leave orlab completely, seeing it as broken.

**Describe the solution you'd like**

As orlab is already giving me the option to display the generated NXC code, I'd like to be able to e.g. tick a "show compiler output" checkbox below the code which would be filled whenever I send a program to the NXT through the USB connector.

1. The user creates a program in NEPO
2. The user clicks on the "Code" button on the right side of the screen
3. The code window opens and shows the generated NXC code
4. The user ticks the "show compiler output/errors" checkbox below the generated code
5. A text area (or similar) is shown with e.g. "Program hasn't been compiled yet"
6. The user sends the program to their NXT using the "play" button in the main window
7. The text area is filled with the compiler output

**Describe alternatives you've considered**

As the most interesting part about the compiler output would be possible errors / warnings, it would be enough if only those were displayed in case they occurred during compilation.

**Additional context**

![compiler-errors](https://user-images.githubusercontent.com/27221/48290833-9c096200-e474-11e8-901d-21acd8313afe.jpg)

**Comment by bjost2s** [comment]
see #144
