### ISSUE TITLE
Avoid flooding the server log with exceptions and stack traces

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#884]
When the server is restarted, the user sessions (whose key called initToken is stored client-side) become invalid.

Both the /rest/ping-Request and any action triggered by the user (compile, run sim, ...) effect an exception, because the initToken is not found server-side and then write a stack trace into the log. Especially problematic is the /rest/ping, because it is re-executed every some seconds for hundreds of users.

TBD:
- suppress the stacktrace for both requests, when the error is the missing initToken
- deacitvate the /rest/ping-Request in that case at client-side in the browser
- extend the error message at client side to express the possible server-restart.

**Comment by boonto** [comment]
These don't seem to happen anymore. I have tested this coming from different versions.
