### ISSUE TITLE
Visualizing the new configuration

### ISSUE THREAD

**Issue by pretodev** [OpenRoberta/openroberta-lab#887]
**Is your feature request related to a problem? Please describe.**

The configuration tab of the lab is user-unfriendly, it not having a realistic view of the robot circuit.

**Describe the solution you'd like**

A view of the robot's settings that allows:

- View wires
- Represent the components with their respective ports
- View selected robot board

**Comment by boonto** [comment]
This should be extended (now or later) to all robots with the new configuration:
- [x] Calliope
- [x] micro:bit
- [ ] Bionics4Education
- [ ] senseBox
- [ ] WeDo
