### ISSUE TITLE
[NXT] Simulator seems to cache function result

### ISSUE THREAD

**Issue by Stex** [OpenRoberta/openroberta-lab#90]
**Describe the bug**

I wrote a simple program to demonstrate using lists in a NXT program: It let the robot drive over black lines, puts the distances between them into a list and then converts them into letters which were stored in a 26 item list (one letter per list item).

[bug_function_result.xml.zip](https://github.com/OpenRoberta/robertalab/files/2567529/bug_function_result.xml.zip)

To keep the program easy to understand, I wrote a function to convert a distance to a letter of the alphabet:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/27221/48288336-17b2e100-e46c-11e8-941f-40283b0009ca.png">

While running the program in the simulator (it won't compile to NXT byte code, reasons are described in some of my other issues), I noticed that I only ever got 2 different letters displayed. From the second letter on, all letters were the same, even though the lines had different distances to each other:

![n-linien](https://user-images.githubusercontent.com/27221/48288553-ca833f00-e46c-11e8-8202-b62620184d81.jpg)

<img width="189" alt="image" src="https://user-images.githubusercontent.com/27221/48288517-aa538000-e46c-11e8-8a93-5bd9a9a75225.png">

I thought it might have been a problem with the list operation, so I decided to test it by replacing the list operation with a random number generation:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/27221/48288599-f8688380-e46c-11e8-87b0-c87c1e0b1ab7.png">

Guess what:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/27221/48288620-0fa77100-e46d-11e8-9761-8577918d151b.png">

**To Reproduce**

1. Load the program linked above
2. Load the image above into the simulator (a similar image would of course work as well)
3. Place the NXT in front of the first row and run the program in the simulator

This behaviour seems to be caused by the combination of functions used, at least I wasn't able to reproduce it by calling `letterFromDistance` directly.

**Expected behavior**

The correct letters (resp. different random numbers) should be displayed instead of a repeating one.
The program behaves correctly when placing the array access directly inside the `displayLetters` function instead of calling `letterFromDistance`

**Comment by bjost2s** [comment]
see #74
