### ISSUE TITLE
Sharing of a program from a group member to another group member behaves unexpectedly

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#903]
- create a group "g" with some members "01"..."05"
- login as a member "01"
- sharing a program to another member **fails** on a public server with the message "account not verified"
- on a private server (and on a public server if the previous problem is solved), a further problem arises: if you name the user as "02", the request fails, but it succeeds, if you name the user "g:02"

Solution:
- first problem: change ClientProgramController:456 (probably)
- second problem: because a group member can only share programs with user of the same group, one solution (among others, maybe better ones) is, that the frontend prefixes the name with "g:"

A further problem is, that the share request is executed **twice**. It should be checked, whether this is a common error pattern and occurs at other places, too.

**Comment by rbudde** [comment]
the first problem is solved by a commit I'll push soon.

for the second problem I propose to tell the user to prefix with the group name. This solves the problem for the next weeks.
The frontend logic of sharing must be redesigned. My comment of "share request .... twice" was misleading. **All** sharing data is written to the data base always (you have 8 shares: the frontend issues 8 REST calls). Only the delta should be sent (usually 1 REST call). When this refactoring is done, the group prefix can be added by the front-end.

**Comment by bjost2s** [comment]
commit mentioned above is a80563a32626b947f2165d68aae3bf5b2e68e5f3
