### ISSUE TITLE
Mbot + Edison: "play tone" block has an unwanted port field

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#906]
![image](https://user-images.githubusercontent.com/1613069/94397869-d06b9180-0164-11eb-8e68-d91e5ebcea81.png)

As this block has no corresponding configuration block, the port field has to be removed.

**Comment by boonto** [comment]
The visual issues of showing the port should be solved with #912, as it will be removed again. The underlying problem of why non Mbed robots use the Mbed block should be handled in #891.

**Comment by bjost2s** [comment]
@boonto , WeDo seems to be affected too:
![image](https://user-images.githubusercontent.com/1613069/95567578-6a63f180-0a23-11eb-9a02-1840db2cbd5c.png)
