### ISSUE TITLE
make LED-matrix (of Calliope, MicroBit, ...) programmable

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#915]
it should be possible to set leds on a matrix on/off **programmatically**, either by a statement 

- on/off x,y (addresses a single LED) or
- setMatrix(integernumber) with a bit encoding of the whole matrix, i.e. 31 for the whole lowest row on 5x5 matrix

**Comment by bjost2s** [comment]
already implemented
