### ISSUE TITLE
[NXT] Certain strings involving quotation marks lead to failed compilation to machine code

### ISSUE THREAD

**Issue by Stex** [OpenRoberta/openroberta-lab#92]
**Describe the bug**

Using a string containing `"Sensor` leads to "The program could not be transformed into machine code."

This was noticed when the text `Please press "Sensor 1"` was used in a program

**To Reproduce**

1. Create a simple program to display the text `"Sensor`
  <img width="547" alt="image" src="https://user-images.githubusercontent.com/27221/48121050-2d5db600-e274-11e8-8ffc-d60fb0924387.png">

2. Try to send the program to a connected NXT

The generated NXC code looks fine to me, but I haven't be able to get a local compiler running to see if it throws an error.

**Edit**: The compiler (resp. the NXC preprocessor) throws the following error:

```
# Status: Current file = "/home/pi/workspace/bug_strings.nxc"
# Status: NXC compilation begins
# Status: Compiling for firmware version 128, NBC/NXC enhanced = FALSE
# Status: Running NXC preprocessor
# Status: Include path = /home/pi/workspace/;/usr/bin/;/usr/local/include/nbc/
# Status: Processing include: NBCCommon.h
# Status: Processing include: NEPODefs.h
# Status: Searching for file: NEPODefs.h
# Status: Found file: NEPODefs.h
# Status: Include path = /home/pi/workspace/;/usr/bin/;/usr/local/include/nbc/
# Error: Preprocessor macro function does not match instance (#_p#asm { ReadSensor(_p, __RETVAL__) })
File "/home/pi/workspace/bug_strings.nxc" ; line 11
```

The corresponding line is the actual `TextOut` call:

```C
TextOut(0, (MAXLINES - 1) * MAXLINES, "\"Sensor\"");
```

Until now, this only happened for `"Sensor`, but I could imagine that there might be other instances. I'd suspect a clash with internal identifiers during the compilation, but that's just a guess.

**Expected behavior**

The program can be compiled and transferred to the NXT.

**Comment by bjost2s** [comment]
will be fixed in #1312
