### ISSUE TITLE
Calliope: "play note" block creates Server Error

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#924]
**Describe the bug**
If you use the "play note" block in one of your programs, the server responds with a server error.

**To Reproduce**
1. Celect Calliope as your robot
2. Drag the "note play whole note c" block into your program
3. Press the play button or start the simulation

**Expected behavior**
A program should be created, that plays the specified note

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/97934751-de6d8d00-1d76-11eb-9de3-4ba8c612247e.png)

**Device information**
 - Server 4.0.5

**Additional context**
Instead of "play [whole] note [c]" the block reads "note play [whole] note [c]" with an additional "note" at the beginning. Is this a wanted behavior?

**Comment by bjost2s** [comment]
```
de.fhg.iais.roberta.util.dbc.DbcException: Could not invoke method jaxbToAst for block mbedActions_play_note with fields ACTORPORT _B 
	at de.fhg.iais.roberta.transformer.Jaxb2ProgramAst.invokeMethod(Jaxb2ProgramAst.java:98)
	at de.fhg.iais.roberta.transformer.Jaxb2ProgramAst.invokeJaxbToAstTransform(Jaxb2ProgramAst.java:72)
```

**Comment by Gillanius** [comment]
Same behaviour for "get angle gyroscope"

<img width="419" alt="grafik" src="https://user-images.githubusercontent.com/73915325/98049362-d160a480-1e2f-11eb-8741-964f4d8cd245.png">

Belongs this error message to the same issue?
