### ISSUE TITLE
[NXT] "Wait until" block with more than one node loses block caption on sending the program to the NXT

### ISSUE THREAD

**Issue by Stex** [OpenRoberta/openroberta-lab#93]
**Describe the bug**

I know this is a pretty specific bug, but it happened in a program created by one of my students.

**To Reproduce**

I am not completely sure about the necessary constellation for this bug to occur in the first place, but using the following program, it is at least reproduceable:

1. Add a new "Wait until" block and add a second node ("or wait until")
2. Fill it with the blocks from the original block (or duplicates)
3. Send the program to the NXT
4. The second caption is gone.

* [Video](https://drive.google.com/open?id=1zIBO1jOrY3aSin-0AyYb6JboXHtpje1P) showing what I did to produce more blocks without caption. Sorry about the bad quality, but when moving the progress slider manually, the behaviour should be noticeable.
* [The program](https://drive.google.com/open?id=1OTcCNcd2A6wlhm3x7GPjBbhbXseYbsxt)

**Expected behavior**
The second caption does not disappear.

**Screenshots**

![2018-11-08 at 20 58](https://user-images.githubusercontent.com/27221/48224115-2a101a80-e399-11e8-95c7-d93cf68cebc0.png)

**Comment by boonto** [comment]
Does not happen anymore.
