### ISSUE TITLE
variable out of scope must be caught by a validating visitor

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#935]
the following program:

![image](https://user-images.githubusercontent.com/15834363/102367697-59eb6c80-3fba-11eb-98af-dbb7a06514b3.png)

uses the variable i in the second loop out of scope. This is detected, the error message is weird:

![image](https://user-images.githubusercontent.com/15834363/102367843-81dad000-3fba-11eb-8ad5-329d2b48f66e.png)

But is is possible to compile the program. For calliope e.g. the compiler message is hard to understand:

![image](https://user-images.githubusercontent.com/15834363/102368047-ba7aa980-3fba-11eb-9b5c-e06aa8235d13.png)

... but correct.

A validator should typecheck the program and detect this kind of user errors.

**Comment by RaghuvirShirodkar** [comment]
Tested successfully on test server with the following program:
[OutOfScopeTest.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/10879199/OutOfScopeTest.xml.txt)
