### ISSUE TITLE
[RaspberryPi] Implement configuration blocks

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/openroberta-lab#936]
Implement for the **RaspberryPi** plugin the configuration blocks that correspond to the hardware elements.

- [ ] Sensor 
     - [x] Button
     - [ ] LineSensor
     - [ ] MotionSensor
     - [x] LightSensor
     - [x] DistanceSensor

- [ ]  Actors
    - [x] LED
    - [x] PWMLED
    - [x] RGBLED
    - [x] Buzzer
    - [ ] TonalBuzzer
    - [x] Motor
    - [x] Servo
    - [x] AngularServo

**Comment by bjost2s** [comment]
no time to work further on it
