### ISSUE TITLE
Update: Share messages

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/openroberta-lab#94]
The messages after changing or deleting the access rights to a program (sharing) aren't right.

![grafik](https://user-images.githubusercontent.com/25958792/44150150-beb08b2c-a09e-11e8-8aa9-5d0a8fed6bce.png)
![grafik](https://user-images.githubusercontent.com/25958792/44150185-dfad51d4-a09e-11e8-9c08-2997e7ecd27b.png)

**Comment by boonto** [comment]
In d628883f1f28da3591cda7b6317ca47fc218b4be I have added a semicolon in the messages which seems to have fixed this.
