### ISSUE TITLE
EV3: Select position of touch sensor

### ISSUE THREAD

**Issue by timof1308** [OpenRoberta/openroberta-lab#944]
As a user I would like to choose the position of the touch sensor  I can mount on my EV3. 
The UI and UX could look like as followed:
For the robot configuration the user 
 1) adds the touch sensor to the EV3-block 
2) can select the position of the touch sensor; the position options should be:
   * front (places the touch sensor to the front of the robot in the direction of travel)
   * right (places the touch sensor to the right side of the robot in the direction of travel)
   * left (places the touch sensor to the left side of the robot in the direction of travel)
   * back (places the touch sensor the the back of the robot against the direction of travel) 
 
The default alignment of the touch sensor should be the front of the robot so the user can start programming the robot intuitively.
This option should only be available inside the simulation as the placement in the real EV3 does not have to be taken into account during programming.

This workflow can also be used as a final test.

**Comment by MariaZemann** [comment]
Mockup proposal: UI Touch Sensor Position
<img width="711" alt="Screenshot 2021-01-03 at 17 28 42" src="https://user-images.githubusercontent.com/74667107/103483683-42e5b080-4de9-11eb-814e-23e1e62fbedd.png">
