### ISSUE TITLE
EV3: Select alignment of the color sensor

### ISSUE THREAD

**Issue by MariaZemann** [OpenRoberta/openroberta-lab#945]
As a user I would like to choose the alignment of the color sensor I can mount on my EV3. 
 The UI and UX could look like as followed:
For the robot configuration the user 
 1) adds the color sensor to the EV3-block 
2) can select the alignment of the color sensor; the alignment options should be:
   * down (lets the color sensor points down towards the ground)
   * horizontal (lets the color sensor points horizontally to the robot) 
 
 The default alignment of the color sensor should be pointing down so the user can start programming the robot intuitively.
This option should only be available inside the simulation as the placement in the real EV3 does not have to be taken into account during programming.

This workflow can also be used as a final test.

**Comment by timof1308** [comment]
Mockup proposal: Colour Sensor Alignment
![color_sensor_alignment](https://user-images.githubusercontent.com/13666446/103483577-7ecc4600-4de8-11eb-8790-465a7c0a7687.PNG)
