### ISSUE TITLE
EV3: Set track width

### ISSUE THREAD

**Issue by philipp-s4** [OpenRoberta/openroberta-lab#948]
As a user I would like to choose the track width in cm I can mount on my EV3. 
The UI and UX could look like as followed:
For the robot configuration the user 
can configure the track width
 
The default width should be 18 cm so the user can start programming the robot intuitively.
This option should only be available inside the simulation as the placement in the real EV3 does not have to be taken into account during programming.

This workflow can also be used as a final test.

**Comment by bjost2s** [comment]
You may want to check in detail the actual track width used for EV3 in the simulation, afaik it is different from 18 cm.
