### ISSUE TITLE
Cross compilation for Calliope fails on windows

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#963]
the setup of the crosscompiler (at least for Calliope) does work on linux, but fails for windows. The command generated is invalid. The console output is `'NEPOprogarm-none-eabi-g++' is not recognized as an internal or external command`

**Comment by rbudde** [comment]
reason: some parameters are empty. The ProcessBuilder gets "" and this is NOT recognized as parameter, but simply skipped. Thus parameters are missing resp. at the wrong place.

**Comment by bjost2s** [comment]
Please check and solve with #1099
