### ISSUE TITLE
Cannot delete individual configurations in config list.

### ISSUE THREAD

**Issue by LilMonk** [OpenRoberta/openroberta-lab#974]
**Describe the bug**
 - When clicking on the delete symbol corresponding to the config name, the ATTENTION(config deletion confirmation) pop-up doesn't appear instead it loads the configuration. If we select and then delete the configuration using the uppermost delete symbol then only we can delete a configuration from the list. This is not the case for the programs list. It works fine.

**To Reproduce**
1. Go to the Configuration tab.
2. Click on the Edit option(upper left corner).
3. Select 'my configuration'.
4. Click on the delete symbol corresponding to the config name.

**Expected behavior**
 - A pop-up should appear for confirming the deletion.

**Comment by EthicalCoder99** [comment]
I have solved the issue. Can I send a PR for this?
