### ISSUE TITLE
Roberta to virtual nao

### ISSUE THREAD

**Issue by fengmao31** [OpenRoberta/openroberta-lab#979]
![image](https://user-images.githubusercontent.com/19343842/112142234-45e68500-8c11-11eb-8ce6-3824b92c7d43.png)

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/112960083-aa0bca80-9176-11eb-97c6-1edf84f58116.png)

**Comment by bjost2s** [comment]
We disscussed this opportunity with Softbank and they recommended not to use it. The current idee is to use webbots for simulating NAO, an issue with some more information will follow soon.
