### ISSUE TITLE
Mbed Simulation: some blocks return undefined

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#98]
The "get pin" block returns undefined:
![image](https://user-images.githubusercontent.com/7438960/40840803-73216fae-65a8-11e8-88d0-fd0e3f0a5b8e.png)
The "get gesture" block returns undefined if the specified gesture is not the current gesture. True is correctly returned when both are the same.
![image](https://user-images.githubusercontent.com/7438960/40840836-99073eec-65a8-11e8-8549-584bc00b00e4.png)

**Comment by bjost2s** [comment]
see #114
