### ISSUE TITLE
Debug command "step over/into" fails with wait until statement

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#984]
run the program below in debug mode. Use the step command. The wait until won't terminate. The drive command seems to be aborted. Running in the frozen state to the next breakpoint doesn't work.

At least, stopping and starting the simulator allows to continue working.

**Expected behavior**

If the step command hits an wait, the debugger should execute that wait until the (or one of the) wait conditions become true, and then finish. The stmt after the wait or the first stmt list in the wait should be highlighted and the debugger should wait for the next command.

![2021-03-25 13_27_04-Open Roberta Lab](https://user-images.githubusercontent.com/15834363/112473501-bbb43300-8d6e-11eb-8682-5ff63a7798f9.png)

**Comment by bjost2s** [comment]
not reproducable anymore
