### ISSUE TITLE
The tutorial option is not available on the upper tool bar in the local build

### ISSUE THREAD

**Issue by LilMonk** [OpenRoberta/openroberta-lab#985]
I have been trying to access the tutorial option on my local build but somehow it's not visible. I have tried to switch to English and German but still the problem persists. [https://lab.open-roberta.org/#](URL) The official links seem to work correctly. I have tried this method on the master and develop branch.

**Comment by bjost2s** [comment]
The tutorials are in the Resources folder. Please try to start the server with the parameter `-d server.admin.dir=./Resources`, than you should see tutorials.
Please use for further questions the Gitter channel.

**Comment by LilMonk** [comment]
Thanks. It worked.
