### ISSUE TITLE
"export program" does not react on iPad

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#988]
![image](https://user-images.githubusercontent.com/1613069/112945916-34cbd580-9135-11eb-8942-b991144d10a6.png)

from a user
iPad Air with Open Roberta Mobile App and without, various browser types
import is working

**Comment by germanicianus** [comment]
I can confirm this bug on my iPhone with iOS 14.4.2. The app as well as Safari displays _Dein Programm wurde gerade heruntergeladen_ (your program has just been downloaded), but the file hasn't been saved anywhere.

**Comment by bjost2s** [comment]
fixed
