### ISSUE TITLE
Support action sequences, such as lifting and twisting on your arm

### ISSUE THREAD

**Issue by fengmao31** [OpenRoberta/openroberta-lab#989]
Support action sequences, such as lifting and twisting on the arm and leg.

**Comment by bjost2s** [comment]
Do you mean NAO? Please give us some more information what exactly you are asking for.

**Comment by fengmao31** [comment]
yes， i want to move arm or head in nao.
for example , move arm forward and move leg to left.


Also,
do you have any idea about the balance of nao when nao move leg and body

**Comment by bjost2s** [comment]
please use this block:
![image](https://user-images.githubusercontent.com/1613069/150079682-f2b055f9-ae16-49cd-b26f-3dbae84b3658.png)
and choose the desire joint
