### ISSUE TITLE
can i use it on nao

### ISSUE THREAD

**Issue by fengmao31** [OpenRoberta/openroberta-lab#990]
i want to finish the sequence action in nao

**Comment by bjost2s** [comment]
This is an issue tracker, what exactly is your issue here?

**Comment by bjost2s** [comment]
@fengmao31 for NAO we do not need an extra installation, because only Python code is generated and then executed on NAO. Python is already installed on NAO.

**Comment by fengmao31** [comment]
ok, thank you.
