### ISSUE TITLE
EV3 Sim: Robot turning with fine degrees not reproducible when using it in while loop

### ISSUE THREAD

**Issue by germanicianus** [OpenRoberta/openroberta-lab#995]
When using the while loop shown on below screenshot, the simulated robot turns to a different direction in every simulation run. Furthermore, the calculation error sums up which is kind of expected.
![openroberta_turning_loop](https://user-images.githubusercontent.com/37223176/113780197-2aaa6800-972f-11eb-9ad9-caf2c2e3dfd7.png)

**Comment by germanicianus** [comment]
This issue is already reproducible with a simple single turn of 90 degrees. In most cases the simulated robot slightly over-turns - see screenshot below.
![overturn](https://user-images.githubusercontent.com/37223176/113786926-68f95480-973a-11eb-9553-e0cedda5453b.png)

**Comment by rbudde** [comment]
the accuracy of turns is a problem for both simulation (frame generation at discrete steps) and real robots (friction). There is a text in our FAQ https://jira.iais.fraunhofer.de/wiki/display/ORInfo/Robotersysteme describing the problem and how to solve it: use sensor data (which is available for both simulation and real robot) for a correction step at low speed.

**Comment by germanicianus** [comment]
@rbudde, thanks for the explanation - I missed that part in the documentation.
