### ISSUE TITLE
UI Change: Start / Stop Buttons in the Debugging Tab

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#997]
I think, the new design of the start/stop buttons for the debugger is superior to the old one, but may generate irritations when using.  The start button is the same as the button "go to next breakpoint". That is fine.

The red stop button is enabled after start and can be used to stop the running program. That is fine, too.

A program running on the **Calliope** in debugging mode does not terminate. Thus, before one can restart the program for a second run, the red stop button *must* be pressed first, then the start button can be used. If you forget this, you may believe, that the simulation is frozen.

**Proposal:** if the last block of a program is executed, this should be remembered as "readyToBeRestarted". The program may "continue" to run as before. Now, if the start button is pressed and "readyToBeRestarted" is true, internally the sequence stop (as if the red button was pressed) followed by (re-)start should be triggered. This should be not too complex to implement.

**Comment by LawfulTheBest** [comment]
Sir @rbudde could you please guide me on how to start working on this issue?

**Comment by heini208** [comment]
A few Questions about the desired looks of the change:
Should the "next-Breakpoint" button become Red or stay Blue?
Should the other Stop button disappear?
Tell me which version looks best:
V1:
![v1](https://user-images.githubusercontent.com/57675018/119639303-c4c98b00-be17-11eb-9ef2-9230815dafbb.png)
V2:
![v2](https://user-images.githubusercontent.com/57675018/119639312-c7c47b80-be17-11eb-962c-0a18c032c488.png)
V3:
![v3](https://user-images.githubusercontent.com/57675018/119639315-c8f5a880-be17-11eb-8b44-b4b1127e6ea2.png)

**Comment by rbudde** [comment]
I'd prefer V1
