### ISSUE TITLE
Nao Gyrosensor - X and Y are replaced with no port

### ISSUE THREAD

**Issue by aykborstelmann** [OpenRoberta/openroberta-lab#998]
If u generate code for the nao gyro sensor it always looks like this:
```python
___Element = h.gyrometer('no port')
```
Instead of `no port` it should be `x`.

This error occures since 01.07.20 when 
```javascript
ports : [ [ 'x', 'X' ], [ 'y', 'Y' ] ], 
```
was replaced with 
```javascript
slots : [ [ 'x', 'X' ], [ 'y', 'Y' ] ]
```

and because 

```javascript
sensors.gyro.nao = sensors.gyro.calliope;
```
this change reflected on the nao.
See
https://github.com/OpenRoberta/blockly/blob/8ae15d9d9d745f2f1373a522faa05efca387a814/blocks/robSensorDefinitions.js#L469-L483

A fix would be 
```javascript
sensors.gyro.nao = {
    title : 'GYRO',
    modes : [ {
        name : 'ANGLE',
        type : 'Number',
        unit : 'DEGREE',
        op : 'NUM_REV',
        value : 90
    } ],
    ports : [ [ 'x', 'X' ], [ 'y', 'Y' ] ],
};
```

**Comment by LilMonk** [comment]
Made a pull request with necessary changes in OpenRoberta/blockly. Please check it.
